mondoohq/cnquery

apps/cnquery/cmd/scan.go
explorer/bundle.go
explorer/bundle_test.go
explorer/executor/executor.go
explorer/filters.go
explorer/impact.go
explorer/mquery.go
explorer/mquery_test.go
explorer/property.go
explorer/query_conductor.go
explorer/query_conductor_test.go
mqlc/mqlc.go
mqlc/mqlc_stats.go

Remaining todos to move this out of draft:
-----
Until now, the only thing developers can configure when it comes to compile-related calls is the schema.
However, there are use-cases where we may want to configure other things in the compiler, like:
- which feature-flags are enabled/disabled
- use of stats
I ran into the last use-case myself, which would have caused large copy-paste rewrites of the Bundle-compiler, just in order to get access to all the stats.
At this point it is a more comprehensive experience to not move the schema around, but instead wire the compiler config directly through all these calls. This means that more future-facing features will be configurable and that a chain of calls (like `Bundle.Compile`) uses a consistent set of compiler configs.
@ Reviewers: I …

🧹 add CompilerConfig on all compile-related calls

---

mqlc/mqlc.go
mqlc/mqlc_stats.go

Support WalkSorted on multi-stat compiler configs.
Bugfix that compiler stats are done after the query is cleaned, otherwise it leads to bad anchors for internal IDs

✨ compiler multi-stat WalkSorted + bugfix

---

cli/providers/providers.go
test/cli/testdata/cnquery.ct

We have overwritten the short description of the root commands. 
**before**
```
> cnquery help
mondoo™      |_|                |___/ 
cnquery is a cloud-native tool for querying your entire infrastructure.
Usage:
cnquery [command]
Available Commands:
bundle        Create, upload, and validate query packs.
completion    Generate the autocompletion script for the specified shell
help          Help about any command
login         Register with Mondoo Platform.
logout        Log out from Mondoo Platform.
providers     Providers add connectivity to all assets.
run           Run a query with your local system
sbom          Collect a …
```

🐛 fix root cmd name

---

providers/aws/connection/platform.go
providers/aws/resources/discovery_conversion.go

The API calls these EC2, which makes sense from an SDK organization standpoint, but doesn't reflect what these platforms are call. The console and documentation calls these EBS volumes/snapshots. This is a breaking change, but the blast radius is very small at this point since discover is not enabled by default. V10 is the perfect time to make this before we enable fine grained scanning by default.

🧹 Rename the ec2-volume and ec2-snapshot platforms to be EBS

---

.github/workflows/pr-test-lint.yml
apps/cnquery/cmd/providers.go
providers/arista/go.mod
providers/atlassian/go.mod
providers/aws/go.mod
providers/azure/go.mod
providers/equinix/go.mod
providers/gcp/go.mod
providers/github/go.mod
providers/gitlab/go.mod
providers/google-workspace/go.mod
providers/ipmi/go.mod
providers/k8s/go.mod
providers/ms365/go.mod
providers/oci/go.mod
providers/okta/go.mod
providers/opcua/go.mod
providers/providers.go
providers/slack/go.mod
providers/terraform/go.mod
providers/vcd/go.mod
providers/vsphere/go.mod
test/cli/testdata/cnquery_run.ct
test/cli/testdata/cnquery_sbom.ct
test/cli/testdata/cnquery_scan.ct

Sometimes it is useful to overwrite all paths and just use a specific provider path. This is useful for shared CICD environments where you want to ensure that your pipeline is using a very specific set of providers.
```
PROVIDERS_PATH=$PWD/.providers cnquery providers install os
PROVIDERS_PATH=$PWD/.providers cnquery providers list
```

⭐️ support custom provider path

---

mqlc/mqlc.go
mqlc/parser/parser.go
providers-sdk/v1/testutils/testutils.go
providers-sdk/v1/util/defaults/defaults.go
providers/aws/connection/awsec2ebsconn/setup.go
providers/aws/resources/discovery.go
providers/github/provider/provider.go
providers/github/resources/github_org.go
providers/okta/resources/policies.go
providers/okta/resources/sdk/policies.go
providers/os/connection/ssh.go
providers/os/detector/detector_all.go
providers/os/detector/platform_resolver.go
providers/os/resources/kubelet.go
providers/os/resources/kubelet_flags.go
providers/os/resources/kubelet_test.go
providers/os/resources/packages/windows_packages.go
providers/os/resources/python.go
providers/os/resources/python/mime.go
providers/os/resources/python/requirestxt.go
providers/os/resources/windows/security_products.go
providers/recording.go
providers/runtime.go

Some data types, a lot of comments, a few log messages

🧹 More minor typo fixes

---

providers/providers.go
providers/runtime.go

Fixes https://github.com/mondoohq/cnspec/issues/998
The implementation is flexible to be used in other places. We can consider packaging it separately down the line, but for now it is in a good place to be very specific and purpose-built for this use-case.

✨ introduce I/O retries for provider installs

---

cli/providers/providers.go
providers/defaults_shared.go
providers/network/config/config.go
providers/providers.go
providers/runtime.go

Legacy providers contain the version in their ID. Modern providers after v10 do not do this anymore.
Support both forms of lookup in this transition time.

🐛 support legacy+modern provider ID lookups

---

apps/cnquery/cmd/bundle.go
apps/cnquery/cmd/login.go
apps/cnquery/cmd/logout.go
apps/cnquery/cmd/plugin.go
apps/cnquery/cmd/providers.go
apps/cnquery/cmd/run.go
apps/cnquery/cmd/sbom.go
apps/cnquery/cmd/scan.go
apps/cnquery/cmd/shell.go
apps/cnquery/cmd/status.go
apps/cnquery/cmd/vault.go
apps/cnquery/cmd/version.go
test/cli/testdata/cnquery.ct
test/cli/testdata/cnquery_vault.ct

after #3031 
simplifies the short description of commands since it is unusual to use trailing dots for short descriptions.

🧹 remove trailing dot for short cmd description

---

providers-sdk/v1/testutils/testutils.go

Testutils are meant as an in-memory testing utility for unit tests. However, in their default configuration they pull providers from the local system, which can have unforseen consequences.
Most of the code in `testutils.go` already sets up the runtime to use in-memory providers with linked dependencies.
This changes ensures that we don't accidentally load installed providers on the system - or try to install online providers. For unit tests, we rely on providers that are fast to grab and execute, thus executable from memory. Other types of testing (particularly smoke/integration) are a different matter and not in scope of these utilities at the time of writing. (Which doesn't mean that they can't become that, but I think we want to be more explicit about when that happens, to avoid …

🐛 prevent testutils from loading local providers

---

providers/arista/config/config.go
providers/atlassian/config/config.go
providers/aws/config/config.go
providers/azure/config/config.go
providers/core/config/config.go
providers/equinix/config/config.go
providers/gcp/config/config.go
providers/github/config/config.go
providers/gitlab/config/config.go
providers/google-workspace/config/config.go
providers/ipmi/config/config.go
providers/k8s/config/config.go
providers/ms365/config/config.go
providers/network/config/config.go
providers/oci/config/config.go
providers/okta/config/config.go
providers/opcua/config/config.go
providers/os/config/config.go
providers/slack/config/config.go
providers/terraform/config/config.go
providers/vcd/config/config.go
providers/vsphere/config/config.go

arista-9.1.16, atlassian-9.1.16, aws-9.1.26, azure-9.2.2, core-9.1.9, equinix-9.1.17, gcp-9.1.19, github-9.1.20, gitlab-9.1.17, google-workspace-9.1.20, ipmi-9.1.17, k8s-9.1.23, ms365-9.2.15, network-9.1.9, oci-9.1.18, okta-9.1.17, opcua-9.1.16, os-9.1.21, slack-9.1.18, terraform-9.1.16, vcd-9.1.16, vsphere-9.1.19
For the sake of releasing #3060

🎉 all provider patch version bump

---

providers/os/resources/port.go

It is possible for the port resource to panic on mac and windows if the process is requested. This can happen because we query for all the processes first, then we query for ports which gets us process ids. A new process showing up between the first and second queries can cause the panic to happen.
Linux has a similar check

🐛 Fix port resource panic

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_rds.go

The most useful is the create date of the snapshot, but this also adds useful things like the version of the engine and the port the DB was running on.
Improved output of default within a RDS DB instance:
```coffee
aws.rds.dbInstances.first: {
enhancedMonitoringResourceArn: "arn:aws:logs:us-west-2:1234:log-group:RDSOSMetrics:log-stream:db-3WQORXB4LEOQXVQAEI2LUWTPHQ"
backupRetentionPeriod: 7
engineVersion: "15.4"
createdTime: 2024-01-20 19:05:45.311 -0800 PST
port: 0
name: null
status: "available"
storageAllocated: 100
storageType: "io1"
tags: {}
publiclyAccessible: false
availabilityZone: "us-west-2c"
0: aws.ec2.securitygroup id="sg-6b43f159" name="default" region="us-west-2" vpc.id="vpc-ffa59787"
]
storageIops: 1000
engine: "postgres"
endpoint: …
```

⭐ Add new fields/defaults to aws.rds.snapshot

---

providers/aws/config/config.go
providers/aws/connection/platform.go
providers/aws/resources/discovery.go
providers/aws/resources/discovery_conversion.go

RDS clusters are very important and should be scanned as their own assets with checks applied to those assets. This starts that process.
```
cnquery shell aws --discover rds-dbclusters
→ loaded configuration from /Users/tsmith/.config/mondoo/mondoo.yml using source default
Available assets
> 1. othercluster (aws-rds-dbcluster)
2. timcluster (aws-rds-dbcluster)
↑/k up • ↓/j down • q quit • ? more
```

⭐ Add discovery for aws-rds-dbcluster

---

apps/cnquery/cmd/bundle.go
examples/complex.mql.yaml
examples/k8s.mql.yaml
examples/lint_test.go
examples/os.mql.yaml
internal/bundle/lint.go

Use our lint requirements to validate our examples. To make this work, we temporarily install the required providers and remove them afterwards. This ensures that other tests like cli tests are not affected by the providers we need here.

🧹 ensure example query packs pass our own lint requirements

---

providers/azure/resources/sql.go

Fixes #3088
```
cnquery> azure.subscription.sql.servers[0].firewallRules
azure.subscription.sql.servers[0].firewallRules: [
0: azure.subscription.sqlService.firewallrule id="/subscriptions/e9ee8090-9784-42d6-9534-bc1d881eeff6/resourceGroups/Security-Team-resources-aqla/providers/Microsoft.Sql/servers/security-team-sql-server1-90sq/firewallRules/ClientIPAddress1" name="ClientIPAddress1"
1: azure.subscription.sqlService.firewallrule id="/subscriptions/e9ee8090-9784-42d6-9534-bc1d881eeff6/resourceGroups/Security-Team-resources-aqla/providers/Microsoft.Sql/servers/security-team-sql-server1-90sq/firewallRules/range2" name="range2"
2: azure.subscription.sqlService.firewallrule id="/subscriptions/e9ee8090-9784-42d6-9534-bc1d881eeff6/resourceGroups/Security-Team-resources-aqla/providers/Microsoft. …
```

🐛 Add id function for sql service firewall rules.

---

providers/runtime.go

this is needed by the k8s provider since it is referencing the containerImage resource, which is defined in the os provider
we also have the issue where filters that shouldn't be executed for an asset may request a provider that shouldn't be called. For example, trying to run aws filters on a k8s asset. This results in printing too many error messages, so I changed the log level of that error to debug

🐛 make sure the os provider can be cross referenced from another provider

---

providers/coordinator.go

Make sure we don't show info messages for the providers since that is a bit too much

🧹 only log warnings and higher for providers

---

providers/os/connection/fs/filesystem.go
providers/os/connection/tar.go

The capability wasn't added to the 2 connections that actually implement this.
fixes #3101 
```
cnspec shell container image ubuntu:latest
→ loaded configuration from /Users/ivanmilchev/.config/mondoo/mondoo.yml using source default
→ connected to Ubuntu 22.04.3 LTS
___ _ __  ___ _ __   ___  ___ 
/ __| '_ \/ __| '_ \ / _ \/ __|
| (__| | | \__ \ |_) |  __/ (__ 
\___|_| |_|___/ .__/ \___|\___|
mondoo™     |_|              
cnspec> files.find()
files.find.list: []
```

🐛 fix findfile capability for providers

---

examples/lint_test.go
providers/defaults.go

makes sure we are not installing the same provider version over and over

🐛 fix default providers IDs

---

llx/builtin_array.go
llx/builtin_array_test.go

This can unfortunately still happen, where the type info is missing and we essentially get the array indication in the type field, but nothing else. The subsequent for loop then crashes it.
Add testing for this use-case and fix the crash by forcing the any-type into it.

🐛 fix crash on empty array.flat with missing type info

---

providers-sdk/v1/upstream/gql/vulnmgmt_gql.go

We do not need to query the sources for advisories and CVEs as we do not use the data.

🧹 Do not query the sources for scans

---

providers/azure/connection/auth/auth.go

This extends the connection capabilities of the azure provider from just CLI creds to env var, workload identity, managed identity and CLI creds.

🧹 Use DefaultAzureCredential for token resolving in the Azure provider

---

providers-sdk/v1/resources/schema.go

We have some indication that it uses up way more memory than it should. Also using clone at this place is... a bit lazy, considering it uses reflections.

⚡ avoid proto.clone in schema

---

providers/runtime.go

sometimes we have seen this error in the logs while scanning. However, the actual error message causing the provider to shutdown isn't printed. This should help investigate the issue further

🧹 log the error that caused a provider to be unavailable

---

providers/aws/resources/aws_efs.go

```
cnquery> aws.efs.filesystem { * }
aws.efs.filesystem: {
backupPolicy: {
BackupPolicy: {
Status: "ENABLED"
}
ResultMetadata: {}
}
availabilityZone: null
```

🐛 fix aws.efs.filesystem resource (add init)

---

providers/providers.go

The `DetectProvider` https://github.com/mondoohq/cnquery/blob/main/providers/runtime.go#L168C1-L178C2 relies on the fact that we either have an error or a proper provider object. 
```go
// DetectProvider will try to detect and start the right provider for this
// runtime. Generally recommended when you receive an asset to be scanned,
// but haven't initialized any provider. It will also try to install providers
// if necessary (and enabled)
func (r *Runtime) DetectProvider(asset *inventory.Asset) error {
provider, err := r.providerForAsset(asset)
if err != nil {
return err
}
return r.UseProvider(provider.ID)
}
```
Turns out this was not always the case. `EnsureProvider` has a case where it returns `nil, nil`. This changes the logic to make the error explicit …

🐛 return proper error when no provider could be detected

---

providers/os/config/config.go
providers/os/connection/shared/shared.go
providers/os/provider/provider.go

The os provider had two places where connection types where defined. This was confusing. The values where the same though. This cleans up the different parts to just use one definition.

🧹 refactor os connection types

---

providers/slack/connection/connection_test.go
providers/slack/go.mod
providers/slack/resources/conversations.go
providers/slack/resources/slack.lr
providers/slack/resources/slack.lr.go

If you are a large organisation with 1000s of conversations, the previous implementation fetched information about the creator via the user rest call. The problem is that the slack api heavily rate limits the user rest call.
This change makes the creator information asynchronous and therefore allows much speedier fetching of the conversations. This avoids reaching the rate limit.

🚤 improve performance for large slack accounts

---

providers/os/config/config.go
providers/os/connection/shared/shared.go
providers/os/connection/ssh_test.go
providers/os/provider/provider.go

after #3139
This PR adds two tests to check for error cases.

🧹 test ssh errors

---

apps/cnquery/cmd/login.go
apps/cnquery/cmd/logout.go

If the server returns aborted for RegisterAgent, that means it aborted the change because of concurrent writes to the IAM policy, likely meaning concurrent registrations. Clients are safe to backoff and retry in this case.

🧹 Retry login command when concurrent IAM updates are detected

---

apps/cnquery/cmd/scan.go
explorer/scan/local_scanner.go

This bug was originally reported by @username-is-already-taken2
When cnquery was executed in a pipeline and a connect error happened, we never collected that error and returned a non-zero exit code. That can lead to silent errors.
We always prepared the report structure to collect the errors. This change handles asset errors now.
**before**
```shell
> cnquery scan ssh user@host
x unable to connect to asset error="rpc error: code = Unknown desc = dial tcp: lookup host: no such host"
> echo $?
0
```
**after**
```shell
> cnquery scan ssh user@host
Summary (1 assets)
==================
Target:     
error: rpc error: code = Unknown desc = dial tcp: lookup host: no such host
> echo $?
1
```

🐛 report asset errors

---

providers/providers.go
providers/providers_test.go

The implementation of `errors.As` is using pointers and reflection to do some black magic when checking for error types. This way of comparison isn't compatible with the `syscall.Errno` errors and results in a panic (see the attached issue). This answer gives an example of how to compare the error properly: https://stackoverflow.com/a/64067281
Fixes #3173

🐛 fix panic in osRetry logic

---

providers/ms365/connection/adapter.go
providers/ms365/connection/connection.go
providers/ms365/connection/connection_test.go
providers/ms365/resources/applications.go
providers/ms365/resources/devicemanagement.go
providers/ms365/resources/domains.go
providers/ms365/resources/groups.go
providers/ms365/resources/microsoft.go
providers/ms365/resources/organizations.go
providers/ms365/resources/policies.go
providers/ms365/resources/rolemanagement.go
providers/ms365/resources/securescores.go
providers/ms365/resources/serviceprincipals.go
providers/ms365/resources/settings.go
providers/ms365/resources/users.go

This change verifies the MS 365 during connection, and not just for each query execution. This allows users to see the issue earlier and with a more clear message.

🧹 improve the validation of the ms365 credentials during the connection

---

providers-sdk/v1/plugin/runtime.go

Errors where not cached and slowed down the execution.

🐛 cache mql field errors

---

cli/printer/printer_test.go
llx/code.go

We currently have a crash that happens on the assertion creation:
```
go.mondoo.com/cnquery/v10/llx.(*CodeV2).entrypoint2assessment(0xc00070f020, 0xc000ca8b40, 0x10000000d, 0xc001254ce0)
/pub/go/src/go.mondoo.com/cnquery/llx/code.go:444 +0x1303
go.mondoo.com/cnquery/v10/llx.Results2AssessmentLookupV2(0xc000ca8b40, 0xc0010898f0?)
/pub/go/src/go.mondoo.com/cnquery/llx/code_bundle.go:57 +0x11a
go.mondoo.com/cnspec/v10/policy.Query2Assessment(0xc000ca8b40, 0xc0009cc3c0?)
/pub/go/src/go.mondoo.com/cnspec/policy/assessment.go:40 +0x25e
go.mondoo.com/cnspec/v10/cli/reporter.(*defaultReporter).printCheck(0xc001225890, 0xc00065df80, 0xc0000e5400, 0xc000f8e200, 0xc0000061a0?, 0xc00006a500?)
/pub/go/src/go.mondoo.com/cnspec/cli/reporter/print_compact.go:560 +0x279
```
The original MS365 check boiled …

🐛 prevent a crash on assertion creation

---

providers/arista/config/config.go
providers/atlassian/config/config.go
providers/aws/config/config.go
providers/azure/config/config.go
providers/equinix/config/config.go
providers/gcp/config/config.go
providers/github/config/config.go
providers/gitlab/config/config.go
providers/google-workspace/config/config.go
providers/ipmi/config/config.go
providers/k8s/config/config.go
providers/ms365/config/config.go
providers/oci/config/config.go
providers/okta/config/config.go
providers/opcua/config/config.go
providers/os/config/config.go
providers/slack/config/config.go
providers/terraform/config/config.go
providers/vcd/config/config.go
providers/vsphere/config/config.go

🎉 arista-9.1.21, atlassian-9.1.21, aws-10.0.6, azure-10.0.8, equinix-10.0.4, gcp-10.0.5, github-10.0.5, gitlab-10.0.4, google-workspace-10.0.5, ipmi-10.0.4, k8s-10.0.5, ms365-10.0.5, oci-10.0.4, okta-10.0.4, opcua-10.0.4, os-10.0.5, slack-10.0.5, terraform-10.0.4, vcd-10.0.4, vsphere-10.0.4

🎉  update providers

---

.github/workflows/pr-test-lint.yml
Makefile

Split the CLI tests into a separate job because they rely on the fact that no providers have been installed. When other unit tests are pulling providers, they make the CLI tests fail. With this change that should no longer be an issue, because CLI and non-CLI tests will be executed independently

🧹 split CLI tests into a separate job

---

explorer/scan/discovery.go
explorer/scan/discovery_test.go

sometimes the root assets are scannable, sometimes they are not. For example, when running a `cnquery scan local`, the root asset is the local machine and it should be scanned. However, when running `cnquery scan k8s`, the root asset is just the unresolved inventory.
This change makes sure both cases work as expected. A test is added to cover the missing case

🐛 properly discover scannable root assets

---

explorer/scan/discovery.go
explorer/scan/discovery_test.go

Forgot to set the labels for the scannable root assets in the previous PR. Test added too

🐛 set runtime labels for scannable root assets

---

explorer/scan/discovery.go

the response of `createRuntimeForAsset` is `nil` when there is an error. We shouldn't use it when storing the errors.
Can't add a test for this yet because I cannot easily mock the coordinator. That will be possible once #3218 merges

🐛 properly handle errors from createRuntimeForAsset

---

apps/cnquery/cmd/shell.go

no need to do a connect here since that is already done in `DiscoverAssets` this improves the responsivess of the shell command

🧹 simplify shell command

---

providers/aws/provider/provider.go

this is the only provider trying to assign a platform id to the root of the discovery. That breaks the new discovery code. I checked and this change is compatible with the new and the old discovery code. We should merge this and release the providers to make sure the provider works as expected with the new cnquery code as well

🐛  make aws discovery consistent with other providers

---

providers/gcp/resources/gcp.lr.manifest.yaml
providers/gcp/resources/storage.go

dict does not support timestamps as json also does not support timestamp. Therefore the implementation of the resource was wrong, which caused errors. In addition the `gcloud.storace.bucket` also used uppercase keys which is not used by GCP.
fixes https://github.com/mondoohq/cnquery/issues/3236
```coffee
gcp.storage.buckets.all(
iamConfiguration['UniformBucketLevelAccess']['enabled'] == true
)
```
needs to be written as:
```coffee
gcp.storage.buckets.all(
iamConfiguration['uniformBucketLevelAccess']['enabled'] == true
)
```

🐛 fix dict parsing for gcp buckets

---

llx/builtin_resource.go
providers-sdk/v1/testutils/testutils.go
providers/core/resources/parse_test.go

fixes https://github.com/mondoohq/cnquery/issues/3207 by making the parsing of the time format case insensitive

🐛 parse time formats case-insensitive

---

apps/cnquery/cmd/status.go

Right now the core provider is displayed as outdated. This ignores the core provider in our status output since the user cannot update this provider without updating cnquery

🧹 do not show the core provider as outdated since it cannot be updated without cnquery update

---

.github/workflows/bump-cnspec.yml

A new cnquery release will trigger a workflow in the cnspec repo to create a PR which updates the dep.

✨ Automatically create cnquery update PR

---

providers-sdk/v1/util/configure/configure.go

Small subcommand that allows you to easily configure the `providers.yaml` from CI/CD:
```
go run ./providers-sdk/v1/util/configure/configure.go edit-providers -f providers.yaml aws os gcp
```

⭐️ new command to configure the provider build config

---

providers/azure/config/config.go
providers/azure/connection/azureinstancesnapshot/provider.go
providers/azure/connection/azureinstancesnapshot/snapshot.go
providers/azure/provider/provider.go

Attach the Azure data disks with a delete option. That means that if the VM gets deleted, the data disks get delete alongside.
Also add an option to skip detach/delete steps. This may be useful when we're performing a scan on a VM we know will get deleted soon after. In that case, manually detaching/deleting the data disk is redundant as we know this will happen when the VM itself gets deleted. To trigger this, add the `--skip-snapshot-cleanup` flag.

🧹 Attach data disks with a delete opt. Add an option to skip detach/delete steps

---

providers/aws/connection/awsec2ebsconn/provider.go
providers/azure/connection/azureinstancesnapshot/provider.go
providers/gcp/connection/gcpinstancesnapshot/provider.go
providers/os/connection/fs/filesystem.go
providers/os/connection/local/local.go
providers/os/connection/ssh.go
providers/os/connection/tar.go
providers/os/connection/winrm.go
providers/terraform/connection/connection.go

Just make sure that we explicitly state that these connections implement the `plugin.Closer` interface. This will make sure that if in the future the interface changes, we will get compiler errors
I removed the `Close` functions from connections that didn't really implement any logic in them to avoid confusion. If we need those in the future we can re-add and implement the `Close` functions.

🧹 safe guard connections that should implement the Closer interface

---

explorer/scan/discovery.go

there was 1 case where the root asset runtime wasn't closed when it should have been. I also moved the close in a defer because it's best to close the connection at the end of the loop instead of before processing the discovered assets. If we do it at the end, we will be properly re-using the root asset MQL cache after #3274 merges

🧹 make sure the root asset runtime is closed

---

explorer/scan/discovery.go

If we are only scanning the root asset we shouldn't close its runtime if no inventory is specified

🐛 Do not close runtime for root asset if no inventory.

---

providers/azure/connection/azureinstancesnapshot/provider.go
providers/azure/connection/azureinstancesnapshot/setup.go
providers/azure/connection/azureinstancesnapshot/snapshot.go

We do not require scanner instance info if we're not attaching anything. Make the `instanceInfo` optional and only retrieve if required.
This means that we can perform a scan on an already mounted disk without ever communicating with the Azure API.

🧹 Do not fetch azure instance info if not required.

---

providers/os/resources/os.lr
providers/os/resources/os.lr.go
providers/os/resources/os.lr.manifest.yaml
providers/os/resources/packages.go
providers/os/resources/packages/aix_packages.go
providers/os/resources/packages/aix_packages_test.go
providers/os/resources/packages/apk_packages.go
providers/os/resources/packages/apk_packages_test.go
providers/os/resources/packages/cos_packages.go
providers/os/resources/packages/cos_packages_test.go
providers/os/resources/packages/dpkg_packages.go
providers/os/resources/packages/dpkg_packages_test.go
providers/os/resources/packages/freebsd_packages.go
providers/os/resources/packages/macos_packages.go
providers/os/resources/packages/macos_packages_test.go
providers/os/resources/packages/opkg_packages.go
providers/os/resources/packages/opkg_packages_test.go
providers/os/resources/packages/packages.go
providers/os/resources/packages/packages_test.go
providers/os/resources/packages/pacman_packages.go
providers/os/resources/packages/pacman_packages_test.go
providers/os/resources/packages/rpm_packages.go
providers/os/resources/packages/rpm_packages_test.go
providers/os/resources/packages/scratch.go
providers/os/resources/packages/solaris_packages.go
providers/os/resources/packages/solaris_packages_test.go
providers/os/resources/packages/testdata/packages_dpkg.toml
providers/os/resources/packages/testdata/packages_redhat7.toml
providers/os/resources/packages/windows_packages.go

When you want to find outdated packages, it is important to know where the files are located. This change adds a new `files` field to the packages resources that allows users to see where the package is located on disk:
```coffee
packages { name version files }
```
Not all operating system package manager have a list of the files associated with the package. At this point we added support for:
- alpine
- deb based systems (Debian, Ubuntu)
- macOS
- rpm based systems (Red Hat, Rocky, Alma)
**alpine**
```coffee
cnquery> packages.list[3] { name version files }
packages.list[3]: {
name: "alpine-keys"
version: "1634579657:2.4-r1"
files: [
0: pkgFileInfo path="etc/apk/keys/alpine-devel@lists.alpinelinux.org-524d27bb.rsa.pub"
1: pkgFileInfo …
```

⭐️ extract files that are used by a package

---

providers/aws/resources/discovery.go

we have a similar flow for k8s. We don't need to do discovery every time we connect to an asset. This is currently happening for aws. With the current code a `Connect` call for an AWS asset takes about 1s. With this change the `Connect` call takes about 500ms
Please verify this works for all discoveries. I only tested this with s3 buckets and kms keys

🏃🏻‍♂️ faster aws connect and discovery

---

providers/vsphere/resources/vsphere.lr
providers/vsphere/resources/vsphere.lr.go

Without the import, the resources.json file was created with `core.cpe` as the resource for `cpes`. This failed on lookup when compiling a query.
Adding the import creates the resources.json file `cpe` as the resource for `cpes`. Then the lookup works again.

🐛 Fix cpes resource definition in vSphere

---

providers/os/resources/npm/package_lock.go
providers/os/resources/npm/package_lock_test.go
providers/os/resources/npm/testdata/package-lock/lockfile-v0.json
providers/os/resources/npm/testdata/package-lock/lockfile-v1.json
providers/os/resources/npm/testdata/package-lock/lockfile-v2-licenses.json
providers/os/resources/npm/testdata/package-lock/lockfile-v2.json
providers/os/resources/npm/testdata/package-lock/lockfile-v3.json
providers/os/resources/npm/testdata/package-lock/simple-lock.json

This PR extends the current package-lock parsing capability and adds more tests to validate that we are able to load its multiple versions.

⭐️ support multiple versions of package lock file

---

providers/os/resources/npm.go
providers/os/resources/npm/npm.go
providers/os/resources/npm/package_json.go
providers/os/resources/npm/package_json_test.go
providers/os/resources/npm/package_lock.go
providers/os/resources/npm/package_lock_test.go
providers/os/resources/npm/yarn_lock.go
providers/os/resources/npm/yarn_lock_test.go
providers/os/resources/os.lr
providers/os/resources/os.lr.go
providers/os/resources/os.lr.manifest.yaml

This PR adds a new `npm` resource to gather npm pacakges.
It supports finding the globally installed packages via:
```coffee
// returns all globally installed direct and transitive dependencies on your operating system
cnquery> npm.packages
npm.global.list: [
0: npm.package name="npm" version="10.2.4"
1: npm.package name="yarn" version="1.22.21"
]
// to query the direct dependencies, use use the directDependencies field
cnquery> npm.packages.directDependencies
npm.packages.directDependencies: [
0: npm.package name="npm" version="10.2.4"
1: npm.package name="yarn" version="1.22.21"
]
```
You can also parse individual projects:
```coffee
// gather transitive dependencies
cnquery> npm.packages("/Users/chris/github/jquery/jquery")
npm.packages.list: [
0: npm.package name="jquery" …
```

⭐️ npm.packages resource

---

sbom/cnquery_bom_test.go
sbom/cyclonedx_test.go
sbom/report_collection.go
sbom/sbom.go
sbom/sbom.mql.yaml
sbom/sbom_test.go
sbom/spdx_test.go
sbom/testdata/alpine.json

The sbom export now includes os, pypi and npm packages.
```shell
> cnquery sbom
npm/which/^4.0.0
npm/write-file-atomic/^5.0.1
pypi/yarl/1.9.4
npm/yarn/1.22.21
macos/zoom.us/5.17.5 (29101)
```

⭐️ include npm packages in sbom export

---

providers/arista/config/config.go
providers/atlassian/config/config.go
providers/aws/config/config.go
providers/azure/config/config.go
providers/equinix/config/config.go
providers/gcp/config/config.go
providers/github/config/config.go
providers/gitlab/config/config.go
providers/google-workspace/config/config.go
providers/ipmi/config/config.go
providers/k8s/config/config.go
providers/ms365/config/config.go
providers/oci/config/config.go
providers/okta/config/config.go
providers/opcua/config/config.go
providers/os/config/config.go
providers/slack/config/config.go
providers/terraform/config/config.go
providers/vcd/config/config.go
providers/vsphere/config/config.go

arista-9.3.1, atlassian-9.3.1, aws-10.2.1, azure-10.2.1, equinix-10.2.1, gcp-10.2.1, github-10.2.1, gitlab-10.2.1, google-workspace-10.2.1, ipmi-10.2.1, k8s-10.2.1, ms365-10.2.1, oci-10.2.1, okta-10.2.1, opcua-10.2.1, os-10.2.1, slack-10.2.1, terraform-10.2.1, vcd-10.2.1, vsphere-10.2.1

🎉 bump providers

---

providers/github/provider/provider.go
providers/github/resources/discovery.go

The root of the scan shouldn't have a platform ID. Also made sure the connections for child assets are re-used which should make scans faster

🐛 fix github scans

---

README.md
apps/cnquery/cmd/status.go
explorer/scan/local_scanner.go

🧹 Use docs URLs that avoid a redirect

---

providers/k8s/resources/discovery.go

instead of erroring out, we should continue with the next container

🐛 do not error out on failing to discover a k8s container

---

providers/k8s/config/config.go

🎉 k8s-10.2.2

---

.gitignore
providers/builtin.go
providers/mock.go

The schema is loaded by the coordinator. The mock provider doesn't need to do anything for that
fixes #3364

🐛 fix mock provider panic

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_vpc.go

AWS VPC Flow Logs supports three types of destinations for flow log data:
1. cloud-watch-logs: Specifies that the flow log data will be published to Amazon CloudWatch Logs.
3. s3
5. kinesis-data-firehose

⭐️  Added destinationType (aws)

---

providers/gitlab/provider/discovery.go

Makes sure we re-use the connections when doing discovery for gitlab. For now this has no added benefits because we don't do discovery via MQL but whenever we migrate it, there will be a performance improvement.
Also makes sure an asset doesn't include itself in the discovered assets since this can cause issues when running a scan

🧹 reuse gitlab connections during discovery

---

providers/gitlab/provider/discovery.go
providers/runtime.go

It is possible to setup gitlab in such a way that 1 project appears in multiple groups. The gitlab provider discovers assets starting from the root and traversing down finding everything along the way. It is possible that the same thing is found in 2 different places. In the end the provider should return a unique list of assets with no duplicates to make sure everything works as expected

🐛 make sure gitlab discovers only unique assets

---

apps/cnquery/cmd/sbom.go
apps/cnquery/cmd/scan.go
cli/inventoryloader/inventory.go

Ensure all assets in the inventory (whether discovered from the inventory or passed in as fallbacks) get annotated correctly.

🧹 Add annotations to all assets in the inventory.

---

apps/cnquery/cmd/shell.go

the shell command panics when multiple assets are discovered and you do `ctrl + C` without selecting an asset. This fixes the issue.

🐛 fix shell command panic

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_vpc.go

Situations Where DeliverLogsStatus May Not Be "SUCCESS":
"FAILED": This status indicates that the flow log failed to deliver logs to the specified log destination. This could be due to several reasons such as:
1. Incorrect permissions: The IAM role specified in DeliverLogsPermissionArn lacks the necessary permissions to publish logs to the destination.
2. Non-existent log group/log stream: The specified CloudWatch Logs log group or log stream does not exist.
3. Incorrect log destination configuration: There may be a misconfiguration with the log destination settings.
4. "ACCESSERROR": This status means that AWS was unable to deliver logs to the specified destination due to an access error. This is typically related to permission issues or the log destination being deleted or modified.

⭐️  Added the status of the Log delivery VPC  (aws)

---

providers/azure/resources/azure.go
providers/azure/resources/azure.lr.go
providers/azure/resources/subscription.go

By caching the azure subscription we avoid that it's being called every single time a query asks for it.
I ran some manual scans and the scan time goes from 55-60s to 18-20s for me

🏃Speed up azure provider by caching the azure subscription.

---

.github/workflows/providers.yaml

Some providers, namely ms365, are running out of disk during builds on the normal hosted runners, using larger instances is possible but increases cost significantly.   Reverting to using our private self-hosted runners.

Revert provider builds to self-hosted runners

---

providers/vsphere/resources/discovery.go

We added the root asset to the inventory which caused the shell/scan to pick the wrong connection.

🐛 do not add root asset to discovered inventory

---

apps/cnquery/cmd/login.go

This change allows providing the scan interval on registration. Passing `timer` / `splay` will ensure they are written to the config file so that the `serve` command in cnspec knows how often to run

🧹 Allow setting the scan interval on registration

---

llx/builtin_global.go

When there were errors, `ifCallV2` would return the type of the predicate for the result of the if block.
That becomes problematic for a query like the following:
```
if (file('/etc/amazon/').exists) {
return "AWS"
} else if ( users.any( name == 'ec2-user' || name == 'ec2-instance-connect' ) ) {
return "AWS"
} else if ( machine.baseboard.manufacturer == 'Amazon EC2') {
return "AWS"
} else if ( asset.platform == "cos" ) {
return "GCP"
} else if ( file('/etc/google_instance_id').exists ) {
return "GCP"
} else if ( file('/var/lib/waagent/').exists ) {
return "Azure"
} else if ( file('/var/lib/dhcp/dhclient.enp1s0.leases').exists && file('/var/lib/dhcp/dhclient.enp1s0.leases').content.lines.contains( /unknown-245/ ) ) {
return "Azure"
} else {
return "Unknown"
}
```
If you cannot run …

🐛 Do not return the type of the predicate for if blocks

---

providers/terraform/resources/hcl.go

Fixes https://github.com/mondoohq/cnquery/issues/3377

🐛 terraform: avoid nil crash on non-existent block in module

---

providers/os/resources/vulnmgmt.go

state and summary weren't populated.

🐛 Add missing data to vuln.cve fields

---

providers/ms365/resources/iterator.go
providers/ms365/resources/serviceprincipals.go
providers/ms365/resources/users.go

Use msgraph page iterator to get the next page (via odata's next link) if there's more elements than what `top` indicates.
Set the top to 999 to reduce the amount of API calls we'd require.

✨ Add page iterator for fetching users and service principals in MS365.

---

llx/builtin_global.go
llx/builtin_simple.go
mqlc/mqlc.go
mqlc/operators.go
mqlc/typemaps.go

Basically:
```coffee
> int(1.23)
1
> bool(1)
true
> float(12)
12
> string(1.89)
"1.89"
> regex("w.r.d") == "world 🌎"
/w.r.d/
```

⭐ add typemaps for simple types

---

mql/mql_test.go

It was late when I pushed this, but I promised to add the missing tests, so here we are. Related to https://github.com/mondoohq/cnquery/pull/3463
I ran into an issue last night where `regex` would only either work as the type-cast or as the keyword we use for eg `regex.ipv4`. It popped up during the previous PR for the latter case, now we are also adding tests for the former.

🟢 add missing tests for typecasts

---

explorer/property.go
explorer/property_test.go

A friend accidentally the `query` (which we used pre v9) attribute for the property, instead of the `mql` field. This led to an empty property, which in this case is never valid. Properties must be non-empty.
Guarantee non-empty props + add more testing.

🐛 avoid accidental empty properties

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_iam.go

⭐️  Added Trust relationship policy  to the role (aws)

---

.github/actions/spelling/expect.txt
providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_config.go

⭐️  Adding a new function to fetch the delivery channel and related info (aws)

---

.github/actions/spelling/line_forbidden.patterns
providers/aws/resources/aws.lr

Fix a minor LR typo

---

providers-sdk/v1/inventory/inventory.go
providers-sdk/v1/plugin/service.go
providers-sdk/v1/plugin/service_test.go
providers/arista/provider/provider.go
providers/atlassian/provider/provider.go
providers/aws/provider/provider.go
providers/azure/provider/provider.go
providers/coordinator.go
providers/core/provider/provider.go
providers/equinix/provider/provider.go
providers/gcp/provider/provider.go
providers/github/provider/provider.go
providers/gitlab/provider/provider.go
providers/google-workspace/provider/provider.go
providers/ipmi/provider/provider.go
providers/k8s/provider/provider.go
providers/ms365/provider/provider.go
providers/network/provider/provider.go
providers/oci/provider/provider.go
providers/okta/provider/provider.go
providers/opcua/provider/provider.go
providers/os/provider/provider.go
providers/runtime.go
providers/slack/provider/provider.go
providers/terraform/provider/provider.go
providers/vcd/provider/provider.go
providers/vsphere/provider/provider.go

Use globally unique connection IDs for providers. This allows us to call `Connect` multiple times for providers without having to create new connections in the process. It also helps us to do cross-provider connections in the future since 1 asset will always have 1 connection ID for all providers it talks to.
**New flow**
Connection IDs are assigned by the coordinator. If a connection has no ID yet, it gets one from the coordinator which makes sure it is globally unique.
- Made sure cloned inventories are cloned without the connection ID. This makes sure discovered assets get their own connection ID
- Made sure that we first check if a connection with this ID exists for the current provider. If there is one, we return that and we do not create a new connection
- This flow is only used for …

✨ use globally unique connection IDs for providers

---

go.mod
go.sum
providers/github/go.mod
providers/github/go.sum
providers/google-workspace/go.mod
providers/google-workspace/go.sum
providers/k8s/go.mod
providers/k8s/go.sum
providers/os/resources/vulnmgmt.go
providers/vsphere/go.mod
providers/vsphere/go.sum

This is needed to determine the applicable app vulns.

🐛 Provide platform family for vulnmgmt

---

apps/cnquery/cmd/scan.go
explorer/scan/local_scanner.go
explorer/scan/reporter.go

- pass through upstream creds if available
- do not fetch the bundle for every asset
- use upstream bundle when upstream config is available (even if in incognito)
fixes #3502

🐛 fix incognito scans

---

apps/cnquery/cmd/root.go
apps/cnquery/cmd/sbom.go
apps/cnquery/cmd/scan.go
sbom/sbom.go

This PR harmonizes the config gathering. Since sbom subcommand does not support all flags, the flag parsing has been converted to viper so that it can be used even if a specific flag is not supported.

🧹 refactor config gathering for sbom cmd

---

providers/gcp/resources/bigquery.go
providers/gcp/resources/compute.go
providers/gcp/resources/dataproc.go
providers/gcp/resources/gke.go
providers/gcp/resources/storage.go

some of the init functions in the GCP provider weren't properly checking for missing asset IDs, which could result in provider panics
also dataproc config was trying to set a non-existent field

🐛 fix gcp init functions panic

---

apps/cnquery/cmd/plugin.go
apps/cnquery/cmd/shell.go
explorer/scan/local_scanner.go

Make sure delayed discovery logic is properly handled for shell and run commands. They now re-use the same logic as scan to make sure the behaviour is consistent across commands

🐛 fix panics in shell and run commands

---

providers-sdk/v1/inventory/asset_url.go
providers-sdk/v1/inventory/asset_url_test.go

We returned too many queries from the list. This approach fixes the underlying bug by:
1. making sure all requested parameters are in the query and
2. removing nodes from the search tree once a descendent is found

🐛 fix multiple parameters in AssetURL

---

explorer/scan/discovery.go
providers-sdk/v1/inventory/ansibleinventory/inventory.go
providers-sdk/v1/inventory/ansibleinventory/inventory_test.go
providers-sdk/v1/inventory/inventory.go

**Restricter Ansible Inventory Parsing**
This implementation makes the ansible inventory parser more restrict. It tests the passed inventory data and returns a proper error. 
While the following inventory is a valid ansible inventory, cnquery & cnspec only parse fully resolved inventories.
```yaml
all:
hosts:
ub2204:
ansible_host: 34.69.247.108
ansible_user: chris
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
```
Instead of a silent pass-through where the inventory could not be parsed and therefore resolves 0 assets, we return a proper error now. This also prevents that the inventory falls back to local machine.
```shell
> cnspec scan --inventory-format-ansible --inventory-file ansible-inventory.yaml
→ load inventory inventory-file=providers-sdk/v1/inventory/ansibleinventory/testdata/ans …
```

🧹 make ansible inventory parser more restrict

---

apps/cnquery/cmd/scan.go
cli/inventoryloader/inventory.go
test/cli/testdata/cnquery_scan.ct

Followup on https://github.com/mondoohq/cnspec/issues/1124 since we learned that the flag name was not intuitive.

🧹 use new `inventory-format-ansible` and `inventory-format-domainlist` names for flags

---

providers/os/resources/os.lr

This results in a weird double comma when it goes into the docs

Remove an empty line in the lr docs

---

providers/os/id/awsec2/metadata_cmd.go
providers/os/id/awsec2/metadata_cmd_test.go

default to instance id for the name, give it the name if we get the tag
fixes https://github.com/mondoohq/cnspec/issues/1144

🐛 ensure ec2 instances get a name when scanned

---

providers/aws/resources/discovery_conversion.go

these labels are useful for users, and were included in v8, but were removed when moving to v9. adding them back in

🧹 add tags to ec2 instances

---

explorer/scan/local_scanner.go

seems like we always need to get the bundle when running a cnquery scan... the implementation here is much different from the one in cnspec and doesn't work without the bundle

🐛 fix upstream scans

---

providers/os/config/config.go

🎉 os-10.3.6

---

providers/os/config/config.go

🎉 os-10.3.7

---

apps/cnquery/cmd/run.go
apps/cnquery/cmd/shell.go
providers-sdk/v1/inventory/asset.go
providers-sdk/v1/inventory/asset_test.go

great for debugging, otherwise hidden to avoid distractions use via:
```bash
cnquery shell --annotations priority=high
```
Now you can
```
> asset.annotations
asset.annotations: {
priority: "high"
}
```
(requires ^ https://github.com/mondoohq/cnquery/pull/3625)

✨ support setting annotations on run/shell commands

---

providers/os/connection/container/image_connection.go
providers/os/connection/docker/container_connection.go

makes sure we can scan docker images that aren't present locally

🐛 fix docker image scan for remote images

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_autoscaling.go

Add new fields for checking on autoscaling groups.
- Add min/max to the defaults
- Add instances
- Add capacityRebalance
- Add defaultInstanceWarmup
The core bit of value here is the instances. We're going to need these to go from EKS cluster -> EKS nodegroup -> Nodes. EKS node groups use autoscaling groups so with this we can get cluster nodes now:
```
cnquery> aws.autoscaling.groups[15]{*}
aws.autoscaling.groups[15]: {
instances: [
0: aws.ec2.instance instanceId="i-12345" region="us-west-2" state="running" instanceType="t3.nano" architecture="x86_64" platformDetails="Linux/UNIX"
]
desiredCapacity: 1
capacityRebalance: true
availabilityZones: [
0: "us-west-2a"
1: "us-west-2b"
2: "us-west-2c"
3: "us-west-2d"
]
tags: {
eks:cluster-name: "tim_test"
eks:nodegroup-name: "high_cpu" …
```

Add new fields to aws.autoscaling.group

---

cli/providers/providers.go

This change prints the cmd help when the command could not be executed.
**before**
```shell
> cnquery scan gcp help
x failed to parse cli arguments error="rpc error: code = Unknown desc = missing argument, use `gcp project id`, `gcp organization id`, `gcp folder id`, `gcp instance name`, or `gcp snapshot name`"
```
**after**
```shell
> cnquery scan gcp help
x failed to parse cli arguments error="rpc error: code = Unknown desc = missing argument, use `gcp project id`, `gcp organization id`, `gcp folder id`, `gcp instance name`, or `gcp snapshot name`"
Scan a Google Cloud project
Usage:
cnquery scan gcp [flags]
Flags:
--annotation stringToString     Add an annotation to the asset. (default [])
--asset-name string             User-override for the asset name
--create-snapshot …
```

🧹 print cmd help when the arguments could not be parsed

---

cli/providers/providers.go
providers/atlassian/provider/provider.go
providers/equinix/provider/provider.go
providers/gcp/provider/provider.go

**before**
```
> cnquery scan gcp help
x failed to parse cli arguments error="rpc error: code = Unknown desc = rpc error: code = InvalidArgument desc = missing argument, use `gcp project id`, `gcp organization id`, `gcp folder id`, `gcp instance name`, or `gcp snapshot name`"
```
**new**
```
> cnquery scan gcp help
x missing argument, use `gcp project id`, `gcp organization id`, `gcp folder id`, `gcp instance name`, or `gcp snapshot name`
```

🧹 extract proto error for better cli rendering

---

providers/gcp/resources/access_approval.go
providers/gcp/resources/apikeys.go
providers/gcp/resources/bigquery.go
providers/gcp/resources/compute.go
providers/gcp/resources/dataproc.go
providers/gcp/resources/dns.go
providers/gcp/resources/essential_contacts.go
providers/gcp/resources/gcp.lr.go
providers/gcp/resources/gke.go
providers/gcp/resources/project.go
providers/gcp/resources/services.go

This change makes better use of GCPs service API. It checks if the service is enabled before MQL tries to fetch data (which will return in errors).
```
error: googleapi: Error 403: Compute Engine API has not been used in project example-test before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=example-test then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Details:
[
{
"@type": "type.googleapis.com/google.rpc.Help",
"links": [
{
"description": "Google developers console API activation",
"url": "https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=example-test"
}
]
```

⭐️ check for enabled gcp services

---

providers/os/connection/container/auth/auth.go
providers/os/connection/container/auth/auth_test.go
providers/os/connection/container/image/registry.go
providers/os/connection/container/image_connection.go
providers/os/connection/container/registry_connection.go
providers/os/connection/docker/container_connection.go
providers/os/provider/provider.go
providers/os/resources/discovery/container_registry/registry.go
providers/os/resources/discovery/container_registry/registry_test.go
providers/os/resources/discovery/docker_engine/resolver.go

Fix scanning a registry, this had never worked properly as it was trying to connect to an image instead. Create a new `RegistryConnection` that can discover all images inside the registry and return those.
ECR registry:
```
~/go/bin/cnquery shell container registry 012973331918.dkr.ecr.us-east-1.amazonaws.com      
→ loaded configuration from /Users/preslavgerchev/.config/mondoo/mondoo.yml using source default
Available assets                                                    
> 1. 012973331918.dkr.ecr.us-east-1.amazonaws.com/preslav@e073956021b9
2. 012973331918.dkr.ecr.us-east-1.amazonaws.com/os@64f4252c7916  
```
ACR registry: …

🐛 Fix docker/container registry scanning. Clean the container code a bit

---

providers/os/connection/container/acr/acr_auth_helper.go
providers/os/connection/container/auth/auth.go
providers/os/connection/container/image_connection.go
providers/os/connection/tar/stream.go
providers/os/resources/discovery/container_registry/registry.go
providers/os/resources/discovery/container_registry/resolver.go

* Load the token for the ACR auth helper lazily. That ensures that if there's an error it's not ignored
* Expose the options for the container registry resolver and add default fallbacks. This allows fine-tuning of auth opts against registries. For example, we can now initialise an azure token externally and pass that in.

⚙️ Expose auth options for registry image resolver, load ACR token lazily

---

providers/os/connection/container/auth/options.go
providers/os/connection/container/image/registry.go
providers/os/connection/container/image_connection.go
providers/os/resources/discovery/container_registry/registry.go
providers/os/resources/discovery/container_registry/resolver.go

* Move all `remote.Options` code to `auth/options`
* Ensure that if we pass external opts, those are also passed all the way down to the image fetching
* Remove redundant code

🧹 Refactor auth opts for registries. Pass through opts when pulling registry images

---

providers/k8s/resources/clusterrole.go
providers/k8s/resources/clusterrolebinding.go
providers/k8s/resources/configmap.go
providers/k8s/resources/cronjob.go
providers/k8s/resources/customresource.go
providers/k8s/resources/daemonset.go
providers/k8s/resources/deployment.go
providers/k8s/resources/ingress.go
providers/k8s/resources/job.go
providers/k8s/resources/k8s.lr
providers/k8s/resources/k8s.lr.go
providers/k8s/resources/namespace.go
providers/k8s/resources/networkpolicy.go
providers/k8s/resources/pod.go
providers/k8s/resources/podsecuritypolicy.go
providers/k8s/resources/replicaset.go
providers/k8s/resources/role.go
providers/k8s/resources/rolebinding.go
providers/k8s/resources/secret.go
providers/k8s/resources/service.go
providers/k8s/resources/serviceaccount.go
providers/k8s/resources/statefulset.go

only calculate specs and manifests when requested. This improves memory usage and allocations for the case where we don't use these fields in queries

🧹 calculate k8s specs and manifests on demand

---

providers/k8s/config/config.go

🎉 k8s-10.5.2

---

cli/reporter/reporter.go

This PR enables the v2 json format as standard. The new format is accessible via:
```
cnquery scan local --json
```
or 
```
cnquery scan local --output json
```
For backwards-compatibility, the old format is available via:
```
cnquery scan local --output json-v1
```

🛑 switch to json v2 output format

---

providers/os/connection/snapshot/blockdevices.go
providers/os/connection/snapshot/blockdevices_test.go
providers/os/connection/snapshot/testdata/alma9_attached.json

we've seen this on a few machines including almalinux. the boot volume is not labeled as a boot volume. we've consistently seen in this case that the last of the matching entries is the volume we want. this slight change in logic allows us to ensure we get the last matching entry of the entries.
example:
```
{
"name": "xvdh3",
"fstype": "xfs",
"fsver": null,
"label": null,
"uuid": "bea841a6-6299-40c4-9586-87fedcd61150",
"fsavail": null,
"fsuse%": null,
"mountpoints": [
null
]
},{
"name": "xvdh4",
"fstype": "xfs",
"fsver": null,
"label": null,
"uuid": "e2445d71-21eb-4c58-a6f7-f8009badd586",
"fsavail": null,
"fsuse%": null,
"mountpoints": [
null
]
}
```
xvdh3 is actually a boot volume, xvdh4 is what we care about

🧹 ensure we grab the non-boot volume when multiple xfs uuid volumes

---

providers/coordinator.go
providers/coordinator_test.go

We have a race condition where providers can be killed at the moment a scan is starting. Then we see errors like: https://github.com/mondoohq/mondoo-operator/issues/1091 This problem occurs specifically when we can start concurrent scans with a single cnspec instance. Currently, that is only when using `serve-api` command.
The issue is that the providers list in runtime isn't using a lock so we can run into race conditions. I changed the implementation to only kill providers if there are no active runtimes, since at the moment we don't have a thread-safe way to compare the providers for each runtime

🐛 fix provider shutdown race condition

---

sbom/sbom.mql.yaml

This updates the pack to use the latest filter structure to avoid warnings on command line:
```
! Found an old use of filters (as a list of strings). This will be removed in the next major version. Please migrate to:
- mql: filter 1
- mql: filter 2
```

🧹 use new filters

---

providers/os/resources/packages/rpm_packages.go

For versions like `attr 2.4.48-1.ph4` we only returned `attr 2.4.48` and `-1.ph4` was missing.

🐛 return the rpm version including the release when static analysis is used

---

providers/os/config/config.go

🎉 os-11.0.1

---

providers/aws/connection/clients.go
providers/aws/go.mod
providers/aws/go.sum
providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_inspector.go
providers/aws/resources/aws_lambda.go

```
}
7: {
scanType: "PACKAGE"
resourceId: "i------------"
resourceType: "AWS_EC2_INSTANCE"
ecrRepo: null
lambda: null
statusReason: "UNMANAGED_EC2_INSTANCE"
ecrImage: null
statusCode: "INACTIVE"
ec2Instance: aws.inspector.coverage.instance id = us-east-1/owner/patrick@mondoo.com/Name/amazonlinux2-for-ebs-volume-scan/
lastScannedAt: null
accountId: "921877-----"
}
]
```

✨ add inspector resource to show ec2,ecr,lambda coverage

---

providers/os/provider/provider.go

A simple update that uses pre-defined keywords instead of strings, for those cases where we already extensively have keywords.

🧹 os: re-use conf-type keywords

---

featureflags.go
llx/llx.go
mql/mql_test.go
mqlc/mqlc.go

We had this feature-flag since v7, aimed to make it the default in v8. Until now, it has not been mainlined.
This is changing today. Compiling with context is generally very helpful and provides nice auto-complete on embedded resources (similar to how you can access embedded fields in golang structs).
There is more work to be done, namely that we want to tie the context of the connection to the MQL execution itself. This will allow us to call fields without constantly refering to the global context in the future. (i.e. instead of `docker.file.sth`, once you connect to a Dockerfile you can just call `sth`). For this reason, we retain the feature-flag and will complete its functionality in this major release.
Note: I deactivated one level of functionality which had been degraded since v9, …

🧹 default to MQL asset context

---

providers/gcp/resources/bigquery.go

This is required to make sure this works with the application default credentials. Otherwise, they are rejected even if the service account has the correct permissions

🐛 Add oauth scope for bigquery calls

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_elb.go

This is pretty important information for a load balancer
```coffee
aws.elb.loadBalancers.first: {
0: aws.ec2.securitygroup id="sg-1234567" name="default" region="us-west-2" vpc.id="vpc-1234567"
]
hostedZoneId: "12345678910"
availabilityZones: [
0: "us-west-2b"
1: "us-west-2a"
]
}
```

Add securityGroups, availabilityZones, and hostedZoneId to ELBs

---

llx/data_conversions.go
llx/rawdata.go

We currently don't have deep support for int-maps, since we don't have any use-cases for them yet. That said, they have been supported in the underlying stack for when we need them. Unfortunately a few of the supporting elements have been out of sync.
This change aligns data conversions in llx to use int64 maps. Ditto for `isTruthy` in rawdata. There are a few more to tackle...

🐛 fix int-map key types

---

providers/aws/config/config.go
providers/azure/config/config.go
providers/gcp/config/config.go

🎉 aws-11.0.3, gcp-11.0.3, azure-11.0.3

---

providers/slack/config/config.go

🎉 slack-11.0.3

---

Makefile

We were pointing at the wrong path for the YAML files

Fix incorrect generation of OS and MS365 resource packs

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_elb.go

Instead of giving someone an ID we should give them the actual resource. This is where MQL really shines. This is somewhat copy/paste from ec2 land.
```coffee
aws.elb.loadBalancers.first.vpc: {
state: "available"
cidrBlock: "172.31.0.0/16"
instanceTenancy: "default"
arn: "arn:aws:vpc:us-west-2:12345678910:id/vpc-1234567"
id: "vpc-1234567"
routeTables: [
0: aws.vpc.routetable id="rtb-1234567" routes.length=2
]
endpoints: []
isDefault: true
tags: {}
flowLogs: []
subnets: [
0: aws.vpc.subnet id="subnet-1234567" cidrs="172.31.32.0/20" availabilityZone="us-west-2a" defaultForAvailabilityZone=true
1: aws.vpc.subnet id="subnet-1234567" cidrs="172.31.0.0/20" availabilityZone="us-west-2c" defaultForAvailabilityZone=true
2: aws.vpc.subnet id="subnet-1234567" …
```

Replace vpcId with vpc in the elb resource

---

providers/os/resources/dockerfile.go
providers/os/resources/os.lr
providers/os/resources/os.lr.go
providers/os/resources/os.lr.manifest.yaml

1. Adds support for the `EXPOSE` keyword in dockerfiles. Adds them as a list of entries and defaults the protocol if not set
2. Fixes a bug where IDs were not set for a range of docker resources
3. Removes the warnings for unsupported keywords in Dockerfiles. We already know what can be supported by looking at the fields we expose.
Looking deeper into the library too, we have a bit more work to properly support some of the contextual keywords...

✨ dockerfile.expose

---

providers-sdk/v1/lr/cli/cmd/markdown.go

The way the filestat was being checked if a user gave an incorrect path we'd love that the file was not provided and move on. These should always be provided so let's just not include this check entirely.
I also improved a bit of text while I was in here and fixed incorrect help

🧹 make lr docs yaml file loading for markdown generation more robust

---

providers/gcp/resources/compute.go

I got this error when scanning a gcp project with a service account:
```
error: rpc error: code = Unknown desc = googleapi: Error 403: Request had insufficient authentication scopes.
Details:
[
{
"@type": "type.googleapis.com/google.rpc.ErrorInfo",
"domain": "googleapis.com",
"metadatas": {
"method": "compute.v1.ZonesService.List",
"service": "compute.googleapis.com"
},
"reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT"
}
]
More details:
Reason: insufficientPermissions, Message: Insufficient Permission
```
the change fixes it

🐛 gcp: add compute scope when listing zones

---

providers/gcp/config/config.go

🎉 gcp-11.0.4

---

providers/slack/config/config.go
providers/slack/connection/connection.go
providers/slack/provider/provider.go
providers/slack/resources/team.go
providers/slack/resources/users.go

This change is required to support org tokens which supports accessing multiple teams.

🧹 introduce a new --team-id argument for slack provider

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_vpc.go

Also cleanup some descriptions and add region into the defaults for aws.vpc.subnet
```coffee
cnquery> aws.vpcs.first.subnets.first{*}
aws.vpcs.first.subnets.first: {
availabilityZone: "ap-south-1c"
cidrs: "172.31.16.0/20"
arn: "arn:aws:ec2:ap-south-1:1234:subnet/subnet-1234"
region: "ap-south-1"
assignIpv6AddressOnCreation: false
id: "subnet-1234"
mapPublicIpOnLaunch: true
state: "available"
defaultForAvailabilityZone: true
}
```

⭐ Add region to aws.vpc.subnet

---

providers/aws/resources/aws.lr
providers/aws/resources/aws_elb.go

This was already added to the NLB/ALBs
```coffee
aws.elb.classicLoadBalancers: [
0: aws.elb.loadbalancer name="tim-classic" region="us-west-2" elbType="classic" scheme="internal" vpcId="vpc-1234" dnsName="internal-tim-classic-1234.us-west-2.elb.amazonaws.com"
]
```

⭐ Add ELB region + elbType to the classic load balancers

---

providers/gcp/resources/discovery.go

make sure when we scan a gcp org, we also discover all the resources under a project
~TODO: this needs to be tested to confirm it works correctly~

🐛 fully discover gcp orgs

---

providers/gcp/config/config.go

🎉 gcp-11.0.5

---

providers/coordinator.go

In #3775 a race condition in providers shutdown logic has been addressed. The issue described there almost never happens now but there are still some cases where we see the error: `ERR error encountered while scanning stdout error="read |0: file already closed"`
I went through the code and the only other reason where things may go wrong is if we have unprocessed runtimes at the moment we check for provider cleanup. I think to fix this case we need to make sure that there are no runtimes and no unprocessed runtimes before killing any providers.

🐛 fix coordinator race for shutting down providers

---

.github/actions/spelling/expect.txt
providers/gcp/resources/gcp.lr
providers/gcp/resources/gcp.lr.go
providers/gcp/resources/gcp.lr.manifest.yaml
providers/gcp/resources/gke.go

Grab additional configuration data for the cluster network config

Add more fields to gcp.project.gkeService.cluster.networkConfig

---

providers/os/resources/os.lr

files{content} was getting parsed as mdx and causing docusaurus failures

Fix a docs server failure due to field description

---

providers/os/config/config.go

🎉 os-11.1.0

---

providers-sdk/v1/sysinfo/sysinfo.go
providers/os/id/platform.go
providers/os/provider/detector.go
providers/os/provider/provider.go
providers/os/provider/provider_test.go

We were getting platform identity information multiple times. We would
connect, then see the asset's platform not set, and redo it.

 🧹 Reduce the number of times we try to get platform ident

---

providers/github/config/config.go
providers/github/connection/connection.go
providers/github/go.mod
providers/github/provider/provider.go
providers/github/resources/discovery.go
providers/github/resources/discovery_test.go

We can now filter out github repos using globs:
```
cnquery scan github org podkrepi-bg --repos-exclude api,frontend
```
```
cnquery scan github org podkrepi-bg --repos api,frontend
```

⭐️ support filtering discovered github repos

---

providers/github/config/config.go

🎉 github-11.1.2

---

providers/azure/config/config.go
providers/azure/resources/discovery.go

Added for the fine grained assets. Everything is prefixed with `azure/tenant/subscription`.

🧹 Add asset urls for azure

---

providers/os/connection/docker/dockerfile_connection.go
providers/os/provider/provider.go
providers/os/resources/docker_file.go
providers/os/resources/user.go

Fixes #3813
* Replace the FS conn with a local connection as we need this to able to fully resolve the docker file's properties (such as the owner).
* Inject the local OS's family into the dockerfile asset to help the local connection run the right commands to be able to fetch users
* Improve error messages that come from the users manager

🐛 Replace fsconn with local connection for docker files, allow running commands

---

apps/cnquery/cmd/root.go
apps/cnquery/cmd/scan.go
cli/inventoryloader/inventory.go
cli/inventoryloader/inventory_test.go

When cnquery is used in CI/CD pipelines, users want to leverage the inventory file which allows a lot of pre-configuration. If you want to scan different assets for different environments you also want to re-use the same template but allow some custom variables so that usage in CI/CD is easier. This PR introduces inventory templates. Just define a template and use the `getenv` function to access environment variables:
```yaml
spec:
assets:
- name: {{ getenv "ASSET_NAME" }}
connections:
- type: local
discover:
targets:
- auto
annotations:
application:  {{ getenv "APPLICATION" }}
```
This inventory can now be used as following:
```shell
ASSET_NAME="my_asset" APPLICATION="my-super-app" cnquery scan --inventory-template template.yaml
```

⭐️ inventory template support

---

providers/arista/config/config.go
providers/atlassian/config/config.go
providers/aws/config/config.go
providers/azure/config/config.go
providers/equinix/config/config.go
providers/gcp/config/config.go
providers/gitlab/config/config.go
providers/google-workspace/config/config.go
providers/ipmi/config/config.go
providers/k8s/config/config.go
providers/ms365/config/config.go
providers/oci/config/config.go
providers/okta/config/config.go
providers/opcua/config/config.go
providers/os/config/config.go
providers/slack/config/config.go
providers/terraform/config/config.go
providers/vcd/config/config.go
providers/vsphere/config/config.go

```
arista-11.0.6, atlassian-11.0.7, aws-11.0.8, azure-11.0.7, equinix-11.0.6, gcp-11.0.9, gitlab-11.0.6, google-workspace-11.0.6, ipmi-11.0.6, k8s-11.0.6, ms365-11.0.6, oci-11.0.6, okta-11.0.6, opcua-11.0.6, os-11.1.3, slack-11.0.8, terraform-11.0.6, vcd-11.0.6, vsphere-11.0.6
```

🎉 Update providers 20240509

---

providers/os/connection/snapshot/blockdevices.go
providers/os/connection/snapshot/blockdevices_test.go
providers/os/connection/snapshot/testdata/fedora_attached.json

we were incorrectly relying on the fsuse field before, this fixes that

🐛 properly handle volumes for fedora snapshot scanning

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_ssm.go

```
1: {
name: "MondooAgentToken"
description: null
dataType: "text"
allowedPattern: null
tier: "Standard"
kmsKey: null
type: "String"
arn: "arn:aws:ssm:us-east-1:9218------:parameter/MondooAgentToken"
version: 3
lastModifiedDate: 2022-06-25 20:43:58.299 -0600 MDT
}
2: {
name: "MondooEnvSSMParam"
description: null
dataType: "text"
allowedPattern: null
tier: "Standard"
kmsKey: null
type: "String"
arn: "arn:aws:ssm:us-east-1:9218------:parameter/MondooEnvSSMParam"
version: 3
lastModifiedDate: 2024-01-29 02:24:09.296 -0700 MST
}
```

✨ add ssm parameters resource

---

providers/gcp/resources/compute.go

Fixes the following issue:
```
→ selected asset asset=gke-cluster selection=1
→ connected to GCP Compute Network
___ _ __  ___ _ __   ___  ___ 
/ __| '_ \/ __| '_ \ / _ \/ __|
| (__| | | \__ \ |_) |  __/ (__ 
\___|_| |_|___/ .__/ \___|\___|
mondoo™     |_|              
cnspec> gcp.compute.network.subnetworks.length
[gcp] cannot set 'region' in resource 'gcp.project.computeService.subnetwork', type does not match
gcp.compute.gcp.project.computeService.network.subnetworks.length: no data available
```
Now:
```
→ selected asset asset=gke-cluster selection=1
→ connected to GCP Compute Network
___ _ __  ___ _ __   ___  ___ 
/ __| '_ \/ __| '_ \ / _ \/ __|
| (__| | | \__ \ |_) |  __/ (__ 
\___|_| |_|___/ .__/ \___|\___|
mondoo™     |_|              
cnspec> …
```

🐛 fix getting gcp compute subnetworks for a network

---

providers/gcp/config/config.go

🎉 gcp-11.0.10

---

providers/azure/resources/discovery.go

Only do so if explicitly asked. This means that `auto` and `all` will skip it.

🧹 Do not discover azure vms twice.

---

providers/aws/resources/aws.lr

We can't use | because that makes a new table column

Fix markdown in some AWS resource descriptions

---

providers/os/config/config.go
providers/os/connection/container/image_connection.go
providers/os/connection/container/registry_connection.go
providers/os/connection/shared/shared.go
providers/os/provider/provider.go
providers/os/resources/discovery/container_registry/registry.go
providers/os/resources/discovery/container_registry/resolver.go

we can now specify a container proxy for scanning containers:
```
cnquery scan docker ubuntu:latest --container-proxy http://localhost:3128
```
this is different from the `api-proxy` setting, which is used only to talk to the Mondoo platform. The `container-proxy` flag is used only for resolving and pulling containers

⭐️ add container-proxy flag for scanning containers

---

providers/os/config/config.go

🎉 os-11.2.0

---

providers/k8s/config/config.go

🎉 k8s-11.1.0

---

providers/os/connection/docker/docker_file_connection.go
providers/os/connection/docker/docker_file_connection_test.go
providers/os/resources/docker_file.go

Fixes https://github.com/mondoohq/cnquery/issues/3962
* Renamed the file because my editor was complaining about the name being `dockerfile*`
* Returned the full absolute path instead of the relative path
* Added tests that cover this change

:bug: docker file `Dockerfile` not found

---

providers/os/config/config.go

🎉 os-11.2.1

---

providers-sdk/v1/sysinfo/sysinfo.go
providers/os/id/platform.go

`SystemInfo.Get` used to return an error if it couldn't get the platform information.
This regressed in https://github.com/mondoohq/cnquery/pull/3660 where nil platform info stopped returning an error

🐛 Return error if no platform information

---

providers/network/config/config.go
providers/network/connection/connection.go
providers/network/resources/http.go

Changed the `insecure` flag to bool. No idea why it was a string. Also added an HTTP client to the host connection, so we define all the properties in 1 place and re-use them where needed.
```
╰─ cnspec shell host https://localhost --insecure
→ loaded configuration from /Users/ivanmilchev/.config/mondoo/mondoo.yml using source default
→ connected to Network Host
___ _ __  ___ _ __   ___  ___ 
/ __| '_ \/ __| '_ \ / _ \/ __|
| (__| | | \__ \ |_) |  __/ (__ 
\___|_| |_|___/ .__/ \___|\___|
mondoo™     |_|              
cnspec> http.get
http.get: http.get url=url id = https://localhost:443 statusCode=200
```
Fixes #3995

🐛 properly handle insecure flag for host scans

---

providers/aws/resources/aws.lr

This improves the output of attached disks when querying the whole instance:
Old:
```
deviceMappings: [
0: aws.ec2.instance.device id = vol-09dce9b718d427cf5
]
```
New:
```
deviceMappings: [
0: aws.ec2.instance.device deviceName="/dev/sda1" volumeId="vol-09dce9b718d427cf5" status="attached"
]
```

:star: Improve default values for AWS instance block devices

---

providers/ms365/resources/groups.go
providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml

⭐️ Adding a resouces to the Microsoft Graph under group (MS365)

---

providers/azure/resources/azure.lr

ID is pretty useless and it's multiple lines long. Replace it with the DB version and FQDN instead.

Better defaults for azure resources

---

providers/coordinator.go
providers/coordinator_test.go
providers/running_provider.go
providers/runtime.go

This should minimize the impact of errors we have observed with the scan API. If a provider crashes, it doesn't get properly cleaned up and results in endless loop of failed scans because no provider instance is available. This change makes sure we remove dead providers after each scan, such that the next scan can start with a fresh provider.
This still has the issue that if we have 1 scan with 300 assets and the provider crashes after scanning the first asset, we will get 299 errors for the remaining assets. The issue should be gone with the next scan. A better approach is to detect that a provider instance is dead before connecting to it, if that is the case, we should implement restart logic. That should happen inside the runtime, since we keep a reference to the `RunningProvider` in …

🐛 remove dead providers from coordinator

---

llx/rawdata_test.go

This ensures the test names are always stable, which means we no longer get this from the test reporting on every PR:

🧹 Use a const time for llx tests.

---

providers/coordinator.go
providers/coordinator_test.go

we are currently leaking memory for long-running cnquery/cnspec instances because the coordinator is keeping around closed unprocessed runtimes. This PR makes sure we throw away these runtimes

🐛 don't keep closed unprocessed runtimes in coordinator

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_account.go
providers/aws/resources/discovery.go
providers/aws/resources/discovery_conversion.go

```
go run apps/cnquery/cnquery.go shell aws --discover organization --role arn:aws:iam::ACCOUNTID:role/test-org-list-accounts-role
```
```
cnquery> aws.account {  organization {accounts }}
aws.account: {
organization: {
accounts: [
0: aws.account id="8913...."
1: aws.account id="0724...."
```
```
→ connected to AWS Account
cnquery> aws.account.id
aws.account.id: "8913..."
```

✨ add accounts to the aws organization resource, --organization discovery

---

providers-sdk/v1/util/version/version.go
providers/atlassian/config/config.go
providers/defaults.go
providers/gcp/config/config.go
providers/mock.go
providers/okta/config/config.go
test/commands/testdata/cnquery_run.ct
test/commands/testdata/cnquery_scan.ct

Right now it's all over the place and we're not describing the actual things we scan within these larger technologies properly
Now:
```
Available Commands:
arista           Scan an Arista EOS device
atlassian        Scan an Atlassian Cloud Jira, Confluence or Bitbucket instance
aws              Scan an AWS account
azure            Scan an Azure subscription
container        Scan a running container or container image
docker           Scan a running Docker container or Docker image
equinix          Scan an Equinix Metal organization
filesystem       Scan a mounted file system target
gcp              Scan a Google Cloud project or folder
github           Scan a GitHub organization or repository
gitlab           Scan a GitLab group or project
google-workspace Scan a Google Workspace account …
```

Update the help text with consistent provider descriptions

---

providers/github/config/config.go

🎉 github-11.2.0

---

providers/aws/resources/aws.lr

Minor tweaks to make things more consistent

Update wording in RDS MQL docs

---

providers/network/resources/tlsshake/tlsshake.go

It was possible for the following query to hang
```
tls.ciphers
```
This happened in cases where the server response with a `HelloRetryRequest`. This looks like a `ServerHello` until you check the random field of that message.
We ended up hanging because we thought the server replied successfully with a hello and were waiting for more data, and the server was waiting for us to write.

🐛 prevent hang when HelloRetryRequest is returned

---

providers/aws/resources/discovery_conversion.go

the ecr-credential-helper library had tag based examples that we used when adding in the functionality. those aren't actually needed, we just need the full uri this changes to code to do that so we will no longer skip no-tag images

🐛 ensure we scan all ecr images, do not rely on tags

---

sbom/sbom.go

🧹 Prevent panic for unsupported operating systems

---

providers/github/config/config.go

- GitHub calls these apps not applications.
- Make sure it's clear we're asking for the path to a pem file not the pem contents as a string

Improve test in GitHub app scanning help

---

providers/network/resources/tlsshake/tlsshake.go

When testing for supported ciphersuites, some servers fail the check with:
```
read: connection reset by peer
```
This seems to consistently happen on these servers. And it seems to happen on requests where the only ciphersuites in the `ClientHello` are unsupported ones

🐛 Assume connection reset means the server rejects all ciphersuites

---

providers/azure/resources/azure.lr

```coffee
azure.subscription.compute.vms.first.publicIpAddresses: [
0: azure.subscription.networkService.ipAddress name="test-ip" location="westus" ipAddress="40.112.145.65"
]
```
This makes it possible to see the IP address attached to a VM without having to query into the IP as well

Use better defaults for the Azure IP addressess

---

providers/network/config/config.go

not sure why it was hidden in the first place

🧹 do not hide insecure flag for network provider

---

providers/os/connection/device/device_connection.go
providers/os/connection/device/device_manager.go
providers/os/connection/device/linux/device_manager.go
providers/os/connection/device/shared/mountinfo.go
providers/os/connection/snapshot/blockdevices.go
providers/os/connection/snapshot/blockdevices_test.go
providers/os/connection/snapshot/volumemounter.go

Split the detection of the partition we're mounting from the actual mounting process. To not make any changes to existing code that's using the volume mounter, I've added two new functions there:  `GetDeviceForMounting` and `MountP` (artition)
The device manager's interface was also reworked:
* Changed `IdentifyBlockDevice` to `IdentifyMountTargets` to better account for the fact we can have multiple targets (even if unimplemented)
* `Mount` now returns the scan dir where it was mounted

🧹 Add new methods for detecting and mounting in the volume mounter.

---

providers/os/config/config.go
providers/os/provider/provider.go

Aligns the provider with #4105 by having the path as an arg.  Passing it in as a flag is still supported, but deprecated

🧹 Make path an arg, not a flag for the FS conn.

---

providers/github/connection/platform.go
providers/github/resources/discovery.go

We can now do terraform discovery for github. Things to note:
- to discover terraform, we need to discover the repo too, this means we provide 2 flags now
```
cnspec scan github repo mondoohq/X--discover repository,terraform 
```
- we use mql to loop over the files and check for terraform files. This means we are caching the directory tree for the repo as we go. Later we can use the same approach when looking for k8s manifests and dockerifiles and can work with the cached tree
- we are cloning the repos in the terraform provider on `Connect`, which means if I am currently scanning a github org, we will pull all repos with terraform files immediately on discovery... We need to change that to only clone the repos on starting the scan and not before. (delayed discovery)
- we probably need to …

⭐️ github terraform discovery

---

providers/os/connection/device/linux/device_manager.go
providers/os/connection/snapshot/blockdevices.go
providers/os/connection/snapshot/blockdevices_test.go
providers/os/connection/snapshot/volumemounter.go

* Rename `GetDeviceForMounting` to `GetMountablePartition`
* Rename `GetBlockByEntryName` to `GetMountablePartitionByDevice`
* Change the cmd we run to be more extensible, using `lsblk -o OPTS` allows us to include things easily.
* Sort all suitable partitions and pick the largest one. In the case where we have non-mounted, non-boot partitions and we cannot distinguish between them, we simply take the biggest one
* Update tests

🧹 Rename functions in blockdevices.go. Add more tests, sort suitable partitions by size before choosing one.

---

providers/aws/connection/clients.go
providers/aws/go.mod
providers/aws/go.sum
providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_sqs.go

✨ aws.sqs.queues resource

---

.github/actions/spelling/expect.txt
providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_ec2.go
providers/aws/resources/aws_vpc.go

✨ add []aws.ec2.networkinterface to aws.ec2.instance

---

.github/actions/spelling/expect.txt
providers/gcp/go.mod
providers/gcp/go.sum
providers/gcp/resources/binary_authorization.go
providers/gcp/resources/gcp.lr
providers/gcp/resources/gcp.lr.go
providers/gcp/resources/gcp.lr.manifest.yaml
providers/gcp/resources/services.go

```
cnquery> gcp.project.binaryAuthorization { policy { * } }
gcp.project.binaryAuthorization: {
policy: {
kubernetesServiceAccountAdmissionRules: {}
name: "projects/manuel-development-3/policy"
globalPolicyEvaluationMode: "GLOBAL_POLICY_EVALUATION_MODE_UNSPECIFIED"
defaultAdmissionRule: gcp.project.binaryAuthorizationControl.admissionRule id = projects/manuel-development-3/policy/defaultAdmissionRule
admissionWhitelistPatterns: [
0: "asia.gcr.io/gke-multi-cloud-release/**"
1: "asia.gcr.io/google-containers/addon-resizer:*"
...
```

✨ Add gcp binary authorization resource

---

explorer/scan/discovery.go
providers/github/resources/discovery.go
providers/gitlab/provider/discovery.go
providers/gitlab/provider/provider.go

- add k8s manifest discovery for gitlab scans
- skip over mql yaml files for gitlab and github
- fix panic in cnquery when no k8s manifests are discovered for a cloned repo
```
./cnquery scan gitlab --group mondoolabs --discover k8s-manifests
```

⭐️ gitlab k8s manifest discovery

---

providers/gcp/resources/gke.go

Fixes the following error message
```
failed to convert dict to primitive, unsupported child type: containerpb.NetworkPolicy_Provider
```
Fixes #3868

🐛 Fix bug in gke networkPolicyConfig

---

providers/os/connection/device/device_connection.go

just in case conf.Options is nil
```
/home/runner/_work/_tool/go/1.22.2/x64/src/runtime/panic.go:770 +0x124
go.mondoo.com/cnquery/v11/providers/os/connection/device.NewDeviceConnection(0x1, 0x40003d80f0, 0x4000f76640)
/home/runner/_work/purplebox-aws/cnquery/providers/os/connection/device/device_connection.go:74 +0x274
go.mondoo.com/cnquery/v11/providers/os/provider.(*Service).connect.func1(0x1)
```

🐛 guard against assignment to entry in nil map in device connection

---

explorer/scan/discovery.go
explorer/scan/discovery_test.go

if we discover multiple assets with the same platform IDs, they will get their runtimes messed up. We will close the runtime and the first asset will show errors that the connection was not found. We need to skip over duplicate assets before creating runtime for them

🐛 fix missing connections for discovered duplicate assets

---

docs/development.md

This is what our `go.mod` says https://github.com/mondoohq/cnquery/blob/main/go.mod#L3

📝 Update go version to 1.22 in development.md

---

providers/gcp/config/config.go

🎉 gcp-11.0.16

---

.github/actions/spelling/expect.txt
providers/os/resources/os.lr
providers/os/resources/os.lr.go
providers/os/resources/os.lr.manifest.yaml
providers/os/resources/windows.go
providers/os/resources/windows/optionalfeatures.go
providers/os/resources/windows/optionalfeatures_test.go
providers/os/resources/windows/testdata/optionalfeatures.json

✨ Add windows.optionalfeatures resource

---

providers/os/resources/os.lr

- Colons get removed as we convert to markdown so don't use those here
- Use the full name of the resources
- Clarify that optionalFeatures is desktop only

Update deprecation documentation for windows resources

---

.goreleaser.yml

With this change, it can override the existing release files. This can help in case something goes wrong.

🧹 Allow re-running the goreleaser job

---

providers/coordinator.go
providers/coordinator_test.go

i noticed we never kill the unused providers in the scan api mode because we always have a couple of empty unprocessed runtimes (that are used for initializing the scanner). Those shouldn't block cleaning up unused providers

🐛 shutdown unused providers

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_applicationautoscaling.go

It's useful to know when this was created

Add `createdAt` to aws.applicationautoscaling.target

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_ec2.go

Images have an EOL date
```
aws.ec2.instances.first.image: {
ownerAlias: "amazon"
deprecatedAt: 2026-02-13 21:24:09 -0800 PST
id: "ami-0f9c44e98edf38a2b"
architecture: "x86_64"
ownerId: "801119661308"
createdAt: 2024-02-13 21:24:09 -0800 PST
arn: "arn:aws:ec2:us-east-1:177043759123:image/ami-0f9c44e98edf38a2b"
name: "Windows_Server-2022-English-Full-Base-2024.02.14"
}
```

Add `deprecatedAt` field to aws.ec2.image

---

providers/os/registry/registrykey_windows.go
providers/os/resources/packages/windows_packages.go
providers/os/resources/packages/windows_packages_test.go

After #4203 
Instead of running a powershell script, query the registry directly for the installed apps.

🧹 Use the registry directly to fetch Windows packages

---

providers/os/registry/registryhandler.go
providers/os/resources/packages/windows_packages.go

After #4204 
```
PS C:\Users\mondoo> ./cnquery run fs --path F:\ -c 'packages'
Flag --path has been deprecated, has been deprecated
Flag --path has been deprecated, has been deprecated
WRN using builtin provider for os
WRN no path provided as an arg, looking for --path flag
WRN using builtin provider for os
- no Mondoo configuration file provided, using defaults
WRN using builtin provider for os
packages.list: [
0: package name="Microsoft Edge" version="124.0.2478.97"
]
```

✨ Fetch registry packages for Windows filesystem connections

---

providers/os/registry/registryhandler_windows.go

Proof-of-concept that we can use the `reg` command instead of the syscall that doesn't seem to work when running with `SYSTEM` user.
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/reg
This ain't pretty...

🔥🪟 use reg.exe to (un)load sub keys

---

providers/os/config/config.go
providers/os/connection/device/device_connection.go
providers/os/connection/device/windows/device_manager.go
providers/os/connection/device/windows/device_manager_test.go
providers/os/connection/device/windows/disk_drive.go
providers/os/connection/device/windows/disk_drive_test.go
providers/os/provider/provider.go
providers/os/registry/registryhandler_windows.go
providers/os/resources/packages/windows_packages.go

Add support for identifying the drive letter where the windows partition is located by only specifying the LUN (logical unit number) or the serial number of the disk.
```
./cnquery.exe shell device --serial-number 123455
```
```
./cnquery.exe shell device --lun 2
```
There's also support for setting a disk online if it's found to be offline. This only happens if we that this is the target disk that we're searching for. Once scanning is done, the disk is set back to offline.

✨ Add basic support for scanning windows disk drives via device conn.

---

providers/aws/resources/aws_iam.go

just an extra error catch for rate limit exceeded errors

🧹 catch rate limit errors earlier when getting credential report

---

providers/os/connection/shared/shared.go
providers/os/fs/find_files.go
providers/os/fs/find_files_test.go
providers/os/fs/fs.go
providers/os/resources/files.go

When we search for riles with `RunCommand` capability, we use `find`. There we can provide permissions filters. In the cases, where we have no `RunCommand` capability we are manually looping over the filesystem files. 
The manual loop we have doesn't check for permissions matching. This is problematic for some queries that we have in our policies. For example:
```
files.find(from: "/", type: "file", xdev: false, permissions: 0002).all(path == "")
files.find(from: "/", type: "directory", xdev: false, permissions: 0002).all(permissions.sticky == true)
```
If we try to execute these queries in a filesystem scan (where no `RunCommand` capability is present), we will be adding all the files on the filesystem as an mql resource. This is very CPU and memory intensive and we have already …

⭐️ allow finding files by permissions

---

providers/os/config/config.go

🎉 os-11.2.10

---

providers/k8s/connection/manifest/connection_test.go
providers/k8s/resources/discovery.go

🧹 add k8s services to discovery

---

providers/os/config/config.go

🎉 os-11.2.11

---

providers/ms365/resources/ms365_exchange.go

A panic happens when we get back a null teams protection policy

🐛 Fix panic in ms365 provider

---

providers/azure/resources/azure.lr

```coffee
cnquery> azure.subscription.sql.servers.first
azure.subscription.sql.servers.first: azure.subscription.sqlService.server name="timtimtimtim" location="eastus" properties.version="12.0" properties.state="Ready" properties.fullyQualifiedDomainName="timtimtimtim.database.windows.net"
cnquery> azure.subscription.sql.servers.first.databases
azure.subscription.sql.servers.first.databases: [
0: azure.subscription.sqlService.database name="master" edition="System" zoneRedundant=false status="Online" creationDate=2024-06-12 12:20:08.777 -0700 PDT maxSizeBytes=53687091200 earliestRestoreDate=null
]
```

Improve defaults for Azure SQL resources + fix some branding

---

providers/gcp/resources/compute.go
providers/gcp/resources/gcp.lr
providers/gcp/resources/gcp.lr.go
providers/gcp/resources/gcp.lr.manifest.yaml
providers/gcp/resources/gke.go

🐛 fix gcp subnetwork navigation from gke resources

---

providers/os/resources/packages/rpm_packages.go

This helps us do better vulnerability assessment when performing static analysis of RPM packages.
Thank you @czunker for the help with this one

🐛 Assign epoch in RPM static package manager.

---

mqlc/mqlc_test.go

#4225  added new defaults for the resource that this test uses

🧹 Fix mqlc checksum test

---

providers/os/fs/find_files.go
providers/os/fs/find_files_unix.go
providers/os/fs/find_files_windows.go

If files do not exist, we return `nil` from the `handleFsError` which means the `WalkDir` doesn't skip over that specific file. This lead to panics when running `files.find` query against an FS connection, e.g. `files.find(from: "/etc/audit/rules.d",regex:'.*\.rules$' , type: "file")`

🐛 Fix find files panic for FS connections.

---

providers/os/connection/device/linux/lun.go
providers/os/connection/device/linux/lun_test.go

Slight improvement to how we determine what block device we should scan when there's more than one candidate. We look for a block device with 0 mounted partitions. Improve logging as well to make it clear

🧹 Only consider devices via LUN when they have no mounted partitions at all

---

mqlc/mqlc_test.go
providers/aws/resources/discovery.go

I'm not sure why I needed the second commit/why that test failed..

🧹 ensure we always read the fine grained assets FF for AWS

---

providers/azure/provider/provider.go
providers/azure/resources/discovery.go

* Use parent connections to take advantage of MQL cache.
* Ensure we do not discover subs multiple times, that's redundant

🏃 Improve azure provider performance

---

providers/azure/resources/discovery.go

Do not clone the inventory twice, ensure all new inventories for sub-assets do not have discovery on.

🧹 Small code improvements around azure mql resources.

---

providers/aws/connection/awsec2ebsconn/provider.go

Even though we tell AWS to mount the block somewhere it's no guarantee it will end up there. We drop the `device-name` config option and let the device connection find the partition itself.

🐛 Do not set device name for aws ebs conn.

---

providers/gcp/config/config.go
providers/os/config/config.go

🎉 os-11.2.13, gcp-11.0.22

---

providers-sdk/v1/util/azauth/token.go

We've seen some transient errors around fetching the managed identity when using the azure sdk. This PR changes the handler we use to allow for retries so that we can handle this better

🧹 Allow retrying fetching of Azure managed identity credential.

---

providers/google-workspace/resources/calendars.go
providers/google-workspace/resources/google-workspace.go
providers/google-workspace/resources/google-workspace.lr
providers/google-workspace/resources/google-workspace.lr.go
providers/google-workspace/resources/google-workspace.lr.manifest.yaml

Adds support for google workspace calendars and their acl rules.
New scopes required for the permissions:
```
https://www.googleapis.com/auth/calendar.readonly
https://www.googleapis.com/auth/calendar.settings.readonly
https://www.googleapis.com/auth/calendar
```
Note that the last scope is not a readonly scope but it is required to retrieve the ACL for the calendars as per [Google's documentation](https://developers.google.com/calendar/api/v3/reference/acl/list#auth)
Fixes #4271

✨ add google workspace calendar and acl resources

---

providers/os/connection/docker/file.go

Fixes #8322
To trigger the issue use the following Dockerfile:
```Dockerfile
FROM wordpress
RUN touch /root/known_host
RUN mkdir /var/www/.ssh
RUN ln -s /root/known_hosts /var/www/.ssh/known_hosts
```
Or just pull the image from my repo: `ivanmilchev/test:loop` (I provided amd64 and arm64 images)
1. Run the image: `docker run -d ivanmilchev/test:loop`
2. Get the running container ID with `docker ps`
3. Run a container scan for the running container `cnspec scan docker <<CONTAINER_ID>>` (it must be cnspec. The issue isn't present in cnquery)
With the updated provider from this PR, the scan should finish successfully

🐛 fix readdirnames for docker scans

---

providers/github/resources/github_repo.go

Resolves #3905 
---
Leaving Protection Rules retrieval as is, since Github API doesn't seem to return full information about Protection rules in GetBranch and just stub instead.
attempted with the tokens (and multiple orgs):
1. Fine-Grained (administration read-only)
2. Fine-Grained (everything read-only)
3. Classic (admin read-only)
Example:
```json
* * *
"protected": true,
"protection": {
"enabled": true,
"required_status_checks": {
"enforcement_level": "off",
"contexts": [
],
"checks": [
]
}
},
"protection_url": "https://api.github.com/repos/mondoohq/cnquery/branches/main/protection"
}
```

Skip protection rules retrieval for unprotected branches

---

providers/github/connection/connection.go

based on: https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#exceeding-the-rate-limit

:octocat: handle GitHub API rate limits

---

providers/github/resources/github_repo.go

redundant error return with personal account as the repo owner(not an org)

🐛 Github: access personal repos: 

---

providers/github/config/config.go

🎉 github-11.3.8

---

mql/internal/nodes.go
providers-sdk/v1/inventory/asset_url.go
providers-sdk/v1/plugin/service.go
providers-sdk/v1/plugin/service_test.go
providers-sdk/v1/util/version/version.go
providers/ansible/play/playbook_test.go
providers/os/resources/machine.go
providers/os/resources/smbios/linux.go
providers/os/resources/smbios/smbios.go
providers/os/resources/smbios/smbios_test.go
providers/os/resources/updates/mac_updates.go
providers/snowflake/connection/connection.go
providers/vsphere/connection/platform.go
utils/multierr/errors.go

Spelling fixes

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_rds.go

⭐️ add subnets to rds db instances

---

providers/os/connection/snapshot/blockdevices.go
providers/os/connection/snapshot/blockdevices_test.go
providers/os/connection/snapshot/testdata/alma9_attached.json

This ensures that when filtering out partitions, both `BOOT` and `boot` labels are filtered out. Also ensure that we sort the partitions by size and return the largest one.

🐛 Normalize partition labels before checking them and sort by size

---

mqlc/mqlc.go
mqlc/mqlc_test.go

apparently private resources are still suggested in cnquery/cnspec shell
For example `aws.ecs.instance` is marked as private and shouldn't be accessible directly [but only via `aws.ecs.containerInstances` ](https://github.com/mondoohq/cnquery/blob/bc3c52de14289111b4db528950ffb2dca391bafb/providers/aws/resources/aws.lr#L1266)
But here is what we can see:
Same for lots of other resources.

🧹🐛 Don't show private resources in the shell auto complete

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_vpc.go

adds missing info, so we can connect `subnets` to `routeTables`

:star:  Expand data collected in aws.vpcs {routeTables {associations}}

---

apps/cnquery/cmd/login.go
apps/cnquery/cmd/status.go

Resolves https://github.com/mondoohq/cnspec/issues/1342

✨Run status check on login errors

---

providers/k8s/config/config.go

🎉 k8s-11.1.14

---

providers/azure/resources/discovery.go

Do not discover containers as part of the fine-grained scanning. They are still discoverable via `--all` or `--storage-containers` discovery flags

🧹 Exclude storage containers from fine-grained scanning.

---

providers/k8s/resources/clusterrole.go
providers/k8s/resources/clusterrolebinding.go
providers/k8s/resources/common.go
providers/k8s/resources/configmap.go
providers/k8s/resources/cronjob.go
providers/k8s/resources/daemonset.go
providers/k8s/resources/deployment.go
providers/k8s/resources/ingress.go
providers/k8s/resources/job.go
providers/k8s/resources/networkpolicy.go
providers/k8s/resources/node.go
providers/k8s/resources/pod.go
providers/k8s/resources/podsecuritypolicy.go
providers/k8s/resources/replicaset.go
providers/k8s/resources/role.go
providers/k8s/resources/rolebinding.go
providers/k8s/resources/secret.go
providers/k8s/resources/service.go
providers/k8s/resources/statefulset.go

We should use kind instead of resources. Also the k8s library doesn't "stringify" the `GroupVersionKind` in the format that is expected by the server. Therefore we are doing that ourselves

🐛 use kind fully qualified names for k8s resources

---

providers/k8s/config/config.go

🎉 k8s-11.1.16

---

explorer/impact.go
explorer/impact_test.go

MarshalJSON was returning values unquoted, i.e. like:
```json
{
"scoring_system": decayed
}
```

🐛 fix: scoring system json marshal

---

.github/actions/spelling/expect.txt
providers/gitlab/resources/gitlab.go
providers/gitlab/resources/gitlab.lr

Important:
we need to figure out why I need to run several time gitlab.project {*} until it works.
Maybe something with initialization which I tried to use and still did not work

⭐️ Adding the resources for approval settings (Gitlab)

---

providers/os/resources/packages/rpm_packages.go

There was a bug in the generated commands. The tests returned the right results that is why they have not catched this case.
The problem was introduced in https://github.com/mondoohq/cnquery/pull/4334/files#diff-f2d1541558cf19abeed69cd85d78939d7a61c44ec541a10d2817bfc513637894

🐛  fix rpm parser

---

providers/os/config/config.go

🎉 os-11.2.19

---

providers/os/resources/macos.go
providers/os/resources/macos_systemextension.go
providers/os/resources/os.lr
providers/os/resources/os.lr.go
providers/os/resources/os.lr.manifest.yaml

List all macOS system extensions
```coffeescript
cnquery> macos.systemExtensions
macos.systemExtensions: [
0: macos.systemExtension teamID="P3FGV63VK7" identifier="io.kandji.KandjiAgent.ESF-Extension" version="1.8.10" state="activated_enabled"
1: macos.systemExtension teamID="X9E956P446" identifier="com.crowdstrike.falcon.Agent" version="7.17" state="activated_enabled"
2: macos.systemExtension teamID="2MMRE5MTB8" identifier="com.obsproject.obs-studio.mac-camera-extension" version="30.1.2" state="activated_waiting_for_user"
3: macos.systemExtension teamID="X9E956P446" identifier="com.crowdstrike.falcon.Agent" version="7.16" state="terminated_waiting_to_uninstall_on_reboot"
4: macos.systemExtension teamID="P3FGV63VK7" identifier="io.kandji.KandjiAgent.ESF-Extension" version="1.8.9" …
```

⭐️ add macos.systemExtensions as new resource

---

providers/gitlab/config/config.go

🎉 gitlab-11.1.12

---

providers/gitlab/config/config.go

🎉 gitlab-11.1.13

---

providers/gitlab/config/config.go

🎉 gitlab-11.1.14

---

providers/azure/resources/network.go
providers/github/provider/provider.go
providers/k8s/resources/resources_test.go
providers/ms365/resources/ms365_exchange.go
providers/ms365/resources/ms365_sharepoint.go
providers/network/resources/domain/name.go
providers/network/resources/tls.go
providers/os/connection/device/linux/lun.go
providers/os/detector/platform_resolver.go
providers/os/id/aws/aws_test.go
providers/os/resources/asset_vuln.go
providers/os/resources/discovery/container_registry/registry.go
providers/os/resources/docker_file.go
providers/os/resources/group_test.go
providers/os/resources/procfs/processes.go

Fix some code only typos (functions/vars/comments) as well as some user facing error messages

Fix typos (code / user facing)

---

providers-sdk/v1/util/configure/configure.go

We currently silently eat all output, which is not helpful when errors occur. This provides the output with any errors that might have led to the build failing. Pure QoL...

🧹 provide more info on errors in make providers/config

---

providers/aws/go.mod
providers/aws/go.sum
providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_eks.go

The support policy requires the latest SDK release.
```
cnquery> aws.eks.clusters{supportType authenticationMode}
aws.eks.clusters: [
0: {
supportType: "EXTENDED"
authenticationMode: "API_AND_CONFIG_MAP"
}
]
```

Add 2 new fields to EKS clusters

---

providers/google-workspace/resources/users.go
providers/google-workspace/resources/users_test.go

The user report usage was broken, this PR introduces better logic to try and get the latest possible report by iterating over a period of 10 days and seeing if there's a report for any of those days

🐛 Fix reports retrieval for google workspace.

---

providers/google-workspace/resources/users.go

🐛 Specify customer id for fetching user report usage.

---

providers/google-workspace/config/config.go
providers/google-workspace/provider/provider.go
providers/google-workspace/resources/domain.go

* Add tech url segments for google workspace
* Asset name now is the primary domain + the customer id. E.g. ` Google Workspace mondoo.com B1g0kA3gQ`
* Improve error message when the creds, specified in `--credentials-path` do not exist.
Fixes #4403

🧹 Add tech url segments for google workspace. Improve asset name

---

providers/os/connection/tar/path.go

With https://github.com/mondoohq/cnquery/pull/1557 we used a tool to add headers. Since the existing attribution was not detected properly by the tool, it accidentally attached the BUSL 1.1 license header. This fixes the header to avoid future confusion.

🧹 fix license header for BSD licensed file

---

apps/cnquery/cmd/scan.go
cli/tmp/file.go
providers/os/connection/container/image_connection.go
providers/os/connection/docker/container_connection.go
providers/os/connection/docker/snapshot_connection.go
providers/os/connection/tar/stream.go

This go package should be used across `cnquery` to generate temporary files and directories.
`tmp.File()` creates a new temporary file.
By default `File()` uses the default directory to create a new temporary file, to change the temporary directory use the environment variable `MONDOO_TMP_DIR`

⭐️ go package to create `tmp.File()`

---

providers/github/resources/github.go
providers/github/resources/github.lr.go
providers/github/resources/github_org.go
providers/github/resources/github_repo.go
providers/github/resources/github_user.go

In the past we did some optimizations to fetch repositories only once. While this makes sense when we do discovery there are cases where fetching all repos from an org or user does not make sense. A specific case is when I just want to scan a single repo. 
```
cnquery shell github repo microsoftgraph/msgraph-sdk-go
```
That call should not fetch all repos of an org. It makes scanning an org for large organizations slower. This PR fixes it. It changes the code to leverage a cache. If that cache exists (eg. because a user called `github.organization.repositories`) then its used.
**before**
```
DEBUG=1 cnquery shell github repo microsoftgraph/msgraph-sdk-go
DBG performing request method=GET url=https://api.github.com/zen
DBG fetching organization microsoftgraph
DBG performing request …
```

GitHub repo discovery performance

---

Makefile

https://github.com/grpc/grpc-go/issues/7448, `v1.5.1` should work

🐛 Unpin protoc-gen-go-grpc as the latest release has a fixed build.

---

.github/workflows/pr-test-generated-files.yaml
Makefile

With the switch to the individual providers have have not included the generation of the .lr.go files into our test suite. This has lead a couple of times to the situation that the provider compilation failed and we had to check it in afterwards. This prevents this case by checking that all files are checked in.

🧹 generate lr.go files during testing to verify all is checked in

---

providers/github/resources/github_repo.go

404 is an expected response for repo/directory being empty (which is even handled already), but there would still be lots of unnecessary error logs, not welcoming and sometimes misleading in the interactive mode especially

🧹 silence error logs for handled error

---

providers/azure/resources/cosmosdb.go

Based on the current capabilities of the Azure SDK for Go, it appears that the kind, tags, and specially **properties** attributes are not directly available for Cosmodb type MongoDB and PostgreSQL server groups through the SDK.

⭐   Adding support to get the MongoDB and PostgreSQL cosmodb Types (Azure)

---

Makefile
providers-sdk/v1/upstream/health/errors.go
providers-sdk/v1/upstream/upstream.pb.go
providers-sdk/v1/upstream/upstream.proto
providers/mondoo/config/config.go

This also updates the short description of the platform that is used in `cnspec scan/shell help`
```
...
mondoo           Scan the Mondoo Platform
...
```

Capitalize Mondoo Platform in a few places

---

providers/mondoo/provider/provider.go
providers/mondoo/resources/mondoo.go
providers/mondoo/resources/mondoo.lr
providers/mondoo/resources/mondoo.lr.go
providers/mondoo/resources/mondoo.lr.manifest.yaml

- also rename `agent` to `client` to be consistent with the way we have it documented

✨ add more asset info to mondoo provider

---

cli/shell/nyago.go
providers/network/resources/certificates/extensions.go
providers/okta/resources/sdk/notifications.go
providers/os/connection/ssh/keypair/edkey.go
providers/os/connection/winrm/cat/winstat.go

With https://github.com/mondoohq/cnquery/pull/1557 we used a tool to add headers. Since the existing attribution was not detected properly by the tool, it accidentally attached the BUSL 1.1 license. This fixes the header to avoid future confusion.

🧹 fix license header for BSD / MPL 2.0 licensed files

---

providers/github/connection/connection.go
providers/github/resources/discovery.go
providers/github/resources/github_org.go
providers/github/resources/github_package.go
providers/github/resources/github_repo.go
providers/github/resources/github_team.go
providers/github/resources/github_user.go
providers/github/resources/github_workflow.go

Github Client is handling rate-limits internally out of the box, which means if rate limits are reached, client will return fake 403 API Rate limits response before even trying out retryable client.
Unfortunately we can't use `bypassRateLimitCheck` strategy, because it's private, but we can use `SleepUntilPrimaryRateLimitResetWhenRateLimited` instead, which should be doing just the same job as the retryable client.
Secondary limits must still be handled by retryable client.

✨ use github-client internal rate-limits timer

---

providers/os/provider/provider.go
providers/os/resources/container.go

This is not a proper fix but a workaround to make sure the specific command works. We will need to re-visit cross-provider resources at some point.
Fixes #4472

🐛 allow cross-provider containers from k8s

---

providers/github/resources/github.lr
providers/github/resources/github.lr.go
providers/github/resources/github.lr.manifest.yaml
providers/github/resources/github_repo.go

This simplifies the access to the default branch.
**Before**
```coffeescript
cnquery> github.repository.branches.where(isDefault == true).all(isProtected == true)
[ok] value: true
```
**After**
```coffeescript
cnquery> github.repository.defaultBranch.isProtected
[ok] value: true
```

⭐️ expose github default branch to make the access easier

---

providers/gitlab/connection/connection.go

PathEscape is handled by `go-gitlab` for at least past 2 years: https://github.com/xanzy/go-gitlab/blob/f4f54fa4a42d2004e5b269921578bfe529ab19a0/projects.go#L525
> Escaping escaped string would produce '/' -> '%2F' -> '%252F'

🐛 gitlab: fix GetProject for projects in subgroups

---

providers/gitlab/config/config.go

🎉 gitlab-11.1.18

---

providers/atlassian/resources/atlassian.lr
providers/atlassian/resources/atlassian.lr.go
providers/atlassian/resources/atlassian.lr.manifest.yaml
providers/atlassian/resources/atlassian_jira.go

1. Adding `created` field to `atlassian.jira.issue`
2. Max results parameter defines maximum amount of issues that will be found by search, but API uses cursor style pagination and depending on the Jira instance returns 50 or 100 results per page. Therefore we must iterate to actually get all issues
Before:
```shell
$ cnquery providers | grep atlassian
atlassian 11.0.24 with connectors: atlassian
$ cnquery run atlassian jira --host https://myjira.atlassian.net -c 'atlassian.jira.issues.length'
atlassian.jira.issues.length: 100
```
After:
```shell
$ go run apps/cnquery run atlassian jira --host https://myjira.atlassian.net -c 'atlassian.jira.issues.length'
atlassian.jira.issues.length: 311
```

✨ jira: created time and improved search

---

providers/atlassian/resources/atlassian.lr
providers/atlassian/resources/atlassian_jira.go

createdAt is what we've been using in other providers. We should align this where we can

Renamed jira created field to createdAt

---

providers/k8s/resources/k8s.lr

Expose the platform and architecture of the nodes
```
cnquery> k8s.nodes
k8s.nodes: [
0: k8s.node name="ip-172-31-22-47.us-west-2.compute.internal" labels[kubernetes.io/arch]="amd64" labels[kubernetes.io/os]="linux"
1: k8s.node name="ip-172-31-7-191.us-west-2.compute.internal" labels[kubernetes.io/arch]="amd64" labels[kubernetes.io/os]="linux"
]
```

Add useful default data for the k8s.node resource

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_iam_accessanalyzer.go

This RP improves the AWS IAM Analyzer resource.
**Rename**
The resource has been moved from `aws.accessAnalyzer` to `aws.iam.accessAnalyzer` better align with AWS naming scheme. We established an alias, so that no migration is required. Old queries keep working as expected.
To check that the default analyzer runs in all aws regions run the following query:
```
cnspec> aws.regions.containsAll(aws.iam.accessAnalyzer.analyzers.where(name == "default-analyzer").map(region))
[ok] value: []
```
**Analyzer**
To verify the analyzer running in AWS, we improved the `aws.iam.accessAnalyzer`  to also include org-level analyzer that apply to the region and activated "unused" analyzer. The following shell output illustrate the new ACCOUNT_UNUSED_ACCESS type analyzer in the list
```
cnspec> …
```

⭐️ aws iam analyzer

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_guardduty.go

**Speed up guard duty resource**
Instead of fetching all data during resource creation, we fetch the detector details only when we need it.
```coffeescript
cnquery> aws.guardduty.detectors
aws.guardduty.detectors: [
0: aws.guardduty.detector id="b4c62d82c40ccf1edd2e6b6868a65872" region="ap-south-1"
1: aws.guardduty.detector id="e6c62d82c19690d3d48422efa0d24e02" region="eu-north-1"
2: aws.guardduty.detector id="a4c62d82c13dc4274e9de5a16b74aa40" region="eu-west-3"
3: aws.guardduty.detector id="40c62d82c69edf8da843fa1f8a9a3839" region="eu-west-2"
...
```
**Use guard duty finding resource for detector**
Previously, we `aws.guardduty.detectors.first.unarchivedFindings` on the resource which was exposed as dict. This made it a bit more difficult than required to navigate. Therefore we …

⭐️ aws guardduty finding

---

.github/workflows/pr-test-generated-files.yaml

Use the protoc action consistently.

🧹 use protoc action consistently

---

.github/actions/spelling/line_forbidden.patterns
providers/gcp/resources/gcp.lr

Don't start a sentence with Indicates

Add another Indicates form to spellcheck

---

providers/ms365/resources/applications.go
providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml

This PR adds a new applicability to quickly identify expiring credentials for Microsoft Entra ID Application Registrations.
First we connect to our [Microsoft 365 account](https://mondoo.com/docs/cnspec/saas/ms365/#log-into-microsoft-365) via shell `cnspec shell ms365 --tenant-id bb22a034-d544-4b9e-a222-6a166840f64c`
**Quickly see all application in Entra ID**
Just type `microsoft.applications` and you see an overview of all applications and if the application has expired credentials.
```coffeescript
cnspec> microsoft.applications
microsoft.applications: [
0: microsoft.application id="0030c47a-6318-431a-9f85-1b051484c7cf" displayName="chis-mac-testing" hasExpiredCredentials=true
]
cnspec>
```
**Verify an specific application has no expired credentials**
For applications it is essential …

⭐️ extend microsoft entra id application resource to search for expiring credentials

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_vpc.go

The name is encoded in the `Name` tag. Exposing this as a direct field makes it way more easier to access. For example you can now write a simple check that you should have other VPC than the default one:
```coffeescript
aws.vpcs.where(name != "Default VPC") != empty
```

🧹 introduce a name field for vpc resource

---

providers/os/resources/windows/computerinfo.go

If `OsProductType` is null, fallback to a custom implementation of `Get-ComputerInfo`. There are versions of powershell where if winrm is not enabled, `Get-ComputerInfo` does not work properly: See https://github.com/PowerShell/PowerShell/issues/3080

Fallback to Get-Ciminstance based get-computerinfo

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_rds.go

With this change it is easier to access the resources in the `aws.rds` namespace.
- rename `aws.rds.dbInstances` to `aws.rds.instances`
- rename `aws.rds.dbClusters` to `aws.rds.clusters`
Everything stays backwards compatible. `aws.rds.dbInstances` and  `aws.rds.dbClusters` will be removed in the next major version.

🧹 simplify the `aws.rds` resource

---

providers-sdk/v1/lr/cli/cmd/docs.go

This PR switches the default version for generated docs from latest to 9.0.0 since the resources are backwards compatible now.

🧹 change lr default version to 9.0.0

---

.github/actions/spelling/expect.txt
providers/aws/connection/clients.go
providers/aws/go.mod
providers/aws/go.sum
providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_neptune.go

This PR adds new resources to query AWS Neptune for its configuration
```javascript
cnquery> aws.neptune.clusters
aws.neptune.clusters: [
0: aws.neptune.cluster arn="arn:aws:rds:us-east-1:162854405951:cluster:db-neptune-1" name=null status="available"
]
cnquery> aws.neptune.instances
aws.neptune.instances: [
0: aws.neptune.instance arn="arn:aws:rds:us-east-1:162854405951:db:db-neptune-1-instance-1" name=null status="available"
]
```

⭐️ AWS neptune cluster and instance resources

---

providers/ms365/resources/applications.go
providers/ms365/resources/groups.go
providers/ms365/resources/microsoft.go
providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/users.go

This PR improves the `microsoft.user` resource.
**Simpler init functions**
User can easily created by their object id and principal name now:
```javascript
cnspec> microsoft.user(userPrincipalName: "ben@example.onmicrosoft.com")
microsoft.user: microsoft.user id="a692f8ff-42e3-4156-8ac2-523379d9b664" displayName="Ben Rockwood" userPrincipalName="ben@example.onmicrosoft.com"
```
```javascript
cnspec> microsoft.user(id: "a692f8ff-42e3-4156-8ac2-523379d9b664")
microsoft.user: microsoft.user id="a692f8ff-42e3-4156-8ac2-523379d9b664" displayName="Ben Rockwood" userPrincipalName="ben@example.onmicrosoft.com"
```
**Retrieve owner for application registration**
We added a new `owners` field to `microsoft.application` which allows you to see all owners of your application:
```javascript
cnspec> …
```

🧹 improve user resource handling in Microsoft 365

---

.github/actions/spelling/expect.txt
providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_rds.go

after https://github.com/mondoohq/cnquery/pull/4526
The AWS RDS `aws.rds.instances` resource is handy to quickly see the RDS instances, their engines and engine version:
```javascript
aws.rds.instances: [
0: aws.rds.dbinstance id="database-1" region="us-east-1" engine="postgres" engineVersion="16.4"
1: aws.rds.dbinstance id="database-2" region="us-east-1" engine="sqlserver-ex" engineVersion="15.00.4382.1.v1"
2: aws.rds.dbinstance id="database-2-instance-1" region="us-east-1" engine="aurora-postgresql" engineVersion="15.4"
3: aws.rds.dbinstance id="database-3" region="us-east-1" engine="postgres" engineVersion="11.22-rds.20240418"
4: aws.rds.dbinstance id="docdb-2024-08-11-08-16-54" region="us-east-1" engine="docdb" engineVersion="5.0.0"
]
```
With this PR we extend the existing resource …

⭐️ improve rds resource

---

.github/actions/spelling/expect.txt
providers/aws/connection/clients.go
providers/aws/go.mod
providers/aws/go.sum
providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_timestream.go

This PR adds new resources to list AWS TimeStream for LifeAnalytics database and tables.
```javascript
cnquery> aws.timestream.lifeanalytics.databases
aws.timestream.lifeanalytics.databases: [
0: aws.timestream.lifeanalytics.database name="timestreamdatabase" region="us-east-1"
]
cnquery> aws.timestream.lifeanalytics.tables
aws.timestream.lifeanalytics.tables: [
0: aws.timestream.lifeanalytics.table name="table1" region="us-east-1"
]
```

⭐️ AWS TimeStream for LifeAnalytics resources

---

providers/aws/resources/aws.go
providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_elasticache.go

AWS added ElastiCache Serverless for Redis and Memcached. This PR exposes those new server via the new `aws.elasticache.serverlessCaches` resource:
```javascript
cnquery> aws.elasticache.serverlessCaches { * }
aws.elasticache.serverlessCaches: [
0: {
createdAt: 2024-08-11 21:45:02.836 +0200 CEST
snapshotRetentionLimit: 0
dailySnapshotTime: "05:00"
description: "memache"
status: "available"
arn: "arn:aws:elasticache:us-east-1:012345678901:serverlesscache:cache1"
kmsKeyId: null
0: aws.ec2.securitygroup id="sg-037203ba3346d36bd" name="default" region="us-east-1" vpc.id="vpc-03800db8f01981fb7"
]
engineVersion: "1.6.22"
name: "cache1"
majorEngineVersion: "1.6"
engine: "memcached"
}
1: {
createdAt: 2024-08-11 22:27:19.125 +0200 CEST …
```

⭐️ aws.elasticache.serverlessCaches resource

---

providers/aws/resources/aws_neptune.go

We need to explicitly filter by the engine because the AWS Neptune API client returns RDS cluster / instances eg. also aurora instances. This is mentioned in their API docs and marked as no fix 🤣 see https://docs.aws.amazon.com/neptune/latest/apiref/API_DescribeDBClusters.html

🧹 refactor the aws neptune resource

---

providers/aws/resources/aws.go
providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws_elasticache.go
providers/aws/resources/aws_rds.go

- filter out engine types that are not rds
- restructure code
- fetch security groups asynchronously

🧹 refactor aws rds resource

---

providers/aws/resources/aws_timestream.go

`ap-south-1 ` as it is only support for InfluxDB service

🧹 deactivate ap-south-1 for aws TimeStream LiveAnalytics 

---

providers/aws/resources/aws_kms.go

If an err happens when we're fetching KMS key, we continue and do not break. This means we get to retry again, however if the error is consistent (say a 403) we will never exit this loop. Instead, let's break out of the loop if we encounter an error.

🐛 Fix endless KMS retrieval loop.

---

providers/os/resources/services/manager.go
providers/os/resources/services/testdata/photon.toml
providers/os/resources/services/testdata/ubuntu2204.toml

If there is no init system, like in containers, we dont have something
managing services to list. This change modifies the code to return an
empty list in the case we do not detect `/sbin/init`

If there is no init system, return empty services

---

providers/ms365/resources/applications.go
providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/serviceprincipals.go
providers/ms365/resources/structs.go

**Get the referenced service principle (enterprise application)**
```javascript
microsoft.application(name: "chris-mac-testing").servicePrincipal
```
**App Manifest**
We also expose more details about your application so that those can be verified automatically:
```javascript
cnspec> microsoft.application(name: "chris-mac-testing") { info api spa }
microsoft.application: {
api: {
acceptMappedClaims: null
knownClientApplications: []
oauth2PermissionScopes: []
preAuthorizedApplications: []
requestedAccessTokenVersion: null
}
info: {
logoUrl: null
marketingUrl: null
privacyStatementUrl: "https://example.com/privacy"
supportUrl: null
termsOfServiceUrl: "https://example.com/terms"
}
spa: {
redirectUris: []
}
}
```

🧹 improve `microsoft.application` resource

---

providers/azure/resources/azure.lr
providers/azure/resources/azure.lr.go
providers/azure/resources/azure.lr.manifest.yaml
providers/azure/resources/cloud_defender.go

⭐️   Azure: Microsoft Microsoft Defender for Cloud resource updates

---

providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/rolemanagement.go

Simplify the way we access roles in Microsoft 365:
Instead of `microsoft.rolemanagement.roleDefinitions` we can just type:
```javascript
cnquery> microsoft.roles
microsoft.roles: [
0: microsoft.rolemanagement.roledefinition id="62e90394-69f5-4237-9190-012177145e10" displayName="Global Administrator"
1: microsoft.rolemanagement.roledefinition id="10dae51f-b6af-4016-8d66-8c2a99b929b3" displayName="Guest User"
2: microsoft.rolemanagement.roledefinition id="2af84b1e-32c8-42b7-82bc-daa82404023b" displayName="Restricted Guest User"
3: microsoft.rolemanagement.roledefinition id="95e79109-95c0-4d8e-aee3-d01accf2d47b" displayName="Guest Inviter"
...
```

⭐ improve access to roles in Microsoft 365

---

.github/actions/spelling/expect.txt
providers/ms365/resources/errors.go
providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/structs.go
providers/ms365/resources/users.go

This PR introduces a new fields for the `microsoft.user` resource `job` and `contact`. Those group the information much better. The old fields are going to be removed in future versions.
```javascript
cnquery> microsoft.user(userPrincipalName: "chris@example.onmicrosoft.com").contact
microsoft.user.contact: {
BusinessPhones: [
0: "Business Phone"
]
city: "City"
country: "Country"
email: "super@example.com"
faxNumber: "+491234656"
mailNickname: "christest"
mobilePhone: "Mobile Phone"
otherMails: []
postalCode: "Postal Code"
state: "Province"
streetAddress: "Street"
}
```
To see information about the users job description:
```javascript
cnquery> microsoft.user(userPrincipalName: "chris@example.onmicrosoft.com").job
microsoft.user.job: {
companyName: "Company Name"
department: "Department" …
```

⭐️ Microsoft 365 user resource improvements incl. authentication methods

---

providers/providers.go

I've been testing cnquery on a machine with heavily degraded disk and network performance and stumbled upon the following bug
If download and/or unpacking takes longer than 30 seconds (currently set Timeout) - context used during the request gets auto-cancelled (per set Timeout as expected). 
Problem tho is that resulting `io.ReadCloser` http client returns has timeout check embedded into it, so when our `walkTarXz` function tries to unpack the tarball, `Read()` returns error like in the log, **despite provider was downloaded sucessfuly**.
This behaviour is well explained here: https://github.com/golang/go/issues/49366
Example logs:
```
DBG performing request method=GET url=https://releases.mondoo.com/providers/latest.json
→ installing provider 'os' version=11.2.22
DBG installing provider …
```

🐛 provider installer timeout fix

---

providers/aws/resources/aws_account.go

e.g. an s3 bucket, iam user
we were actually returning the arn of the iam user and s3 bucket in those cases, because we were grabbing the asset identifier ARN value.
this ensures we always return the account id.
tested with `cnspec shell aws `, `cnspec shell aws --discover iam-user`, `cnspec shell aws --discover s3-bucket`

🧹 return the correct value for aws account id when connected to subresource

---

providers/atlassian/connection/jira/connection.go

https://github.com/mondoohq/cnquery/issues/4445

🧹 return error when invalid host value is provided for atlassian provider

---

providers/ms365/resources/rolemanagement.go

We need to fetch the field `isBuiltIn` when we fetch roles. This allows us to filter roles quickly:
```javascript
cnquery> microsoft.roles.where(isBuiltIn == false)
microsoft.roles.where: []
```

🐛 fix fetching of fields for role definitions

---

providers/azure/resources/azure.lr
providers/azure/resources/azure.lr.go
providers/azure/resources/azure.lr.manifest.yaml
providers/azure/resources/iam.go
providers/azure/resources/subscription.go

This changes improves the Azure experience for IAM access. Instead of `azure.subscription.authorization.roleDefinitions` we can simply call `azure.subscription.iam.roles` now:
```
cnquery> azure.subscription.iam.roles
azure.subscription.iam.roles: [
0: azure.subscription.authorizationService.roleDefinition name="Security-Team-CustomRole" type="CustomRole"
1: azure.subscription.authorizationService.roleDefinition name="AcrPush" type="BuiltInRole"
2: azure.subscription.authorizationService.roleDefinition name="API Management Service Contributor" type="BuiltInRole"
...
]
````

⭐️ simplify azure iam access

---

providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/serviceprincipals.go
providers/ms365/resources/structs.go

When you want to verify enterprise apps and their permissions, it is essential to focus on the right enterprise applications. Therefore we introduce a new field `isFirstParty` to service principals:
```
cnquery> microsoft.serviceprincipals.where( isFirstParty == false)
microsoft.serviceprincipals.where: [
0: microsoft.serviceprincipal name="chris-ms365"
1: microsoft.serviceprincipal name="chris-mac-test"
]
```

⭐️ Microsoft 365 first party apps filtering

---

providers/ms365/resources/applications.go
providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/serviceprincipals.go

after https://github.com/mondoohq/cnquery/pull/4572
Microsoft 365 applications can define custom app roles. Those can be read with the new field:
```javascript
cnquery> microsoft.applications { name appRoles }
microsoft.applications: [
0: {
appRoles: [
0: microsoft.application.role name="App Role Reader" value="AppRole.Read" isEnabled=true
]
name: "chris-mac-test"
}
]
```
You can also see the app roles from the service principals perspective:
```
cnquery> microsoft.enterpriseApplications { name appRoles }
microsoft.enterpriseApplications: [
0: {
appRoles: [
0: microsoft.application.role name="App Role Reader" value="AppRole.Read" isEnabled=true
]
name: "chris-mac-test"
}
]
```

⭐️ Microsoft 365 application roles and service principal app roles

---

providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/security_riskyusers.go
providers/ms365/resources/security_securescores.go
providers/ms365/resources/users.go

This PR adds the new `microsoft.security.riskyUsers` resource.
**List of risky users**
You can easily query for Entra risky users:
> Note this requires an Microsoft Entra ID P2. See [Entra ID License requirements](https://learn.microsoft.com/en-us/entra/id-protection/overview-identity-protection#license-requirements) for more details
```javascript
cnquery> microsoft.security.riskyUsers
microsoft.security.riskyUsers: [
0: microsoft.security.riskyUser principalName="ben@example.onmicrosoft.com" riskLevel="high" riskState="atRisk" lastUpdatedAt=2024-06-26 13:41:57.1498281 +0200 CEST
]
```
Or if you want to see all details:
```javascript
cnquery> microsoft.security.riskyUsers { * }
microsoft.security.riskyUsers: [
0: {
id: "346de954-64f8-40db-bc19-aef1001858c0"
principalName: …
```

⭐️ Microsoft 365 risky users resource

---

providers/ms365/resources/microsoft.go
providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/serviceprincipals.go

after https://github.com/mondoohq/cnquery/pull/4574
One of the challenges for Microsoft 365 applications is to verify that permissions are set properly.
**Permissions for one specific app**
Application permissions are managed via service principal in Microsoft Entra ID. You can easily check a specific application:
```javascript
cnquery> microsoft.serviceprincipal(name: "chris-mac-test") { permissions }
microsoft.serviceprincipal: {
permissions: [
0: microsoft.application.permission appName="Microsoft Graph" name="User.ReadBasic.All" type="application" status="granted"
1: microsoft.application.permission appName="Microsoft Graph" name="Directory.Read.All" type="application" status="granted"
2: microsoft.application.permission appName="Microsoft Graph" name="User.Read.All" …
```

⭐️ Microsoft 365 service principal permmission field

---

providers/google-workspace/config/config.go

`saas` is now a common tree and needs to behave properly with the other providers

🐛 Fix google workspace asset url

---

providers-sdk/v1/plugin/service.go

This will make it easier to identify cases where the heartbeat failed and the provider shut down without a panic.

🧹 use custom exist code when we shutdown the provider due to outstanding heartbeat

---

providers/github/resources/github.lr
providers/github/resources/github.lr.go
providers/github/resources/github.lr.manifest.yaml
providers/github/resources/github_repo.go

Introduces authored and commited dates to `github.commit` resource
From Github Docs:
> ... the author date is used to calculate when a commit was made. Whereas, in a repository, the commit date is used to calculate when a commit was made in the repository
Can be used like
```
github.repository.commits.where(authoredDate > parse.date('2019-01-01'))
github.repository.commits.where(commitedDate > parse.date('2019-01-01'))
```
---

✨ Authored and Commited dates to :octocat: commits

---

providers/github/resources/discovery.go

Aligns the discovery with the user expectation:
- by default the org is scanned when user uses `cnquery scan github org <gh-org>`
- skip org scan if `cnquery scan github org <gh-org> --repos <repo1,repo2>` is used where 
- skip org scan if `scan github org <gh-org> --discover repos` is used

🧹 improve github org discovery

---

providers/coordinator.go
providers/coordinator_test.go
providers/providers_test.go
providers/running_provider.go
providers/running_provider_test.go
providers/runtime.go

Makes providers reconnectable. Keeps track of all connect requests to a provider. If it crashes, and is restarted, all the connect requests are replayed. Disconnected connections are also recreated because they can be a parent connect, and its non-existence can cause a child to fail to connect

make provider reconnectable

---

providers/os/config/config.go

🎉 os-11.2.27

---

providers/azure/resources/azure.lr
providers/azure/resources/azure.lr.manifest.yaml
providers/azure/resources/keyvault.go

- Ensure Automatic Key Rotation is Enabled Within Azure Key Vault for the Supported Services

🧹 Improving the keyVault resources to cover automatic key rotation policy

---

providers/azure/resources/azure.lr
providers/ms365/resources/conditional-access.go
providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml

- Ensure Trusted Locations Are Defined

⭐️ Adding conditional Access - Named location part

---

providers/aws/resources/aws_ec2.go

* use passed in tags as filters
* use passed in instance ids as filters

✨ Improve ec2 discovery: do not fetch instances twice, use tags to filter

---

providers/aws/config/config.go

🎉 aws-11.3.8

---

providers/azure/go.mod
providers/azure/go.sum
providers/azure/resources/azure.lr
providers/azure/resources/azure.lr.go
providers/azure/resources/azure.lr.manifest.yaml
providers/azure/resources/compute.go
providers/azure/resources/network.go
providers/azure/resources/web.go

```
azure.subscription { network  { applicationGateways { wafConfiguration }}}
```
```
azure.subscription { web { apps { functions { * } } }}
```

✨ add resource for azure functions & WAF config

---

cli/printer/mql.go

Boolean data queries will have an assessment. When we display them as data queries, we do not want an assessment

🧹 Allow printing data queries without an assessment

---

providers/aws/connection/connection.go
providers/aws/connection/connection_test.go
providers/aws/provider/provider.go
providers/aws/resources/aws.go
providers/aws/resources/aws_ec2.go
providers/aws/resources/aws_ec2_test.go
providers/aws/resources/discovery.go
providers/aws/resources/discovery_test.go

- Removed `DiscoveryFilters` from `Discover(...)` function and use the parameters from the `AwsConnection` instead.
- Fixed parsing of inventory config discovery filters into `DiscoveryFilters` struct.
- Added new cases for ECS filters to be specified from inventory because they were only passed down from the removed parameter in `Discovery(...)`.
- Removed duplicate filtering of EC2 instances inside the AWS discovery that was already done by `GetInstances()`.
- Added corresponding exclude filters in `Ec2DiscoveryFilters`.
- Filter out EC2 instances if they match the values specified in the exclude filters. `ExcludeRegions` happens before the call to AWS, `ExcludeTags` and `ExcludeInstanceIds` happen after (AWS doesn't support server-side filtering for those).
- Added unit tests for a …

🧹 Remove discovery filters parameter from Discover

---

logger/eventlog/eventlog_windows.go

i still think we are not using the windows event log correctly. It's not meant to store log messages but events that occur that are either sucessful or not... The current issue is that for info messages the windows log shows this:
With this PR the message will be change to:
For error and warning messages, we need to decide what we want to do. At the moment, they will be logged as "Incorrect function." as well. The codes are mapped according to this table https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/18d8fbe8-a967-4f1c-ae50-99ca8e491d2d

🧹 log success event for info messages on windows

---

providers/os/resources/windows.go
providers/os/resources/windows/computerinfo.go

In https://github.com/mondoohq/cnquery/pull/4520 we introduced a fallback mechanism to be able to retrieve the windows computer info for machines that don't have winrm enabled. However, this change affected some clients where we run into command prompt command length limits. https://learn.microsoft.com/en-gb/troubleshoot/windows-client/shell-experience/command-line-string-limitation
An easy way to reproduce the error is if you try to run `windows.computerInfo` via ssh. That always connets to a command prompt and triggers the length limitation error:
```
cnspec run ssh admin@my-win-machine --password mypass -c windows.computerInfo
! could not find keys in ssh agent
unexpected end of JSON input
windows.computerInfo: null
```
In this PR:
- we make sure to read stderr if the command's exit …

🧹 improve computer info retrieval for windows

---

providers/os/config/config.go

🎉 os-11.2.29

---

providers/os/config/config.go

🎉 os-11.2.30

---

providers/ansible/config/config.go

Adds long-form CLI help for the Ansible provider.
From what I could see in the code, there are no subcommands and only the path is required. So this is one super simple. Did I miss anything, @chris-rock? 
Thanks!

Add Ansible long-form CLI help

---

.github/workflows/main-benchmark.yml
.github/workflows/pr-test-lint.yml

saving the new benchmark on main seems to be not working correctly since the new version of the cache has immutable entries. This change should make sure we create a new cache entry for each run on main. Branch runs will pull latest cache entry with `restore-keys` 
Ref: https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache

🧹 fix benchmark

---

providers/aws/resources/aws_ec2.go
providers/aws/resources/aws_ec2_test.go

Closes #4739 
This adds the possibility of specifying comma-separated values for the same key in a include/exclude tag filter. Those filters can now be specified as follows:
```
ec2:tag:Name=name1,name2,name3
```
and
```
exclude:ec2:tag:Name=name1,name2,name3
```
We keep treating the filter as a single `key : value` so this is backwards compatible. We just expand the string value right before applying the filters.
There is a quirk with how filters are applied. Comma-separated values on the same key are applied with a logical `OR`. If we specify 2 tag filters on different keys, they are applied with a logical `AND`.

✨ Add support for comma-separated values on the same key for EC2 tag filters

---

.github/workflows/main-benchmark.yml
.github/workflows/pr-test-lint.yml
providers/os/resources/processes/flag.go
providers/os/resources/processes/flag_test.go

We don't properly parse commands that contain `--` syntax. For example:
- `/package/admin/s6/command/s6-svscan -d4 -- /run/service`
- `tini -- fleetcontroller gitjob --gitjob-image rancher/fleet:v0.10.2`
Those currently return an error `bad flag syntax: ...`
This PR makes sure we only parse flags as long as we don't encounter `--`. Once we have `--` we terminate flag parsing as anything after that is not a flag. This also what cobra does -> https://github.com/spf13/cobra/blob/v1.8.1/command.go#L659-L661

🐛 properly parse flags for commands containing --

---

providers/os/config/config.go

🎉 os-11.2.31

---

cli/config/config.go

`getFeatures` was called before viper/cobra was initialized therefore skipping `features`
> Setting features via env would still overwrite those from config

🐛 load features from config

---

providers/os/resources/packages/windows_packages.go
providers/os/resources/port.go
providers/os/resources/smbios/win.go
providers/os/resources/updates/win_updates.go
providers/os/resources/windows.go
providers/os/resources/windows/bitlocker.go
providers/os/resources/windows/security_health.go
providers/os/resources/windows/security_products.go
providers/os/resources/windows_firewall.go

Make sure we properly surface errors from powershell execution

🐛 properly handle windows powershell errors

---

providers/os/config/config.go

🎉 os-11.2.32

---

providers/os/config/config.go

🎉 os-11.2.33

---

providers/os/resources/windows.go

The error message about the command length doesn't need to be in English. It can be in any other language Windows supports, therefore checking explicitly the error text is not a feasible approach to capture all command length errors.
This PR changes the behaviour so we always use the short command as a fallback to any type of error

🐛 use short windows computer info command as fallback always

---

providers/os/config/config.go

🎉 os-11.2.34

---

providers/shodan/provider/provider.go

Using an inventory file which provides the Shodan token as a vault secret triggeres an error. This is now fixed and we can run scans with vault secrets for Shodan

🐛 allow running shodan provider with inventory file

---

providers/os/provider/provider.go

🐛 Use explicitly specified asset name in SSH connection.

---

providers/os/config/config.go

🎉 os-11.2.35

---

providers/aws/connection/connection.go
providers/aws/connection/connection_test.go
providers/aws/provider/provider.go
providers/aws/resources/aws_ec2.go
providers/aws/resources/aws_ec2_test.go
providers/aws/resources/aws_ecr.go
providers/aws/resources/aws_ecs.go
providers/aws/resources/discovery.go
providers/aws/resources/discovery_test.go

- Made include/exclude region filters general for all assets. Incorporated them in `.Regions()` function so that should be applied everywhere.
- Removed tag filter from the general discovery filters. It did not make sense to have the same tag filter for all discovered assets as that is way too restrictive and often times would conflict, e.g. if you filter by a tag you use for EC2 instances, that automatically ignores every other asset in your AWS account. Furthermore, many assets do not have tags (containers/accounts, etc) so you need to ensure you do not filter those out which makes having global tag filters difficult to implement properly and reason about. Likely in the future we can make the filters more modular and have dedicated filters for different assets.
- Modified the existing …

✨ Streamline AWS discovery filters

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_ec2.go
providers/aws/resources/aws_iam.go

This adds the following resource:

:star: Create AWS resource aws.ec2.instances {iamInstanceProfile}

---

providers/os/config/config.go

🎉 os-11.3.0

---

providers/os/resources/packages/rpm_packages.go
providers/os/resources/packages/rpm_packages_test.go

Fixes #4714 
SuSE's vendor name changed for some reason from `SUSE LLC` to `SUSE LLC <https://www.suse.com/>` which no longer matched the regex pattern.
- Added `/`, `:`, `<` and `>` as allowed characters in the vendor regex pattern.
- Cleaned up vendor name after the fact and removed this tag at the earliest opportunity. It is not particularly useful and was causing trouble with CPEs generation.
- Used regex to remove any string of characters from the vendor name between a closed pair of angle brackets `<...>`. That way, we are agnostic as to what the contents of this tag are and we do not hardcode some arbitrary string which may change in the future. This assumes that angle brackets are not used in some other way in the vendor name which I think is a fair assumption given that this is …

🐛 Fix regex for matching RPM packages with unorthodox vendor name

---

providers/os/config/config.go

🎉 os-11.3.1

---

providers/aws/resources/aws_eks.go

fix for aws.eks.clusters { * }
```
cnquery> aws.eks.clusters
aws.eks.clusters: [
0: aws.eks.cluster arn="arn:aws:eks:us-west-2:-----:cluster/tim_test" version="1.30" status="ACTIVE"
]
cnquery> aws.eks.clusters { * }
aws.eks.clusters: [
0: {
networkConfig: {
```
fixes https://github.com/mondoohq/cnquery/issues/4257

🐛 fix aws.eks.clusters { * } panic

---

providers/os/resources/packages/rpm_packages.go
providers/os/resources/packages/rpm_packages_test.go

```sh
cnquery run -c 'packages' | grep pulse
```
```
601: package name="pulseaudio-libs" version="16.1-8.fc40"
650: package name="pulsesecure" version="2:9.1-R14"
653: package name="pipewire-pulseaudio" version="1.0.9-1.fc40"
```
---
```sh
cnquery run -c 'packages.where(name == /pulse.*/) { name description vendor epoch version arch }'
```
```graphql
packages.where.list: [
0: {
name: "pulseaudio-libs"
description: "Libraries for PulseAudio clients"
vendor: "Fedora Project"
version: "16.1-8.fc40"
epoch: ""
arch: "x86_64"
}
1: {
name: "pulsesecure"
description: "Pulse Secure Client For Linux"
vendor: "(none)"
version: "2:22.7-R1"
epoch: "2"
arch: "x86_64"
}
2: {
name: "pipewire-pulseaudio"
description: "PipeWire PulseAudio implementation"
vendor: "Fedora Project"
version: "1.0.9-1.fc40" …
```

🐛 RPM: fix match "(none)" vendor

---

providers/ms365/connection/adapter.go
providers/ms365/go.mod
providers/ms365/go.sum
providers/ms365/resources/microsoft.go
providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/users.go

Uses the beta-available only API for listing user details: https://learn.microsoft.com/en-us/graph/api/authenticationmethodsroot-list-userregistrationdetails?view=graph-rest-1.0&tabs=http
This API is only available for P1/P2 licenses. When running the query against a tenant that doesn't have that license:
```
4: {
mfaEnabled: Neither tenant is B2C or tenant doesn't have premium license
displayName: "Chris Test"
}
```
When running against a properly licensed tenant:
```
30: {
mfaEnabled: true
displayName: "Preslav Gerchev"
}
```
The code ensures that we can still grab users, even if the user registration details API call fails.

✨ Add microsoft.user.mfaEnabled field.

---

explorer/scan/discovery.go
llx/llx.go
logger/tracer.go
providers/github/provider/provider.go
providers/github/resources/discovery.go
providers/github/resources/github_org.go
providers/github/resources/github_repo.go
providers/github/resources/github_user.go

`FuncDur` must be used in a `defer` statement.
This new helper function receives the function name and the time when the
function started and logs out the time it took to run.
Example:
```go
package mypackage
func MyFunction() {
defer logger.FuncDur(time.Now(), "mypackage.MyFunction")
...
}
```

🔨 new `logger.FuncDur()`

---

providers/github/resources/github.go

Long running scan executions ask for the same resources multiple times since we
expire the github provider cache every 30 minutes. This change is increasing the
time to 24 hours. This will avoid a single scan to ask for the same resources multiple
times, this way we will decrease the execution time of long running scans.

⚡️ increase github expiration cache to 24h

---

providers/ansible/config/config.go
providers/arista/config/config.go
providers/atlassian/config/config.go
providers/aws/config/config.go
providers/azure/config/config.go
providers/cloudformation/config/config.go
providers/core/config/config.go
providers/equinix/config/config.go
providers/gcp/config/config.go
providers/github/config/config.go
providers/gitlab/config/config.go
providers/google-workspace/config/config.go
providers/ipmi/config/config.go
providers/k8s/config/config.go
providers/mondoo/config/config.go
providers/network/config/config.go
providers/oci/config/config.go
providers/okta/config/config.go
providers/opcua/config/config.go
providers/os/config/config.go
providers/shodan/config/config.go
providers/slack/config/config.go
providers/snowflake/config/config.go
providers/terraform/config/config.go
providers/vcd/config/config.go
providers/vsphere/config/config.go

…re-11.3.10, cloudformation-11.0.29, core-11.0.16, equinix-11.0.37, gcp-11.0.43, github-11.4.21, gitlab-11.1.31, google-workspace-11.1.15, ipmi-11.0.37, k8s-11.1.31, mondoo-11.1.15, network-11.0.32, oci-11.0.37, okta-11.0.37, opcua-11.0.37, os-11.3.2, shodan-11.0.26, slack-11.0.39, snowflake-11.0.23, terraform-11.0.37, vcd-11.0.37, vsphere-11.0.37

🎉 Update providers 20241030

---

providers/os/resources/windows.go
providers/os/resources/windows/computerinfo.go

We split up the big script in 2 separate scripts. If 1 fails or gives us incomplete data, we execute the other. We also do the mapping of the results in Go now instead of in powershell to make sure the script is short enough to run remotely

🐛 rework windows.computerInfo to not go over size limit

---

providers/os/config/config.go

🎉 os-11.3.3

---

providers/gcp/connection/gcpinstancesnapshot/provider.go
providers/os/connection/snapshot/blockdevices.go

This fixes the GCP snapshot scanning. In GCP devices are aliased under `/dev/disk-by-id/<device-name>`. This PR builds on top of the already supported alias finding by looking into that directory as well

✨ Support searching /dev/disk/by-id aliases.

---

providers/os/config/config.go

🎉 os-11.3.4

---

llx/builtin_simple.go

MQL to reproduce panic with unpatched versions:
```
"foo".in("bar baz".split(" ").map( [""][1] ))
```
> [!NOTE]
> It appears that the usage of `.map()` allows to bypass the type assertion for `.in()`

🐛 handle malformed array argument

---

providers/os/detector/detector_platform_test.go
providers/os/detector/detector_win.go
providers/os/detector/testdata/detect-windows2019.toml
providers/os/detector/testdata/detect-windows2022.toml
providers/os/detector/testdata/detect-windows2025.toml
providers/os/detector/windows/build_version.go
providers/os/detector/windows/build_version_test.go
providers/os/resources/powershell/encode.go

```
cnquery shell ssh administrator@192.168.64.3 --ask-pass
→ connected to Windows Server 2025 Datacenter
cnquery> asset { platform version build labels arch  }
asset: {
build: "5000"
version: "26311"
arch: "ARM64"
labels: {
windows.mondoo.com/display-version: "24H2"
windows.mondoo.com/product-type: "3"
}
platform: "windows"
}
cnquery> 
```

⭐️ support Windows 2025 on arm via SSH

---

providers/os/connection/shared/shared.go
providers/os/fs/find_files.go
providers/os/fs/find_files_test.go
providers/os/fs/fs.go
providers/os/resources/files.go
providers/os/resources/packages/windows_packages.go

To avoid walking the entire FS when looking for packages, this PR introduces a depth limit parameter to speed up the traversal of the FS by stopping when a certain depth is reached.
This is currently only used for windows FS packages search where we've observed the following:
* Some packages are under `Program Files\WindowsApps`
* Some packages are under `Windows\SystemApps`
* Some packages are found under `Windows`
We could easily solve this by looking into just `Windows` and `Program Files\WindowsApps` but that proves to be slowly since we then search the entire `Windows` dir which is quite big

✨ Add depth to file searching.

---

.github/actions/spelling/expect.txt
providers/os/resources/fstab.go
providers/os/resources/fstab_test.go
providers/os/resources/os.go
providers/os/resources/os.lr
providers/os/resources/os.lr.go
providers/os/resources/os.lr.manifest.yaml

```
cnquery run -c "fstab.entries { * }"
fstab.entries: [
0: {
fsck: 1
options: "defaults,noatime"
device: "UUID=7c4e7e0e-ce36-42f9-b456-16f78f3a1eb1"
fstype: "xfs"
mountpoint: "/"
dump: 1
}
1: {
fsck: 2
options: "defaults,noatime,uid=0,gid=0,umask=0077,shortname=winnt,x-systemd.automount"
device: "UUID=C155-24D2"
fstype: "vfat"
mountpoint: "/boot/efi"
dump: 0
}
]
```
```
cnquery run device -c "fstab.entries { * }" --device-name sdby
fstab.entries: [
0: {
fsck: 1
options: "discard,commit=30,errors=remount-ro"
device: "LABEL=cloudimg-rootfs"
fstype: "ext4"
mountpoint: "/"
dump: 0
}
1: {
fsck: 2
options: "defaults"
device: "LABEL=BOOT"
fstype: "ext4"
mountpoint: "/boot"
dump: 0
}
2: {
fsck: 1
options: "umask=0077"
device: "LABEL=UEFI"
fstype: "vfat"
mountpoint: "/boot/efi"
dump: 0
}
]
```

✨ fstab parser

---

.github/workflows/providers.yaml

Uses cert alias from Github Actions Secrets to use in provider build script for signing.

Update jSign to use secret cert alias

---

providers/ms365/resources/conditional-access.go
providers/ms365/resources/ms365.lr.go

🧹 fixing a bug in NamedLocation under conditional access - MS365

---

providers/ms365/resources/conditional-access.go
providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml

🧹 Adding Country location to NamedLocation under conditional access - MS365

---

cli/providers/providers.go
test/providers/os_test.go

This change allows `cnquery` to load all provider flags via environment variables. For instance, if a provider exposes a flag named `foo`, the user can export the environment variable `MONDOO_FOO` to provide a value.
The trick here was to switch loading the flag values from `cobra` to `viper`, since we already ran `viper.BindPFlag()` inside the command `PreRun`, we can now use `viper.Get()` directly.

🐛 Load provider flags from environment variables

---

providers/gitlab/config/config.go
providers/gitlab/resources/gitlab.go
providers/gitlab/resources/gitlab.lr
providers/gitlab/resources/gitlab.lr.go
providers/gitlab/resources/gitlab.lr.manifest.yaml

Get some more data
```coffee
gitlab.group.projects.first.projectMembers: [
0: gitlab.project.member username="root" role="Owner" name="Administrator"
1: gitlab.project.member username="group_3_bot_b7fcf7deff3b60d0c34254b9fe169255" role="Reporter" name="mondoo-scanner"
]
```
```coffee
cnquery> gitlab.group.projects.first{jobsEnabled emptyRepo sharedRunnersEnabled groupRunnersEnabled}
gitlab.group.projects.first: {
emptyRepo: false
groupRunnersEnabled: true
jobsEnabled: true
sharedRunnersEnabled: true
}
```
```coffee
cnquery> gitlab.group.projects.first.approvalSettings{*}
gitlab.group.projects.first.approvalSettings: {
mergeRequestsAuthorApproval: false
mergeRequestsDisableCommittersApproval: false
approvalsBeforeMerge: 0
resetApprovalsOnPush: false
requirePasswordToApprove: false …
```

Expand fields for GitLab project

---

providers/gitlab/config/config.go

🎉 gitlab-11.1.36

---

providers/os/id/aws/aws.go
providers/os/id/aws/aws_test.go
providers/os/id/azure/azure.go
providers/os/id/clouddetect/clouddetect.go
providers/os/id/gcp/gcp.go
providers/os/id/gcp/gcp_test.go
providers/os/provider/detector.go
providers/os/resources/smbios/win.go

Retrieving the smbios info for windows can be expensive. This PR makes sure the resposne is cached in the manager and that we use a single manager during detection. It will make sure we will run the powershell script once instead of 3 times

🧹 cache windows smbios response 

---

providers/os/config/config.go

🎉 os-11.3.9

---

providers/os/id/azcompute/azcompute.go

Dear Mondoo team,
this change should fix the issue https://github.com/mondoohq/cnspec/issues/1486
Kind regards
Tom

Add curl timeout for cloud metadata lookup at unix systems on Azure

---

cli/providers/providers.go
test/providers/os_test.go

The problem from my original PR https://github.com/mondoohq/cnquery/pull/4847  to load provider flags from environment
variables was that I didn't consider the case where a provider defines a flag with
`ConfigEntry = "-"`. For those cases, we do NOT bind the flag to the `viper` config
and therefore, we couldn't load these flags.
This PR fixes that issue and, for those flags that are not bind to the config, we will
continue to fetch the value directly from the flag itself, that is, from `cobra`.

🐛 bring back loading provider flags from env vars

---

providers/os/config/config.go

🎉 os-11.3.12

---

Makefile

Update the Makefile for Cloudflare

---

providers/github/resources/github.lr

Show values that matter instead of IDs
```
github.organization.packages: [
0: github.package name="foo" packageType="npm" visibility="private" repository.fullName="mondoohq/bar"
...
```

⭐ Improve output of GitHub packages

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_ecr.go

- lastRecordedPullTime
- pushedAt
- sizeInBytes
```
...
lastRecordedPullTime: 2024-11-14 15:23:42.949 -0800 PST
pushedAt: 2024-03-19 11:50:13 -0700 PDT
sizeInBytes: 83520228
...
```

⭐ Add additional fields to ECR resource

---

providers/github/resources/github.lr

IDs are useless. List the human readable logins and names instead
Before:
```
cnquery> github.repository.adminCollaborators
github.repository.adminCollaborators: [
0: github.collaborator user=github.user id = github.user/14072
]
```
Now:
```
cnquery> github.repository.adminCollaborators
github.repository.adminCollaborators: [
0: github.collaborator user.login="bbobberson" user.name="Bob Bobberson"
]
```

⭐ GitHub: Improve the output of collaborators

---

.github/workflows/pr-test-lint.yml

Porting over the changes we did in the cnspec repo:
https://github.com/mondoohq/cnspec/blob/main/.github/workflows/pr-test-lint.yml#L138-L151
This will approve and merge these sorts of PRs:
https://github.com/mondoohq/cnquery/pull/4956
https://github.com/mondoohq/cnquery/pull/4948

🤖 Auto approve dep bump and provider release PRs

---

providers/os/connection/container/image_connection_test.go
providers/os/connection/tar/connection_test.go
providers/os/connection/tar/fs.go
providers/os/fs/fs.go
providers/os/resources/files.go

🐛 fix find files for tar

---

providers/os/config/config.go

🎉 os-11.3.13

---

providers/vsphere/provider/provider.go
providers/vsphere/resources/discovery.go

The top level here should really be vmware so we don't end up with vsphere under vsphere
Paging @arlimus on this one

Fix the vmware technology URLs

---

.github/actions/spelling/expect.txt
providers/nmap/resources/nmap.lr

- Capitalize Nmap per their website
- Move some terms over to the main dictionary so we don't have to also exclude them from the docs site repo

Nmap provider lr updates

---

internal/workerpool/collector.go
internal/workerpool/pool_test.go
providers/github/resources/github_org.go

When workers return empty results with `nil` errors, the `workerpool` would return those
`nil` errors. 
This change fixes that issue by not returning `nil` errors.

🐛 fix github provider by checking for `nil` errors

---

providers/ms365/resources/applications.go

A panic was reported and this is the fix.
```
cnspec> microsoft.application{*}
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x8b7baca]
goroutine 166 [running]:
go.mondoo.com/cnquery/v11/providers/ms365/resources.(*mqlMicrosoftApplication).servicePrincipal(0xc000b00008)
/home/runner/_work/cnquery/cnquery/providers/ms365/resources/applications.go:256 +0x16a
go.mondoo.com/cnquery/v11/providers/ms365/resources.(*mqlMicrosoftApplication).GetServicePrincipal.func1()
/home/runner/_work/cnquery/cnquery/providers/ms365/resources/ms365.lr.go:4301 +0x7f
go.mondoo.com/cnquery/v11/providers-sdk/v1/plugin.GetOrCompute[...](0xc000b003c0?, 0x805385)
/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/runtime.go:269 +0x37 …
```

🐛 ms365: check error before accessing resp

---

cli/providers/providers.go

Current:
```
--discover strings             Enable the discovery of nested assets. Supports: all,auto,repos,users,organization,terraform,k8s-manifests
```
With this PR
```
--discover strings             Enable the discovery of nested assets. Supports: all, auto, repos, users, organization, terraform, k8s-manifests
```

Improve printing of discovery options in help

---

providers/github/config/config.go

fixes this:
```
Use the github provider to query resources within GitHub organizations and repositories.
Available commands:
org					              GitHub organization
repo                      GitHub repo
```

Fix formatting in GitHub help

---

providers/azure/resources/armsecurity.go
providers/azure/resources/azure.lr
providers/azure/resources/azure.lr.go
providers/azure/resources/azure.lr.manifest.yaml
providers/azure/resources/policy.go

extend `azure.subscription.policy.assignments` to include `{parameters}` field 
```
}
6: {
parameters: {
allowedSkus: {
value: ""
}
approvedExtensions: {
value: [
0: "GuestAttestation"
]
}
effect: {
value: "Deny"
}
}
}
```

:sparkles: Extend `azure.subscription.policy.assignments` to include `{parameters}` field 

---

Makefile
providers-sdk/v1/lr/cli/cmd/markdown.go

- Rename the Mondoo pack to be Mondoo Platform so it's more clear what this does
- Avoid `Mondoo Mondoo Platform` by renaming the pack headers

Improve the MQL resource pack docs generation

---

providers/azure/resources/cloud_defender.go

for https://github.com/mondoohq/cnquery/issues/5000
@mm-weber can you check if this is the data that you need/if this works for you?

🧹 add extensions values to defender for containers resource

---

providers/github/connection/connection.go
providers/github/connection/connection_test.go
test/providers/github_test.go
test/providers/os_test.go

Similar to https://github.com/mondoohq/cnquery/pull/5004

🐛 fix loading private key from inventory

---

providers/k8s/resources/k8s.lr
providers/k8s/resources/k8s.lr.go
providers/k8s/resources/k8s.lr.manifest.yaml
providers/k8s/resources/node.go

Fetch the creation date, the port, and the overall OS config.
```coffee
cnquery> k8s.nodes.first{ created nodeInfo kubeletPort }
k8s.nodes.first: {
kubeletPort: 10250
nodeInfo: {
architecture: "arm64"
bootID: "ae92580d-e68f-4108-8074-2c6e9c8e3351"
containerRuntimeVersion: "docker://24.0.7"
kernelVersion: "6.10.11-linuxkit"
kubeProxyVersion: ""
kubeletVersion: "v1.31.0"
machineID: "c08bfdd8746d444497cb3dfe0a128dc2"
operatingSystem: "linux"
osImage: "Ubuntu 22.04.3 LTS"
systemUUID: "c08bfdd8746d444497cb3dfe0a128dc2"
}
created: 2024-02-23 11:58:20 -0800 PST
}
```
Paging @imilchev to see if I did any of this correctly

Add new values to the k8s.node resource

---

providers/network/config/config.go
providers/network/connection/connection.go
providers/network/provider/provider.go
providers/network/resources/http.go
providers/network/resources/network.lr
providers/network/resources/network.lr.go
providers/network/resources/network.lr.manifest.yaml
providers/network/resources/url.go

By default, we will not follow redirects. You can follow redirects with a flag:
```
go run ./apps/cnquery -- shell host --follow-redirects http://mondoo.com
```

⭐️ Make following redirects configurable for http.get resource

---

providers/defaults.go

Adds cloudflare to the default provider.
```
cnquery run cloudflare -c "cloudflare.zones[1] { name dns { * } }"
→ installing provider 'cloudflare' version=11.0.5
→ successfully installed cloudflare provider path=/Users/chris/.config/mondoo/providers/cloudflare version=11.0.5
```

🧹 add cloudflare to default providers

---

providers/os/config/config.go
providers/os/connection/device/device_connection.go
providers/os/provider/provider.go

+ skip asset detection option for the connections, that reuse device connection for blocks mounting, but have their own asset

feat: keep block devices mounted option

---

providers/aws/connection/connection.go

fixes issue with region fetching - we already have a configured region when we need to fetch the regions list

🐛 use configured region to fetch regions list (aws)

---

providers/defaults.go

Some provider IDs didn't match between what is expected and what it actually is. This caused downloading providers that are already present on the machine. This PR fixes the issue
fixes mondoohq/cnspec#1537

🐛 do not download providers when already present

---

providers/gcp/resources/gcp.lr
providers/gcp/resources/gcp.lr.go
providers/gcp/resources/gcp.lr.manifest.yaml
providers/gcp/resources/storage.go

add encryption settings as a dict

✨ add encryption to gcp storage bucket resource

---

providers/gcp/config/config.go

🎉 gcp-11.0.57

---

mqlc/mqlc.go

```
panic: something bad [recovered]
panic: panic compiling "asset { kind platform runtime version family }": something bad
go.mondoo.com/cnquery/v11/mqlc.Compile.func1()
/home/jaym/workspace/mondoo/cnquery/mqlc/mqlc.go:2189 +0xb3
panic({0x256d240?, 0x30aef10?})
/usr/lib/go/src/runtime/panic.go:785 +0x132
go.mondoo.com/cnquery/v11/mqlc.compile({0x2c3a735?, 0xc000a5fcf0?}, 0x0, {{0x30ec1f0, 0xc000742290}, 0x0, {0x30fa3d8, 0x49908a0}})
/home/jaym/workspace/mondoo/cnquery/mqlc/mqlc.go:2177 +0x248
go.mondoo.com/cnquery/v11/mqlc.Compile({0x2c3a735?, 0x2?}, 0x2?, {{0x30ec1f0, 0xc000742290}, 0x0, {0x30fa3d8, 0x49908a0}})
/home/jaym/workspace/mondoo/cnquery/mqlc/mqlc.go:2193 +0xbe
go.mondoo.com/cnquery/v11/explorer/executor.MustCompile({0x2c3a735, 0x2e}) …
```

🧹 add query in panic when compiling

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_iam.go

createdAt is what Amazon uses in most of their SDK. Some of the older APIs use different values and in many cases we copied those over into our resources. This continues the work to unify all of the AWS resources on createdAt so it's easier to explore fields on resources without looking at the docs.
```
aws.iam.policies.first: {
createdAt: 2022-11-27 13:27:54 -0800 PST
}
aws.iam.users.first: {
createdAt: 2021-06-15 00:18:34 -0700 PDT
}
aws.iam.credentialReport.first: {
createdAt: 2019-11-08 06:02:45 -0800 PST
}
aws.iam.instanceProfiles.first: {
createdAt: 2024-07-22 11:57:13 -0700 PDT
}
aws.iam.policies.first.versions: [
0: {
createdAt: 2023-05-03 22:29:29 -0700 PDT
}
1: {
createdAt: 2022-11-27 13:27:54 -0800 PST
}
]
aws.iam.roles.first: {
createdAt: 2024-06-27 13:10:34 -0700 PDT
}
```

Unify more of the aws resources on createdAt

---

cli/shell/completer.go
cli/shell/shell.go
feature_string.go
featureflags.go

It can be run with
```
MONDOO_FEATURES=ForceShellCompletions cnquery shell local
```
edit:
I guess on windows that would be
```
$env:MONDOO_FEATURES = "ForceShellCompletions"
cnquery shell local
```

Add featureflag to force shell completions for windows

---

providers/gcp/config/config.go

🎉 gcp-11.0.60

---

providers/gcp/resources/cloudrun.go

before
```
traffic: failed to convert dict to primitive, unsupported child type: int32
```
after
```
traffic: [
0: {
percent: "100"
revision: ""
tag: ""
type: "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"
}
]
```

🐛 fix dict translation for cloudrun service traffic

---

providers/network/resources/tlsshake/tlsshake.go

The current code can wait indefinitely if nothing gets sent over the network socket. I added a deadline to make sure if nothing comes back within 5s we just timeout.

🐛 don't wait indefinitely when testing tls

---

.github/workflows/providers.yaml

RELEASR_ACTION_TOKEN seems to have expired: `Error: Bad credentials`

Replace repo-level token with GH App

---

providers/vsphere/resources/resourceclient/README.md

This link is gone:
https://blogs.vmware.com/PowerCLI/2018/03/installing-powercli-10-0-0-macos.html
So as http://docs.vmware.com/

📝 vsphere README.md broken link

---

providers/github/connection/connection.go
providers/github/provider/provider.go
test/providers/github_test.go

Github provider has two authentication methods.
1. Application credentials
2. Personal access token
We give precedence to the former and, if both auth methods are provided,
we will output a warning.
Closes https://github.com/mondoohq/cnquery/issues/5036

🐛  github: fix precedence flag vs env-var

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws_rds.go

Makes this resource work with the asset discover
```
cnquery> aws.rds.dbcluster{*}
aws.rds.dbcluster: {
hostedZoneId: "1234"
preferredBackupWindow: "08:29-08:59"
tags: {}
id: "tim-cluster"
createdTime: 2024-12-31 22:48:02.639 -0800 PST
members: [
0: aws.rds.dbinstance id="tim-cluster-instance-1" region="us-west-2" engine="aurora-postgresql" engineVersion="15.4"
]
activityStreamMode: ""
iamDatabaseAuthentication: false
port: 5432
availabilityZones: [
0: "us-west-2a"
1: "us-west-2b"
2: "us-west-2d"
]
storageAllocated: 1
autoMinorVersionUpgrade: true
engineLifecycleSupport: "open-source-rds-extended-support-disabled"
storageType: null
0: aws.ec2.securitygroup id="sg-1234" name="default" region="us-west-2" vpc.id="vpc-ffa59787"
]
storageIops: 0 …
```

Add init for aws.rds.dbcluster

---

cli/printer/mql.go
llx/data_conversions.go
llx/primitives.go
llx/range.go
llx/range_test.go
llx/rawdata.go
providers-sdk/v1/lr/go.go
providers-sdk/v1/lr/lr.go
providers-sdk/v1/lr/lr_test.go
providers-sdk/v1/lr/schema.go
providers/os/resources/file.go
providers/os/resources/os.lr
providers/os/resources/os.lr.go
providers/os/resources/os.lr.manifest.yaml
providers/os/resources/sshd.go
providers/os/resources/sshd/params.go
providers/os/resources/sshd_test.go

remaining todos after this: fix printing of the range, fix extractor, and make a nice context extraction
```
> sshd.config.blocks { criteria context }
sshd.config.blocks: [
0: {
criteria: ""
context: file.context file.path="/etc/ssh/sshdconfig" range=1-172
}
1: {
criteria: "Group sftp-users"
context: file.context file.path="/etc/ssh/sshdconfig" range=173-177
}
2: {
criteria: "User myservice"
context: file.context file.path="/etc/ssh/sshdconfig" range=178-181
}
]
```

🌟 file.context on sshd

---

llx/range.go
llx/range_test.go
providers/os/resources/file.go
providers/os/resources/sshd/params.go

Add a test-suite and tests to make sure the range extractor works as expected, including misconfigured ranges.
Please note, this is not yet about fancy content excerpt printing on CLI, just about making sure the extraction of content using a range works as expected.
Basically now we get correct content:
```
> sshd.config.blocks { criteria context context.content }
sshd.config.blocks: [
0: {
criteria: ""
context: file.context file.path="/pub/go/src/github.com/mondoohq/cnquery/sshdconfig" range=    1-171
context.content: "# 
#
... lots of content, just removed it here but needs proper handling ...
"
}
1: {
criteria: "Group sftp-users"
context: file.context file.path="/pub/go/src/github.com/mondoohq/cnquery/sshdconfig" range=    173-176
context.content: "Match Group sftp-users
X11Forwarding …
```

🐛 ExtractString for ranges

---

providers/ms365/resources/api_query_parameters.go
providers/ms365/resources/applications.go
providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/ms365_exchange.go
providers/ms365/resources/rolemanagement.go
providers/ms365/resources/users.go

When writing policies that require fetching huge amount of data only to search or filter for specific resources, we fetch all resources and then we apply the filters using the builtin functions `where()` `any()` and more.
An example of a policy check that uses these patterns is:
```
// search for emergency accounts
microsoft.users.any(displayName == /emergency/)
// emrgIds holds the ids which match the above criteria
emrgID = microsoft.users.where(displayName == /emergency/).map(id)
// check if at least one of the accounts identified as such is attached to the "Global Administrator" role
microsoft.rolemanagement.roleDefinitions.where(displayName == "Global Administrator").all(assignments.any(principalId == emrgID))
```
To improve these resources, I am proposing a new pattern, similar to …

⚡️ filtered resources: `microsoft.users` & `microsoft.roles`

---

apps/cnquery/cmd/plugin.go

For some reason we had missed to migrate the feature-setting from env variables for this command

🐛 support features on cnquery run

---

.github/actions/spelling/expect.txt
providers/azure/resources/azure.lr
providers/azure/resources/azure.lr.go
providers/azure/resources/azure.lr.manifest.yaml
providers/azure/resources/web.go

```
cnquery> azure.subscription.web.apps { ftp {*} scm {*} }
azure.subscription.web.apps: [
0: {
ftp: {
type: "Microsoft.Web/sites/basicPublishingCredentialsPolicies"
allow: true
name: "ftp"
id: "/subscriptions/abc123-1111-2222-3333-abc123xyz890/resourceGroups/azure-group-9d81d/providers/Microsoft.Web/sites/app-275u5hwyego5q/basicPublishingCredentialsPolicies/ftp"
}
scm: {
allow: true
name: "scm"
id: "/subscriptions/abc123-1111-2222-3333-abc123xyz890/resourceGroups/azure-group-9d81d/providers/Microsoft.Web/sites/app-275u5hwyego5q/basicPublishingCredentialsPolicies/scm"
type: "Microsoft.Web/sites/basicPublishingCredentialsPolicies"
}
}
]
```
Closes https://github.com/mondoohq/cnquery/issues/5056

✨ azure: new `appsite` fields `ftp` & `scm`

---

llx/range.go
llx/range_test.go

After #5187
effectively giving us:
```
content="  1:  # Include drop-in configurations
2:  Include /etc/ssh/sshd_config.d/*.conf
3:  
4:  # This is the sshd server system-wide configuration file.  See
...
116:  #	PermitTTY no
117:  #	ForceCommand cvs server
118:  "
```

⭐ add line numbers to file.context snippets

---

providers/os/connection/device/device_connection.go
providers/os/connection/device/linux/device_manager.go
providers/os/connection/device/linux/lun.go
providers/os/connection/device/linux/lun_test.go
providers/os/connection/device/windows/device_manager.go
providers/os/connection/device/windows/device_manager_test.go
providers/os/connection/device/windows/disk_drive.go

Do not fetch devices by lun. Instead fetch the matching device names, that way we ensure there's only one code path for fetching devices which is via their name

✨ Simplify retrieval of devices via logical unit numbers.

---

providers/azure/go.mod
providers/azure/go.sum
providers/azure/resources/armsecurity.go
providers/azure/resources/azure.lr
providers/azure/resources/azure.lr.go
providers/azure/resources/azure.lr.manifest.yaml
providers/azure/resources/cloud_defender.go

~BREAKING CHANGE!!!~
----------------------
Azure deprecated `AlertNotifications` in favor of `NotificationSources`
https://learn.microsoft.com/en-us/rest/api/defenderforcloud/security-contacts/get?view=rest-defenderforcloud-2023-12-01-preview&tabs=Go#notificationssourceattackpath
This change is an alternative to https://github.com/mondoohq/cnquery/pull/5183 where we fetch the latest information about security contacts.
With this change we will now detect both notification sources, Alert and AttackPath.
```
cnquery> azure.subscription.cloudDefender.securityContacts { notificationSources }
azure.subscription.cloudDefender.securityContacts: [
0: {
notificationSources: {
Alert: {
minimalSeverity: "High"
sourceType: "Alert"
}
AttackPath: {
minimalRiskLevel: "Critical"
sourceType: "AttackPath" …
```

✨ azure support for defender email notification sources

---

apps/cnquery/cmd/sbom.go
sbom/cnquery_bom_test.go
sbom/cyclonedx_test.go
sbom/generator/generator.go
sbom/generator/report_collection.go
sbom/generator/sbom_test.go
sbom/generator/testdata/alpine-failed-package.json
sbom/spdx_test.go

This ensures that if the SBOM query pack errors out, we still get an SBOM pack with a status of Failed and the correct error message. If one of the queries error out the whole SBOM generation will fail. For example, this report will fail without the current changes:
```json
// this is just the sbom packages piece, the rest is omitted for brevity
"//local.cnquery.io/run/local-execution/queries/mondoo-sbom-packages": {
"content": {
"packages.list": {
"error": "error fetching sbom packages for some reason"
}
}
}
```

✨ Do not error out on SBOM generation, use the sbom ErrorMessage instead

---

llx/builtin_global.go
llx/builtin_version.go
mqlc/typemaps.go
providers/core/resources/mql_test.go

```
cnquery> version("1.2.3", type: 'semver')
version: 1.2.3
cnquery> version("1:1.2.3", type: 'semver')
version '1:1.2.3' is not a semantic version
version: 1:1.2.3
cnquery> version("1:1.2.3", type: 'debian')
version: 1:1.2.3
cnquery> version("1!1.2.3", type: 'python')
version: 1!1.2.3
cnquery> version("1:1.2.3")
version: 1:1.2.3
```
Also adds support for parsing named arguments on builtin type conversion functions (like `version`).
Part 1 of https://github.com/mondoohq/cnquery/pull/5106#issuecomment-2606678743

✨ version(.., type: "semver")

---

providers/gcp/resources/gke.go
providers/gcp/resources/iam.go

fixes https://github.com/mondoohq/cnquery/issues/5133

🐛 fix fetching of service accounts on gke cluster nodepool config

---

providers/os/resources/packages/rpm_packages_test.go
providers/os/resources/purl/purl.go
providers/os/resources/purl/purl_test.go

Align the namespace with the osv ecosystem.
'pkg:rpm/photon/...' -> 'pkg:rpm/photon%20os/...'

🐛 Align photon PURL namespace with ecosystem

---

cli/printer/mql.go
feature_string.go
featureflags.go
llx/range.go
mqlc/mqlc.go
mqlc/mqlc_test.go
providers/os/resources/os.lr

Specialized printer for file context for resources that support it:
```
sshd.config.blocks: [
0: sshd.config.matchBlock criteria=""
in /pub/go/src/go.mondoo.com/cnquery/sshd_config:1-172
1:  # #
2:  # Ansible managed
...
171:  RevokedKeys /etc/ssh/revoked_keys
172:
1: sshd.config.matchBlock criteria="Group sftp-users"
in /pub/go/src/go.mondoo.com/cnquery/sshd_config:173-177
173:  Match Group sftp-users
174:         X11Forwarding no
175:         PermitRootLogin no
176:         AllowTCPForwarding yes
177:
2: sshd.config.matchBlock criteria="User myservice"
in /pub/go/src/go.mondoo.com/cnquery/sshd_config:178-181
178:  Match User myservice
179:
180:
]
```

⭐ print file context to CLI

---

.github/actions/spelling/line_forbidden.patterns
.github/actions/spelling/patterns.txt

Catch all the new stuff w/o false positives

Pull in new spellcheck patterns

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml

It was in the code but not the lr which caused failures
```
[failed] [].all()
error: [aws] cannot set 'createdAt' in resource 'aws.iam.group', field not found
```

🧹 Wire up the remainder of aws.iam.role.createdAt

---

llx/range.go
llx/range_test.go

There was a mixup with how this method works, because it adds line start
+ end before adding each column. I had it sorted differently earlier and this was a leftover on the CLI printer that messed it up.

🐛 print line+column range correctly

---

providers/os/resources/purl/purl.go
providers/os/resources/purl/purl_test.go

Align the namespace with the osv ecosystem.
'pkg:rpm/sles/...' -> 'pkg:rpm/suse/...'
...

🐛 Fix SUSE PURLs

---

providers/os/detector/detector_test.go
providers/os/detector/detector_win.go

Windows 11 returns `Windows 10` for `ProductName` in `HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion`. We use that as the platform title. This corrects the platform title if its a build that falls into with windows 11 build numbers

🐛 Detect windows 11 name

---

providers/os/resources/purl/purl.go
providers/os/resources/purl/purl_test.go

Align the namespace with the OSV data.
'pkg:rpm/rockylinux/...' -> 'pkg:rpm/rocky-linux/...'

🐛 Fix Rocky Linux PURLs

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_s3.go

This change allows running `aws.s3.bucket.policy` when in discovery mode.
```
cnspec shell aws --discover s3-buckets
```
Also, fixes the issue discovered at https://github.com/mondoohq/cnquery/pull/5218
where we noticed that the policy resource doesn't implement the `id()` func properly.
Closes https://github.com/mondoohq/cnquery/issues/5169

🐛 fix `aws.s3.bucket.policy` resource

---

providers/azure/resources/azure.lr.go
providers/azure/resources/policy.go

Closes https://github.com/mondoohq/cnquery/issues/5040
The problem is that the `DisplayName` is not unique, but the `PolicyDefinitionID` is.

🐛 fix azure.subscription.policy.assignments id

---

providers/aws/resources/aws_s3.go

This fixes a panic reported by @mm-weber 
```
cnspec> aws.s3.bucket.policy
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x80676e0]
goroutine 1274 [running]:
go.mondoo.com/cnquery/v11/providers/aws/resources.(*mqlAwsS3BucketPolicy).MqlID(0x88a7380?)
/home/manuel/go/src/go.mondoo.io/cnquery/providers/aws/resources/aws.lr.go:20888
go.mondoo.com/cnquery/v11/providers/aws/resources.NewResource(0xc00171b3e0, {0xc000b20ea0, 0x14}, 0xc000d315f0)
/home/manuel/go/src/go.mondoo.io/cnquery/providers/aws/resources/aws.lr.go:796 +0x1df
go.mondoo.com/cnquery/v11/providers-sdk/v1/plugin.(*Service).GetData(0x8e7ad40?, 0xc000842d90)
/home/manuel/go/src/go.mondoo.io/cnquery/providers-sdk/v1/plugin/service.go:160 +0x9b …
```

🐛 fix `aws.s3.bucket.policy` panic

---

.github/workflows/goreleaser.yml

Remove repository-dispatch event triggering a release to releases.mondoo.com. Releases will be entirely managed inside the [installer](https://github.com/mondoohq/installer/) repo in the future.

#498 BURP: Remove dispatch event for releases.mondoo.com

---

providers-sdk/v1/util/convert/dict.go
providers-sdk/v1/util/convert/dict_test.go
providers/github/resources/discovery.go
providers/github/resources/github.lr
providers/github/resources/github.lr.go
providers/github/resources/github.lr.manifest.yaml
providers/github/resources/github_org.go
providers/github/resources/github_repo.go

Relates to https://github.com/mondoohq/cnquery/pull/5227
GitHub has a new concept of Custom Properties which allow organizations to have their own properties on each repo in their GitHub orgs.
https://docs.github.com/en/organizations/managing-organization-settings
As a user I need to be able to see GitHub Custom Properties I've set on my organizations and repositories using Mondoo, so I can understand key metadata values such as team ownership.
To retrieve these custom properties, the authenticated user must be one of:
* An administrator for the organization.
* A user, or a user on a team, with the fine-grained permission of
`custom_properties_org_definitions_manager` in the organization.
From:
To:
No custom properties:
With custom properties:

✨ github: repo and org custom properties

---

providers/ms365/resources/applications.go
providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml

Depends on https://github.com/mondoohq/cnquery/pull/5156
Contributes to https://github.com/mondoohq/cnquery/issues/5116
Relates to https://github.com/mondoohq/cnquery/pull/5153
Use Microsoft `$count` parameter to make `microsoft.applications.length` more performant.
https://learn.microsoft.com/en-us/graph/query-parameters?tabs=http#count-parameter

⚡️ improve `microsoft.applications.length`

---

llx/builtin_global.go
llx/rawdata.go
llx/rawdata_test.go

This helps us write 
```go
llx.IPData("1.2.3.4")
```
rather than 
```go
&llx.RawData{Type: types.IP, Value: "1.2.3.4"}
```

✨ adds `llx.IPData()` for easy initialization

---

mqlc/builtin_resource.go

The most common examples look like this:
```coffee
> packages.where("noname")
or
> packages.contains("something")
```
These will always be true, because they don't test the condition!
The correct use is:
```coffee
> packages.where(name == "noname")
```
This will be followed up by the linter (to catch this) and v12 which will make this a breaking change going forward.

🐛 warn users not to use standalone filters

---

llx/builtin_global.go
llx/builtin_ip.go
llx/builtin_ip_test.go
providers/core/resources/mql_test.go

As suggested by @frozen425 add support for integer-based IP addresses:
```coffee
> ip(2885681153)
ip: "172.0.0.1"
```
Currently limited to IPv4 only, I'm not sure yet what the approach would be for 128bit addresses (IPv6) with only 64-bit integers...

✨ integer-based IP addresses

---

providers/os/config/config.go

```
➜  cnquery git:(main) version update providers/os
crawling git history....................................................................................................................................................................................................................................................................................................................................................................................
! looks like there is no previous version in your commit history => we assume this is the first version commit
→ provider changed changes=373 provider=os version=11.3.30
→ set new version previous=11.3.30 provider=os version=11.3.31
→ updated config path=providers/os/config/config.go
→ git add providers/os/config/config.go && git commit -m "🎉 …
```

🎉 os-11.3.31

---

llx/builtin_ip_test.go
llx/rawdata.go
llx/rawdata_test.go
providers-sdk/v1/lr/go.go
providers/os/resources/os.lr.go

We switched the new `ip` type from a `string` to `llx.RawIP`, this change only modifies two things:
* The providers SDK generator to use the new `RawIP`
* The `IPData` accessor to return `NilData` when there is no valid ip

🐛 use `RawIP` inside sdk `lr` generator

---

cli/printer/mql.go
cli/printer/printer_test.go

Fixes this panic:
```
panic: interface conversion: interface {} is nil, not llx.RawIP [recovered]
panic: interface conversion: interface {} is nil, not llx.RawIP
go.mondoo.com/cnquery/v11/providers-sdk/v1/upstream/health.ReportPanic({0x2f11b42, 0x7}, {0x3374d80, 0x8}, {0x3374d90, 0x9}, {0x0, 0x0, 0x0?})
/Users/afiune/go/src/go.mondoo.com/cnquery/providers-sdk/v1/upstream/health/errors.go:32 +0x16c
panic({0x2a2ac80?, 0xc0008675c0?})
/opt/homebrew/Cellar/go/1.23.4/libexec/src/runtime/panic.go:785 +0x132
go.mondoo.com/cnquery/v11/cli/printer.(*Printer).Data(0x4e6d350, {0x4c36c78, 0x1}, {0x0, 0x0}, {0xc000886600, 0x58}, 0xc0008786e0, {0xc00087b378, 0x4})
/Users/afiune/go/src/go.mondoo.com/cnquery/cli/printer/mql.go:790 +0x1ef1 …
```

🐛 fix mql printer for `RawIP`

---

providers/os/resources/packages/windows_packages.go

If the package has an empty name skip it. It can cause errors downstream later due to creating invalid PUrls that can't be parsed.
Fixes: #5261.

Ignore packages with empty names

---

apps/cnquery/cmd/login.go
cli/config/store.go
cli/config/store_test.go
go.mod

Additionally, we have a way to add more fields we want to omit from storing
in the config.

🐛 omit storing `force` flag in config

---

providers/os/config/config.go

```
➜  cnquery git:(main) version update providers/os
crawling git history...
! looks like there is no previous version in your commit history => we assume this is the first version commit
→ provider changed changes=552 provider=os version=11.3.33
→ set new version previous=11.3.33 provider=os version=11.3.34
→ updated config path=providers/os/config/config.go
→ git add providers/os/config/config.go && git commit -m "🎉 os-11.3.34"
```

🎉 os-11.3.34

---

providers/k8s/connection/shared/resources/discovery.go

Closes https://github.com/mondoohq/cnquery/issues/5165
A sand-boxed cluster doesn't have metrics server enabled:
https://cloud.google.com/kubernetes-engine/docs/concepts/sandbox-pods#limitations-incompatible
This code fails just because that single API resource, out of 40+ resources, fails.
Now we will just display a warning that "some" api resources aren't available.

🐛 k8s: don't fail during api resource discovery

---

.github/.golangci.yml
.golangci.yml

This fixes https://github.com/mondoohq/cnquery/actions/runs/13896435625/job/38878008963\?pr\=5321

🧹 Fix deprecated/removed parameters for golangci

---

.github/.golangci.yml
.golangci.yml

This fixes https://github.com/mondoohq/cnquery/actions/runs/13896435625/job/38878008963\?pr\=5321
Follow-up to https://github.com/mondoohq/cnquery/pull/5325
They were not only renamed, but also moved to a different section.

🧹 Fix moved parameters for golangci

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_ec2.go
providers/aws/resources/aws_vpc.go

- Default values for the aws.ec2.eip resource
- Add `completionTime` and `storageTier` to aws.ec2.snapshot
- Add `internetGatewayBlockMode` to `aws.vpc` and `aws.vpc.subnet`
- Add `availableIpAddressCount` to `aws.vpc.subnet`
- Add `enaSupport` and `tpmSupport` to `aws.ec2.image`

Resource improvements in the AWS provider

---

providers/os/resources/packages/macos_packages.go
providers/os/resources/packages/macos_packages_test.go
providers/os/resources/packages/windows_packages.go
providers/os/resources/packages/windows_packages_test.go

- Fixes an issue with missing arch in packages for windows and macos

🐛 Fix missing package arch in windows and macos

---

.github/.golangci.yml

Fixes: https://github.com/mondoohq/cnquery/actions/runs/13915522402/job/38937767869\?pr\=5321

🧹 Empty exclude dirs are no longer supported

---

.golangci.yml

Fixes: https://github.com/mondoohq/cnquery/actions/runs/13915522402/job/38937767869\?pr\=5321

🧹 Empty exclude dirs are not longer supported - 2nd config file

---

providers/os/resources/lsblk.go
providers/os/resources/lsblk_test.go

Depending on a version of lsblk json output might differ slightly
Has `MOUNTPOINT` only: https://man7.org/linux/man-pages/man8/lsblk.8.html
Has both `MOUNTPOINT` and `MOUNTPOINTS`  https://man.archlinux.org/man/lsblk.8.en#:~:text=The%20relationship%20between,with%20the%20device.
Bonus: handle `null` entries

🐛 lsblk: empty mountpoints

---

providers/os/config/config.go

```
➜  cnquery git:(main) version update providers/os
crawling git history...
! looks like there is no previous version in your commit history => we assume this is the first version commit
→ set new version previous=11.3.35 provider=os version=11.3.36
→ updated config path=providers/os/config/config.go
→ git add providers/os/config/config.go && git commit -m "🎉 os-11.3.36"
```

🎉 os-11.3.36

---

providers/aws/connection/awsec2ebsconn/destroy.go
providers/aws/connection/awsec2ebsconn/provider.go
providers/aws/provider/provider.go
providers/aws/resources/discovery_conversion.go

Found two panics.
One when we don't specify the ebs snapshot id.
```
[ec2-user@ip-172-31-6-3 ~]$ cnspec shell aws ec2 ebs snapshot
panic: runtime error: index out of range [3] with length 3
goroutine 34 [running]:
go.mondoo.com/cnquery/v11/providers/aws/resources.EbsConnectAsset({0xc0003ce140?, 0xc0009634b8?, 0x41a453?}, 0xc000560ed0)
/home/runner/_work/cnquery/cnquery/providers/aws/resources/discovery_conversion.go:731 +0x385
go.mondoo.com/cnquery/v11/providers/aws/provider.handleAwsEc2Subcommands({0xc0003ce140, 0x3, 0x4}, 0xc000560ed0)
/home/runner/_work/cnquery/cnquery/providers/aws/provider/provider.go:77 +0x85
go.mondoo.com/cnquery/v11/providers/aws/provider.(*Service).ParseCLI(0xc0000c4d30?, 0xc0008b9ce0)
/home/runner/_work/cnquery/cnquery/providers/aws/provider/provider.go:45 …
```

🐛 prevent aws ebs panics

---

providers/os/id/aws/aws.go
providers/os/resources/smbios/smbios.go
providers/os/resources/smbios/smbios_test.go

Why do we need this? Mainly because our `aws` provider sets the platform family to unix.
https://github.com/mondoohq/cnquery/blob/fa345791676d0a3773fcaad9d70bc9a92b24815e/providers/aws/resources/discovery_conversion.go#L242-L250
Since we check for `darwin` first, this shouldn't have any implication for the `smbios` package, though, changing the `aws` provider may have implications that we can't detect.
This issue prevented our `clouddetect` package to identify some aws assets correctly.

🐛 fix smbios unix family filter

---

llx/builtin_global.go

For the version resource we have been very restrictive. Checking for the type string prevented us from using Ref and Dict for `version`.

🧹 lift type restrictions for version resource

---

providers/k8s/resources/admission.go
providers/k8s/resources/discovery.go
providers/k8s/resources/k8s.lr
providers/k8s/resources/k8s.lr.go
providers/k8s/resources/k8s.lr.manifest.yaml

This PR introduces a new resource to easily ask for [validating webhooks](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/).
```javascript
k8s.validatingWebhookConfigurations { * }
```
```javascript
cnquery> k8s.validatingWebhookConfigurations { webhooks { clientConfig } }
k8s.validatingWebhookConfigurations: [
0: {
webhooks: [
0: {
clientConfig: {
caBundle: "LS0tLS1CR....VEUtLS0tLQo="
service: {
name: "ingress-nginx-controller-admission"
namespace: "ingress-nginx"
path: "/networking/v1/ingresses"
port: 443
}
}
}
]
}
]
```

⭐️ ability to easily fetch the validating webhook configuration

---

sbom/formats.go

Now the command works as expected:
```
cnquery sbom --output cnquery-json
```

🐛 fix json output label for cnquery sbom

---

providers/k8s/config/config.go
providers/k8s/connection/api/aks_auth.go
providers/k8s/connection/api/auth.go
providers/k8s/connection/api/connection.go
providers/k8s/connection/shared/connection.go
providers/k8s/go.mod
providers/k8s/provider/provider.go

Added a `--kubelogin` boolean flag to the Kubernetes provider which gives the option to authenticate against a remote AKS cluster using a JWT bearer token. This flow mimics the flow `kubelogin` ([docs](https://learn.microsoft.com/en-us/azure/aks/kubelogin-authentication)) uses without needing the `kubelogin` CLI to be present locally.
Azure provides us a kubeconfig file with the following exec:
```bash
kubelogin get-token --environment AzurePublicCloud --server-id {value} --client-id {value} --tenant-id {value} --login devicecode
```
this would then get modified to:
```bash
kubelogin get-token --login msi --server-id {value}
```
which is the flow implemented in this PR (uses the inferred managed identity).
Running cnquery with:
```bash
cnquery shell k8s --kubelogin
```
yields
Also …

✨ Authenticate against AKS cluster by mimicking kubelogin managed identity credential token flow.

---

providers/k8s/config/config.go

🎉 k8s-11.1.63

---

providers/os/config/config.go

🎉 os-11.3.41

---

providers/os/resources/docker.go
providers/os/resources/os.lr
providers/os/resources/os.lr.go
providers/os/resources/os.lr.manifest.yaml

This exposes the docker host config and allows us to write the following checks:
*Ensure NET_RAW capability is not enabled*
```javascript
docker.containers.all(hostConfig.CapDrop.contains("ALL") || hostConfig.CapDrop.contains("NET_RAW"))
```
*Check that no privileged container are running*
```
docker.containers.none(hostConfig.Privileged)
```

⭐️ expose docker host config

---

cli/printer/mql.go
providers-sdk/v1/plugin/errors.go
providers/os/provider/provider.go
providers/terraform/provider/provider.go
providers/vsphere/connection/connection.go
utils/multierr/errors.go

Fixes #5389
Instead of showing errors like in the issue above, we now show a simple message where fields are not supported: 
```
asset: {
cpes: unsupported platform
kind: "api"
build: ""
version: ""
platformMetadata: {}
title: "AWS Account"
annotations: {}
purl: unsupported platform
arch: ""
labels: {}
platform: "aws"
vulnerabilityReport: unsupported platform
runtime: "aws"
ids: [
0: "//platformid.api.mondoo.app/runtime/aws/accounts/162854405951"
1: "arn:aws:sts::162854405951"
]
name: "AWS Account 162854405951"
fqdn: ""
family: []
}
```

🐛 only inform on unsupported providers

---

providers/os/resources/packages/aix_packages.go
providers/os/resources/packages/aix_packages_test.go
providers/os/resources/packages/testdata/packages_aix.txt
providers/os/resources/purl/purl.go

This reads the package state from AIX:
```
cnspec> packages.where(name == /bos.sysmgt./) { name version status purl}
packages.where.list: [
0: {
purl: "pkg:generic/aix/bos.sysmgt.hmc@7.3.3.0?arch=powerpc"
version: "7.3.3.0"
name: "bos.sysmgt.hmc"
status: "COMMITTED"
}
1: {
purl: "pkg:generic/aix/bos.sysmgt.loginlic@7.3.3.0?arch=powerpc"
version: "7.3.3.0"
name: "bos.sysmgt.loginlic"
status: "COMMITTED"
}
2: {
purl: "pkg:generic/aix/bos.sysmgt.nim.client@7.3.3.0?arch=powerpc&efix=locked"
version: "7.3.3.0"
name: "bos.sysmgt.nim.client"
status: "COMMITTED|EFIXLOCKED"
}
3: {
purl: "pkg:generic/aix/bos.sysmgt.pvc@7.3.3.0?arch=powerpc"
version: "7.3.3.0"
name: "bos.sysmgt.pvc"
status: "COMMITTED"
}
4: {
purl: "pkg:generic/aix/bos.sysmgt.quota@7.3.3.0?arch=powerpc"
version: "7.3.3.0"
name: …
```

🧹 mark AIX packages that have an efix applied

---

providers/os/detector/detector_all.go
providers/os/detector/detector_platform_test.go
providers/os/detector/testdata/detect-suse-sles-15-sap.toml
providers/os/resources/purl/platform_purl.go

This PR adds support to detect Suse SLES variants.
```
→ connected to SUSE Linux Enterprise Server 15 SP2
cnquery> asset.platformMetadata
asset.platformMetadata: {
distro-id: "sles"
variant-id: "sles-sap"
}
```

⭐️ detect Suse OS variant id

---

providers/os/config/config.go

🎉 os-11.3.42

---

providers/os/config/config.go

🎉 os-11.3.43

---

cli/execruntime/README.md
cli/execruntime/env_circle.go
mqlc/builtin.go
mqlc/mqlc.go
mqlc/parser/operators.go
mqlc/parser/parser.go
types/types.go
types/types_test.go

This only gets the ball rolling, but it starts to expose these builtin types and starts to add docs to them. A lot more work needs to be done to give docs to all of them, but it gets us started at least.
We now also get programmatic access to the `mqlc.BuiltinDocs`, which is a `Schema` containing all our types and their fields and functions.

✨ add docs to builtin types, expose their schema, and operators

---

providers/os/resources/purl/platform_purl.go
providers/os/resources/purl/platform_purl_test.go
sbom/generator/generator.go
sbom/generator/report_collection.go
sbom/pack/pack.go
sbom/pack/sbom.mql.yaml

- we used the platform name in the namespace but not the name
- add build qualifier to include build versions in the purl
- collects build version for sbom generation

🧹 use platform name in purl not as namspace, add build qualifier

---

providers/os/resources/python.go

🧹 do not show warning if a python directory is not existing

---

go.mod
providers-sdk/v1/inventory/asset.go
providers-sdk/v1/inventory/inventory.go
providers-sdk/v1/inventory/inventory_test.go
providers/os/provider/detector.go
providers/os/provider/provider.go
providers/terraform/provider/detector.go

One of the core data structures of Mondoo’s plugin system is the `inventory.Asset` struct that contains details about an asset, including platform information that is stored in `Asset.Platform`.
The `inventory.Platform` struct stores important information used by the Mondoo platform (`server`) like the runtime, the platform kind, and additional metadata.
When we run `cnquery` or `cnspec` most of the times the first thing we do is an initial discovery to detect the asset and platform we are going to scan, then we pass these core data structures to our providers where, sometimes, we do additional discovery and enrichment of data. An example of this is the discovery of AWS instances (`aws` provider) that later gets enriched with additional information from the `os` provider.
We are …

✨ Safe manipulation of `inventory.Platform`

---

providers/os/resources/os.lr.go
providers/os/resources/python.go

Seems like we try to pre-load all dependencies as MQL resources during initialization of python packages. It looks like in some cases this can result in a stack overflow. I don't fully understand python deps but at least with this new approach we will only populate the dependency field if explicitly requested. That should remove the stack overflow and hopefully makes the code easier to follow

🐛 do not load all python package dependencies on init

---

providers/os/config/config.go

i was getting an error when i tried to bump to 45 cause we already tried that version and failed

🎉 os-11.3.46

---

providers/os/config/config.go

🎉 os-11.3.47

---

providers/gcp/resources/gcp.lr
providers/gcp/resources/gcp.lr.go
providers/gcp/resources/gcp.lr.manifest.yaml
providers/gcp/resources/storage.go

Adds support for Storage Lifecycle configuration.
https://cloud.google.com/storage/docs/lifecycle#configuration
```
cnquery> gcp.project.storage.buckets.where( lifecycle != empty) {name lifecycle.first {*}}
gcp.project.storage.buckets.where: [
0: {
lifecycle.first: {
condition: gcp.project.storageService.bucket.lifecycleRuleCondition age=null numNewerVersions=3
action: gcp.project.storageService.bucket.lifecycleRuleAction type="Delete" storageClass=""
}
name: "gcf-v2-sources-239626230709-us-central1"
}
1: {
lifecycle.first: {
condition: gcp.project.storageService.bucket.lifecycleRuleCondition age=30 numNewerVersions=0
action: gcp.project.storageService.bucket.lifecycleRuleAction type="Delete" storageClass=""
}
name: "lunalectric-bucket-owjv"
}
]
```

⭐️ gcp: support storage lifecycle rules

---

providers/gcp/config/config.go

🎉 gcp-11.0.80

---

providers/gcp/connection/clients.go
providers/gcp/connection/connection.go
providers/gcp/connection/gcp_organization.go
providers/gcp/connection/gcpinstancesnapshot/provider.go
providers/gcp/connection/platform.go
providers/gcp/connection/shared/shared.go
providers/gcp/go.mod
providers/gcp/go.sum
providers/gcp/provider/provider.go

We are hitting rate limits like:
```
GCP integration error: rpc error: code = Unknown desc = googleapi: Error 429: Quota exceeded for quota metric 'Project V3 get requests' and limit 'Project V3 get requests per minute' of service 'cloudresourcemanager.googleapis.com' for consumer 'project_number:1234567890
```
This change reduces the number of requests by verifying the connection only once per configuration. We have done this in the past for Github.
Closes https://github.com/mondoohq/cnquery/issues/5095

⚡️ gcp: verify connection only once

---

providers/os/config/config.go

🎉 os-11.4.0

---

.github/actions/spelling/expect.txt
providers/gcp/resources/gcp.lr
providers/gcp/resources/gcp.lr.go
providers/gcp/resources/gcp.lr.manifest.yaml
providers/gcp/resources/gke.go

This PR adds the ability to get GKE node pool autoscaling configuration
```
cnquery> gcp.project.gke.clusters { nodePools.first { autoscaling {*}}}
gcp.project.gke.clusters: [
0: {
nodePools.first: {
autoscaling: {
minNodeCount: 0
totalMinNodeCount: 0
enabled: true
totalMaxNodeCount: 0
maxNodeCount: 1000
autoprovisioned: false
}
}
}
]
```

🌟 Adds GKE autoscaling resource

---

providers/gcp/config/config.go

🎉 gcp-11.0.82

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_rds.go

Adding the `aws.rds.parameterGroup.parameter`, `aws.rds.parameterGroup` resources, as well as field for `aws.rds.dbcluster.parameterGroupName`.
https://github.com/mondoohq/cnquery/issues/5454

✨ add parameter groups and cluster parameter group in AWS RDS

---

providers/aws/connection/connection.go
providers/aws/connection/connection_test.go

Fixes panic:
```
│ DBG new aws connection                                                                                                                                                                                                                                                                                                     │
│ panic: assignment to entry in nil map                                                                                                                                                                                                                                                                                      │
│ …
```

🐛 aws: initialize asset options

---

providers-sdk/v1/testutils/testdata/arch.json
providers/os/resources/auditd.go
providers/os/resources/auditd_test.go
providers/os/resources/os.lr
providers/os/resources/os.lr.go
providers/os/resources/os.lr.manifest.yaml

Add the auditd resource. You can access the configuration via `params` like this:
```coffee
> auditd.config.params
{
action_mail_acct: "root"
admin_space_left: "50"
admin_space_left_action: "suspend"
disk_error_action: "suspend"
disk_full_action: "suspend"
distribute_network: "no"
...
> auditd.config.params.log_format
"enriched"
```
By default, it will read out `/etc/audit/auditd.conf`.  All parameters are lowercase by default. As with similar resources, you can change the path of the file via the first parameter i.e. `auditd.config('/my/path')...`.
Note:
- We downcase all keys in the file, because auditd appears to be case-insensitive
- We do the same to only some of the values. Please check if the list is correct, otherwise feedback is welcome! We felt it was dangerous to downcase …

⭐ auditd.config

---

providers-sdk/v1/testutils/testdata/arch.json
providers/os/resources/mql_test.go
providers/os/resources/os.lr
providers/os/resources/os.lr.go
providers/os/resources/os.lr.manifest.yaml
providers/os/resources/parse.go
providers/os/resources/parse_test.go

Add support for parsing XML files, either by providing the file or by providing the XML contents directly.
Using inline data:
```coffee
> parse.xml(content: '<root />').params
parse.xml.params: {
root: {}
}
```
Via file `example.xml`:
```xml
<root>
<box>
<hello a="1"/>
</box>
<box>
<world b="2">
<c>3</c>
4
</world>
</box>
<box>🌎</box>
</root>
```
Running this in MQL:
```coffee
> parse.json('example.xml').params
parse.xml.params: {
root: {
box: [
0: {
hello: {
@a: "1"
}
}
...
```
Since the conversion from XML to a flat (JSON-like) structure isn't standardized, we took an approach very similar to other formatters (e.g. [xq](https://github.com/sibprogrammer/xq), [jsonformatter](https://jsonformatter.org/xml-to-json)). This means:
- single items are added as a flat child element, e.g. the …

⭐ parse.xml

---

providers/os/resources/processes/testdata/aix72.toml
providers/os/resources/processes/unixps.go

This code was calling log.Fatal when it failed to parse a line. The line was something like
```
18875522                                    -      <idle>
```
Looks like some sort of kernel process
Regardless, this change allows idle and kproc. And it removes uses of fatal and just returns an error

🐛 Fix crash in processes resource on AIX

---

providers/terraform/resources/hcl.go

The block `terraform {}` can be defined multiple times but we don't support that yet,
we will point to the first block and collect all the settings from all blocks to give
as much information as possible back

🐛 terraform: read multiple settings blocks

---

providers/os/id/awsec2/awsec2.go

This change fixes fetching the instance name from the instance tags, before this change we weren't able to run `DescribeTags()` from the `awsec2` package.

🐛 aws: fetch asset name via instance-connect

---

providers-sdk/v1/plugin/start.go
providers-sdk/v1/util/defaults/defaults.go
providers/defaults.go
providers/os/config/config.go
providers/providers.go

The `os` provider has some dependency on the `network` provider. This PR adds a dependencies array to providers that be be updated in the providers configuration. It will search through these dependencies and install any that are missing. 
This is to fix: https://github.com/mondoohq/server/issues/10794

🐛 OS Provider Segfault Fix

---

providers-sdk/v1/lr/lr_test.go
providers-sdk/v1/lr/schema.go
providers-sdk/v1/plugin/start.go
providers-sdk/v1/resources/resources.pb.go
providers-sdk/v1/resources/resources.proto
providers-sdk/v1/util/defaults/defaults.go
providers/defaults.go
providers/os/config/config.go
providers/providers.go

Resources within a provider can depend on resources from another provider,
for example; The `os` provider depends on `network` provider.
The `lr` parser already reads these imports but it wasn't passing it to the
schema. This change adds the list of dependencies so that we can install
them at runtime.

⭐️ `lr`: add provider dependencies to schema

---

providers/os/id/hypervisor/hypervisor_test.go
providers/os/id/hypervisor/testdata/windows_serer_2022_running_hyper_v.toml
providers/os/id/hypervisor/windows_h.go

Modern configurations like Windows Server 2022 running Hyper-V return
generic data so we need a more reliable method, we are going to check the
SMBIOSBIOSVersion as our last detection.

🐛 improve windows hypervisor detection

---

providers/os/id/hostname/hostname.go

The device connection was panicking since we were doing the following check:
```
if err != nil && cmd.ExitStatus != 0
```
If the command exec errs, it's likely `cmd` is nil, so we cannot access it. To reproduce, run
```sh
DEBUG=1 /tmp/cnquery scan device --device-name /dev/sda --include-mounted --mount-all-partitions
```
on a unix machine, replace `/dev/sda` with the root partition device.

🐛 Fix panic when failing to run hostname cmds.

---

explorer/scan/benchmark/benchmark_test.go
explorer/scan/discovery_test.go
providers-sdk/v1/testutils/testutils.go
providers/coordinator.go
providers/providers.go
providers/runtime.go

This change fixes a number of things from our latest release:
* Removes hardcoded `AutoUpdate` setting and uses the config
* Avoids re-installing already installed dependencies
* Propagates the setting `AutoUpdate` to all runtimes created with a parent via `NewRuntimeFrom()`

🐛 Propagate AutoUpdate to all runtimes + avoid reinstalling deps

---

providers/azure/resources/azure.lr
providers/azure/resources/azure.lr.go
providers/azure/resources/azure.lr.manifest.yaml
providers/azure/resources/web.go
providers/azure/resources/web_test.go

Closes https://github.com/mondoohq/cnquery/issues/5386
This change fixes the way we fetch app runtime stacks and exposes a native MQL resource
to make it easier to write policies against this data.
**List all runtime stacks**
**List all Python minor versions**

🐛 azure: fix web app runtime stacks

---

providers/os/resources/packages/windows_packages.go
providers/os/resources/packages/windows_packages_test.go

The single MS SQL Server packages do not show the correct version. Only in combination with the installed MS SQL KBs you can derive the running version.
Before:
```
packages.where.list: [
0: {
name: "Hotfix 4003 for SQL Server 2022 (KB5022375) (64-bit)"
purl: "pkg:windows/windows/Hotfix%204003%20for%20SQL%20Server%202022%20%28KB5022375%29%20%2864-bit%29@16.0.4003.1?arch=AMD64"
version: "16.0.4003.1"
}
...
14: {
name: "Hotfix 4150 for SQL Server 2022 (KB5046059) (64-bit)"
purl: "pkg:windows/windows/Hotfix%204150%20for%20SQL%20Server%202022%20%28KB5046059%29%20%2864-bit%29@16.0.4150.1?arch=AMD64"
version: "16.0.4150.1"
}
...
27: {
name: "SQL Server 2022 Database Engine Services"
purl: "pkg:windows/windows/SQL%20Server%202022%20Database%20Engine%20Services@16.0.1000.6?arch=AMD64"
version: …
```

✨ Show running version of MS SQL based on KBs

---

providers/os/connection/fs/filesystem.go
providers/os/resources/npm.go
providers/os/resources/npm_test.go
providers/os/resources/packages/testdata/gc_package.json
providers/os/resources/packages/testdata/yo_package.json

When the same package is installed in different locations, generate unique IDs to show correct information for each package.
Before:
```
cnspec run vagrant default -c "npm.packages.where(name == /yosay/){ id name version files }" 
npm.packages.where.list: [
0: {
name: "yosay"
id: "yosay/usr/local/lib/node_modules/yo/package.json"
version: "^2.0.2"
files: [
0: pkgFileInfo path="/usr/local/lib/node_modules/yo/package.json"
]
}
1: {
name: "yosay"
id: "yosay/usr/local/lib/node_modules/generator-code/package.json"
version: "^3.0.0"
files: [
0: pkgFileInfo path="/usr/local/lib/node_modules/generator-code/package.json"
]
}
]
```
With this PR:
```
npm.packages.where.list: [
0: {
name: "yosay"
id: "yosay"
version: "^2.0.2"
files: [
0: pkgFileInfo path="/usr/local/lib/node_modules/yo/package.json" …
```

🐛 Fix npm package ID to be uniq across directories

---

providers/network/resources/socket.go
providers/network/resources/tls.go
providers/network/resources/tlsshake/tlsshake.go
providers/os/resources/lsof/lsof.go
providers/os/resources/port.go

The `tls` resource is part of multiple core providers, it requires a `socket`
to know the host, port and protocol, many fields of this resource require
that the server (configured in the socket) speaks TLS and not plain text
(like HTTP), therefore this change makes it so that we only detect once if
the socket is running on TLS or not. If not, we return null properly to
indicate that there are no certificates, if it does, then we collect TLS
information.
Additionally, I am setting a default timeout of one minute to dial to the
socket compared to what was before (unlimited=no timeout).
Finally, if the TLS tester returns a timeout, we don't error the detection
but instead, we set the fields as null.

🐛 detect if tls is enabled

---

llx/builtin.go
providers/core/resources/mql_test.go

When trying to compare a float with an integer, users will get this error:
```
cannot find operator handler: float == int
```
This adds the missing comparison.
Unblocks https://github.com/mondoohq/cnquery/pull/5504

🐛 mqlc: missing float builtin comparison

---

llx/builtin.go
llx/builtin_map.go
llx/builtin_simple.go
mqlc/builtin.go
mqlc/builtin_simple.go
providers/core/resources/mql_test.go

The operator `inRange` currently only works on numbers. This makes it work with number-like strings as well, by parsing the number in the string and then comparing them.
```coffee
> "2".inRange(1,3)
true
```

✨ support inRange on strings

---

providers/os/config/config.go

🎉 os-11.4.10

---

mqlc/mqlc.go
providers-sdk/v1/testutils/testdata/arch.json
providers/core/resources/mql_test.go
providers/os/resources/mql_test.go

Discovered a really nasty bug when accessing maps through the shortcut chaining of identifiers:
```coffee
> sshd.config.params.Port.inRange(20, 23)
cannot find function "[]" for type "string"
```
This is caused by an error in how the type was handled when chaining this way. This is now fixed.
```coffee
> sshd.config.params.Port.inRange(20,23)
true
```

🐛 fix map named access chaining

---

llx/builtin_simple.go
providers/core/resources/mql_test.go

This was previously producing errors or would outright crash with a panic if the value was not set. Maps have fixed types, so it looks for typed functions to do the actual test. However, since a key of a map may not exist, the typed value may still be nil.

🐛 support inRange for nil values in maps

---

providers/k8s/connection/admission/connection.go
providers/k8s/connection/api/connection.go
providers/k8s/connection/manifest/connection.go
providers/k8s/connection/manifest/connection_test.go
providers/k8s/connection/manifest/testdata/no-discovered-objects.yaml
providers/k8s/connection/shared/connection.go
providers/k8s/connection/shared/manifest_parser.go
providers/k8s/provider/provider.go
providers/k8s/resources/discovery.go
providers/k8s/resources/platform_ownership.go

Addressing the issue 👉 [#10441](https://github.com/mondoohq/server/issues/10441)
✅ The new way of building the platform IDs relies solely on the namespaces now.
🟢 n/a

[Issue - 10441] Improved k8s cluster discovery

---

providers/os/resources/packages/snap_packages.go

Fixing the warning `! cannot find snap dir path=/snap` which is not required.

🧹 not having snap is not an error, so we do not need to warn

---

providers/k8s/resources/applications.go
providers/k8s/resources/k8s.lr
providers/k8s/resources/k8s.lr.go
providers/k8s/resources/k8s.lr.manifest.yaml

Adds a new resource to make it easy to detect installed applications in k8s:
```
cnquery> k8s.apps { * }
k8s.apps: [
0: {
version: "1.12.0"
partOf: "ingress-nginx"
managedBy: "Helm"
name: "ingress-nginx"
components: [
0: "controller"
]
instance: "ingress-nginx"
}
]
```

⭐️ discover k8s applications

---

providers/core/resources/core.lr.go
providers/core/resources/vulnerability_exchange.go

Before:
```
cnquery ...  -c "shodan.host.vulnerabilities { vulnerability.exchange ( id: _,  source: 'shodan' )}" 
shodan.host.vulnerabilities: [
0: {
vulnerability.exchange: vulnerability.exchange id="CVE-2023-44487" source="shodan"
}
1: {
vulnerability.exchange: vulnerability.exchange id="CVE-2023-44487" source="shodan"
}
...
```
With this PR:
```
cnquery ... -c "shodan.host.vulnerabilities { vulnerability.exchange ( id: _,  source: 'shodan' )}"      
shodan.host.vulnerabilities: [
0: {
vulnerability.exchange: vulnerability.exchange id="CVE-2023-44487" source="shodan"
}
1: {
vulnerability.exchange: vulnerability.exchange …
```

🐛 Fix id for vulnerability.exchange

---

providers/os/resources/kernel.go
providers/os/resources/kernel/manager.go
providers/os/resources/kernel/manager_test.go
providers/os/resources/kernel/modules.go
providers/os/resources/kernel/testdata/aix.toml

```
cnquery> kernel.modules
kernel.modules: [
0: kernel.module name="bpf" loaded=true
1: kernel.module name="autofs.ext" loaded=true
2: kernel.module name="ahafs.ext" loaded=true
3: kernel.module name="pfcurh" loaded=true
4: kernel.module name="pfccache" loaded=true
5: kernel.module name="pfcreg" loaded=true
6: kernel.module name="pfcdd" loaded=true
7: kernel.module name="if_en" loaded=true
8: kernel.module name="cfs.ext" loaded=true
9: kernel.module name="random" loaded=true
10: kernel.module name="nfs.ext" loaded=true
11: kernel.module name="krpc.ext" loaded=true
12: kernel.module name="nfs_kdes.ext" loaded=true
13: kernel.module name="cluster" loaded=true
14: kernel.module name="posix_aiopin" loaded=true
15: kernel.module name="posix_aio.ext" loaded=true
16: kernel.module name="aiopin" …
```

Add kernel modules and version for AIX

---

providers/os/resources/smbios/aix.go
providers/os/resources/smbios/smbios.go
providers/os/resources/smbios/smbios_test.go
providers/os/resources/smbios/testdata/aix.toml

```
cnquery> machine.baseboard { * }
machine.baseboard: {
version: "IBM,FW950.D0 (VL950_175)"
manufacturer: "IBM"
serial: "7835450"
assetTag: ""
product: "IBM,9009-22A"
}
```
Fixes https://github.com/mondoohq/cnquery/issues/5542

Add `machine.baseboard` support for AIX

---

providers/os/id/azure/azure.go
providers/os/id/clouddetect/clouddetect.go
providers/os/id/gcp/gcp.go
providers/os/id/ibm/ibm.go
providers/os/id/ibm/ibm_test.go
providers/os/id/ibm/testdata/instance_linux.toml
providers/os/id/ibm/testdata/instance_no_metadata.toml
providers/os/id/ibm/testdata/instance_unix_aix.toml
providers/os/id/ibmcompute/ibmcompute.go
providers/os/id/ibmcompute/metadata_unix_cmd.go
providers/os/id/ibmcompute/metadata_windows_cmd.go
providers/os/resources/cloud/cloud.go
providers/os/resources/cloud/ibm.go

Enhance our cloud detect package to detect IBM instances. This change follows the patterns
already implemented for AWS, GCP, Azure, and VMware.
🚫 **Note** that IBM Cloud doesn't have the Metadata service turned on by default, users must opt-in
to have it available. Only those instances are the ones we will detect.
Docs: https://cloud.ibm.com/docs/vpc?topic=vpc-imd-configure-service&interface=ui#imd-metadata-service-enable
From the UI, you can turn it on when launching the instance
Or, accessing advance options after launch.
##Minimal Instance Metadata
I added the raw metadata that needs to be parsed on a follow up PR.

✨ IBM cloud detect + AIX

---

providers-sdk/v1/resources/schema.go
providers/extensible_schema.go
providers/extensible_schema_test.go
providers/providers.go

We use the `ResourcesSchema` interface to interact with the `resources` package. However, when we introduced provider dependencies into `resource.Schema`, we didn't update or extend this interface accordingly.
A few additional issues were observed:
* When loading providers, we only read the `{provider}.json` file, but not the corresponding `{provider}.resources.json` metadata file.
* For built-in providers, we intentionally skip loading files—but we also forgot to pass the schema. This omission results in errors like:
```
x provider without schema, unable to look up dependencies provider=core
```
* While `ResourcesSchema` is used consistently throughout the codebase, it’s not used within `providers.Provider.Schema`.
This change addresses all of the issues mentioned above.

🐛 Add dependencies to `ResourceSchema` interface

---

providers/os/resources/os.lr
providers/os/resources/os.lr.go
providers/os/resources/os.lr.manifest.yaml
providers/os/resources/parse.go
providers/os/resources/parse_test.go

add documents option for parse.yaml to have multi-document YAML
* added Unit-Tests
```
make providers/build/os
make providers/install/os
make build artifacts.platform
```
single manifest:
```
cnquery> parse.yaml(content: command("cat t2.yaml").stdout).params
parse.yaml.params: {
apiVersion: "ec2.aws.upbound.io/v1beta1"
kind: "Instance"
metadata: {
annotations: {
crossplane.io/composition-resource-name: "instance"
}
generateName: "ec2-with-root-snapshot-"
labels: {
crossplane.io/composite: "ec2-with-root-snapshot"
}
name: "ec2-with-root-snapshot"
ownerReferences: [
0: {
apiVersion: "aws.haarchri.io/v1alpha1"
blockOwnerDeletion: true
controller: true
kind: "XEC2Instance"
name: "ec2-with-root-snapshot"
uid: ""
}
]
}
spec: {
forProvider: {
ami: "ami-12345678910"
iamInstanceProfile: …
```

⭐ (parse.yaml): add option for multi-document YAML for parse.yaml

---

.gitignore
apps/cnquery/cmd/plugin.go
apps/cnquery/cmd/run.go
shared/proto/cnquery.pb.go
shared/proto/cnquery.proto
test/commands/cli_test.go
test/commands/testdata/cnquery_run.ct
test/commands/testdata/cnquery_run_exit_1_on_failure.ct
test/commands/testdata/cnquery_sbom.ct
test/commands/testdata/cnquery_scan.ct

This change adds a new flag named `--exit-1-on-failure` which will make
`cnquery` exit with code `1` if any query result failed.
Simple Example: **This should fail.**
```
cnquery run -c "1==2" --exit-1-on-failure
```
Closes https://github.com/mondoohq/cnspec/issues/1671

✨ cnquery run `--exit-1-on-failure`

---

cli/printer/mql.go
llx/builtin_simple.go
llx/rawdata_json.go
llx/rawdata_json_test.go

They were being put in as a timestamp
Also, fixes an issue where we were saying there are 24 mins in an hour instead of 60

🐛 Convert to durations for JSON

---

providers/os/detector/detector_all.go
providers/os/detector/detector_sles.go
providers/os/detector/detector_sles_test.go

This adds the actiavted SLES modules to the platform metadata.
```
cnquery run container image registry.suse.com/suse/sle15 -c "asset.platformMetadata"
asset.platformMetadata: {
activated_modules: "Basesystem, Python 3, Server Applications"
distro-id: "sles"
}
```

✨ Detect activated SLES modules/extensions

---

.github/actions/spelling/expect.txt
providers/ms365/connection/scopes.go
providers/ms365/resources/devicemanagement.go
providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/structs.go

Add support for intune managed devices
```
cnquery> microsoft.devicemanagement.managedDevices { * }
microsoft.devicemanagement.managedDevices: [
0: {
manufacturer: "Apple"
model: "VirtualMac2,1"
imei: ""
emailAddress: "john@example.onmicrosoft.com"
name: "admin’s Virtual Machine"
azureActiveDirectoryDeviceId: "bf860ef6-a23c-4029-84a7-dc8548cbe67c"
isSupervised: true
wiFiMacAddress: ""
iccid: null
udid: null
userDisplayName: "John  Doe"
easActivated: true
osVersion: "14.4.1 (23E224)"
operatingSystem: "macOS"
meid: ""
easDeviceId: "ApplAB1AB2A1A1"
isEncrypted: false
ethernetMacAddress: null
userId: "42f9eb1c-d5e8-427f-95f4-b8007c60e587"
notes: null
azureADRegistered: true
enrollmentProfileName: null
windowsProtectionState: {}
serialNumber: "AB1AB2A1A1"
jailBroken: "Unknown" …
```

⭐️ add m365 managed device support

---

cli/printer/mql.go

This is a start to tackle some long-standing printing issues we have experienced with results.
Take the following example:
```sh
> cnquery run -c "terraform.blocks.none(arguments.source == /google/)" terraform tf
```
The current output will look like this:
```coffee
[failed] [].none()
actual:   [
0: terraform.block type="module" labels=[
0: terraform.block "project-factory"
] {
arguments: {
source: "terraform-google-modules/project-factory/google"
version: "14.4.0"
}
arguments.source: "terraform-google-modules/project-factory/google"
}
]
```
As you can see, the printing of the `actual` value is really broken. If we focus on the problem, we see it's related to how the labels are printed.
Here is the fixed version:
```coffee
[failed] [].none()
actual:   [
0: terraform.block type="module" …
```

🐛 fix long-standing print issues in assertions

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_applicationautoscaling.go

The private resource didn't have the same case which resulted in `help aws` printing both cases. This isn't a breaking change since this was a private resource name.

Prevent duplicate ALB docs when running help

---

cli/printer/mql.go
mqlc/mqlc.go

This won't affect any end-users, but it's very helpful for debugging purposes.

🔨 print datapoints as well as entrypoints in ast view

---

providers/ms365/resources/conditional-access.go
providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml

```graphQL
cnquery> microsoft.conditionalAccess {authenticationMethodsPolicy{ id displayName description policyVersion lastModifiedDateTime policyVersion authenticationMethodConfigurations {id state} } }
microsoft.conditionalAccess: {
authenticationMethodsPolicy: {
policyVersion: "1.5"
id: "authenticationMethodsPolicy"
description: "The tenant-wide policy that controls which authentication methods are allowed in the tenant, authentication method registration requirements, and self-service password reset settings"
displayName: "Authentication Methods Policy"
authenticationMethodConfigurations: [
0: {
id: "Fido2"
state: "disabled"
}
1: {
id: "MicrosoftAuthenticator"
state: "disabled"
}
2: {
id: "Sms"
state: "disabled"
}
3: {
id: "TemporaryAccessPass"
state: "disabled"
}
4: {
id: …
```

⭐️ MS365: Extend microsoft.conditionalAccess with authenticationMethodsPolicy

---

providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/ms365_teams.go

I don't think this was working correctly before, but now hopefully it does
```graphQL
cnquery> ms365.teams.csTeamsMeetingPolicy.allowAnonymousUsersToJoinMeeting
[ok] value: true
cnquery> ms365.teams.teamsMeetingPolicyConfig {allowAnonymousUsersToJoinMeeting}
ms365.teams.teamsMeetingPolicyConfig: {
allowAnonymousUsersToJoinMeeting: true
}
cnquery> ms365.teams.teamsMeetingPolicyConfig {*}
ms365.teams.teamsMeetingPolicyConfig: {
allowExternalNonTrustedMeetingChat: true
allowAnonymousUsersToJoinMeeting: true
allowAnonymousUsersToStartMeeting: true
allowPSTNUsersToBypassLobby: true
allowCloudRecordingForCalls: false
allowExternalParticipantGiveRequestControl: true
allowSecurityEndUserReporting: false
meetingChatEnabledType: "Enabled"
designatedPresenterRoleMode: "EveryoneInCompanyUserOverride" …
```

ms365: teams meeting policy config allow cloud recording

---

providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/ms365_sharepoint.go

Extended `ms365.sharepointonline` with `DefaultLinkPermission`
```graphQL
cnquery> ms365.sharepointonline { defaultLinkPermission }
ms365.sharepointonline: {
defaultLinkPermission: "Edit"
}
```
resolve #5616

MS365: Extend ms365.sharepointonline with DefaultLinkPermission

---

providers/network/resources/tls.go

We are seeing some slow queries that try to access `tls.params`, this is because we have
a timeout of 1m per TLS version, a total of 5 versions so this query could end up running
for 5 minutes.
Since the `tlsshake` package has already a 2s timeout, re-use it to avoid slow queries.

🧹 network: update default dialer timeout to 2s

---

providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/structs.go
providers/ms365/resources/tenant.go

Added missing fields to `microsoft.tenant` resource
```graphQL
cnquery> microsoft.tenant{privacyProfile technicalNotificationMails preferredLanguage}
microsoft.tenant: {
preferredLanguage: "en"
technicalNotificationMails: [
0: "chris@mondoo.io"
]
privacyProfile: {
contactEmail: "john@mondoo.onmicrosoft.com"
statementUrl: "https://example.com/privacy"
}
}
```
resolve #5672

ms365: added  missing resource fields in microsoft.organization resource

---

providers/os/detector/detector_all.go
providers/os/detector/detector_rhel.go
providers/os/detector/detector_rhel_test.go

Implements: https://github.com/mondoohq/cnquery/issues/5695
Example RHEL 9 GCP VM:
```
cnquery run ssh -i ~/.ssh/google_compute_engine XXX -c "asset.platformMetadata" 
asset.platformMetadata: {
distro-id: "rhel"
redhat/modules: ""
}
```
With enabled maven module:
```
asset.platformMetadata: {
distro-id: "rhel"
rhel/modules: "maven"
}
```
RHEL 8 GCP VM:
```
asset.platformMetadata: {
distro-id: "rhel"
redhat/modules: "python36,virt"
}
```

✨ Detect activated RHEL modules

---

providers/ms365/resources/ms365.lr

Added missing comment for `microsoft.user.licenseDetail.servicePlanInfo` resource

ms365: added comment for microsoft.user.licenseDetail.servicePlanInfo

---

providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/policies.go

Added microsoft.policies.externalIdentitiesPolicy 
```graphQL
cnquery> microsoft.policies {externalIdentitiesPolicy {*}}
microsoft.policies: {
externalIdentitiesPolicy: {
id: "externalIdentityPolicy"
description: null
allowDeletedIdentitiesDataRemoval: false
allowExternalIdentitiesToLeave: true
displayName: "External Identities Policy"
}
}
```
resolves #5606

ms365: Extend microsoft.policies with externalIdentitiesPolicy

---

providers-sdk/v1/plugin/git.go
providers/k8s/connection/manifest/connection.go

tested with gitlab and GitHub, e.g. `scan github --discover k8s-manifests` and `scan gitlab --discover k8s-manifests`
just adds a cleaned up url as a label on the asset so we can reference it later

🧹 add label to k8s manifest assets when discovered via git

---

providers/sbom.go
sbom/cnquery_bom.go
sbom/spdx.go

This adds support to use cnquery shell sbom with cnquery's own sbom format.
First create a new sbom for a container:
```shell
cnquery sbom container rockylinux:9 --output cyclonedx-json --output-target rockylinux.cyclonedx.json
```
Then you can use the sbom file to connect with the shell:
```shell
$ cnquery shell sbom rockylinux.cyclonedx.json
→ connected to 
cnquery> asset.platform
asset.platform: "rockylinux"
cnquery> packages
packages.list: [
0: package name="libgcc" version="0:11.4.1-2.1.el9"
1: package name="crypto-policies" version="0:20230731-1.git94f0e2c.el9_3.1"
2: …
```

⭐️ support cnquery sbom with shell

---

.github/workflows/providers.yaml

When this runs the releases website only lists the providers package
I've check the times of the workflow and there is no speed advantage for only reindexing a certain path due to the way it evaluates the bucket contents.
Remote Call - https://github.com/mondoohq/releasr/actions/runs/16296722224
Manual Trigger - https://github.com/mondoohq/releasr/actions/runs/16343633311
I'm proposing here to remove that path and just leave the job to run with the defaults.  Which is what I have to run to fix it :)

Removed Index path as it breaks the html of the releases website

---

llx/builtin_map.go
mql/mql_test.go

I can get cnquery to panic with the following:
```
go run ./apps/cnspec/ run local -c "
lsblkDevice = parse.json(content: command('lsblk -a --json -s overlay').stdout).params
lsblkDevice['blockdevices'][0]['children'][0]['type'] == 'crypt' || lsblkDevice['blockdevices'][0]['type'] == 'crypt'
"
```
```
panic: runtime error: index out of range [0] with length 0
goroutine 93 [running]:
go.mondoo.com/cnquery/v11/llx.dictGetIndexV2(0x32c9590?, 0xc001b86180, 0x2cd4c13?, 0x2?)
/home/jaym/workspace/mondoo/cnquery/llx/builtin_map.go:371 +0x64b
go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runBoundFunction(0xc0004a9f10, 0xc001b86180, 0xc00181c280, 0x100000007)
/home/jaym/workspace/mondoo/cnquery/llx/builtin.go:905 +0x16e
go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runFunction(0xc0004a9f10, …
```

Fix dict array dict

---

explorer/bundle.go
explorer/bundle_test.go
explorer/mquery.go
explorer/mquery_test.go
explorer/property.go
explorer/property_test.go
explorer/query_conductor.go
explorer/scan/local_scanner.go

DO NOT MERGE
- Props are now namespaced to either a pack or query
- Props on packs need to reference props through `for`
- We will automatically make the `for` references if a pack does
not define any props but includes queries with props
Examples:
```yaml
packs:
- uid: example1
name: Example policy 1
version: "1.0.0"
authors:
- name: Mondoo
email: hello@mondoo.com
groups:
- title: group1
filters: return true
queries:
- uid: variant-1
- uid: variant-2
- uid: variant-3
- uid: variant-4
props:
- uid: userHome
for:
- uid: home
- uid: homeDir
mql: return "ex"
queries:
- uid: variant-check
title: Variant check
variants:
- uid: variant-1
- uid: variant-2
- uid: variant-3
- uid: variant-1
mql: props.home + " on 1"
props:
- uid: home
mql: return "p1"
- uid: variant-2
mql: props.home + " on 2" …
```

Make properties work properly

---

providers/os/detector/detector_all.go
providers/os/detector/detector_sles.go
providers/os/detector/detector_sles_test.go

For some versions of SLES SAP, this is where that information is capturued as opposed to VARIANT_ID

🧹 Capture baseproduct for sles

---

.github/.goreleaser-unstable.yml
.github/workflows/goreleaser.yml
.goreleaser.yml

**Summary**
This PR updates the Windows file signing process from DigiCert to Azure Trusted Signer.
**Key Changes**
* Removed redundant tasks: Some tasks became unnecessary after switching to Azure and were removed to simplify the workflow.
* Azure-specific tasks: Added new tasks to handle authentication required for jsign to work with Azure.
* Note: jsign was upgraded on the runner to version 7.1, which supports trusted signing.
* Task conditionals update: During development, some task inputs changed to booleans, breaking existing conditionals. These have been updated accordingly.
* Goreleaser upgrade attempt:
* Attempted to upgrade goreleaser, which worked for most targets.
* However, the resulting RPM signatures were invalid, so we’ve remained pinned to version 2.5.1.
* Comments were …

Migrate Code Signing from DigiCert to Azure Trusted Signer

---

.github/workflows/providers.yaml
scripts/provider_bundler.sh

This PR migrates the windows provider file signing process from DigiCert to Azure Trusted Signer.
- Removed redundant tasks: Some tasks became unnecessary after switching to Azure and were removed to simplify the workflow.
- Azure-specific tasks: Added new tasks to handle authentication required for jsign to work with Azure.  Authentication to micrsoft is done using OIDC
_Note: jsign was upgraded on the runner to version 7.1, which supports trusted signing._
New inputs were added to the workflow_dispatch to aid with troubleshooting:
- use-test-cert: Signs the binary using our test certificate (not publicly trusted).

Refactored provider signing to use trusted signing

---

providers/aws/resources/aws_applicationautoscaling.go
providers/aws/resources/aws_autoscaling.go
providers/aws/resources/aws_backups.go
providers/aws/resources/aws_cloudtrail.go
providers/aws/resources/aws_cloudwatch.go
providers/aws/resources/aws_codebuild.go
providers/aws/resources/aws_dms.go
providers/aws/resources/aws_dynamodb.go
providers/aws/resources/aws_ec2.go
providers/aws/resources/aws_efs.go
providers/aws/resources/aws_eks.go
providers/aws/resources/aws_elasticache.go
providers/aws/resources/aws_elb.go
providers/aws/resources/aws_emr.go
providers/aws/resources/aws_es.go
providers/aws/resources/aws_guardduty.go
providers/aws/resources/aws_iam_accessanalyzer.go
providers/aws/resources/aws_inspector.go
providers/aws/resources/aws_kms.go
providers/aws/resources/aws_lambda.go
providers/aws/resources/aws_neptune.go
providers/aws/resources/aws_rds.go
providers/aws/resources/aws_redshift.go
providers/aws/resources/aws_sagemaker.go
providers/aws/resources/aws_secretsmanager.go
providers/aws/resources/aws_sqs.go
providers/aws/resources/aws_timestream.go
providers/aws/resources/aws_vpc.go
providers/oci/resources/identity.go
providers/oci/resources/network.go

- Since Go >=1.22 we don't need to copy the loop variable anymore. Removed such code from the AWS provider since it was prevalent there.
- Removed redundant err check that was resulting in a compiler warning.

✨ Remove redundant variable copying in AWS provider.

---

providers/os/resources/auditd.go

Ensure that ">=" and "<=" parse properly
Before this the fields were not getting parses correctly when using >= or <= operators:
```
fields: [
0: {
key: "auid"
op: ">" <-- This should be ">="
value: "=1000" <-- This should be "1000"
}
```

🐛 Reorder the auditd rule resource operator regex parsing

---

providers/os/connection/device/device_connection.go
providers/os/connection/device/device_manager.go
providers/os/connection/device/linux/device_manager.go
providers/os/connection/device/linux/device_manager_test.go
providers/os/connection/device/windows/device_manager.go
providers/os/connection/snapshot/blockdevices.go
providers/os/connection/snapshot/blockdevices_test.go
providers/os/connection/snapshot/partition.go
providers/os/connection/snapshot/partition_test.go
providers/os/connection/snapshot/volumemounter.go

* Add new structs
* `Partition` : simply indicates a partition that should be mounted. It has no mountpoint information as we do not differentiate between a mounted and a non-mounted partition here. The filtering happens when doing `lsblk` and using `BlockDevices`
* `MountedPartitionInput`: `Partition` + `MountOptions` and `MountDir`
* `MountedPartition`: `Partition` + `MountOptions` and `MountPoint`. We could unite this and the input struct but I like keeping them split. 
* All connections now do their own mounting in their own tmp folders. This means that connections do not rely on one another anymore. 
* Improve the device manager interface to make the functions more intuitive. 
* Improve the volume mounter interface to make it more intuitive.
* Overall code improvements where possible

⭐️ Refactor device connection and partition mounting

---

mql/mql_test.go
mqlc/builtin.go
mqlc/builtin_resource.go
mqlc/mqlc_test.go

So now we can do things like:
```coffee
users.first
services.last
```

✨ add missing resources.first and resources.last

---

providers/os/connection/snapshot/blockdevices.go
providers/os/connection/snapshot/blockdevices_test.go
providers/os/connection/snapshot/partition.go
providers/os/connection/snapshot/partition_test.go

Older versions of lsblk do not support `MOUNTPOINTS`.

🐛 Use single mountpoint from lsblk.

---

.github/actions/link-check/config.json
explorer/impact.go
explorer/impact_test.go

You can now specify the impact as a name, instead of just a number. For example:
```yaml
- uid: my-query
title: A critical check that needs to succeed
impact: critical
...
```
The keywords are: `critical`, `high`, `medium`, `low`, and `none`.

✨ support impact by name

---

.goreleaser.yml
apps/provider-scaffold/README.md
providers/gcp/resources/discovery_test.go
providers/os/resources/languages/python/testdata/rhel.json

I’ve made some updates to the goreleaser config to reflect the major version change. I also stumbled upon a few other references to version 11 that were hiding under the carpet.

Update goreleaser for v12

---

providers/github/connection/connection.go
providers/github/connection/connection_test.go
providers/github/go.mod
providers/github/go.sum
providers/github/resources/discovery.go
providers/github/resources/git.go
providers/github/resources/github.go
providers/github/resources/github_org.go
providers/github/resources/github_package.go
providers/github/resources/github_repo.go
providers/github/resources/github_team.go
providers/github/resources/github_user.go
providers/github/resources/github_workflow.go

Lots of feature updates here. v72 still comes in as an indirect dep, but this gets the main usage onto the newer lib

🧹 Update GitHub dep to v74

---

providers/os/resources/packages/windows_packages.go
providers/os/resources/packages/windows_packages_test.go

The updated CU version will then be used to also update the Exchange package version.

✨ Detect Microsoft Exchange SU updates

---

llx/matcher.go
llx/matcher_test.go
mqlc/mqlc.go
providers-sdk/v1/lr/go.go
providers/terraform/resources/hcl.go
providers/terraform/resources/terraform.lr

Simple accessor for terraform, now supports both names and regex.
Here's an example. For the Terraform HCL file:
```hcl
resource "aws_instance" "example-1" {
ami           = "ami-a1b2c3d4"
instance_type = "t2.micro"
}
resource "aws_instance" "example-2" {
ami           = "ami-a1b2c3d4"
instance_type = "t2.micro"
}
```
You can now run
```coffee
terraform.resources("aws_instance")
terraform.resources("aws_instance", "example-1")
terraform.resources(/aws_/)
terraform.resources("aws_instance", /example-[0-9]+/)
```

✨ terraform.resources( resource, name )

---

content/mondoo-gcp-inventory.mql.yaml

This has been replaced with ID which we already collect

Remove a deprecated field from a query pack

---

content/mondoo-vmware-inventory.mql.yaml

Meant to fix: https://github.com/mondoohq/cnquery/issues/5914
Does this
`esxi.host` -> replaced with `vsphere.host`

:broom: Removes v13 deprecations in `mondoo-vmware-inventory.mql.yaml` 

---

providers/os/detector/detector_all.go
providers/os/detector/detector_rhel.go
providers/os/detector/detector_rhel_test.go

When Extended Update Support (EUS) or Enhanced Extended Update Support (E4S) is active, add it to the support types.
```
asset: {
version: "8.6"
platformMetadata: {
distro-id: "rhel"
redhat/support-type: "e4s"
}
title: "Red Hat Enterprise Linux 8.6 (Ootpa), Virtual machine"
labels: {
distro-id: "rhel"
}
platform: "redhat"
...
```

✨ Support Red Hat EUS and E4S/SAP support types

---

llx/builtin_global.go

this fix adds handling arguments dereferencing when `ipCall` is invoked with the argument passed down from a function/clojure.
For example the following expression:
```
cnquery> ["8.8.8.8"].map(ip(_))
map: [
0: no data available
]
```
This happens due to the `called `ip` with incorrect argument type, expected string or int` returned from `ipCall`(built-in `ip` constructor) under the hood.
This patch resolves it:
```
cnquery> ["8.8.8.8"].map(ip(_))
map: [
0: 8.8.8.8
]
```
Effectively type checking is redundant, since `ipCall` invokes `any2ip` to actually parse the argument into `ip` resource. BUT, if we go the `Ref` logical branch it will be down to one (only the `any2ip`).

🐛 handle arguments dereferencing in built-in `ip` constructor

---

explorer/scan/local_scanner.go
providers-sdk/v1/recording/asset_recording.go
providers-sdk/v1/recording/asset_recording_test.go
providers-sdk/v1/recording/recording.go
providers-sdk/v1/recording/upstream_recording.go
providers/runtime.go

* Do not store assets without MRN or an id. We do not know what to do with those assets, so best to not just store them at all
* Adding an asset by MRN after it's been added by id will now overwrite the asset
* Ensure `runtime.AssetUpdated` gets called when we update the asset's MRN. Recordings that get sent upstream are only retrieved by MRN so we need to ensure that every time the MRN gets updated we need to update the recording
* Some tests for adding an asset to a recording. We should start adding more of those to make the recording bug-free now that we are storing it upstream
To test, first run `make cnquery/install`, then run this qp:
```
packs:
- uid: rec-test
name: Recording test
filters:
- mql: asset.family.contains("unix")
queries:
- uid: packages
title: packages
mql: packages
- …
```

🐛 Fix recordings, do not store assets if they do not have an MRN or an id

---

.github/workflows/cla.yaml
.github/workflows/goreleaser-edge.yml
.github/workflows/goreleaser.yml
.github/workflows/license.yml
.github/workflows/link-check.yaml
.github/workflows/main-benchmark.yml
.github/workflows/pr-extended-linting.yml
.github/workflows/pr-test-generated-files.yaml
.github/workflows/pr-test-lint.yml
.github/workflows/providers.yaml
.github/workflows/release-providers.yml
.github/workflows/spell-check.yaml
.github/workflows/test-report.yml
.github/workflows/update-deps.yaml

Use hashes instead of mutable tags.
We can still use dependabot for the updates. And according to this [issue](https://github.com/dependabot/dependabot-core/issues/4691), dependabot will also take care of the human-readable comments.

✨ Pin GitHub actions to hashes

---

providers/os/id/metadata/crawler.go

The `user-data` attribute was not being recognised as a multi-line attribute, resulting in a loop and subsequent scan failure. This issue was reported by a customer. 
The other attributes were added after reviewing the Google schema, so I decided to take advantage of this opportunity to include them now. For reference, the other SSH attribute is deprecated, but I thought it prudent to add it nonetheless.

🐛 declare additional attributes that are multiline strings

---

.github/actions/spelling/expect.txt
providers/azure/resources/azure.lr
providers/azure/resources/azure.lr.go
providers/azure/resources/azure.lr.manifest.yaml
providers/azure/resources/web.go

```
cnspec> azure.subscription.web.apps[1].slots[0].configuration.properties
azure.subscription.web.apps[1].slots[0].configuration.properties: {
acrUseManagedIdentityCreds: false
alwaysOn: true
appCommandLine: ""
autoHealEnabled: false
azureStorageAccounts: {}
cors: {
allowedOrigins: [
0: "xxx"
]
supportCredentials: false
}
```
```
cnspec> azure.subscription.web.apps[1].slots[0].properties
azure.subscription.web.apps[1].slots[0].properties: {
availabilityState: "Normal"
clientAffinityEnabled: false
clientCertEnabled: false
clientCertMode: "Required"
containerSize: 1536.000000
customDomainVerificationId: "xxx"
dailyMemoryTimeQuota: 0.000000
defaultHostName: "xxx"
enabled: true
enabledHostNames: [
0: "xxx"
1: "xxx"
]
```

Add support for Azure Web App slots and enhance resource handling

---

providers/os/detector/detector_all.go
providers/os/detector/detector_platform_test.go
providers/os/detector/testdata/detect-openeuler.toml
providers/os/id/networki/linux_n.go
providers/os/resources/packages/packages.go
providers/os/resources/packages/rpm_packages.go

openeuler is RHEL based, but it doesn't have an /etc/os-release file. Detect the package + the family with a special check for openeuler within the redhat family check. Also add the path where it stores the RPM db so we can parse package data.

⭐ openeuler platform/family detection + package detection

---

providers/os/detector/detector_all.go
providers/os/detector/detector_platform_test.go
providers/os/detector/testdata/detect-mx.toml

/etc/os-release says debian, but /etc/lsb-release says mx.

:star: Detect MX Linux as platform "mx" and family "debian"

---

providers/os/config/config.go

🎉 os-11.4.46
