mondoohq/cnquery

apps/cnquery/cmd/root.go
apps/gen-docs/main.go
cli/reporter/print.go
go.mod
go.sum

allows you to generate the cli docs:
```
go run apps/gen-docs/main.go --docs-path path/docs/cli
```
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>

⭐️ markdown cli docs generator

---

cli/printer/printer_test.go
llx/code_bundle.go

Previously we would error out and not show results, just the errors. With this change, the existing output is handed over to the output renderer, making queries like `users.list{*}` possible now.
We retain the summary of errors at the top, so that with more output items people can still see quickly if there was an error somewhere in between.

⭐ show partial output in queries

---

apps/cnquery/cmd/plugin.go
llx/rawdata_json.go

1. We used to conditionally create a list of entries for every entrypoint in a query. But this only happened when there were more than 1 entry. This conditional handling creates inconsistencies for the output. It also looses all information about the query that produced it (eg users.list in the example) and it prevents us from attaching more meta-information (since it's just a list item and not structured). So, go for structured info. This is a breaking change.
2. Errors tend to eat up all available JSON output. Try to provide as much output as possible and give access to errors inside of it. There are multiple follow-ups here like aggregating errors (see the point above) and giving structured errors instead of strings in the appropriate fields (which allows for way easier checking ie …

🛑⭐ restructure JSON output

---

.vscode/launch.json
apps/cnquery/cmd/explore.go
apps/cnquery/cmd/plugin.go
cli/reporter/json.go
cli/reporter/reporter.go

Introduces a custom printer to create reports. It doesn't just take the raw data and dump it all to CLI, but instead carefully constructs a JSON representation of the report that is useful for further processing. It contains MRNs for queries, eliminates pesky lookups, and nicely aggregates data.
Features 3 fields on the top level: assets (for quick lookup and aggregation), reports (for all the data) and errors (for error aggregation).
Unlike `json.Marshal` it doesn't dump any compiled code, doesn't dump the resolved pack, and doesn't force lookups of all data fields.

⭐ explore report --json

---

mqlc/builtin.go
mqlc/mqlc_test.go

Finally getting those descriptions for shadowed resources:
BEFORE
AFTER
Fixes #215
Something is off with sorting on those child fields, i may have another PR coming

🐛 fix missing metadata from autocomplete

---

mqlc/mqlc.go

It was off when we have the same prefix as seen:
Here we want to sort alphabetically, since fuzzy isn't needed for this:
This has the beautiful side-effect that it also fixes the edge-case where we don't type anything in, since everything is prefixed by empty string ;)

🐛 properly sort suggestions with matching prefix or empty

---

apps/cnquery/cmd/scan.go

Rename the `cnquery explore` command to `cnquery scan`, because it is more intuitive. It still explores the assets given the provided query packs, but semantically it's easier to remember to "scan an asset" like the crew in Star Trek would scan a planet they were looking at. We explore things by looking at the gathered data or walking the planet, but first we scan it.
Note: the package was not renamed, because it contains a scanner inside of it (see ). So we can think of it as the space ship that has an explorer module with a scanner that does the work.

⭐ cnquery scan ..

---

cli/printer/printer_test.go
llx/code_bundle.go

we want to use the assertion approach whenever we see an assessment, not just if the last expression was an assertion

🐛 be more defensive with assertion creation

---

llx/code.go
llx/types.go
mqlc/builtin.go
mqlc/builtin_array.go
mqlc/builtin_resource.go
mqlc/mqlc.go
mqlc/mqlc_test.go
resources/lr/go.go
resources/packs/core/core_test.go

Instead of `users.list` just run `users`:
Access to individual elements can now be written simply as `users[0]` instead of `users.list[0]`
Block operations don't require `list` anymore and always apply to child elements:
For V6 compatibility (which we maintain throughout V7 lifetime) you can still write things the old way, but should switch to the new way soon:
```
old> users { list }
new> users
old> ports { listening list }
new> ports
new> ports.listening
```
Additionally we show nice deprecation warnings (e.g. for `ports { listening list }`):

🛑⭐ access resource lists without calling `list`

---

motor/motorid/motorid.go

the cloud detector return `""` when nothing was detected which lead to an invalid platform mrn. This change fixes this and only adds the platform mrn if one was detected

🐛 handle case where the cloud detector returned an empty string

---

cli/components/hbar.go

fyi hbar is only used in cnspec, which is quickly getting an update for this change

🧹 remove extra space after hbar to allow for more control over rendering

---

apps/cnquery/cmd/scan.go
cli/config/config.go
resources/lr/cli/cmd/root.go

Format all the default values in help the same

---

mqlc/mqlc.go
mqlc/mqlc_test.go
types/types.go

block calls during auto expansion were not correctly checking if the result of the block call was supposed to be a list of blocks or just a single block

🐛 Fix type of block call in auto expansion code

---

Makefile
motor/discovery/vsphere/vsphere_resolver.go
motor/platform/detector/detector.go
motor/platform/detector/os_release.go
motor/platform/detector/os_release_test.go
motor/platform/detector/parser_esxi_version.go
motor/platform/detector/parser_esxi_version_test.go
motor/platform/detector/parser_linux_version.go
motor/platform/detector/parser_linux_version_test.go
motor/platform/detector/parser_macos_version.go
motor/platform/detector/parser_macos_version_test.go
motor/platform/detector/parser_sol.go
motor/platform/detector/parser_sol_test.go
motor/platform/detector/platform_resolver.go
motor/platform/detector/platform_specs.go
motor/platform/detector/platform_test.go
motor/platform/detector/tree.go
motor/platform/detector/vsphere.go
motor/platform/platform.go
resources/packs/os/services/manager.go

We introduced a circular dependency that only happened on Windows:
```
package command-line-arguments
imports go.mondoo.com/cnquery/apps/cnquery/cmd
imports go.mondoo.com/cnquery/apps/cnquery/cmd/builder
imports go.mondoo.com/cnquery/motor/asset
imports go.mondoo.com/cnquery/motor/platform
imports go.mondoo.com/cnquery/motor/platform/windows
imports go.mondoo.com/cnquery/motor/providers/local
imports go.mondoo.com/cnquery/motor/asset: import cycle not allowed
```
We imported the windows provider in the the platform package. To avoid that I moved the platform specs into the detector package (where they are used anyway).

🐛 restructure platform specs into detector package

---

.github/workflows/pr-test-generated-files.yaml

Signed-off-by: Preslav <preslav@mondoo.com>
Seen in https://github.com/mondoohq/cnquery/pull/326, there is no check if we forget to regen the info json files for the resources.

🧹 Check LR generated json files for resource packs.

---

apps/cnquery/cmd/builder/builder.go

This PR fixes a reference to `GITHUB` that should be `GITLAB`. I also updated text from `access token` to reference `personal access token` to match GitHub and GitLab documentation.
Signed-off-by: Scott Ford <scott@scottford.io>

Fixes a reference to GitHub for GitLab

---

apps/cnquery/cmd/plugin.go
resources/packs/all/info/all.go

It was only using the OS pack, which is insufficient to run `cnquery run aws -c ...`. Also fixes a problem where we didnt pull the gitlab resource pack correctly into all.

🐛 use all resource packs on cnquery run

---

resources/packs/aws/aws_applicationautoscaling.go

https://github.com/mondoohq/cnquery/issues/333#issuecomment-1283644060
```
cnquery> aws.applicationAutoscaling { * }
failed to create resource 'aws.applicationAutoscaling': namespace required. please provide an aws service as argument. valid values: [comprehend, rds, sagemaker, appstream, elasticmapreduce, dynamodb, lambda, ecs, cassandra, ec2, neptune, kafka, custom-resource, elasticache]: "aws.applicationAutoscaling" failed: no value provided for static field "namespace"
aws.applicationAutoscaling: no data available
cnquery> exit
```

🧹 improve the err msg on the aws application autoscaling resource

---

motor/discovery/aws/ec2_instances.go
motor/discovery/aws/ssm_instances.go

```
DBG completed instance search insecure=false instances=6
DBG resolved ec2 instance name=k8s-operator01
DBG resolved ec2 instance name=k8s-operator02
DBG resolved ec2 instance name=k8s-operator03
DBG resolved ec2 instance name=vm-with-ebs-iam-role
DBG resolved ec2 instance name=amazonlinux2-for-ebs-volume-scan
DBG resolved ec2 instance name=i-020eed3b1e4965d8d
```
Signed-off-by: Victoria Jeffrey <vj@mondoo.com>

🧹 use the aws ec2 instance name as asset name (instead of instance id) when it exists

---

apps/cnquery/cmd/builder/builder.go
motor/providers/gitlab/provider.go

- we accidentally attached the ebs subcommand twice to the aws root command
- the gitlab command used the wrong provider type

🐛 fixes two issues with the command builder

---

README.md
apps/cnquery/cmd/builder/builder.go

If no other provider is specified, assume the provider to be `local`. Additionally print a message to say that this is the default behavior and that there are many more providers.
Works for `run`, `shell`, and `scan`.

⭐ assume default provider to be local

---

.vscode/launch.json
cli/reporter/print_compact.go

It will try to grab either to print it. If neither is available, we will just stick to printing the output of the query itself. It will improve over time, so that it becomes clearer where it originated. At least for the short version, we want to avoid printing the full query.

🌈 add query title or UID to output

---

llx/builtin.go
llx/builtin_simple.go
resources/packs/core/core_test.go

This was missing and I noticed it while writing the effective MQL guide. Also quickly realized why it was missing. We should revisit the types around time and duration as well.

✨ time + duration

---

motor/providers/ssh/awsinstanceconnect/ec2instanceconnect.go
motor/providers/ssh/session.go

Supports both:
```
cnquery shell aws ec2 ssm ubuntu@255.255.255.255
cnquery shell aws ec2 instance-connect ubuntu@255.255.255.255
```
and
```
cnquery shell aws ec2 ssm ubuntu@i-03a9f7b6c706f43d5
cnquery shell aws ec2 instance-connect ubuntu@i-03a9f7b6c706f43d5
```

✨Support IP addresses and instance ids for ic and ssm connectivity.

---

README.md
apps/cnquery/cmd/login.go
apps/cnquery/cmd/logout.go

This change allows cnquery to login to Mondoo Platform
```
cnquery login --token $MONDOO_TOKEN --config cnquery-test.yml
→ token will expire at Thu, 20 Oct 2022 21:34:22 CEST
→ saving config path=cnquery-test.yml
→ config file does not exist, create a new one path=cnquery-test.yml
→ client //agents.api.mondoo.app/spaces/test-infallible-taussig-796596/agents/2G89H49tT6yJyR37vaGRONzFWuP has logged in successfully
```
- renamed old `registration` subcommand to new `login`subcommand
- renamed old `unregistration` subcommand to new `logout`subcommand

⭐️  new login and logout subcommands

---

README.md
apps/cnquery/cmd/bundle.go
apps/cnquery/cmd/scan.go
explorer/querypack.go

This change allows users to upload from cnquery to Mondoo Platform
```
$ cnquery bundle validate example-pack.mql.yaml
→ validate query pack file=example-pack.mql.yaml
x could not validate query pack
pack example-pack does not define a name
$ cnquery bundle validate example-pack.mql.yaml
→ validate query pack file=example-pack.mql.yaml
→ valid query pack
$ cnquery bundle upload example-pack.mql.yaml
→ load query pack bundle file=example-pack.mql.yaml
→ valid query pack
→ add query pack bundle to space space=//captain.api.mondoo.app/spaces/test-infallible-taussig-796596
→ successfully added query packs
```
- improves the validate function
- compiles the bundle before upload
Once the file is uploaded you see it in Mondoo's Query Hub

⭐️ pack upload to query hub

---

explorer/scan/local_scanner.go
explorer/scan/scan.go
resources/runtime.go

This change allows authenticated users to use eol and vulnerability data from mql resources. This is the first step. In a second iteration we connect cnquery to the public Mondoo Vulnerability Database (MVD) so that users do not need to be authenticated.

⭐️ use upstream configuration if credentials are provided

---

apps/cnquery/cmd/scan.go
explorer/bundle.go
explorer/scan/local_scanner.go

This behavior was buggy for querypack. Note, it only works in incognito right now

🐛 select querypacks on cli

---

apps/cnquery/cmd/builder/builder.go
apps/cnquery/cmd/builder/parse.go
motor/discovery/k8s/list_images.go
motor/discovery/k8s/list_images_test.go
motor/discovery/k8s/list_workloads.go
motor/discovery/k8s/list_workloads_test.go
motor/discovery/k8s/resolver.go

--namespaces-exclude allows cnquery to ignore a comma-separated list of Namespaces whose resources should be skipped when performing discovery.
On the other hand, specifying --namespaces will only allow resources matching the list of Namespaces provided.
Combining the previously-existing --namespace param (singular) with --namespaces (plural) will just be joined into one big allow-list. So --namespaces=default,kube-system is the same as saying --namespace=kube-system --namespaces=default.
Signed-off-by: Joel Diaz <joel@mondoo.com>

add --namespaces-exclude --namespaces parameters

---

README.md

- new ascii art header
- simplify `services.list` to `services`

🧹 remove .list from services in readme

---

motor/discovery/container_registry/registry.go
motor/discovery/k8s/list_images_test.go

This change simplifies the container image names from:
```
index.docker.io/library/debian@sha256:604db908f7ce93379b1289c0c7ba73b252002087a3fa64fe904b430083ba5f69
```
to
```
index.docker.io/library/debian@604db908f7ce
```
The long sha is not helpful and the first 12 characters are usually enough to identify the image. This has no effect on the identification of the image, that logic will continue to use the full hash.
```
Asset: index.docker.io/library/debian@sha256:604db908f7ce93379b1289c0c7ba73b252002087a3fa64fe904b430083ba5f69
=============================================================================================================
Data queries:
platform.eol.date: 2022-07-01 02:00:00 +0200 CEST
platform.vulnerabilityReport: {
platform: {
arch: "amd64"
name: "debian"
release: "10.13" …
```

🧹 use shorter name for container images

---

motor/discovery/k8s/resolver.go

Fixes a bug that still discovers `k8s-node` assets via asset relationships

🐛 Make sure k8s-node assets are not created for asset relationships

---

motor/discovery/docker_engine/container.go

For container images stored in the docker engine, we use the short sha. It was difficult for users to know which image it was. Now we use Docker's repo tags, to improve the user experience.
The output of the asset name switches from:
```
Asset: edcf96f9d9d9
===================
Data queries:
platform.eol.date: 2022-07-01 02:00:00 +0200 CEST
... 382 more lines ...
```
to:
```
Asset: debian:10@edcf96f9d9d9
=============================
Data queries:
platform.eol.date: 2022-07-01 02:00:00 +0200 CEST
... 382 more lines ...
```

🧹 improve name of docker image

---

apps/cnquery/cmd/builder/parse.go

Fixes https://github.com/mondoohq/cnquery/issues/291
```
➜ go run apps/cnquery/cnquery.go shell ssh ubuntu@255.255.255.255
→ loaded configuration from /Users/preslavgerchev/.config/mondoo/mondoo.yml using source default
! No identity file or password are provided for ssh authentication, use either --identity-file, --ask-pass or --password. Falling back to ssh agent authentication.
→ resolved assets resolved-assets=0
x could not connect to asset error="ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain" asset=255.255.255.255
FTL could not resolve assets
exit status 1
```
Please feel free to improve the error message if you want to!

🧹 Improve error message if no identity file or password are provided for ssh auth

---

motor/providers/resolver/resolver.go

This change covers a few more renames that we forgot.

🧹 rename transport to provider

---

apps/cnquery/cmd/builder/parse.go
explorer/scan/local_scanner.go
motor/providers/ssh/config.go
motor/providers/ssh/session.go

When the cli was refactored, the cli always added a credential with password authentication as soon as a username was set. The ssh provider check to enable ssh config reading and ssh agent fallback only triggered when no credential was provided. This change adapts the checks so that the fallbacks to ssh config and ssh agent start working again.
fixes #291

🐛 fix ssh authentication

---

motor/discovery/vsphere/vsphere_resolver.go

This change enables the auto-detection of vSphere ESXi hosts.

⭐️ enable auto-discovery of ESXi hosts for vSphere

---

resources/packs/aws/aws.lr

Avoid a spell check warning in docs

Fix spelling in AWS resource

---

.vscode/launch.json
resources/packs/k8s/common.go
resources/runtime.go

🧹 Use extra Error type for 'object not found'

---

llx/rawdata_json.go

Sometimes json keys can have very nasty contents in them. Escape them properly. Especially true in k8s-land.

🐛 escape json keys

---

motor/discovery/docker_engine/container.go

It seems containers get tagged with the `mondoo.com/instance` which is an AWS-specific label.

🐛 Remove mondoo.com/instance label for containers.

---

motor/providers/resolver/resolver.go
resources/packs/github/github.lr.manifest.yaml

This PR removes the "experimental" status from GITHUB....
Signed-off-by: Scott Ford <scott@scottford.io>

Removes experimental status from GitHub resource

---

motor/platform/detector/detector_test.go
motor/platform/detector/platform_specs.go
motor/platform/detector/testdata/detect-rocky-linux-8.toml
motor/platform/detector/testdata/detect-rocky-linux-9.toml

Withing the proper detection of the family, `package` and `service` resources do not work properly. This change detects Rocky Linux 9 as proper RHEL clone.

⭐️ detect Rocky Linux 9 as RHEL clone

---

apps/cnquery/cmd/bundle_querypack-example.mql.yaml

the previous implementation generated a policy which was a copy and paste error from cnspec

🐛 fix sample pack

---

explorer/bundle.go

When in incognito mode and no querypack-bundle specified, this was panicking during scan.

🐛 prevent cnquery from panicking if there are no querybundles

---

resources/packs/core/port.go
resources/packs/core/processes.go
resources/packs/core/processes/linuxproc.go
resources/packs/core/processes/linuxproc_unix.go
resources/packs/core/processes/linuxproc_windows.go
resources/packs/core/processes/manager.go

Previously when reading out the file descriptors, we would silently ignore errors that happened there. However, it is quite common for someone without sufficient permissions to read this list, e.g. when we ask which port is opened by which process. When this happens, now we propagate the errors and wrap it nicely so that users know it is a permissions issue and can sudo their way out of it.

🐛 propagate errors about port-process-relationships

---

apps/cnquery/cmd/scan.go
explorer/scan/local_scanner.go

Before this change querypack filtering only worked for local bundles but not for bundles fetched from public query hub. This adds this ability. It also prints `-o full` info at the end of the scan.

🧹 allow filtering of query packs

---

resources/packs/github/github.go

fixes https://github.com/mondoohq/cnquery/issues/426
we were logging the error -- if it's a 404 that means nothing was found, so we can just move right along. if there is a non-404 error it will be returned, so really no need to log the error here

🐛 clean up error handling on github webhooks resource

---

Makefile
apps/cnquery/cmd/root.go
apps/cnquery/cmd/scan.go

add cnquery version and build to client headers on upstream scan so that we can read in the client version and build info server-side on upstream scan

🧹 add cnquery version and build to client headers on upstream scan

---

cli/config/config.go

When a default config file is present, it previously overrode the env var. Now reading the default config file is skipped when the config is loaded as base64 encoded env var.

🐛 Fix loading of base64 config from env

---

resources/runtime.go

This error message still doesn't make a ton of sense, but now the double word is gone

Remove double resoure in error message

---

apps/cnquery/cmd/builder/builder.go

Right now we just say we're "using defaults" but what is the default?

Be more clear that no provider == local

---

mqlc/builtin.go
mqlc/mqlc_test.go

Fixes #440 
Allows us to use resources where there are embedded fields:
This would fail previously as `{*}` also included embeddded resources, which requires the `MQLAssetContext` flag on.

🐛 Do not use embedded fields when expanding {*} for resources.

---

motor/discovery/gcp/resolver_org.go

fixes an issue reported by @scottford-io where
```
cnquery shell gcp --organization 1234456 --discover auto 
```
has not worked properly. It only worked with `--discover all` or `--discover projects`

🐛 enable auto discovery for gcp organizations

---

llx/builtin.go
llx/builtin_array.go
resources/packs/core/core_test.go

Pretty straightforward, after implementing ways to concat arrays, add the ability to quickly remove elements. This is going to be the most commonly used intuitive shorthand for this type of operation. We already have ways to filter content (`where`) and will likely use similar approaches to remove elements via index. That however is a different use-case.
```
> [1,2,3,3,4] - [3,4,5]
[1,2]
```

✨ array delete: [1,2,3,3,4] - [3,4,5] = [1,2]

---

apps/cnquery/cmd/builder/parse.go

We were using the wrong arg here, the client secret was being ignored

🐛Fix passing of client secret for ms365.

---

apps/cnquery/cmd/builder/builder.go
apps/cnquery/cmd/builder/parse.go
motor/discovery/gcp/resolver_gcp.go
motor/discovery/gcp/resolver_org.go
motor/discovery/gcp/resolver_project.go
motor/providers/gcp/provider.go

Before it was a bit unclear which arguments should be used. `project` can also be the name of the project but we only supported the project-id. This is a non-breaking change because the old flags stay available but are hidden now. If the inventory is used, the old properties are being supported as well.
```
cnquery shell gcp --organization-id 12345678
```

🧹 be more specific for gcp flags and use `--project-id` and `organization-id`

---

motor/providers/config.go
resources/packs/googleworkspace/domain.go

- uses the correct scope for domains call
- removes warning about unknown provider

🧹 smaller fixes for Google Workspace

---

.goreleaser.yml

goreleaser does not like "--target root", it requires "--target=root"

🐛 fix target argument for docker buildx with goreleaser

---

motor/providers/github/provider.go

Fixes #495  by performing a quick call when initializing the client

🧹 Check if provided github token is valid

---

go.mod
go.sum

This is required to switch our packer plugin to use cnquery / cnspec. See https://github.com/mondoohq/packer-plugin-mondoo/pull/48 for more details.

🐛 downgrade to cty 1.10.0

---

motor/providers/ssh/provider.go

This is required for the packer integration since the integration cannot change the env variable from their own process.

🧹 allow configuration of scp via asset opts

---

cli/sysinfo/sysinfo.go
motor/motorid/awsec2/awsec2.go
motor/motorid/awsec2/metadata_cmd.go
motor/motorid/awsec2/metadata_cmd_test.go
motor/motorid/awsec2/metadata_local.go
motor/motorid/awsec2/metadata_local_test.go
motor/motorid/awsec2/testdata/instance-identity_document_linux.toml
motor/motorid/awsec2/testdata/instance-identity_document_linux_no_tags.toml
motor/motorid/awsec2/testdata/instance-identity_document_windows_no_tags.toml
motor/motorid/clouddetect/clouddetect.go
motor/motorid/clouddetect/providers/aws/aws.go
motor/motorid/clouddetect/providers/aws/aws_test.go
motor/motorid/clouddetect/providers/aws/testdata/instance.toml
motor/motorid/clouddetect/providers/azure/azure.go
motor/motorid/clouddetect/providers/gce/gce.go
motor/motorid/clouddetect/providers/gce/gce_test.go
motor/motorid/motorid.go
motor/providers/ssh/session.go

- Extend the `PlatformFingerprint` to also be able to return an asset name, next to the platform ids
- Update the `aws` detectors to be able to fetch a name for an instance. This can either happen via using the tags local endpoint (if enabled) or using the AWS API if there's a config. If neither's present we fallback to using the instance id as the name.
- Tests
This will help with properly naming EC2 assets when scanning those via ssh (instance-connect,ssm)

Extend aws fingerprint detection

---

apps/cnquery/cmd/builder/parse.go
apps/cnquery/cmd/scan.go
motor/discovery/local/local.go
motor/discovery/resolve.go

A new `asset-name` flag that allows for overwriting the root asset name. Essentially equal to passing an inventory file with the name of the asset being set.

✨Add asset-name flag, allowing overwriting of asset names.

---

motor/providers/awsec2ebs/destroy.go
motor/providers/awsec2ebs/provider.go
motor/providers/awsec2ebs/setup.go
motor/providers/awsec2ebs/types.go

In some cases, e.g., snapshot scans we create volumes which we have to delete afterwards. But when scanning an available volume, we shouldn't delete it afterwards.
Fixes #500

🐛 Only delete volumes we created

---

cli/printer/mql.go
cli/printer/printer_test.go

It's much easier to address individual entries if you have the index as a prefix:

🌈 add index to auto-expanded list items

---

mqlc/mqlc.go

When working with special resources (or in this case: dicts) that expand builtin functions, we sometimes run into the case where the builtin function does not exist. This was never checked, before the guardrail only looked for errors, but not if the function is actually non-nil. Remedy it to fix the panic.

🐛 prevent crash on empty builtin

---

motor/discovery/aws/ebs/resolver.go
motor/providers/awsec2ebs/types.go

If `asset-name` flag is set, use it in the EBS provider.

🐛 Set asset name in ebs scanning if it is provided.

---

motor/providers/aws/provider.go

fixes https://github.com/mondoohq/cnquery/issues/539#issuecomment-1335645776

🐛 aws: use default region if none is specified

---

motor/providers/github/provider.go

If we're reading in the env var the user won't necessarily know that's where the value came from. Help them to understand where we're pulling this from.

Improve the invalid GitHub message

---

.github/workflows/pr-test-generated-files.yaml

after #559 
This change reduced the code-generation time from more than 30 min to 3 min

🧹 use self-hosted runner for code generation test

---

llx/rawdata.go
llx/rawdata_test.go

This is had been burried for a bit: Empty arrays should count as falsy. They are often used in statements where people use the `where` clause instead of `contains` and have a hard time figuring out why the query is not behaving right. This is because "where" semantically in a boolean statement often tends to be thought of as "where xyz contains". Users should still use `contains` in these cases, but this change makes it easier to work around it for a moment. Also linting... tba

🐛 empty arrays are falsy

---

llx/builtin.go
llx/builtin_map.go
llx/builtin_simple.go
mqlc/builtin.go
resources/packs/core/core_test.go
types/types.go

Originally contains was only created for simple strings. However, we have since started to support the keyword for arrays and maps. The problem is: dicts can be either and the behavior betweenboth is very different.
This PR adds the first level of support for contains on dicts, that works on both arrays and strings. The printing is still shot, but this is the first step to add proper support.

🐛 prevent crash on dict[string].contains

---

cli/reporter/print_compact.go
motor/providers/k8s/manifest_provider.go
motor/providers/k8s/manifest_provider_test.go
motor/providers/k8s/resources/testdata/subdir/README.md
motor/providers/k8s/resources/testdata/subdir/kustomization.yaml
motor/providers/k8s/resources/testdata/subdir2/2cronjobs.yaml
motor/providers/k8s/resources/testdata/subdir2/README.md
motor/providers/k8s/resources/testdata/subdir2/mondooauditconfig.yaml

When a directory is provided as an argument, we will recursively read it and add the k8s manifest files. Currently, only yaml and yml files will be read. Non-manifest yaml files will be skipped.

✨ Recursively search directory for k8s manifests

---

resources/packs/core/certificates/cert.go

Was getting a panic when running something like:
./cnquery run host mondoo.com -c 'certificate { * }'
This at least avoids the panic.
Signed-off-by: Joel Diaz <joel@mondoo.com>

⭐️ avoid panic when accessing empty certificate

---

cli/config/config.go

This is a super confusing error message that makes it unclear what config file is not being found. Is it K8s? Is it AWS? Is it Mondoo? Who knows.
Current message:

Update no config file error message

---

resources/packs/os/updates/mac_updates.go
resources/packs/os/updates/mac_updates_test.go
resources/packs/os/updates/testdata/com.apple.SoftwareUpdate.plist
resources/packs/os/updates/updates.go

addresses #588
after #586 
brings the handling for os updates to macOS
```
cnquery> os.updates
os.updates: [
0: os.update name="MSU_UPDATE_21G217_patch_12.6.1"
1: os.update name="Command Line Tools beta 3 for Xcode"
2: os.update name="Command Line Tools for Xcode"
3: os.update name="Safari16.1MontereyAuto"
]
```

⭐️ expose macOS updates as `os.updates`

---

motor/providers/microsoft/msgraph/msgraphclient/client.go
motor/providers/microsoft/msgraph/msgraphconv/structs.go
resources/packs/ms365/msgraph.go

It's now under `/groupSettings`, rather than just `/settings` for the production API.

Implement msgraph.settings.

---

cli/progress/progress.go

The terminal cursor was not properly recovered because we have not waited until the go routine is properly completed

🐛 properly wait until progress bar is closed

---

resources/packs/ms365/msgraph.go

To keep the current policies intact, add the properties manually. Previously those came directly from the API, now we need to see what kind of object is being returned and fill those in by hand.
There are 2 things that are missing, marked with TODOs.

Add properties for device configurations, domain dns records, compliance policies

---

Makefile
resources/lr/cli/cmd/go.go

This errors out when an issue was detected. This is helpful to ensure we do not accidentally miss errors as happened for gcp, see #611 
needs #611 merged first to get it green

🧹 make lr compiler more robust and not silently ignore errors

---

resources/packs/ms365/msgraph.go

🐛 Fix microsoft resource identifier.

---

motor/providers/ssh/session.go

- Make it clear this is a local install
- Make it clear this site has instructions for installing the plugin

Improve the no AWS SM plugin warning message

---

motor/discovery/k8s/container_utils.go
motor/discovery/k8s/list_images.go
types/maps.go

I needed to perform some assertions on the assets that are being created from a scan. I did that in https://github.com/mondoohq/mondoo-operator/pull/727 For that reason I had to expose some functions from cnquery such that I don't need to copy-paste some complicated code. These are the changes needed for the mondoo-operator tests.

🧹 Reusable k8s container resolution

---

motor/providers/mock/record.go

makes sure the `enoent` property is correctly set so it can be used:
```
[files]
[files.blabla]
path = "blabla"
enoent = true
content = ""
[files.blabla.stat]
mode = 0
time = 0001-01-01T00:00:00Z
isdir = false
uid = 0
gid = 0
size = 0
```

🐛 Set recorder file enoent property correctly when file does not exist.

---

apps/cnquery/cmd/scan.go

We were missing a few, our k8s description skipped over manifest scans, and host scanning could use some clarification.
Previous output:
```
Available Commands:
arista          Scan an Arista endpoint
aws             Scan an AWS account or instance
azure           Scan a Microsoft Azure account or instance
container       Scan a container, an image, or a registry
docker          Scan a Docker container or image
gcp             Scan a Google Cloud Platform (GCP) account
github          Scan a GitHub organization or repository
gitlab          Scan a GitLab group
googleworkspace
host            Scan a host endpoint
k8s             Scan a Kubernetes cluster
local           Scan a local target
mock            Scan a mock target (a simulated asset)
ms365           Scan a Microsoft 365 endpoint …
```

Update scan help

---

motor/providers/mock/file.go

A simple fix to get the mocked gid file related commands to work.

🐛Fix incorrect assignment of uid over gid for file info stat data.

---

llx/builtin_map.go

~~Sometimes, the data in the LR resources is an int32 int. Comparing such a field against an input, say~~
```
// resource.id is 5 (32-bit int)
resource.id == 5  // false
```
~~would be faulty since the input is always assumed to be a 64-int bit.~~
~~There are 2 scenarios I see to fix this:~~
~~1. What this PR does: when comparing 2 ints, up-cast to 64-int bit always to make sure we can properly compare~~
~~2. Make sure no resource has a 32int bit on it. This might be a bit harder to maintain as we cannot really impose this during compile time (or can we?), so it might be hard to spot~~
Edit:
This cannot happen for resources as there's a built-in check. I only extended the functions that are called when doing comparisong against a dict. Both
```
5 == dict['val']
```
and
```
dict['val'] == …
```

✨Cast 32-bit ints to 64-bit ints when comparing dict values

---

.github/workflows/goreleaser-edge.yml
.gitignore

Since we cannot use goreleaser directly to do our edge releases I created a separate workflow for that. The workflow is triggered for every commit to `main`. It will do a snapshot release of the binary and then create a container with that binary. The container is then pushed to our registry. This PR will create a container for every architecture. If we agree to the approach I will create a follow-up PR to do the virtual tag that combines all architectures.

⭐️ Container edge releases

---

.github/.goreleaser-edge.yml
.github/workflows/goreleaser-edge.yml
.gitignore

The goal here is to have the following tags for edge releases:
- edge-latest
- edge-latest-rootless
- edge-VERSION
- edge-VERSION-rootless
I spent quite some time trying to make the magic happen with `yq` but it seems too much effort. 80% of the goreleaser config for edge releases is the docker configuration. In this case it has to be quite different from the one for the normal release procedure. This is the reason why I decided to just manually configure the file and use that

🧹 Use proper tag naming for edge releases

---

cli/shell/shell.go

Before:
```
cnquery> help aws
aws:                                                 AWS Resource
accessAnalyzer aws.accessAnalyzer:
account aws.account:
acm aws.acm:
apigateway aws.apigateway:
applicationAutoscaling aws.applicationAutoscaling:
autoscaling aws.autoscaling:
backup aws.backup:
cloudtrail aws.cloudtrail:
...
```
After:
```
cnquery> help aws
aws:                                                 AWS Resource
accessAnalyzer aws.accessAnalyzer:                 AWS Access Analyzer resource for assessing the configuration of AWS IAM Access Analyzer
account aws.account:                               AWS Account
acm aws.acm:                                       AWS Certificate Manager resource for assessing the configuration of AWS Certificate Manager
apigateway aws.apigateway: …
```

🧹 fall back to resource title for field comments

---

motor/discovery/aws/ec2_instances.go
motor/discovery/aws/resolver.go
motor/discovery/aws/ssm_instances.go

⚠️ this changes the default behavior of the ec2 discovery to only return running/online instances (we'll need to update the lambda behavior as a follow up)
before:
after:

🧹 aws ec2 & ssm discovery: add running instance state filter by default

---

motor/discovery/aws/ec2_instances.go
motor/discovery/aws/ssm_instances.go
motor/providers/ssh/session.go

with command:
`DEBUG=1 go run apps/cnquery/cnquery.go shell aws --discover ssm --profile AWSPROFILE`
after selecting an asset - 
before & after:
```
[3/01/23 22:00:00] ❯ cnquery shell aws --discover ssm --profile vvdefault
→ loaded configuration from /Users/vj/.config/mondoo/mondoo.yml using source default
→ resolved assets resolved-assets=3
→ selected asset asset=test.smm-5.25 selection=2
FTL could not connect to asset error="could not find the instance"
~/go/src/go.mondoo.io/cnquery vj/ssm-discover-connect* 10s
[3/01/23 22:00:59] ❯ go run apps/cnquery/cnquery.go shell aws --discover ssm --profile vvdefault
→ loaded configuration from /Users/vj/.config/mondoo/mondoo.yml using source default
→ resolved …
```

🐛 aws ssm discovery and connect: use instance id for search when available

---

llx/llx.go
resources/packs/core/core_test.go
resources/packs/testdata/arch.toml

Setup:
```sh
mkdir tmp
echo "tmp/a" > tmp/ref1
echo "asdf" > tmp/a
```
A sample query that failed:
```
a = file("tmp/ref1").content.trim
file(a).path == "tmp/a"
file(a).content.trim == "asdf"
```
Fixes #674

🐛 Fix bug where concurrent chain executions would not complete

---

apps/cnquery/cmd/builder/builder.go
apps/cnquery/cmd/builder/parse.go
motor/discovery/azure/resolver.go
motor/discovery/azure/subscriptions.go

Lets us include or exclude specific subscriptions when running an azure discovery. Very similar to the k8s namespaces filtering in terms of behaviour.
`~/go/bin/cnquery shell azure  --subscriptions-exclude=984df67f-fc2e-4ebf-80a2-98380182f060,1e829eb0-e6a3-4c7b-8212-5868aaebd318`

✨Add subscriptions and subscriptions-exclude arguments for azure scanning

---

.github/CODEOWNERS

This way we get reviews on potential docs changes before they make it into the docs. This reduces followup PRs and wasted effort.

Make letha the codeowner on the LR files

---

motor/vault/config/vaultconfigstore.go
motor/vault/gcpberglas/berglas.go

Add `WithBucket` and `WithKmsKeyId` opts to set the bucket and kms key to be used when using berglas for storing secrets. The vault now also returns the berglas key by using the passed in value and returning it in a formatted manner. This lets us inject the bucket to which we want data to be stored in an easier way, rather than relying on a passed in string.

✨ Extend Berglas vault provider with opts.

---

resources/packs/azure/azure.go
resources/packs/core/socketstats.go
resources/packs/gcp/gcp.go
resources/packs/ms365/ms365.go
resources/packs/os/command.go

when used on a povider that does not allow to run commands, it returned an empty error:
```
cnspec> socketstats.openPorts
socketstats.openPorts: []
```
Not it returns:
```
cnspec> socketstats.openPorts
socketStats not supported on this provider
socketstats.openPorts: []
```

🧹 socketstats resource was returning an empty error 

---

apps/cnquery/cmd/builder/builder.go
motor/discovery/aws/resolver_debug_test.go
motor/providers/aws/provider.go
motor/providers/aws/provider_test.go

improve the logging messages and updates the debug test to be able to test aws discovery and provider quicker

🧹 update aws debug tests and logging

---

cli/printer/printer_test.go
mqlc/mqlc.go

**Problem**
I want to be able to assign variables in block to store specific values and then print them out accordingly with the proper label.
```javascript
cnquery> ['a', 'b'] { x = _ x }
[
0: {
x: "a"
}
1: {
x: "b"
}
]
```
**Solution**
We updated the output to generate labels for variables. It fixes https://github.com/mondoohq/cnquery/issues/574 updates reported by @chris-rock.

🐛 print labels for variables inside of blocks

---

cli/printer/printer_test.go
mqlc/labels.go

One more special case I had overlooked, kudos @chris-rock for the reminder.
Finalizes https://github.com/mondoohq/cnquery/issues/574
**Problem**
I have a query where I assign a value to a variable and then compare the variable e.g. `["a", "b"] { a=_ a=="a" }` The output is sub-optimal since I do not see anymore in the results which value it was compared to.
```javascript
cnquery> ["a", "b"] { a=_ a=="a" }
[
0: {
== "a": true
}
1: {
== "a": false
}
]
```
**Solution**
The new output includes the proper label of the variable:
```javascript
cnquery> ["a", "b"] { a=_ a=="a" }
[
0: {
a == "a": true
}
1: {
a == "a": false
}
]
```

🐛 fix var labels in comparable assertions in blocks

---

cli/reporter/cli.go

after #815
**before**
```
Asset: kube-system/kube-proxy
=============================
Asset: kube-system/coredns-64897985d
====================================
````
**after**
```
Asset: kube-system/coredns-64897985d
------------------------------------
error: rpc error: code = InvalidArgument desc = asset does not match any of the activated query packs
Asset: kube-system/coredns
--------------------------
error: rpc error: code = InvalidArgument desc = asset does not match any of the activated query packs
```

⭐️ print asset error in section

---

motor/providers/github/platform.go

fixes https://github.com/mondoohq/cnspec/issues/226
```
[24/01/23 14:53:58] ❯ go run apps/cnspec/cnspec.go scan github repo Lunalectric/does-not-exist
zsh: correct 'github' to '.github' [nyae]? n
→ no Mondoo configuration file provided. using defaults
→ resolved assets resolved-assets=0
x could not resolve asset error="could not detect GitHub asset type: GET https://api.github.com/repos/Lunalectric/does-not-exist: 404 Not Found []" asset=
FTL failed to run scan error="failed to resolve multiple assets"
exit status 1
```

🧹 improve err msg for missing/incorrect github repo

---

motor/providers/google/provider.go

We do not really show what the actual error is that prevented us from connecting to GCP. This PR makes sure that we bubble up the real error next to our own message
Old output:
```
./cnquery scan --inventory-file vault-inv.yml         
→ loaded configuration from /Users/ivanmilchev/.config/mondoo/mondoo.yml using source default
→ load inventory inventory-file=vault-inv.yml
→ resolved assets resolved-assets=0
x could not resolve asset error="could not find or have no access to project mondoo-dev-262313" asset=cool-stuff
FTL failed to run scan error="failed to resolve multiple assets"
```
New output:
```
./cnquery scan --inventory-file vault-inv.yml   
→ loaded configuration from …
```

🧹 Improve GCP connection error message

---

resources/packs/github/github_repo.go

Fixes https://github.com/mondoohq/cnspec/issues/289

🐛 Check GitHub RequiredPullRequestReviews before access

---

motor/discovery/k8s/asset_data.go

Fixes #647
The double labeling described in #647 is present only for k8s admission controller scans. That is because the admission controller labels objects with `k8s.mondoo.com/resource-version` and cnquery does that with `k8s.mondoo.com/resourceVersion`. Since we parse `k8s.mondoo.com/resource-version` to `Resource Version` in the UI I picked that one to be the label for resource version. Making it consistent between cnquery and the operator means that there will be just 1 label on the scanned assets

🐛 Use consistent k8s resource version label

---

resources/packs/gcp/cluster.go

For GCP GKE clusters that are still provisioning some of the properties are not set. When trying to access them cnquery panics. This PR makes sure it accesses these fields only if they are set

🐛 GCP GKE cluster resource for clusters that are still provisioning

---

resources/runtime.go

Example policy that causes things to hang
```
policies:
- uid: testpolicy3
name: Test Policy 3
version: 0.10.1
is_public: false
scoring_system: 2
tags:
stability: "testing"
specs:
- asset_filter:
query: |
true == true
scoring_queries:
jay-scoring-query-2:
jay-scoring-query-3:
queries:
- uid: jay-scoring-query-2
title: test it 1
severity: 10
query: |
file("foo").content
- uid: jay-scoring-query-3
title: test it 2
severity: 10
query: |
os.base.file("foo").content
```
The issue lies in the fact that the cache key used by some of the observer code differs from the runtime code that caches the resources. The observer thinks its already seen a resource, so it must already be computed (or will be computed). However, the runtime code cached it using the aliased name. It then tries to ask the …

🐛 fix mql hangs with aliased and direct resource in the same policy

---

motor/discovery/aws/ecs.go

some of this information was missing for the scan time results of ecs containers

🧹 add a few more details to the ecs container assets discovered

---

motor/discovery/gcp/resolver_gcp.go

Only call the gcloud cli if both `project` and `project-id` are empty.

🐛Only request project-id from gcloud cli if its not in the options.

---

motor/providers/google/provider.go

The root `gcp` asset got kind `api`. That was not intentional as it should still remain `api`

🐛 Make sure GCP kind remains api instead of gcp-object

---

motor/discovery/gcp/mql_assets.go
motor/discovery/gcp/resolver_project.go
motor/providers/google/provider.go

Initially, the idea was to copy the resolved secret over to the cloned provider configs. That is not ideal since it requires other changes as well. After a discussion with @chris-rock we concluded that resolving secrets multiple times is a vault problem, not a provider problem. This PR makes sure that scanning GCP assets work. In a follow up PR I will address the issue with the retrieval of the same secret multiple times.

🧹 Resolve secret for each provider config in GCP

---

motor/providers/terraform/platform.go

different platforms `terraform-hcl`, `terraform-plan` and `terraform-state` also share the same family now
followup on  #861

⭐️ introduce terraform family 

---

explorer/bundle.go
explorer/mquery.go
explorer/mquery_test.go

The current call only allowed the overwriting of the query that was trying to merge with a base. This is problematic in places where we do not want to alter the original query. This is not the case in cnquery, but it is the case in cnspec (which will be updated shortly after this merged to accomodate the change for v8).

🧹 semantically split up mquery Merge and AddBase

---

explorer/mquery.go

When we take the base MQL, we should also retain the CodeID and type, which is always connected to the MQL code. This makes merging queries easier and doesn't require them to get re-compiled.

🐛 mquery AddBase/Merge transfer MQL CodeID

---

explorer/mquery.go

after #887 
There are two ways in which checksums can be refreshed: One does the compile step and the other doesn't. The latter is used whenever we use Merge or AddBase. At the same time we didn't want to overload those two methods and add too much functionality into them.

🧹 separate mquery RefreshChecksum from Compile

---

resources/packs/core/tlsshake/tlsshake.go

w/o this, you get silent failures when we run into failures while testing out TLS
For example, when connecting to an IPv6 port (w/o the fix in #875 ):
```
[jdiaz@fedora cnquery (joel/tls-errors *+$%)]$ cnquery run local -c "ports.listening.where(port == 443) { tls { * }}"                                            
→ discover related assets for 1 asset(s)                                                                                                                         
→ resolved assets resolved-assets=1                                                                                                                              
ports.listening.where: [ …
```

bubble up errors while processing TLS

---

apps/cnquery/cmd/vault.go
motor/inventory/manager.go
motor/vault/config.go
motor/vault/keyring/keyring.go
motor/vault/keyring/keyring_test.go

**Problem**
I want to use an inventory to scan multiple assets and use secure vaults to store the secrets. 
**Solution**
Add Vault support on command line to allow users to simply configure the used vault.
**Use Case** 
A simple inventory looks like: 
```
kind: Inventory
spec:
assets:
- id: 34.122.119.102
connections:
- host: 34.122.119.102
backend: ssh
credentials:
- type: password
user: chris
password: mypwd
```
This inventory can be used to scan all assets in the inventory:
```
cnquery scan --inventory-file inventory.yml
```
Next we configure the keychain vault:
```bash
cnquery vault set mondoo-client-vault --type keyring
→ set new vault configuration name=mondoo-client-vault
→ stored vault configuration successfully
```
We can list that the vault is configured in cnquery:
```bash …
```

⭐️ manage vaults

---

motor/discovery/gcp/resolver_project.go
motor/providers/google/provider.go

Make sure the root asset has platform kind `gcp-object` and platform name `gcp-project`. This should be merged only after we have updated the existing policies to match the new asset filter

🧹 Change GCP root asset when scanning projects to gcp-project

---

motor/vault/gcpberglas/berglas.go

With the removal of secret encoding from credentials in #840 we need to be explicit about the encoding of the secret that gets returned from the vault so that we can convert it correctly to a credential
This fixes only the berglas vault, I have not looked at the rest of our vault implementations

🐛 Set secret encoding in berglas vault.

---

apps/cnquery/cmd/scan.go
motor/discovery/aws/ecs.go
motor/motor.go
motor/motorid/awsecs/awsecs.go
motor/motorid/awsecs/metadata_cmd.go
motor/motorid/awsecs/metadata_cmd_test.go
motor/motorid/awsecs/testdata/container-identity.toml
motor/motorid/clouddetect/providers/aws/aws.go
motor/motorid/clouddetect/providers/aws/aws_test.go
motor/motorid/clouddetect/providers/aws/testdata/container.toml
motor/motorid/motorid.go
motor/providers/provider.go

adding aws-ecs id-detector to allow for ecs container id detection when running a local scan on an ecs container.
also, it looks like we dropped support for passing thru the user-id-detector on the local scan path at least at some point, it's back in there now
`scan local --id-detector aws-ecs`

⭐️ add aws-ecs id-detector, ensure the iddetectors get passed thru

---

motor/providers/microsoft/msgraph/msgraphclient/errors.go
resources/packs/ms365/msgraph.go

Add the fields explicitly in the `select` clause for the request to make sure we get back all the data we need for the users resource. 
Before (an example with one specific field):
After:
Also fix error handling for msgraph queries by checking if the error is indeed an `ODataError` and if not then return the original error.

🐛 Add explicit select fields for fetching microsoft graph users. Fix error handling

---

.github/workflows/goreleaser-edge.yml
.github/workflows/goreleaser.yml
Makefile

This fixes:
DEPRECATED: --rm-dist was deprecated in favor of --clean, check https://goreleaser.com/deprecations\#-rm-dist for more details

🧹 Replace deprecated goreleaser arg

---

motor/discovery/slack/resolver.go
motor/providers/runtime.go
motor/providers/slack/platform.go
motor/providers/slack/provider.go

switches the asset platform name for slack from "slack" to "slack-team"
```graphql
cnquery> asset { * }
asset: {
kind: "api"
build: ""
version: ""
title: "Slack Team"
arch: ""
labels: {}
platform: "slack-team"
vulnerabilityReport: nil
platform
runtime: "slack"
ids: [
0: "//platformid.api.mondoo.app/runtime/slack/team/ABCDEFG"
]
name: "Slack team superstar labs"
fqdn: ""
family: [
0: "slack"
]
}
```

🧹 improve asset platform information for slack

---

apps/cnquery/cmd/builder/builder.go

This changes the cmd for google workspace from:
```
cnquery shell googleworkspace
```
to 
```
cnquery shell google-workspace
```
It is much easier to read. This is based on feedback from @scottford-io

🧹 update subcommand for google workspace

---

apps/cnquery/cmd/builder/builder.go
motor/discovery/slack/resolver.go
motor/providers/google/platform.go
motor/providers/google/provider.go
motor/providers/runtime.go
motor/providers/slack/platform.go
motor/providers/slack/provider.go

backports https://github.com/mondoohq/cnquery/pull/905, https://github.com/mondoohq/cnquery/pull/906 and https://github.com/mondoohq/cnquery/pull/907 to v7

backport fixes to v7

---

motor/motorid/awsecs/awsecs.go
motor/motorid/awsecs/awsecs_test.go
motor/motorid/motorid.go

to ensure that we categorize the ecs container correctly

🧹 assign the ecs runtime and container kind when ecs motor id used

---

apps/cnquery/cmd/builder/builder.go
motor/providers/microsoft/auth.go

- Remove the `pfx` word from the error we return if the certificate cannot be parsed, we do not know what's the format of the file from where the data came in
- Add .pem as a supported format for the `--certificate-path` arg of `azure shell`

Small text improvements to azure provider cmd.

---

resources/packs/core/port.go
resources/packs/core/tls.go

ipv4 and ipv6 are not recognized as protocols when being parsed through
golang's net package. While something like 'ip6:tcp' is accepted, it
then causes further problems when opening the socket connection.
Just set the protocol to tcp as what happens on Linux.
But!, change the linux protocol field when parting /proc/net to match
what we do in other OSes (namely setting ipv4 and ipv6 as the protocol
when appropriate).
Before this PR's changes, you can see no TLS certificate date fetched
from an ipv4 endpoint (a non-Windows/Darwin-specific fix - that also affects
Windows/Darwin - on ipv6 is fixed in #875).
```
>c:\Users\canef\cnquery.exe run local -c "ports.listening.where(port == 11443)[1]{ tls.certificates.length }"
→ resolved assets …
```

🐛 pass down a golang-recognized protocol for TLS discovery

---

resources/packs/core/port.go
resources/packs/core/tls.go

ipv4 and ipv6 are not recognized as protocols when being parsed through golang's net package. While something like 'ip6:tcp' is accepted, it then causes further problems when opening the socket connection.
Just set the protocol to tcp as what was happening on Linux.
But!, change the linux protocol field when parting /proc/net to match what we do in other OSes (namely setting ipv4 and ipv6 as the protocol when appropriate).
Before this PR's changes, you can see no TLS certificate date fetched from an ipv4 endpoint (a non-Windows/Darwin-specific fix - that also affects
Windows/Darwin - on ipv6 is fixed in #875).
```
>c:\Users\canef\cnquery.exe run local -c "ports.listening.where(port == 11443)[1]{ tls.certificates.length }"
→ resolved assets …
```

🐛 pass down a golang-recognized protocol for TLS discovery (v7 backport)

---

motor/platform/detector/detector_test.go
motor/platform/detector/platform_specs.go
motor/platform/detector/testdata/detect-plcnext.toml

Detects https://www.plcnext-community.net / https://github.com/plcnext as valid operating system.
```
platform: {
name: "plcnext"
build: "d755854b5b21ecb8dca26b0a560e6842a0c638d7"
title: "PLCnext"
version: "23.0.0.65"
}
```

⭐️ detect PLCnext as platform and read its version and build

---

motor/providers/aws/provider.go
resources/library/jobpool/jobpool.go

First commit tries to handle the case where the jobpool wasn't completely set up b/c of a permissions/credentials error (for example when building the job pool and hitting https://github.com/mondoohq/cnquery/blob/main/resources/packs/aws/aws_vpcs.go#L58 ). Just check the job function for nil before calling it.
Second commit doesn't try to bury the initial credentials errors, and just errors early before we get further down the discovery codepaths.

🐛 jobpool and aws creds error handling

---

apps/cnquery/cmd/scan.go

Without this change, the default value for `iddetector` can be `""` empty string, which is then handed down all the way to `motor/motorid`, where it then fails, because it falls through the empty check and then tries to run with an empty string ID-detector, not finding anything.
Fixes the issue introduced in e806cb11033f058b7c584bea8389fafd07bbc28c.

🐛 fix empty iddetector

---

motor/platform/detector/platform_resolver.go
motor/providers/container/docker_engine/docker_engine.go

Before this change, we couldn't show an architecture for running containers build from scratch images:
```
cnquery run container 1ff13294e780 -c 'platform{ name arch }'
platform: {
arch: ""
name: "scratch"
}
```
The reason was, we couldn't execute any command or read any file inside the container.
But we can query the docker daemon for the architecture:
```
cnquery run container 1ff13294e780 -c 'platform{ name arch }'
platform: {
arch: "amd64"
name: "scratch"
}
```

🐛 Fix arch detection of scratch containers

---

cli/config/aws-ssm-ps.go
cli/config/aws_ssm_ps_test.go
cli/config/config.go

```
[15/02/23 12:27:02] ❯ go run apps/cnspec/cnspec.go scan aws --config aws-ssm-ps://region/us-east-1/parameter/MondooAgentConfig
→ loaded configuration from aws-ssm-ps://region/us-east-1/parameter/MondooAgentConfig using source --config
```
cnspec can read the service account credentials stored in AWS ssm parameter store

 cnquery can read config file from aws ssm parameter store

---

resources/packs/gcp/logging.go

GCP alert policies condition filters can be complex queries with more than 1 statement in them. The assumption before was that the condition filter looks like this:
```
filter: "metric.type=\"logging.googleapis.com/user/major-foo-1\""
```
However, we just learned that this is not the case and valid filters are also:
```
filter: "metric.type=\"logging.googleapis.com/user/pass-audit-config-changes-0br0\" AND resource.type=\"metric\""
```
This PR makes sure the filter is split on ` ` and then every segment is checked until we locate the one containing the `metric.type`. Then we extract the metric name.

🐛 Make sure GCP alert policies conditions are always parsed correctly

---

apps/cnquery/cmd/builder/parse.go
motor/providers/okta/okta.go
resources/packs/okta/users.go

The okta provider now supports using the `OKTA_CLIENT_TOKEN` env var to get a token. This makes the --token arg optional.
Using an env var, token is optional
```
OKTA_CLIENT_TOKEN=<token> cnquery shell okta --organization <org>
```
Using a token
```
cnquery shell okta --organization <org> --token <token>
```
Using both, the env var will have precedence
```
OKTA_CLIENT_TOKEN=<token> cnquery shell okta --organization <org> --token <token>
```
Furthermore, this PR also fixes retrieving an okta user profile by making sure it's a correct dictionary, allowing queries on it.
Before:
```
cnquery> okta.users{profile}
okta.users: [
0: {
profile: &map[email:preslav@mondoo.com firstName:Preslav lastName:Gerchev login:preslav@mondoo.com mobilePhone:<nil> secondEmail:<nil>]
}
]
```
After:
```
cnquery> …
```

🧹Parse okta profile correctly. Use OKTA_CLIENT_TOKEN env var over --token if set

---

apps/cnquery/cmd/builder/parse.go
motor/providers/slack/provider.go

Similar to #943, move the env var check to the command parser for Slack. Add a FIXME to remove a deprecated inventory file option.

Move env var check for slack to the cmd parser.

---

cli/printer/printer_test.go
llx/code.go
mqlc/labels_test.go
mqlc/mqlc.go
mqlc/mqlc_test.go
mqlc/operators.go
resources/packs/core/core_test.go
resources/packs/os/secpol_test.go

Some queries can get very hard to read and understand, if there is a long preamble before the actual assertion. For example:
```
sshd.config('/etc/ssh/my_sshd_config').params["Protocol"] == 2
```
A way to simplify this is to use named variables. This allows users to write:
```
sshProto = sshd.config('/etc/ssh/my_sshd_config').params["Protocol"]
sshProto == 2
```
This is done with the intention to have the named variable show up in the result like this:
```
[failed] sshProto == 21
expected: == 21
actual:   "22"
```
However, up until this PR we would always bind the source of the reference, which lost track of the variable's name, and led to this:
```
[failed] sshd.config.params[Protocol] == 21
expected: == 21
actual:   "22"
```
This PR remedies it by retaining the original reference.
FYI …

✨ use variable names in labels

---

explorer/filters.go
explorer/mquery.go

1. unmarshaling into `filter.Items` doesn't make any sense, since we don't want users to set their own keys; they are computed and only used for deduplication/lookup
2. if we don't do the temporary type the `UnmarshalJSON` will be called recursively without end. This is true for both Filter and Remediation

🐛 fix incorrect (and recursive) filter+docs unmarshal

---

apps/cnquery/cmd/builder/builder.go
apps/cnquery/cmd/builder/parse.go
apps/cnquery/cmd/scan.go

This PR sets up new commands for scanning GCP:
```bash
cnquery scan gcp org 342423 # <-- scan GCP organization; `org` and `organization` both work
cnquery scan gcp project mondoo-dev # <-- scan GCP project
cnquery scan gcp folder 3421423 # <-- scan GCP folder
```
The current commands still work but they show a deprecation warning message.
_Note that folder scanning doesn't work yet because it is still not merged into `main`. This should start working once #892 is merged._

🧹 Мake GCP scanning consistent with other scan commands

---

resources/packs/core/port.go
resources/packs/core/tls.go

The new way the proto is saved, allows for new filtering, like:
```
cnquery run local -c "ports.listening.where(protocol == /6/)" 
...
ports.listening.where: [
0: port port=111 protocol="tcp6" address="[::]" process.executable=no data available
1: port port=443 protocol="tcp6" address="[::]" process.executable=no data available
2: port port=631 protocol="tcp6" address="[::1]" process.executable=no data available
3: port port=8989 protocol="tcp6" address="[::]" process.executable="nexus"
]
```
or
```
cnquery run local -c "ports.listening.where(protocol == /tcp/)" 
...
ports.listening.where: [
0: port port=53 protocol="tcp4" address="127.0.0.53" process.executable=no data available
1: port port=53 protocol="tcp4" address="192.168.122.1" process.executable=no data available
2: port …
```

✨ Change ports proto to include tpc/udp + IPv4/6

---

apps/cnquery/cmd/builder/builder.go
apps/cnquery/cmd/builder/parse.go
motor/providers/google/clients.go
motor/providers/google/provider.go

This PR adds `--credentials-path` arg to both `gcp` and `googleworkspace` shell/scan commands.
Furthermore it moves out the env var reading to the commands, the provider now only works with credentials, making it easy to do a inventory-file scan.
Environment variables will have precedence over the new `--credentials-path` arg
Examples:
With env var:
```
GOOGLE_APPLICATION_CREDENTIALS=~/mondoo-dev-1111111.json cnquery shell gcp
```
With `--credentials-path`:
```
cnquery shell gcp --credentials-path ~/mondoo-dev-1111111.json
```

🧹 Add --credentials-path param for gcp/googleworkspace commands.

---

motor/discovery/azure/resolver.go
motor/discovery/gcp/resolver_folder.go
motor/discovery/gcp/resolver_org.go

ensure that gcp and azure assets are correctly assigned as related in the console ui

🧹 mark azure and gcp related assets

---

motor/providers/microsoft/platform.go

Fixes the platform for ms365 which was accidentally broken with the release of #963 
Before:
```
cnquery> platform{title kind runtime name}
platform: {
kind: "azure-object"
name: "microsoft365"
runtime: "azure"
title: "Microsoft Azure"
}
```
After:
```
cnquery> platform {name title kind runtime}
platform: {
kind: "api"
name: "microsoft365"
runtime: "ms-graph"
title: "Microsoft 365"
}
```

🐛 Only override platform if it's an azure asset.

---

motor/providers/microsoft/platform.go

Fixes the platform for ms365 which was accidentally broken with the release of #963
Before:
```
cnquery> platform{title kind runtime name}
platform: {
kind: "azure-object"
name: "microsoft365"
runtime: "azure"
title: "Microsoft Azure"
}
```
After:
```
cnquery> platform {name title kind runtime}
platform: {
kind: "api"
name: "microsoft365"
runtime: "ms-graph"
title: "Microsoft 365"
}
```

🐛 Only override platform if it's an azure asset. (#1001)

---

resources/packs/terraform/hcl.go
resources/packs/terraform/hcl_test.go
resources/packs/terraform/terraform_test.go
resources/packs/terraform/testdata/terraform-module/aws.tf

When the provider setting was missing:
```
terraform {
required_providers {
aws = {
source  = "hashicorp/aws"
version = "~> 3.74"
}
}
}
```
we threw an error in during execution.
```
cnquery> terraform.settings
failed to create resource 'terraform.settings': no `terraform` settings block found
terraform.settings: no data available
```
Since this is valid terraform configuration, we treat empty values as ok too

🐛 do not throw error for missing terraform configuration in hcl

---

motor/discovery/aws/ec2_instances_test.go

Observed in https://github.com/mondoohq/cnquery/actions/runs/4342703577/jobs/7583851503
Map keys are access randomly so building the where filter on multiple key-value pairs can produce different output.
This PR makes sure that all possibilities are accounted for and the output is equal to at least one of then.

🐛Fix flaky aws where filters test.

---

motor/discovery/azure/resolver.go
resources/packs/k8s/k8s.lr.go

Assign the right platform id to subscriptions, until now it was using the wrong provider.
Removed links from root to assets. It seems that the root right now is a completely blank asset so that's of no use. The assets already have to links to the subscriptions assets so that does not change

🐛 Fix subscription platform id. Do not link assets to empty root.

---

motor/discovery/container_registry/registry.go

This deduplicates images in a registry by their digest. Images with multiple tags, but the same digest will only be scanned once.
It stores all tags found for the image with the same digest.
In the UI, it looks like this:
Fixes https://github.com/mondoohq/cnspec/issues/399

🐛 Scan images only once per digest

---

apps/cnquery/cmd/builder/parse.go
apps/cnquery/cmd/builder/parse_test.go
motor/providers/ssh/provider.go

trying to connect to an ipv6 address w/o the surrounding []s around the ipv6 address will error.
detect when we're dealing with an ipv6 address and add the []s as needed.
This will solve it for cases like when dealing with ansible inventory files with ipv6 addresses for some of the target hosts.
Specifying an ipv6 host via the CLI still would require the []s be added for example `cnquery shell ssh user@[fe80::0010]`
Fixes: https://github.com/mondoohq/cnspec/issues/403

🧹 rewrite ipv6 addresses before connecting over ssh

---

explorer/bundle.go
explorer/querypack.go

Filters from querypacks are converted to filters inside a group when saved as a policy. when we get the policy back as a querypack, we need to query the group for filters.

🐛 Use filters from groups

---

motor/providers/ssh/provider.go

the golang To16() function call will succeed against an ipv4 address.
what we need to test is whether we can succeed with a To4() call as that will return nil when given an ipv6 address.
w/o this, we get []s around the ipv4 addresses (which doesn't cause an error, but it still seems wrong)
```
DBG could not establish ssh session error="dial tcp 192.168.86.4:22: connect: operation timed out" host=[192.168.86.4] insecure=false port=22 provider=ssh
```
w/this PR the host we try to connect to no longer gets the unecessary []s:
```
DBG could not establish ssh session error="dial tcp 192.168.86.4:22: connect: operation timed out" host=192.168.86.4 insecure=false port=22 provider=ssh
```

🐛 fix ipv6 address test

---

explorer/scan/local_scanner.go

This checks whether we have duplicate platformID across the assets.
When not checked here, we would see this:
FTL failed to run scan error='could not create progress bar: number of elements and orderedKeys must be equal'

🧹 Catch asset problems before they reach the progressbar

---

apps/cnquery/cmd/builder/builder.go
apps/cnquery/cmd/builder/common/common.go
apps/cnquery/cmd/scan.go
apps/cnquery/cmd/shell.go
apps/cnquery/cmd/slimbuilder/builder.go

This should allow building a wrapper tool w/o pulling in all the real dependencies, so that the wrapper can mimmick the CLI subcommands and parameters of cnquery.
Essentially we move the functions for building the subcommands out into a separate package to allow the current cmd/builder to wrap the function that receives the ProvidersType and AssetType info around a standard cobra.Command function signature. For example:
```
func(cmd *cobra.Command, args []string) {
callCmdBuilderFunction(cmd, args, providers/ProviderType_AZURE, defaultAssetType)
}
```
The new "slim builder" will allow building the subcommands w/o needing to pull in the `cnquery/motors/providers` package as a dependency (and avoiding all the sub-dependencies that come along with it (like azure, aws, gcp, etc...)).

reduce potential dependencies in the command builder

---

motor/discovery/azure/consts.go
motor/discovery/azure/mql_asset_objects.go
motor/discovery/azure/mql_assets.go
motor/discovery/azure/resolver.go

Problem: Trying to scan an instance right now with an azure policy does not work since the instances have an attached SSH connection. This means that a query like `azure.compute.subscription.vm{...}` will not work on the ssh provider.
To fix this, this PR introduces a new target `instances-api`.
- `instances` is meant to instantiate the instances as proper VMs with attached SSH connection to them.
- `instances-api` is meant to instantiate the instances as API objects, solely looking at what the azure API returns on them
Discovering both will produce 2 assets for 1 VM, one on the 'API' (external) side and one for the 'OS' (inside) side
```
➜ ~/go/bin/cnquery shell azure --discover instances-api,instances
→ loaded configuration from /Users/preslavgerchev/.config/mondoo/mondoo.yml using …
```

Add instances-api azure discovery target

---

.goreleaser.yml
scripts/windows-upx.sh

This takes the size from 200MB to 50MB. It doesn't work for arm.
Some downsides may be that the binaries now take longer to start. Its also possible that this is more likely to trigger antivirus software.

🧹Compress windows amd64 binary with upx

---

.github/workflows/pr-test-generated-files.yaml

Jobs on self hosted runners do not run in containers, they run on the host.  Allowing a workflow to install software or otherwise manipulate the system as root is a major security risk.  Instead lets just check that it's installed.  (Sadly, there isn't an 'if' expression to determine if we're on a shared or self-hosted runner, which would be ideal.)

Avoid sudo on self-hosted runners

---

explorer/filters.go
explorer/mquery.go
explorer/mquery_test.go

it expected the `items` structure to be created in non-simple remediations, which is annoying. We intended for remediations to either be simple string or to be an array of remediation items (but without the need for an addition `items` field).

🐛 fix remediation parsing

---

explorer/bundle.go
explorer/filters.go

1. Add a versatile method to add child filters with a query lookup (instead of just a map of queries). This is necessary when we don't have all queries at hand (like requesting queries outside of a bundle).
2. Rename filter helpers for more clarity. Also add docs.

Allow looking up query through a function

---

explorer/query_conductor.go
explorer/query_conductor_test.go

After https://github.com/mondoohq/cnquery/pull/1080
This method had been externalized before, but was entirely tailored to querypacks, instead of being open to other objects. Its structure is meant to take an asset, its provided filters and a set of supported filters. Clean up the method and open it up.

🧹 make NewAssetMatchError re-usable

---

resources/packs/core/processes/manager_test.go
resources/packs/core/processes/testdata/debian.toml
resources/packs/core/processes/unixps.go
resources/packs/core/processes/unixps_test.go

We have seen that the 'ps' output returned can have an empty field for the COMMAND column. Update the regexp to allow for the possibility of it being empty.
Extend the test case to explicitly cover this scenario.
Upgrade the checking for unexpected regexp results to a Fatal().

🐛 handle empty COMMAND ps column

---

explorer/property.go

PropsCache seems to get filled top down. So asset policy, space policy, actual policies. This means that the bases go in last. If something is in the cache, then the thing thats being merged into it is more base than what was there

🐛 Fix the property merging in props cache

---

motor/providers/k8s/manifest_parser.go

With the changes related to namespace scanning, we now use  listing namespaces in more places. That uncovered a bug in the code that lists namespaces for a manifest. If a resource in a manifest has an unspecified namespace, cnquery will return a namespace with no name. That has a different meaning if k8s. Namespace with no name means "all namespaces".
This behaviour triggers [this bug](https://github.com/mondoohq/mondoo-operator/actions/runs/4492994964/jobs/7903820410?pr=727).

🐛 ignore empty namespaces for k8s manifests

---

resources/packs/azure/azure_cloud_defender.go

If there are no security contacts, the Microsoft API brings back the response as `ContactList` instead of `[]Contact` so unmarshalling fails. Fallback to attempt both before returning an error.

🐛 Add fallback unmarshalling for azure security contacts.

---

motor/discovery/aws/mql_asset_objects.go

the image id is later used (in the lambda) to determine more information about the image used for the instance

🧹 add label with image id to ec2 instance discovery

---

apps/cnquery/cmd/root.go

this way, when the 'login' subcommand goes to save the config file, the --api-proxy that was set via CLI param just goes along for the ride and ends up in the config file.
presently it ends up in the config file as 'api-proxy' which wouldn't be picked up when reading the config file.

🐛 change viper binding from api-proxy to api_proxy

---

apps/cnquery/cmd/builder/builder.go
apps/cnquery/cmd/builder/common/common.go
apps/cnquery/cmd/builder/parse.go
apps/cnquery/cmd/scan.go
motor/providers/tar/provider.go
motor/providers/tar/provider_test.go

related to https://github.com/orgs/mondoohq/discussions/855

⭐️ expose scanning of container images as tar

---

go.mod
go.sum

Apache Arrow v11 includes a bug impacting our builds: https://github.com/apache/arrow/pull/3707  This change rolls back BigQuerys Go Module to before that change.
Log from the build: https://github.com/mondoohq/cnquery/actions/runs/4608284597/jobs/8149573219#step:10:79

Rollback BigQuery  to 1.49

---

go.mod
go.sum

Refer to https://github.com/mondoohq/cnquery/pull/1129, the problem now appears with arrow v10 as well.  Rolling back to the previous known good version of the bigquery module.

Rollback all the way to 44

---

resources/packs/os/uptime/unix.go
resources/packs/os/uptime/unix_test.go

During testing I discovered case with update that has not happened before. I added a new test case and adjusted the parser to handle the case where both days and mins are included in the output.

🐛 fix uptime parser for some new cases

---

explorer/bundle.go
explorer/bundle_test.go

we forgot to ensure that we need to create uids for embedded queries when bundles are loaded from memory

🐛 ensure uids are also generated when BundleFromYaml is used

---

explorer/query_hub.go
explorer/query_hub_test.go
explorer/scan/local_scanner.go
explorer/scan/local_scanner_test.go

This change adds support to filter the query packs available in https://mondoo.com/registry by short mrns:
```
cnquery scan okta --organization dev-12345.okta.com --token $OKTA_TOKEN --querypack mondoohq/mondoo-okta-incident-response
```

⭐️ allow filtering of query packs by short mrns

---

motor/platform/detector/detector_test.go
motor/platform/detector/platform_specs.go
motor/platform/detector/testdata/detect-eurolinux-7.toml
motor/platform/detector/testdata/detect-eurolinux-8.toml
motor/platform/detector/testdata/detect-eurolinux-9.toml

This is another RHEL-deriv
cnquery> platform { name version family }
platform: {
name: "eurolinux"
family: [
0: "redhat"
1: "linux"
2: "unix"
3: "os"
]
version: "9.1"
}

Add support for Eurolinux 7/8/9

---

explorer/mquery.go

This simplifies things in a few way. There are many places where we assume there is a code id. Sometimes if code is missing, a mrn is put in its place. But this is confusing. We shouldn't mix these 2 concepts

Give queries with variants a code id

---

explorer/mquery.go

This reverts commit c5078bb58a29ed0ab3813162faa7fa1f1e980a04.
Talked to Dom, and variants are not supposed to have code ids. There are other things coming that also won't have code ids, so we need to find the places where we make that assumption and fix them

Revert "Give queries with variants a code id (#1154)"

---

apps/cnquery/cmd/bundle.go

This was fixed in the docs, but we need to get it fixed here to avoid reverting things.

Fix wording in bundle command

---

apps/cnquery/cmd/status.go
explorer/scan/local_scanner.go

Related to mondoohq/cnspec#365
```
→ loaded configuration from /Users/ivanmilchev/Downloads/temp.json using source --config
→ Platform:     macos
→ Version:      13.3.1
→ Hostname:     Ivan-Milchev.local
→ IP:           192.168.2.4
→ Time:         2023-04-24T12:44:02+02:00
→ Version:      v8.6.0 (API Version: unstable)
→ API ConnectionConfig: https://us.api.mondoo.com
→ API Status:   SERVING
→ API Time:     2023-04-24T10:44:02Z
→ API Version:  8
! API versions do not match, please update the client
→ Owner:        //captain.api.mondoo.app/spaces/keen-banzai-154123
→ Client:       no managed client
→ Service Account:      //agents.api.mondoo.app/spaces/keen-banzai-154123/serviceaccounts/2OrwvXItmEV0Aue93mep5oPIiS4
→ client is registered
x The Mondoo Platform credentials provided at …
```

🧹 make status err reporting clearer

---

apps/cnquery/cmd/builder/common/common.go
apps/cnquery/cmd/builder/parse.go

Mark client-id and tenant-id as required flags when scanning ms365.

---

apps/cnquery/cmd/builder/common/common.go
apps/cnquery/cmd/scan.go

Specify PEM format is supported for ms365 connections, extend example cmds

---

resources/packs/core/asset_advisories.go
resources/packs/core/core.go
resources/packs/core/mondoo_eol.go
resources/packs/core/platform_advisories.go
resources/packs/core/platform_eol.go

For the cases when authentication is actually needed but not provided:
```
cnquery> platform.cves
This resource requires data from the Mondoo Platform.
For instructions on using cnspec with the Mondoo platform, see:
https://mondoo.com/docs/cnspec/cnspec-adv-install/registration/
platform.cves.list: []
```
Fixes mondoohq/cnspec#364

🧹 add user-friendly err when using unauthenticated cnquery

---

motor/discovery/ms365/resolver.go
motor/providers/microsoft/auth.go

Fixes #1113 
```
~/go/bin/cnquery shell ms365 --certificate-path ~/cert-no-pk.pem --client-id xxxxxxx --tenant-id xxxxxxxx
→ loaded configuration from /Users/preslavgerchev/.config/mondoo/mondoo.yml using source default
→ resolved assets resolved-assets=0
x could not connect to asset error="could not parse provided certificate at /Users/preslavgerchev/azure-cert.pem: found no private key" asset=
FTL could not resolve assets
```

🧹 Test provided cert/pass when creating an ms365 connection.

---

cli/reporter/json.go

In cases where cnquery could not find a suitable query pack and the json exporter was used eg. via `cnquery scan local --output json`, cnquery created a panic:
```
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x10b0c01e0]
go.mondoo.com/cnquery/cli/reporter.ReportCollectionToJSON(0x14002b1a190, {0x10e2b2c30, 0x14000b3a0c0})
/Users/chris/go/src/go.mondoo.com/workspace/cnquery/cli/reporter/json.go:50 +0x70
go.mondoo.com/cnquery/cli/reporter.(*Reporter).Print(0x14002b2c000, 0x14002b1a190, {0x10e223280?, 0x140001aa008})
/Users/chris/go/src/go.mondoo.com/workspace/cnquery/cli/reporter/reporter.go:110 +0x1f8
go.mondoo.com/cnquery/apps/cnquery/cmd.printReports(0x140028cd980?, …
```

🐛 fix panic for cnquery json reporter when asset could not be scanned

---

resources/packs/aws/aws_cloudtrail.go

Fixes #1184 
We cannot query information about a trail (log group, kms key,  etc) if that trail is coming from another account. In that case, we should just skip it

🧹 Do not fetch trails if they are not part of the account.

---

motor/discovery/github/github.go

We were passing in a new repo options data structure each time that set the pagination back to the initial value.

🐛 Fix failures in GitHub pagination when fetching org repos

---

motor/providers/container/docker_engine/docker_engine.go
motor/providers/container/docker_engine/file.go
motor/providers/container/docker_engine/fs.go
motor/providers/os/statutil/stat.go
motor/providers/ssh/cat/cat_file.go

Before this PR we have not supported UID/GID parsing for running docker containers. This PR changes this and adds support.
*before*
```coffeescript
cnquery> file("/tmp").user.name
cannot cast resource to resource type: <nil>
file.user.name: no data available
```
*after*
```coffeescript
cnquery> file("/tmp").user.name
file.user.name: "root"
```

⭐️ support uid / gid for files on running docker containers

---

apps/cnquery/cmd/builder/parse.go

We had support for this but we broke it when we added some validation whether the file exists or not
Fixes mondoohq/cnspec#402
`cat p.yaml | ./cnquery scan k8s -  `:
```                                                                                                                                                                                                              
→ loaded configuration from /Users/ivanmilchev/.config/mondoo/mondoo.yml using source default
→ discovery option auto is used. This will detect the assets: cluster, cronjobs, daemonsets, deployments, ingresses, jobs, pods, replicasets, statefulsets
→ resolved assets resolved-assets=2
→ synchronize assets
K8s Manifest - …
```

🐛 parse manifests from stdin

---

apps/cnquery/cmd/plugin.go
apps/cnquery/cmd/root.go
apps/cnquery/cmd/shell.go
apps/cnquery/cmd/shell_run.go
explorer/scan/local_scanner.go
motor/motor.go

This issue was reported by @mm-weber. The recordings where working for `cnquery shell` but not for `cnquery scan`. This brings back the ability to record the data (os provider only) for a query pack.

🐛 fix the recording

---

apps/cnquery/cmd/builder/builder.go
apps/cnquery/cmd/builder/common/common.go
apps/cnquery/cmd/builder/parse.go
apps/cnquery/cmd/scan.go
apps/cnquery/cmd/shell.go
motor/providers/fs/provider.go

This allows you to test mounted firmware files:
```
cnquery shell fs /mnt/firmware/
cnquery> asset {name version platform }
asset: {
version: "v3.1.17"
platform: "poky-iot2000"
name: "iot2000"
}
```
You can easily test this locally via:
```
cnquery shell fs motor/providers/fs/testdata/centos8 
```

⭐️ add filesystem provider to command builder

---

mqlc/mqlc.go
mqlc/mqlc_test.go

We have difficulty storing the unset type. It doesn't seem unreasonable to me that switch should behave similar to if and have a type set.
The following query wasn't properly typed before:
```
switch {
case tls.versions.containsOnly(["tls1.2", "tls1.3"]):
score(100);
case tls.ciphers.all( /rc4/i ):
score(100);
case tls.ciphers.none( /null|dh_anon|export|des|rc2|idea/ ):
score(80);
default:
score(0);
}
```
Now, it gets compiled as:
```
-> block 1
entrypoints: [<1,13>]
1: tls
2: versions bind: <1,1> type:[]string
3: difference bind: <1,2> type:[]string ([
0: "tls1.2"
1: "tls1.3"
])
4: == bind: <1,3> type:bool ([])
5: tls
6: ciphers bind: <1,5> type:[]string
7: $whereNot bind: <1,6> type:[]string (ref<1,6>, => <3,0>)
8: $all bind: <1,7> type:bool
9: tls
10: ciphers bind: <1,9> type:[]string …
```

🧹 Assign a type to switch statements similar to if statements

---

llx/builtin_map.go
resources/packs/core/core_test.go

This technically doesnt work and is in line with the way it works for arrays. However, I think we should change this because more users are runingn into this...

🐛 prevent crashes on calling dict.containsOnly without array

---

llx/builtin_array.go
resources/packs/core/core_test.go

`first` and `last` both were introduced as helper methods to easily access the first and last element of an array. As such, having to deal with empty lists and the consequences of `null` is really annoying.
To better fit their behavior, these methods will now return `null` if you access elements from an empty or null array. For the latter case we already had this behavior, so now it better fits together.
Users can still use `[0]` to access the first and `[-1]` for the last element and have it throw an error if those elements could not be found.
```
> [1,2,3].where(_>4).first
where.first: null
```

🛑 change the behavior of first/last to support empty lists

---

llx/builtin.go
llx/builtin_array.go
llx/builtin_map.go
mql/testdata/arch.toml
mqlc/builtin.go
resources/packs/core/core_test.go
resources/packs/testdata/arch.toml

After https://github.com/mondoohq/cnquery/pull/1236 !
We have supported `first` and `last` for arrays already, now we are adding it to dicts, i.e. parsed JSON, to also access these first and last elements.
```
cnquery> parse.json("dummy.json").params["string-array"].first
parse.json.params[string-array].first: "a"
cnquery> parse.json("dummy.json").params["string-array"].last
parse.json.params[string-array].last: "c"
cnquery> parse.json("dummy.json").params["string-array"].where("non-exist").first
parse.json.params[string-array].where.first: null
cnquery> parse.json("dummy.json").params["string-array"].where("non-exist").last
parse.json.params[string-array].where.last: null
cnquery> parse.json("dummy.json").params.first
parse.json.params.first: 1.000000
cnquery> …
```

✨ add first/last to dict, including support for empty lists

---

resources/packs/core/dnsshake/dnsshake.go

closes #833 
According to the documentation 
```
Exchange performs a synchronous query\. It sends the message m to the address
contained in a and waits for a reply\. Basic use pattern with a \*dns\.Client\:
c := new(dns.Client)
in, rtt, err := c.Exchange(message, "127.0.0.1:53")
Exchange does not retry a failed query, nor will it fall back to TCP in
case of truncation\.
It is up to the caller to create a message that allows for larger responses to be
returned\. Specifically this means adding an EDNS0 OPT RR that will advertise a larger
buffer, see SetEdns0\. Messages without an OPT RR will fallback to the historic limit
of 512 bytes
To specify a local address or a timeout, the caller has to set the \`Client\.Dialer\`
attribute appropriately
```
In the issue mentioned above we are hitting …

:bug: dns handle bigger amount of txt records

---

resources/packs/core/dns.go
resources/packs/core/dns_test.go

closes #993 
Instead of a panic the output would now be 
```
cnquery> domainName
failed to validate resource 'domainName': Initialized "domainName" resource without a "effectiveTLDPlusOne". This field is required.
domainName: no data available
```
I also thought about returning an error here when `if fqdn == nil` 
```
if fqdn == nil {
return nil, nil, errors.New("some error")
}
```
Which would then be 
```
cnquery> domainName
failed to create resource 'domainName': some error
domainName: no data available
```
Of course using something more descriptive then "some error". Which way do you guys prefer?

:bug:  fix panic on domainName

---

motor/providers/k8s/manifest_provider.go

#1213 fixed reading manifests from stdin but it seems like this works only for manifests that have 1 resource and that resource must have a UID. In all other cases the scan would fail.

🐛 fix k8s stdin for manifests with resources with no UIDs

---

.github/workflows/goreleaser-edge.yml
.github/workflows/goreleaser.yml
.github/workflows/pr-test-generated-files.yaml
.github/workflows/pr-test-lint.yml
docs/development.md
go.mod
llx/builtin_resource.go
mqlc/builtin_resource.go
resources/packs/core/core.lr
resources/packs/core/core_test.go

After: https://github.com/mondoohq/cnquery/pull/1255
It is now possible to call `parse.time` with many different formats (other than the default RFC3339). cnquery will try to auto-detect what it is.
Here are a few examples using the new calls:
```coffee
parse.date("2006-01-02T15:04:05Z")
parse.date("2006-01-02 15:04:05")
parse.date("2006-01-02")
parse.date("15:04:05")
parse.date("Mon, 02 Jan 2006 15:04:05 MST")
parse.date("Mon Jan 2 15:04:05 2006")
parse.date("02 Jan 06 15:04 MST")
parse.date("Monday, 02-Jan-06 15:04:05 MST")
parse.date("3:04PM")
parse.date("Jan 2 15:04:05")
```
Additionally, timezones can be specified with numeric values for RFC1123
and RFC822:
```coffee
parse.date('Mon, 02 Jan 2006 15:04:05 -0700')
parse.date('02 Jan 06 15:04 -0700')
```

✨ parse.time auto-detect multiple formats

---

apps/cnquery/cmd/builder/parse.go
motor/discovery/k8s/resolver_cluster.go
motor/providers/k8s/api_provider.go
motor/providers/k8s/provider.go

Closes https://github.com/mondoohq/cnspec/issues/593
Working example of the `--context` flag
If the flag is not provided it still falls back to the default cluster

:bug: fix --context option ignored in cnspec

---

resources/packs/terraform/hcl.go
resources/packs/terraform/hcl_test.go

fixes https://github.com/mondoohq/cnspec/issues/599
```
cnquery> terraform.blocks { * }
terraform.blocks: [
0: {
end: terraform.fileposition id = file.position//Users/vj/test.tf/1/1
labels: []
arguments: {
blah: {
test-random_string.rando.id: {
type: "something"
}
}
}
snippet: "     1 | locals {
2 |   blah = {
3 |     \"test-${random_string.rando.id}\" = {
4 |       type = \"something\"
"
type: "locals"
blocks: []
attributes: {
blah: {
type: "any"
value: {
test-random_string.rando.id: {
type: "something"
}
}
}
}
```

🐛 fix tf resource panic (check type of hcl key)

---

apps/cnquery/cmd/bundle.go

This PR aligns the bundle sub-commands to the new cnspec version
- `cnquery bundle validate` -> `cnquery bundle lint` 
- `cnquery bundle upload` -> `cnquery bundle publish` 
The commands are backwards-compatible with aliases.

🧹 align bundle subcommands

---

cli/shell/shell.go

When running soemthing in shell that generates thousands of lines of output, the shell will block and take a long time to process (and pipe) all the output to STDOUT. We can't speed up STDOUT a lot, but we can make sure we don't push an insane amount of data to it, that would slow it down.
With this change we are introducing a maximum number of lines. The 1k lines is the default that many CLI shells come with. This is a ton of entries, even if we block-extract 8 fields, accounting for 2 extra lines per block, we would be able to display 100 items. This is a very sane amount for a regular REPL environment.
We will make this configurable again down the line. Feedback is very welcome!
For now, it will stop the shell from almost locking up when a ton of lines/items are extracted.

⚡ reduce # of lines printed in shell

---

cli/printer/printer_test.go
mqlc/mqlc.go

Queries like `users.list.duplicates(uid).none()` produced the error message `failed to find where function for assessment`. These errors were wrong.
In cases where no field is checked for the assessment, there is no `where` function

🐛 Fix error messages for `.none()` queries

---

mqlc/builtin_map.go
mqlc/mqlc.go
resources/packs/core/core_test.go

... was incorrectly interpreted as a non-standalone block. That is wrong. The `standalone` attribute in compilers referes to the contents of the compiler not to reference its bindings, i.e. everything in the expressions to stand on their own (or said differently: the expressions to be standalone). We had a bug where standalone was set to `false` when variables were used. The use of vars does not make something non-standalone. Only the values inside of vars can do that, which are handled in their assignment.
Example:
```
allowed_roles = ["roles/owner", "roles/editor", "roles/viewer"]
role = "roles/owner2"
allowed_roles.contains(role)
```
Since `role` is not in allowed roles, this should fail. Before, this was interpreted incorrectly and returned true. This bug is now fixed.

🐛 where/contains/... + vars

---

llx/builtin.go
llx/builtin_map.go
llx/builtin_simple.go
mqlc/builtin_simple.go
resources/packs/core/core_test.go

**AFTER https://github.com/mondoohq/cnquery/pull/1279**
Feel free to remove the `DRAFT` from the title once the above PR is merged!
... and a handful of derivates like string.contains([]regex), dict.contains(regex) and dict.contains([]regex).
Now you 
```
"hello world".contains(/wor.d/)
```
Please note: if the regex has beginning or end conditions (i.e. `^` or `$`) these will be respected by `contains`, i.e. it will not magically remove these.
We are introducing this operation to deprecated the old approach of `x == regex` with v9. It currently leads to very misleading results with e.g. `1.2.3.4abc == regex.ipv4` returning `true`.

✨ string.contains(regex)

---

llx/builtin.go
llx/builtin_array.go
mqlc/builtin.go
resources/packs/core/core_test.go

for flat mapping arrays:
```
> [[0],[[1, 2]], 3].flat
[0,1,2,3]
```
Type detection still needs some work.

✨ array.flat

---

apps/cnquery/cmd/builder/common/common.go
apps/cnquery/cmd/builder/parse.go
apps/cnquery/cmd/run.go
motor/discovery/docker_engine/container.go
motor/providers/container/container.go
motor/providers/container/image/docker.go

This fix prevents a copy of the image in memory. But that has a performance impact.

🐛 Fix memory usage when scanning large images

---

apps/cnquery/cmd/builder/parse.go
motor/discovery/k8s/resolver_cluster.go
motor/providers/k8s/manifest_provider.go
motor/providers/k8s/manifest_provider_test.go
motor/providers/k8s/provider.go

fixes https://github.com/mondoohq/cnspec/issues/622
The initial implementation https://github.com/mondoohq/cnquery/pull/1213 was reading data from stdin directly inside of the provider. This does not work well for manifest files with multiple entries since the discovery splits them up into multiple scans. You can read from stdin only once.
In general I think it is best practice do avoid doing cli / terminal handling inside of the provider. Therefore this PR moves this logic to the cli to read the file. The initial version used a temporary file on disk. Problem with temporary files is that someone has to clean up the file after everything is complete. In case of a manifest file, multiple provider instances are created and it would require additional logic to handle the close down. Instead …

🐛 fix piped kubernetes manifests

---

apps/cnquery/cmd/builder/common/common.go
apps/cnquery/cmd/builder/parse.go
motor/discovery/oci/resolver.go
motor/providers/oci/provider.go

Extends support for opening a shell to an OCI instance by letting the user specify all the required params via the CLI. Also makes it possible that we use an inventory file to perform OCI scanning.
```
cnquery shell oci
```
will use the default provider, reading default config files and env vars
```
cnquery shell oci --tenancy ocid1.tenancy..--user ocid1.. --region "us-ashburn-1" --fingerprint aa:aa:aa:aa...--key-path ~/.oci/private.pem
```
All of `tenancy`, `user`, `region`, `fingerprint` and `key-path` values are required if trying to establish a connection via the CLI params.

✨Add support for passing in OCI provider params via the CLI.

---

llx/builtin_map.go
mqlc/builtin.go
mqlc/builtin_array.go
mqlc/builtin_map.go

Now you can call this and get the right results:
```coffee
> pam.conf.entries.values.flat{*}
pam.conf.entries.values.flat: [
0: {
options: []
control: "sufficient"
module: "pam_rootok.so"
pamType: "auth"
lineNumber: 1
service: "/etc/pam.d/chsh"
},
...
]
```

🐛 fix map values correct type

---

apps/cnquery/cmd/builder/builder.go
apps/cnquery/cmd/builder/common/common.go
apps/cnquery/cmd/builder/parse.go
apps/cnquery/cmd/scan.go
apps/cnquery/cmd/shell.go
motor/discovery/gcp/instancesnapshot/resolver.go
motor/providers/gcpinstancesnapshot/platform.go
motor/providers/gcpinstancesnapshot/provider.go
motor/providers/gcpinstancesnapshot/snapshot.go

follow up on https://github.com/mondoohq/cnquery/pull/1311
This change allows users to scan GCP compute snapshots directly:
```bash
cnquery shell gcp snapshot suse12 --project-id my-project-id
→ found target volume device name=/dev/sdb3
___ _ __  ___ _ __   ___  ___ 
/ __| '_ \/ __| '_ \ / _ \/ __|
| (__| | | \__ \ |_) |  __/ (__ 
\___|_| |_|___/ .__/ \___|\___|
mondoo™     |_|              
cnspec> asset.platform
asset.platform: "sles"
cnspec> asset.version
asset.version: "12.5"
cnspec> packages
packages.list: [
0: package name="release-notes-sles" version="12.5.20200504-3.11.1"
1: package name="libqrencode3" version="3.4.3-1.31"
2: package name="lifecycle-data-sle-module-toolchain" version="1-3.15.1"
3: package …
```

⭐️ add support for GCP snapshot scanning

---

apps/cnquery/cmd/builder/common/common.go
apps/cnquery/cmd/builder/parse.go
motor/providers/gcpinstancesnapshot/provider.go
motor/providers/gcpinstancesnapshot/snapshot.go
motor/providers/gcpinstancesnapshot/snapshot_debug_test.go
motor/providers/os/snapshot/volumemounter.go

after #1314
With this change we introduce a new flag `--use-latest-snapshot` and allow users o use existing snapshots of instances if they exist. If no snapshot exists we still fallback to create a instance disk clone.
```bash
cnspec scan gcp instance sles12 --project-id my-project-id --zone us-central1-a --use-latest-snapshot
→ no Mondoo configuration file provided. using defaults
sles12 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% score: C
Asset: sles12
-------------
Checks:
✕ Fail:  D  20  Ensure auditing for processes that start prior to auditd is enabled
✕ Fail:  D  20  Ensure successful file system mounts are collected
✕ Fail:  C  40  Ensure Advanced Intrusion …
```

⭐️ allow users to use latest GCP instance snapshots instead of creating new ones

---

explorer/bundle.go
explorer/querypack.go

I ran the experiment with https://github.com/mondoohq/cnquery-packs on the `scottford/terraform-asset-inventory-variants` branch. In this example, we have a querypack with queries in a group that use variants. The way the syntax is set up was not originally support. This PR enables it.

🐛 support variants for querypacks

---

apps/cnquery/cmd/builder/common/common.go
apps/cnquery/cmd/builder/parse.go
motor/providers/aws/provider.go

add assume role support for aws
`go run apps/cnquery/cnquery.go shell aws --option role-arn=ROLEARN `
`go run apps/cnquery/cnquery.go shell aws --option role-arn=ROLEARN --option external-id=EXTERNALID`

⭐ add assume role support for aws

---

.vscode/launch.json
apps/cnquery/cmd/shell.go
llx/data_conversions.go
providers-sdk/v1/inventory/manager/credentials_query.go
providers-sdk/v1/inventory/manager/credentials_query_test.go
providers-sdk/v1/inventory/manager/manager.go
providers-sdk/v1/lr/go.go
providers/mock/mock.go
providers/os/connection/ssh.go
providers/os/provider/detector.go
providers/os/provider/provider.go
providers/runtime.go

Shoving the entire MQL runtime into providers is not very helpful, we should keep them slim. This change moves the asset resolution with credentials to the calling runtime (cnquery/cnspec) instead of the plugin. This keeps plugins more focused and slim, fewer things for developers to know.
get closer to turning the tests green

🧹 decouple inventory manager from providers 

---

llx/code.go
mqlc/mqlc.go
mqlc/mqlc_test.go

This fixes an issue where the call binding chain was not being maintained when adding fields from the assessment block to the default fields block
For example:
```
go run apps/cnquery/cnquery.go run --ast -c '
entires = ["/etc/hosts"]
entires {
files.find(from: _, type: "file").all( permissions.other_readable == false )
}
'
```
was producing:
```
-> block 1
entrypoints: [<1,3>]
1: [
0: "/etc/hosts"
]
2: ref<1,1>
3: {} bind: <1,2> type:[]block (=> <2,0>)
-> block 2
entrypoints: [<2,6>]
1: _
2: files.find bind: <0,0> type:files.find ("from", ref<2,1>, "type", "file")
3: list bind: <2,2> type:[]file
4: $whereNot bind: <2,2> type:files.find (ref<2,3>, => <3,0>)
5: list bind: <2,4> type:[]file
6: $all bind: <2,5> type:bool
7: {} bind: <2,5> type:[]block (=> <4,0>)
-> block 3
entrypoints: …
```

🐛 maintain correct binding chain when adding assessment fields to defaults

---

motor/discovery/github/github.go

The wrong function was used to list the repos. Now it's using the same function that is used by the MQL resources

🐛 fix discovery for private github repos

---

llx/rawdata_json.go

Properly handle cases where the value of `RawData` cannot be parsed

🐛 raw data json err

---

providers-sdk/v1/lr/collector.go
providers-sdk/v1/lr/go.go
providers-sdk/v1/plugin/runtime.go
providers-sdk/v1/testutils/testdata/arch.json
providers/core/resources/core.lr.go
providers/os/provider/provider.go
providers/os/resources/authorizedkeys.go
providers/os/resources/authorizedkeys_test.go
providers/os/resources/os.lr.go
providers/runtime.go

- 🐛 fix the detection of new init-style argument parsers for resources
- ✨ add the provider that generated an error message to a few of the auto-generated messages (more to come)
- 🐛 handle errors from resource ID-generation
- 🧹 stop exposing data setters for call-arguments in resources
- 🐛 avoid loading resource fields from within providers when calling recordings (needs recursive loading in a follow-up, for now it prevents a crash)
- and most importantly: 🟢 fix 3/4 authorized keys tests (without actually storing the authorized keys resource or fields!) (which caused this giant rewrite)

🐛 load resource async from recording

---

providers-sdk/v1/lr/go.go
providers-sdk/v1/plugin/runtime.go
providers-sdk/v1/testutils/testdata/arch.json
providers/core/resources/core.lr.go
providers/os/provider/provider.go
providers/os/resources/os.lr.go
providers/os/resources/user.go
types/types.go

- re-expose SetAllData because we need it in calling providers to set resources from recordings
- types can now check if they contain a resource; this is important because loading resources from recordings requires proper initialization
- 🐛 a resource that cannot be found in a provider may have not been initialized from the caller; this happens when we load data from a recording, but are missing a number of fields in the recording. This is actually a great case where the recording only needs the data it cannot compute on the fly
This makes it 4/4 for authorized keys tests

🐛 allow bi-directional loading of recordings

---

cli/printer/printer_test.go
providers-sdk/v1/lr/go.go
providers-sdk/v1/plugin/runtime.go
providers/core/resources/core.lr.go
providers/os/provider/provider.go
providers/os/resources/os.lr.go
providers/os/resources/user.go

After https://github.com/mondoohq/cnquery/pull/1389
Sometimes a plugin provider will decide to load a resource that comes from a recording, which has embedded child resources. This does not pass the regular flow where the host (cnquery) would be able to detect that such a resource was requested and could intervene. Instead, all of this plays inside of the plugin. Thus, we need to know when embedde resources are requested and load them on the fly.
Note: we don't want to load it all in the beginning, because (1) it could mean a lot of data which is never used and (2) (more importantly) it can lead to a chain-reaction of resources that are all connected (which we love to do because it's awesome) and then lock the provider into a loading loop (which needs additional handling to be …

🐛 load embedded recording resources inside of plugins

---

providers-sdk/v1/testutils/testdata/arch.json
providers/os/resources/files_test.go

After https://github.com/mondoohq/cnquery/pull/1399
This was just missing some testdata in the recording, so I picked a few files from a local record

add testdata for files.find

---

providers/os/resources/packages.go
providers/os/resources/services.go
providers/os/resources/user.go

recently introduced for services, this pattern is excellent to keep the cache separate from the initial load (even if we have to cycle things again) AND it makes it so that we can load these things safely from recordings.
Up until this point there was the edge-case where we loaded a cached list of resources from a recording during a call for eg `resource(name)`. Since it is loaded from a recording, it did not create the mqlResourceInternal structures. A nasty workaround to this problem has now been removed as well. This model is much cleaner and safe to use across recordings

🐛 establish cache refresh from recording pattern

---

Makefile
providers/coordinator.go
providers/providers.go

In the old model, all plugin files were flat in a plugins folder. That can get out of hand because a ton of files will be all over the place. 
Instead, put all plugin files into a folder with the plugin name, e.g.:
```
.config/mondoo/providers
└── os
├── os
├── os.json
└── os.resources.json
```

✨ structure provider plugins into folders

---

apps/cnquery/cmd/providers.go
cli/providers/providers.go
providers/coordinator.go
providers/providers.go
providers/runtime.go

- instead of printing '.' for builtin, it now says 'builtin'
- print providers in the order: builtin, home, and then system
- list out all providers in all locations, not just whatever is active
example (on my dev setup):
```
> cnquery providers                                                                                                                                   x130 
→ builtin (found 2 providers)
core 9.0.0
os 9.0.1 with connectors: local, ssh, winrm
→ /home/zero/.config/mondoo/providers (found 1 providers)
os 9.0.0 with connectors: local, ssh, winrm
→ /opt/mondoo/providers has no providers
```
^^  also if i have a builtin `os` now i also see the local plugin in the folder and the builtin one separate

✨ list providers: builtin vs other

---

.gitignore
Makefile
providers-sdk/v1/lr/cli/cmd/docs.go

to generate tar.xz files for every bundle locally. Great for testing, not meant for distirbution (since you want to do this for every architecture)
Also: remove some older resource generation code, which we no longer use. Do not install the core provider by install (it is meant to be builtin by default). And finally: do not build the lr.manifest.json into the dist folder, since we don't distribute it. Instead it will be kept alongside the manifest.yaml for further processing.

✨ make providers/bundle

---

apps/cnquery/cmd/providers.go
providers/providers.go

After https://github.com/mondoohq/cnquery/pull/1413
The mechanisms where it was only loaded from disk when necessary breaks because we need the CLI options to be loaded before we de-dupe any providers. This is done via name, so we have to have their metadata loaded. This makes the code simpler and removes any surprises with having a provider that has no metadata.

🐛 pre-load all providers

---

llx/runtime.go
mqlc/mqlc.go
providers-sdk/v1/resources/schema.go
providers/mock/mock.go
providers/runtime.go

This way calls like `asset{*}` will fundamentally work. Parts of the resource resides with the original provider for it, parts reside with the override.
On the example we still have to fix the `eol` call within the asset resource, since it is forwarded...

⭐ support loading fields across multiple providers

---

providers/os/resources/updates/suse_updates.go

During a cnspec scan on a system without access to the suse repositories, zypper waits for user input. This results in an unresponsive cnspec scan.

🐞 add non-interactive flag to the zypper command

---

cli/providers/providers.go

Without this, PreRun for these new commands is not called. This means that things like `viper.BindPFlag` is not executed, which in term breaks later execution.

🐛 attach cli PreRun on command-generation

---

explorer/scan/local_scanner.go
explorer/services.go
internal/datalakes/inmemory/inmemory.go
providers/coordinator.go

After https://github.com/mondoohq/cnquery/pull/1430
Currently, when creating a new set of local services, we are actually creating a new runtime. So far that never caused problems, because cnquery was monolithic. Now that is changing, and we want the correct runtime to be injected and used (ie not created anew) into services. This popped up as a bug when running scans, where part of the queries were not executable because providers were missing.
This is also bad behavior in the previous iteration, since we never used the correct runtime.

🐛 inject runtime into services

---

providers/core/provider/provider.go
providers/os/provider/provider.go

After https://github.com/mondoohq/cnquery/pull/1431
We have to return non-nil on success or grpc will fail to encode

🐛 prevent grpc nil errors

---

explorer/scan/fetcher.go
explorer/scan/local_scanner.go

After https://github.com/mondoohq/cnquery/pull/1432
1. Like previously stated, in the past we were taking a lot of shortcuts by instantiating schemas multiple times. Now that we have runtime-bound schemas (with specificly loaded plugin providers) we have to do this properly, i.e. schemas are handed over.
2. We do not always have an upstream config, so for the cases where we don't, we have to work around it. We don't want to set an upstream config when we didn't load one, so it needs a check now.

🐛 use correct schema + conditional upstream config

---

motor/providers/aws/provider.go

Right now an AWS Account passes into this functionw with the name of "" and we set the name to "aws" and the title to "Amazon Web Services". The "aws" platform is actually the account so we should properly name it. This is important as time goes on with fine grained scanning where we need to distinguish between the resources and the main account.

🧹 Set the title of AWS accounts to be AWS Account

---

apps/cnquery/cmd/providers.go
cli/providers/providers.go
providers/coordinator.go
providers/providers.go
providers/runtime.go

A great starting point!
**How does it work?**
1. This only operates on whatever provider the user wants to use. It doesn't consider other providers. This keeps updates focused on things that are in use only. This is done when a provider is started by the coordinator. I.e. it does not happen when we attach to shell, only when we actually make use of a provider.
2. Updates will only be checked for non-builtin providers. We ignore builtin providers, since we never load them from disk (no matter the version). Builtin is builtin after all ;)
3. It looks at the binary for the installed provider. If the last change time is too recent (1h by default) it will not try to check for new versions. If we check for new versions, the change time will be updated, no matter if something was installed or …

⭐ support auto-update for installed providers

---

apps/cnquery/cmd/root.go
providers/coordinator.go
providers/providers.go

After https://github.com/mondoohq/cnquery/pull/1447
- 🐛 clear out the cache of providers during the installation
- inject the installation as early as possible, because we need to reload CLI options

✨ auto-install missing providers

---

explorer/scan/local_scanner.go

After https://github.com/mondoohq/cnquery/pull/1448
This caused very very early logs to be printed, because even with an `init()` call this runs before the CLI `root.go` is able to call its `init()`. So, we have to work around these limitations...
Before:
After:

🐛 avoid logging before logger is initialized

---

providers-sdk/v1/plugin/grpc.go
providers/coordinator.go
providers/runtime.go

After https://github.com/mondoohq/cnquery/pull/1450
If we close it too early, then the plugin cannot call back to another plugin to create resources or get data.

🐛 retain reverse connection to provider

---

motor/vault/hashivault/hashivault.go
motor/vault/hashivault/hashivault_test.go

To use hashi-vault, use the following config:
```yaml
apiVersion: v1
kind: Inventory
metadata:
name: mondoo-inventory
labels:
environment: production
spec:
assets:
- name: vsphere
connections:
- backend: vsphere
host: 192.168.1.24
credentials:
- secret_id: test-key # uses the secret kv backend automatically
discover:
targets:
- host-machines
vault:
name: local
type: hashicorp-vault
options:
url: http://127.0.0.1:8200 # dev-server url
token: <token>
```

🐛 fix hashi vault

---

llx/data_conversions.go

In case we have a resource without data, it also does not have a type. We need to catch this to prevent the error: `cannot convert primitive with NO type information`
This happens, e.g., when we test for the exists of a file before doing anything else with the resource.
Partially-Fixes #957

🐛 Fix conversion of primitives with NO type

---

resources/packs/os/smbios/linux.go

When running a snapshot scan we can run into the issue that we log a `SkipDir` error when reading bios. That error is irrelevant and we should just return empty data

🧹 do not error on filepath.SkipDir when reading linux bios

---

resources/packs/aws/aws_ec2.go

🐛 Use bool value and not pointer for `aws.ec2.networkacl.entry.egress`

---

resources/packs/core/packages/rpm_packages.go
resources/packs/core/packages/rpm_updates.go
resources/packs/core/packages/rpm_updates_test.go
resources/packs/core/packages/testdata/updates_zypper.toml
resources/packs/os/services/sysv.go

This fixes the following reported issues:
- cnspec scan unresponsive - "zypper --xmlout list-updates" missing -n flag
- handles suse system services specially
Followup on https://github.com/mondoohq/cnquery/pull/1424

🐛 fixes for suse linux

---

scripts/provider_bundler.sh

This fixes the build of the plugins. All current available archs where accidentally just compiled as linux, therefore plugins do not work on macOS or other platforms.

🐛 fix arch specific provider builds

---

resources/packs/aws/aws_ec2.go

For `egress` ids weren't unique across egress and ingress rules. That resulted in strange outputs not matching AWS.
For `portRange` we had a type mismatch and the resource wasn't created as expected
Fixes #1463

🐛 Fix networkAcl portRange and egress

---

resources/packs/os/services/sysv.go

... as it hangs on at "boot" during any service check. Applies to #1469

🐛 SUSE11 ignore all *boot* services

---

resources/packs/os/services/manager_test.go
resources/packs/os/services/sysv.go
resources/packs/os/services/upstart_test.go

Make the v8 build green again, looks like we now ignore more services due to https://github.com/mondoohq/cnquery/commit/b4047b4a8b16576b95b0818ac2932fa0cfba4a9d

🐛 Fix manager test, gofmt a file.

---

explorer/scan/local_scanner.go

We now assign the asset id during the connection to the provider so we don't have to check that anymore

🐛 Assign default MRN to incognito assets.

---

Makefile

To validate the license headers:
```bash
make license
copywrite headers --plan
Executing in dry-run mode. Rerun without the `--plan` flag to apply changes.
Using license identifier: BUSL-1.1
Using copyright holder: Mondoo, Inc.
Exempting the following search patterns:
**/*.tf
**/testdata/**
**/*.pb.go
**/*_string.go
The following files are missing headers:
```
To add license headers automatically:
```bash
make license/headers/apply
```

🧹 add make command to check for license headers

---

providers-sdk/v1/lr/go.go

It was never returning an error, since errors are collected in the internal multi-error field.

🧹 remove error from generator struct

---

motor/discovery/gcp/mql_asset_objects.go

fixes https://github.com/mondoohq/cnquery/issues/1578

🐛 ensure the subnetwork asset name, not mql object name, is the one with the region suffix

---

.github/workflows/goreleaser.yml
.goreleaser.yml

This morning a change to Apple's Notorization service suddenly caused https://github.com/anchore/quill/issues/118 in the excellent Quill tool.  This change update quill to the new fixed version, also allow releaser to continue in the event of a notorization failure (to avoid holding up all platforms) and dumps the logs for quill to allow for easier debugging.

Debugging improvements for goreleaser failures

---

providers-sdk/v1/lr/go.go
providers/vcd/resources/externalnetworks.go
providers/vcd/resources/vcd.lr
providers/vcd/resources/vcd.lr.go

After https://github.com/mondoohq/cnquery/pull/1572
tldr: use static `id` fields in resources, dynamic fields would need the same `id()` method we use for internal IDs
Long explanation: It is possible for a resource to define itself an `id` field. We have done this before (eg in yum repos) where the field returns a custom ID that users can access.
All MQL resources have their own internal ID. The confusion happens, when we have a semantic `id` field we expose to users and an internal `id` field that we do not expose. At the time of writing, we have no scenario where we would ever need an ID field that is different from the internal ID of the resource. Ideally we can have both use the same ID, i.e. if users ever expose an `id` field it should semantically provide everything we would expect …

🐛 avoid building dynamic `id` fields in resources

---

Makefile
providers/arista/go.mod
providers/arista/go.sum
providers/equinix/go.mod
providers/equinix/go.sum
providers/github/go.mod
providers/github/go.sum
providers/gitlab/go.mod
providers/gitlab/go.sum
providers/google-workspace/go.mod
providers/google-workspace/go.sum
providers/ipmi/go.mod
providers/ipmi/go.sum
providers/oci/go.mod
providers/oci/go.sum
providers/okta/go.mod
providers/okta/go.sum
providers/opcua/go.mod
providers/opcua/go.sum
providers/slack/go.mod
providers/slack/go.sum
providers/terraform/go.mod
providers/terraform/go.sum
providers/vcd/go.mod
providers/vcd/go.sum
providers/vsphere/go.mod
providers/vsphere/go.sum

When we update dependencies in cnquery (eg. via dependabot), the build of the plugins will fail since they depend on latest cnquery with the statement of `replace go.mondoo.com/cnquery => ../..`. This is still the desired behavior since when I check out a commit, all code references should only depend on that specific commit in cnquery. Otherwise debugging issues will become very painful going forward.
This PR is a first step to automate go.mod update for all the providers via a `make providers/gomodtidy`. Once that runs well, we probably want to run this as an automatic task for PRs that change go.mod in cnquery base.

🧹 update go dependencies of providers

---

motor/discovery/gcp/mql_asset_objects.go

also, i didn't touch the logic for this part right now, but why are we entirely skipping windows instances, like not discovering them at all? @preslavgerchev @imilchev does one of you know?
```
if disksContainWindows(i.Disks) {
log.Debug().Msgf("skipping windows instance %s", i.Name)
continue
}
```

🐛 gcp compute instances should be labelled as platform instance not image

---

apps/cnquery/cmd/login.go
apps/cnquery/cmd/logout.go
apps/cnquery/cmd/root.go
apps/cnquery/cmd/run.go
apps/cnquery/cmd/shell.go
apps/cnquery/cmd/status.go
apps/cnquery/cmd/vault.go

We are exposing:
- vault
- status
- run
- login
- logout
Additionally, the shell command can largely be re-used with a few config changes in cnspec. We still expose it, but we expect the runner to be overwritten to make adjustments to the config. 
This will help finalize cnspec for v9.

expose a variety of shared CLI commands

---

Makefile

In the case of K8s, the config pulls in discovery options from the remaining provider, which ultimately pull a dependency to the k8s resources. These, however, do not exist on a clean build, because LR has not yet been executed. Swap the order so that LR runs first, creating the lr-generated files (like k8s.lr.go) which then make the dependency chain work for creating the config.

🐛 create LR before CLI config

---

providers/azure/config/config.go
providers/azure/provider/provider.go
providers/azure/resources/discovery.go
providers/gcp/config/config.go
providers/gcp/resources/discovery.go

After https://github.com/mondoohq/cnquery/pull/1625
Taking the k8s pattern. The config should not have to be imported by other modules (at the time of writing).

🧹 align discovery options between k8s + azure + gcp

---

providers/coordinator.go
providers/providers.go

Updates are mostly optional. The system may be working fine and displaying it as an error at this stage may lead to unnecessary fear.

🌈 replace provider update error with warning

---

explorer/scan/local_scanner.go
providers/runtime.go

This makes sure that scans for a list of assets work. The current implementation would kill the provider after the first asset is scanned. We do a simple fix here that will only kill open providers after the whole scan is complete. As a long term fix we should probably look into keeping track of assets that need a specific provider. Only when all assets for the provider have been scanned, it can be killed.

🐛 make sure providers are not killed after an asset is scanned

---

explorer/scan/local_scanner.go

Not necessarily the fix, but an attempt to get a proper solution for this.
There are 2 problems I am trying to solve here:
1. Do not rely on two separate `assets` and `runtime` lists to get the scan to work. This will crash if we do not have an equal amount of assets and runtimes. Instead use a private struct to tie those two together
2. Running filters (queries) on a provider uses the currently attached asset, see https://github.com/mondoohq/cnquery/blob/main/providers/runtime.go#L419. At this moment we can only attach one asset, found under `r.Provider.Connection.Asset`. To ensure this works for all discovered assets, we need to make sure there's a proper runtime for each of those assets. This is where I am not sure if this is the right fix as we're now creating a runtime for each …

Attempt at fixing the scan runtime problem.

---

cli/providers/providers.go
explorer/scan/local_scanner.go
providers-sdk/v1/plugin/grpc.go
providers/runtime.go

🐛 fix provider shutdown

---

cli/printer/printer_test.go
cli/reporter/json_test.go
cli/shell/shell_test.go
explorer/filters_test.go
mql/mql_test.go
providers-sdk/v1/testutils/testutils.go
providers/core/resources/core_test.go
providers/core/resources/mql_test.go
providers/core/resources/time_test.go
providers/network/resources/network_test.go
providers/os/resources/mql_test.go
providers/os/resources/os_test.go
providers/os/resources/python_test.go

No more specifying the path. Especially when you import these testutils it is hard to figure out the path.

🧹 make testutils easier to use

---

apps/cnquery/cmd/root.go

We printed to stderr, but no visual indication which sucked. Streamline error handling in this phase with the remaineder of the application (which uses `log.Error`).

🐛 print proper errors for early provider checks

---

cli/providers/providers.go
providers/providers.go
providers/runtime.go

We have conflated connection types (which are coming from asset detection) and connection names (which are coming from CLI). One of the last changes has broken the support of CLI-based connector-detection (at least when the connection type and name differed, like in the case of OS).
This PR clarifies the difference between these types, by allowing the `EnsureProvider` call to either take the type or the name for the connection. In the CLI, we get names like `docker`, which then translate to the `os` provider. In contrast, the connection type is something like `docker-image` which translates to the `os` provider. We could have mixed them all together, but it may lead to confusing results (it should not, but it can and then it really falls apart).
This is also important because …

🐛 fix detection of provider via connector

---

providers-sdk/v1/testutils/testutils.go

We don't have all the resources json schemas in this repo. That's because they get generated together with the build process of each provider. Because we don't all the schemas in the repo, testutils cannot just be included in other projects, because they don't go through the json resources schema generation.
We now have 2 options: (1) check in all the schemas into the repo or (2) generate the schema from LR files.
This PR takes the second option. It treats these LR files in the same way the schema loader treats JSON files: they contain all the metadata, we don't need to generate any Go-files for tests, we don't need to generate manifests, we only need the schema which is fully self-contained in LR files. Thus, instead of parsing JSONs step by step, it parses LR files step by step (but …

🧹 testutils: load schema from LR

---

mqlc/mqlc.go

This method also exists in explorer/executor, but with a few differences:
1. it has tests
2. it is actually in use (in any of our projects)
3. it provides useful functionality like using the default runtime
Deduplicate it between mqlc and the explorer/executor.
To understand why we remove this but keep the other method: This method is used as an analogy to regexp.MustCompile and thus you'd want it to be self-contained without having to do additional steps.
However, this needs a bit more follow-up work, because the runtime may not contain the providers necessary for the piece of code to run. This is surfacing right now in cnspec, where MQL code is requested by the reporter which is provided by the `os` plugin (which may not be installed!). Thus, these methods will likely need a bit more …

🧹 remove mqlc.MustCompile

---

providers/os/resources/packages.go

it uses the wrong method, which causes the internal list of packages by name to not get refreshed

🐛 package init does not get list from recording

---

docs/development.md

We used the old release symbol 🎉. Technically not incorrect, but we switched to the different levels of stars and would like to stick to that. Major releases and major capabilities can use 🌟 or even 🌠 (like providers for v9).

📃 update emojiguide

---

apps/cnquery/cmd/providers.go

... because we use the same command in cnspec

🔧 expose providers cli command

---

explorer/scan/local_scanner.go

All the remaining code that deals with synchronization and test execution is unnecessary if there are no assets.

🐛 abort scans if there are no assets

---

providers/os/provider/provider.go

The behavior of the connect call is defined in the proto here: https://github.com/mondoohq/cnquery/blob/main/providers-sdk/v1/plugin/plugin.proto\#L35-L38 It clarifies that the inventory only returns other discovered assets, while the asset field contains the one asset that the connection call was requesting.
Remove the code that added the connection asset to the inventory, since it does not count as a discovered asset.

🐛 os.Connect should not return the asset in the inventory

---

Makefile
providers/providers.go

```
PS C:\Users\ivan\Desktop> .\cnquery.exe run local -c os.name
os.name: "IVAN-WIN"
```

🐛 fix running on windows

---

providers/defaults.go

Without these, an installation without providers in the very early stage does not know what to install. With this, they know what to install. Example: remove all provider plugins and try `cnquery shell aws`.

🐛 add all default providers

---

mql/mql_test.go
providers-sdk/v1/lr/schema.go
providers-sdk/v1/lr/schema_test.go
providers/runtime.go

We could no longer call aliased resource properly. This was partly because the way the schema generation had changed (where I missed to migrate the `IsImplicitResource` field) and partly because the resource lookup had also changed (since we want to call the base resource now with the provider, not the alias).

🐛 fix aliased resources

---

providers/gcp/resources/gke.go

Fixes the following error for GKE clusters:
```
masterAuthorizedNetworksConfig: failed to convert dict to primitive, unsupported child type: []map[string]interface {}
```

🐛 fix GKE cluster resource

---

apps/cnquery/cmd/plugin.go
providers/recording.go
providers/runtime.go

After introducing multiple runtimes for execution, the recording function broke. Attach recordings to every execution.

🐛 fix recordings

---

.vscode/launch.json
apps/cnquery/cmd/run.go
explorer/scan/local_scanner.go

Note: there is a bug where it does not associate the correct asset, because we reconnect and the ID of the asset is wrong. Will be fixed...

🐛 support --record on scan command

---

.github/workflows/goreleaser.yml

To help with testing of v9 we want to create releases for test but not distribute them via the normal channels, they will only be available on the Github release page.

Skip publish on alpha/beta tags

---

providers/gcp/resources/discovery.go

- set platform kind and runtime for gcp assets
- make sure platform name and title for gcp gke clusters matches v8 values

🐛 set kind and runtime for gcp assets platform

---

.github/workflows/goreleaser.yml

Similar to alpha and beta, adding 'rc' to a release tag will skip publishing the release.

Support rc release tags

---

mqlc/mqlc_test.go
mqlc/parser/parser.go

We were not able to call things like `mondoo { version ; build }` cleanly. Fix it.

🐛 support semicolons in blocks

---

cli/printer/mql.go
providers-sdk/v1/plugin/runtime.go

An example for how this works using the `user` resource and setting its `group` field to null:
```go
func (x *mqlUser) group(gid int64) (*mqlGroup, error) {
x.Group.State = plugin.StateIsSet|plugin.StateIsNull
return nil, nil
}
```
Once you set the field internally (`StateIsSet`), it will ignore the return values and instead read it from the field that you set. Then it will see `StateIsNull` and use it on the return data

🐛 support null resources

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_lambda.go

This adds the runtime of a lambda to the information returned when querying functions.
resolves mondoohq/cnquery#1727

✨ add runtime field to AWS lambda function resources

---

mqlc/labels.go
mqlc/mqlc.go
mqlc/mqlc_test.go
providers/os/resources/parse.go

Accessing dict structures sometimes feels a bit painful:
```coffee
dict["one"]["more"]["field"]
```
Luckily for us, this pattern is well-known in the framework that birthed the scripting part of MQL: JS.
With that in mind:
```coffee
dict.one.more.field
```
is a much better way of expressing this use-case.
Now: combine this with the power of GraphQL, and all of a sudden you get something like this:
```coffee
dict {
one {
more.field
}
another
}
```
Here is an example of using it in this repo:
```graphql
{
Name 
Version 
Connectors {
Name 
Short
}
}
```
If we run it like this:
```bash
cnquery run -c "parse.json('providers/os/dist/os.json').params{Name Version Connectors {Name Short}} --json"
```
and prettify the output:

⭐ add simple accessors for dicts

---

providers-sdk/v1/util/convert/pointers.go
providers/github/connection/connection.go
providers/github/connection/platform.go
providers/github/provider/provider.go
providers/github/resources/discovery.go
providers/github/resources/github.lr.go
providers/github/resources/github_org.go
providers/github/resources/github_repo.go
providers/github/resources/github_user.go

fixes https://github.com/mondoohq/cnquery/issues/1644

🐛 fix github discovery for v9

---

llx/rawdata.go
llx/rawdata_test.go
providers/recording.go

Up until this point, errors were marshalled into `error:{}` into JSON files. This caused problems when trying to load the structure (because the error type is not familiar with empty object).
This fixes the issue in the RawData to JSON marshal/unmarshal calls and additionally handles type problems for int (which is by default read as a float) and time (which is read as a string). It also fixes a problem with reconnecting resources when the field in question is an error.

🐛 store+load recordings with errors

---

providers/slack/connection/connection.go

local and ssh are also missing asset name --- i think it's because we didn't port over all the id detection stuff we had in v8...looking into it

🐛 fix missing slack team name

---

logger/debug.go

A small one: dump all the debug files if logging is set to TRACE, not just DEBUG. This helps when debugging with 'TRACE=1' to get some more verbosity

🧹 Dump debug files if TRACE env var is set.

---

providers/terraform/resources/hcl.go

fixes https://github.com/mondoohq/cnquery/issues/1737

🐛 fix for terraform <cannot get hcl block> err

---

providers-sdk/v1/util/configure/configure.go
providers/builtin.go
providers/os/config/config.go

- the os provider does not support the mock connection
- add back the builtin comments for the os provider, since we still use it (until it gets wired into its own go.mod)

🐛 fix incorrect os-connection + 🧹 add os builtin

---

apps/cnquery/cmd/builder/common/common.go
apps/cnquery/cmd/builder/parse.go
motor/discovery/gitlab/gitlab.go
motor/providers/terraform/provider.go
motor/providers/terraform/provider_test.go

This PR adds the ability to the gitlab provider to detect terraform inside of the git repo.
```bash
cnquery shell gitlab --group example --project example-gitlab
→ resolved assets resolved-assets=2
Available assets                               
> 1. example / Example Gitlab (gitlab-project)
2. example / Example Gitlab (terraform-hcl) 
```

⭐️ gitlab terraform discovery

---

cli/providers/providers.go

Thsi prevents panics wherre a arg is missing:
```
cnquery run vagrant -c "asset" 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x112b609]
go.mondoo.com/cnquery/providers/os/connection.(*VagrantConnection).Asset(0x40c72d?)
<autogenerated>:1 +0x9
go.mondoo.com/cnquery/providers/os/provider.(*Service).connect(0xc000308910, 0xc0006e3aa0, {0x1e546c0?, 0xc00009f600})
/home/christian/workspace/mondoo/github.com/cnquery/providers/os/provider/provider.go:187 +0x2b0
go.mondoo.com/cnquery/providers/os/provider.(*Service).Connect(0x1e3faa0?, 0xc0006e3aa0, {0x1e546c0?, 0xc00009f600?}) …
```

🐛 Check args before calling a plugin

---

providers/os/config/config.go
providers/os/connection/docker_container.go
providers/os/provider/provider.go
providers/os/resources/discovery/docker_engine/container.go
providers/os/resources/discovery/docker_engine/images.go
providers/os/resources/discovery/docker_engine/resolver.go

The PR breaks the normal local run right now:
```bash
..go/src/go.mondoo.com/cnquery ±> go run apps/cnquery/cnquery.go shell local                                                                 8m main[0e7b2f9b]
→ loaded configuration from /home/zero/.config/mondoo/mondoo.yml using source default
FTL could not find an asset that we can connect to
exit status 1
```
Reverts mondoohq/cnquery#1701

Revert "✨ Add container discovery to v9 os provider"

---

providers/os/resources/kernel.go
providers/os/resources/packages.go
providers/os/resources/services.go

This is in line with v8 and would otherwise break a number of existing queries. It is inconsistent with a few other resources (like `user`) and needs further alignment (as descriped in https://github.com/mondoohq/cnquery/issues/1622).
That said, some fields are now null instead of empty strings:
```coffee
cnquery> package("blah"){*}
package: {
name: "blah"
version: null
epoch: null
available: null
description: null
status: null
outdated: false
arch: null
origin: null
installed: false
format: null
}
cnquery> service("blah"){*}
service: {
name: "blah"
installed: false
description: null
type: null
enabled: false
running: false
masked: false
}
cnquery> kernel.module("blah"){*}
kernel.module: {
size: null
name: "blah"
loaded: false
}
```

🐛 revert error on non-existent package, service, and kernel.module

---

llx/primitives.go
llx/rawdata.go
llx/rawdata_test.go

Serializing to string tries to follow timestamp norms. However, the two infinity times are set as beyond regular date ranges and cause it to crash.
We decided to use integers to represent the unix time (which is intuitive from reading it) and is much faster to read/write.
However, due to limitations in JSON precision for integers (RFC 7159) we had to limit the range and eagerly interpret things to be either Never-times (future and past).
This needs to be merged before the v9 release to avoid breaking changes in recordings.

🐛 support Never in json read/write

---

providers/os/config/config.go
providers/os/provider/provider.go

This fixes two errors:
```
cnquery run container registry gcr.io/mondoo-base-infra/mvd:latest -c "asset{ name platform ids kind runtime title }" --verbose     
Error: accepts 1 arg(s), received 2
...
x accepts 1 arg(s), received 2
```
This check was introduced with https://github.com/mondoohq/cnquery/pull/1503
And
```
cnquery run container registry gcr.io/mondoo-base-infra/mvd:latest -c "asset{ name platform ids kind runtime title }" --verbose 
DBG using provider os with connector container
DBG found valid container registry reference ref=gcr.io/mondoo-base-infra/mvd:latest
! unknown credentials for container image
[
{
"type": "ssh_agent"
}
]
...
panic: runtime error: invalid memory …
```

🐛 Fix errors when scanning container images

---

providers/os/connection/docker_container.go
providers/os/resources/discovery/docker_engine/resolver.go

Now, the os providers tries to find a requested container image locally within the dcker daemon. When this doesn't work, it tries to find the image in a remote registry.
Fixes #1699

🐛 Fix container image resolve in v9

---

cli/providers/providers.go

This fixes a regression in v9
Before:
After:
Works for `run`, `shell`, and `scan` now
Here is the same thing when the provider is not yet installed:

🐛 fix -h/--help for all attached subcommands

---

apps/cnquery/cmd/run.go
apps/cnquery/cmd/scan.go
apps/cnquery/cmd/shell.go

🐛 show scan+run+shell as regular commands in --help

---

motor/providers/terraform/provider.go

Add the missing space to errors like this:
```
x could not connect to asset error="path 'https://gitlab.com/mondoolabs/example-gitlab.git'is not a valid file or directory" asset=
```

Fix missing space in invalid path error

---

.github/workflows/providers.yaml
scripts/provider_bundler.sh

This change fixes several oddities in the provider build action, namely using the version variable for the providers list.  It also removes manual invocation inputs because it currently builds the latest.json file based on what its built in dist/

Improvements to provider building

---

providers/os/id/awsec2/id.go
providers/os/id/clouddetect/clouddetect.go
providers/os/id/ids/ids.go
providers/os/provider/detector.go
providers/os/provider/platform.go
providers/os/provider/provider.go

this fixes the asset name detection for local and ssh - it's a portover from v8.
~this still needs some cleanup, ill get back to it this weekend. ran outta steam.~

🐛 fix asset name for local, ssh conn

---

cli/providers/providers.go
providers-sdk/v1/plugin/flag.go
providers-sdk/v1/plugin/start.go
providers/mock.go

This avoids an error-message which makes users think that recordings were not loaded.
Before 
```bash
..go/src/go.mondoo.com/cnquery ±> go run apps/cnquery/cnquery.go run -c sshd.config.params --use-recording a.json
! pre-processing of cli had an error error="unknown flag: --use-recording"
→ no provider specified, defaulting to local. Use --help to see all providers.
→ loaded configuration from /home/zero/.config/mondoo/mondoo.yml using source default
```
After:
```bash
..go/src/go.mondoo.com/cnquery ±> go run apps/cnquery/cnquery.go run -c sshd.config.params --use-recording a.json
→ no provider specified, defaulting to local. Use --help to see all providers.
→ loaded configuration from /home/zero/.config/mondoo/mondoo.yml using source default
```

🐛 add builtin flags for cli pre-processing

---

providers/terraform/provider/testdata/tfplan-replace-paths/tfplan.json
providers/terraform/provider/tfplan_test.go
providers/terraform/resources/tfplan.go

Migrate https://github.com/mondoohq/cnquery/pull/1511
Fixes https://github.com/mondoohq/cnquery/issues/1512
Note: These Terraform tests need a proper migration of their test as described in https://github.com/mondoohq/cnquery/issues/1787

🐛 Fix unmarshal for terraform plan `replace_paths`

---

motor/discovery/gitlab/gitlab.go

the error i encountered is reproducible by running `unset SSH_AUTH_SOCK` and then running `DEBUG=1 cnquery shell gitlab --group mondoolabs --token TOKEN`
you should see it fail out when cloning the repos 
(with this change it should just work. in my test i have one repo i can't clone due to perms, so it get 36 assets discovered)
------
i'm a little uncertain about this change, i would have expected some process before resolve, like the enrich assets one,  to take care of doing this
but i did test this on two diff machines and got the same result on both

🐛 ensure we use the credential token for gitlab scan

---

explorer/scan/local_scanner.go
providers/aws/provider/provider.go

When scanning k8s with container image discovery, it paniced. That happened because asset data was missing.
Fixes #1749

🐛 Prevent k8s scan panic

---

providers/network/provider/provider.go

noticed this while testing out another pr

🐛 make sure network provider asset has platform id

---

Makefile

Add a build mode which (1) uses dist ldflags stripping all extra information from binaries and (2) statically links them, which matches the desired default distribution model.
I had initially thought static linking would cause our binary size to increase, but curiously the opposite happened. The total size decreased by 4% on average across all providers.
Additionally I tried the approach described by https://mt165.co.uk/blog/static-link-go/ with `-ldflags "-linkmode 'external' -extldflags '-static'"`. However, adding these two flags made things go haywire for me. 
Here are all 3 modes for all providers, `static` is `CGO_ENABLED=0` and `ldstatic` is with the above described flags in addition to cgo (tried with and without the mode, enabling it made things worse).
Metadata info:
```bash
> …
```

✨ make providers/dist

---

.github/workflows/providers.yaml
scripts/provider_bundler.sh

superseeds #1795
This moves the provider build to a matrix build and also adjust the build script to use static compile. There is followup work required to align the bash script with the make script a bit more.
In addition it removes the latest json configuration from the build process since it was error prone. It will be generated in releasr to make the generation more stable.

🧹 use matrix for provider build

---

providers/terraform/connection/connection.go
providers/terraform/provider/detector.go
providers/terraform/provider/provider.go

This fixes the values for:
- platform name
- platform title
- platform ID
Fixes #1743

🐛 Fix terraform platform information

---

providers/gitlab/resources/gitlab.go
providers/gitlab/resources/gitlab.lr
providers/gitlab/resources/gitlab.lr.go
providers/gitlab/resources/gitlab.lr.manifest.yaml

Add new properties to gitlab.group
- emailsDisabled
- preventForkingOutsideGroup
- mentionsDisabled
- webURL
These are helpful for expanding the gitlab security policy + asset overview data for the console
```
gitlab.group: {
name: "mondoolabs"
webURL: "https://gitlab.com/groups/mondoolabs"
path: "mondoolabs"
mentionsDisabled: false
description: ""
projects: [
0: gitlab.project name="Example Gitlab" visibility="private"
]
id: 5409231
requireTwoFactorAuthentication: true
visibility: "private"
emailsDisabled: false
preventForkingOutsideGroup: false
}
```

⭐ Add new properties to `gitlab.group` resource

---

providers/gitlab/go.mod
providers/gitlab/go.sum
providers/gitlab/resources/gitlab.go
providers/gitlab/resources/gitlab.lr
providers/gitlab/resources/gitlab.lr.go
providers/gitlab/resources/gitlab.lr.manifest.yaml

Add a pile of new properties we need to improve the security policy + asset overview data.
```
gitlab.group.projects.first: {
webURL: "https://gitlab.com/lunaelectric/rover"
issuesEnabled: true
wikiEnabled: true
requirementsEnabled: false
path: "rover"
createdAt: 2023-09-20 15:56:18.042 -0700 PDT
containerRegistryEnabled: true
name: "Rover"
visibility: "private"
id: 50575105
defaultBranch: "main"
description: ""
archived: false
serviceDeskEnabled: true
emailsDisabled: false
mirror: false
allowMergeOnSkippedPipeline: false
autoDevopsEnabled: false
onlyAllowMergeIfAllDiscussionsAreResolved: false
onlyAllowMergeIfPipelineSucceeds: false
fullName: "Lunalectric / Rover"
packagesEnabled: true
mergeRequestsEnabled: true
snippetsEnabled: true
}
```
Highlights:
- Update the defaults to use the new …

Add new properties to gitlab.project

---

examples/complex.mql.yaml
explorer/mquery.go
explorer/mquery_test.go

We had missed to process checksums and MRNs for properties of queries with this call. Since semantically it is supposed to refresh the entire checksum of the Mquery object, it needs to cover properties as well.

🐛 compute checksum for properties of queries

---

providers/os/resources/packages.go

fixes https://github.com/mondoohq/cnquery/issues/1719
epoch was also not filled in on v8. same todo is on the resource there. we should followup and address that!

🐛 do not fail out on incomplete epoch field on packages

---

cli/config/config.go
cli/providers/providers.go

We ignored the configured value by default and it only worked from CLI argument. Now it reads the config first and defers to the CLI for overrides.
Config used `.config/mondoo/mondoo.yml` contains:
```yaml
auto_update: false
```
Then without providers to start:

🐛 read auto update from config

---

providers-sdk/v1/util/configure/configure.go

makes development easier, since the rest of the wiring can still happen, even if the provider is faulty

🐛 allow make providers/config to run with failing providers

---

cli/config/path.go

Add special handling for MacOS / Darwin and make sure all configs + providers are in the same shared directory `/Library/Mondoo`
Fixes https://github.com/mondoohq/cnquery/issues/1832

🐛 move default provider path on macos to /Library/Mondoo

---

apps/cnquery/cmd/providers.go

Root just uses the system path, so trying to print a home path that is an empty string is confusing and wrong.
Before:
After:

🐛 avoid printing home-path for root

---

motor/providers/terraform/provider.go

fixes https://github.com/mondoohq/cnquery/issues/1835

🐛 fix platform id for git clone tf assets

---

providers/os/resources/privatekey.go

fixes https://github.com/mondoohq/cnquery/issues/1724

🐛 fix for users { * }: check for nil file data before returning path

---

providers/aws/config/config.go
providers/aws/connection/awsec2ebsconn/destroy.go
providers/aws/connection/awsec2ebsconn/provider.go
providers/aws/connection/awsec2ebsconn/setup.go
providers/aws/connection/awsec2ebsconn/setup_test.go
providers/aws/connection/awsec2ebsconn/setup_unit_test.go
providers/aws/connection/awsec2ebsconn/types/types.go
providers/aws/connection/awsec2ebsconn/types/types_test.go
providers/aws/connection/platform.go
providers/aws/go.mod
providers/aws/go.sum
providers/aws/provider/provider.go
providers/aws/resources/discovery_conversion.go
providers/os/connection/snapshot/volumemounter.go

` DEBUG=1 go run apps/cnquery/cnquery.go shell aws ec2 instance-connect ec2-user@i-01cbf9d3b50b96946 --profile home --region us-east-1`
` DEBUG=1 go run apps/cnquery/cnquery.go shell aws ec2 ssm ec2-user@i-01cbf9d3b50b96946 --profile home --region us-east-1`
i transferred the ebs stuff over but it's not all hooked up yet, that's coming in the next pr

🧹 aws fixes; make aws ec2 instance-connect and aws ec2 ssm work

---

cli/providers/providers.go

The way it was written before, the 3 commands run/shell/scan were missing their providers when they are not in active use. The problem: shell-completion relies on them to exist.

🐛 fix shell completion

---

providers/os/provider/provider.go

🐛 Handle ssh connection errors

---

providers/aws/go.mod
providers/aws/go.sum

fixes https://github.com/mondoohq/cnquery/actions/runs/6276988079/job/17047840205#step:7:187
we probably want to check go mod tidy on PRs, but we can also wait until os+network have their go.mod files

🐛 go mod tidy providers/aws

---

providers/providers.go

ListAll was able to return providers that could not be loaded.

🐛 only add loaded providers

---

providers/aws/resources/aws_cloudtrail.go
providers/aws/resources/aws_cloudwatch.go
providers/aws/resources/aws_ec2.go
providers/aws/resources/aws_iam.go
providers/aws/resources/aws_sagemaker.go

this gets matching reports for aws-foundations, aws-operational-bp, and mondoo-aws-sec

🐛 aws resource bugfixes

---

providers/gcp/config/config.go

```
[22/09/23 10:29:07] ❯ go run apps/cnquery/cnquery.go shell gcp project mondoo-dev-262313
! using builtin provider for gcp
→ connected to GCP Project mondoo-dev
cnquery> asset { platform ids version kind }
asset: {
kind: "gcp-object"
version: ""
platform: "gcp-project"
ids: [
0: "//platformid.api.mondoo.app/runtime/gcp/projects/mondoo-dev-262313"
]
}
cnquery> exit
```

🐛 allow args for gcp connection

---

providers/os/config/config.go

```
[22/09/23 10:15:36] ❯ go run apps/cnquery/cnquery.go shell docker d0e78872d058
→ connected to Ubuntu 22.04.1 LTS
cnquery> exit
```
```
[22/09/23 10:15:13] ❯ go run apps/cnquery/cnquery.go shell container d0e78872d058
→ connected to Ubuntu 22.04.1 LTS
\___|_| |_|\__, |\__,_|\___|_| …
```

🐛 also support the docker conn for cnquery shell docker <id>

---

providers/oci/config/config.go
providers/okta/config/config.go
providers/opcua/config/config.go

This release was created by cnquery's provider versioning bot. You can find me under: `providers-sdk/v1/util/version`.

🎉 oci-9.0.1, okta-9.0.1, opcua-9.0.1

---

go.mod
go.sum
providers-sdk/v1/util/version/version.go

The last few beta releases have shown how hard it is to keep all provider versions updated. To ease the pain, we are starting a small utility.
It is still in its infancy, but it is already really helpful:
```bash
alias version="go run providers-sdk/v1/util/version/version.go"
```
Check what needs updating (fast)
```bash
version check providers/*/ --fast
```
Update one provider, automatically bump the patch version when applicable, and add a commit:
```bash
version update providers/o* --fast --increment=patch --commit
```
Note 1: We use Golang's `go-git` for git processing, which is cleaner than using git in go, but also a lot slower, especially with larger files (beware: it sometimes may look like it's blocking on things, but it just takes long to process files).
Note 2: We are not …

🔧 add utility to help version providers

---

cli/providers/providers.go

We were getting errors about pre-processing failing when used in conjunction with full-fledged CLI commands.
Example: If you didn't have `cnquery` installed and copy-pasted:
```bash
cnquery run github org mondoohq --token github_.. -c ".."
```
... you'd get an error about not being able to parse `--token`.
This is a bit inefficient, but it at least results in a clean run for now.

🐛 pre-process known provider flags

---

providers/os/connection/local/statutil/stat.go
providers/os/connection/local/statutil/testdata/linux.toml
providers/os/connection/ssh/cat/testdata/cat.toml

stat does not support all the flags on Alpine, particularly printf. We can skip newline escapes, since we only grab simple fields. The only limitation here is the SElinux context, which we do not return yet (so we can revisit that then). Even so, it is the last value returned, so we can stick with `-c`

🐛 support sudo over ssh on alpine

---

providers/os/resources/group.go

Cannot request values from the list if we fail to initialize it in the firt place.

🐛 fix crash on user.members without init

---

explorer/executor/executor.go
explorer/scan/local_scanner.go

Analogous to https://github.com/mondoohq/cnspec/pull/741
Also adjust naming of the filter function in the executor. This needs more deduplication of course, but a small step ... 🤏

🐛 make filter queries optional

---

providers/coordinator.go
providers/runtime.go
utils/multierr/errors.go
utils/multierr/errors_test.go

1. Crashed providers print their plugin panic and then an error message about being unable to shutdown the provider. This is wrong and misleading.
2. Since we have potentialy multiple runtimes, the shutdown call can come down multiple paths to the same provider, leading to duplication of errors and reporting. Fix it by giving providers one clear shutdown.
3. Multierr did not handle nil errors correctly and would then end up in panic-land. Fixed.
With these updates we get:
Future ideas: hide away the panic behind a DEBUG flag

🐛 report on crashed provider + dedupe shutdown + fix multierr nil

---

providers-sdk/v1/inventory/inventory.go
providers/gcp/resources/discovery.go
providers/k8s/resources/discovery.go

We use a similar logic in multiple providers to clone a config but remove the discovery options. This is useful since we most likely do not want the discovery options when we clone. This change makes the the `config.Clone()` more smart by providing more options that can be provided. It makes the code of the providers more readable.

🧹 new logic to customise inventory config clone

---

providers/os/config/config.go
providers/slack/config/config.go
providers/terraform/config/config.go
providers/vcd/config/config.go
providers/vsphere/config/config.go

This release was created by cnquery's provider versioning bot. You can find me under: `providers-sdk/v1/util/version`.

🎉 os-9.0.2, slack-9.0.1, terraform-9.0.1, vcd-9.0.1, vsphere-9.0.1

---

motor/discovery/gitlab/gitlab.go
resources/packs/gitlab/gitlab.go

...i was able to reproduce the error that led to creating this pr earlier, and now i cannot. i do not understand why. 
in any case, this is the error that was reported:
```
failed to create resource 'gitlab.project': GET https://gitlab.com/api/v4...
404 {message: 404 Project Not Found}
```
we were previously hitting the api every time we init-ed a project..this changes it to use the group projects. i kept on convincing myself this wasn't correct, but since we always require a group along with a project, it does still work. and it means we don't hit the api every time

🐛 use gitlab mql group projects for project init

---

resources/packs/gitlab/gitlab.go

we're still having trouble finding projects in _some_ groups.  
i haven't been able to repro, but this is more cleanup that gets us one less api call

🧹 more gitlab group and project fetching cleanup

---

llx/builtin_resource.go
llx/runtime.go
providers/runtime.go

Mandatory arguments were never submitted, because the new provider concept meant that we had to request all the fields individually. We were missing a good pattern to execute this.
Turns out the CreateResourceWithID was only used in one place and its primary purpose was to clone the resource. This method has now been adjusted to better reflect its purpose and its arguments can now do the heavy lifting or getting all the necessary fields for cloning the resource. This method can be further refined to grab mandatory fields automatically.
Before:
After:

🐛 fix error when cloning resources

---

providers/slack/config/config.go
providers/slack/connection/connection.go

no args needed, its just `shell/scan slack` with a token, just like v8

🧹 fix slack asset name and discovery/req args

---

providers/gcp/resources/discovery.go
providers/gcp/resources/logging.go

fixes https://github.com/mondoohq/cnquery/issues/1856

🐛 fix gcp platform family and nil bucket id panic

---

apps/cnquery/cmd/plugin.go
go.mod
go.sum
providers/arista/go.mod
providers/arista/go.sum
providers/aws/go.mod
providers/aws/go.sum
providers/equinix/go.mod
providers/equinix/go.sum
providers/gitlab/go.mod
providers/gitlab/go.sum
providers/opcua/go.mod
providers/opcua/go.sum
providers/recording.go
providers/runtime.go
providers/vcd/go.mod
providers/vcd/go.sum

There are a few things that were wrong when replaying recordings for more discoverable services:
1. Any resource with the ID field would not correctly store or read it from recordings. The ID field can be grabbed from the resource in the recording.
2. Asset detection from recording was very inaccurate when using the Platform.Title. Fix it and make it actually usable.
3. Finally, when cloning runtimes during later stages of the discovery process, we loose all connections from the mock provider. Copy them over.

🐛 get id field from recordings + recording asset detection + runtime cloning

---

providers/os/resources/os.lr
providers/os/resources/os.lr.go
providers/os/resources/port.go

This is a preliminary step: One of the main resources ports is slow is because it is trying to find the process that is connected to each port. This can take a while.
This change is only an initial step, but it makes the process part async and optional. If all you need is a list of open ports, the request is now very fast on linux. It only slows down when you request the process.
We still use the process in the defaults. Additionally the process detection can be massively improved on linux...

⚡ speed up ports under linux

---

providers-sdk/v1/util/version/version.go

1. super long branch names break git, shorten them
2. we still commit everything in the title, but this will move to the body next, as the title is getting out of hand
3. give progress indication for the "git add" step because go-git is surprisingly slow to process this

🐛 support updating all providers in versions helper

---

apps/cnquery/cmd/providers.go
providers/coordinator.go
providers/providers.go

Allows users to install providers by just name or ver
```
➜ ~/go/bin/cnquery providers  install okta@9.0.0                             
→ installing provider 'okta' version=9.0.0
→ successfully installed okta provider path=/Users/preslavgerchev/.config/mondoo/providers/okta version=9.0.0
```
```
➜ ~/go/bin/cnquery providers  install okta@9.0.1
→ installing provider 'okta' version=9.0.1
FTL failed to install error="cannot find provider okta-9.0.1 under url https://releases.mondoo.com/providers/okta/9.0.1/okta_9.0.1_darwin_arm64.tar.xz"
```
There's an issue with the CLI pre-processing, I will look into it, seems unrelated to the changes in this PR

✨ Install a specific provider version

---

.github/workflows/providers.yaml
providers/providers.go

This change introduces several improvements to building of providers:
- Only providers which are changed are built.  This is determined by examining the version of each provider in the repo and comparing that version number against that of the latest.json on releases.mondoo.com.  If the number is the same the provider is skipped in the build process.  If it is different the provider is build and deployed.
- Providers are built any time a push to main includes a change in the providers/ directory
- The manual invocation of the workflow includes the ability to forcably build and deploy all providers and also the ability to skip publishing
- Providers that are built but not deployed (such as by forcing a skip such as above) will retain the built artifacts with the job for inspection or …

⭐️ Provider Builder v2

---

go.mod
go.sum
motor/discovery/gitlab/gitlab.go
motor/providers/gitlab/platform.go
motor/providers/gitlab/provider.go
resources/packs/gitlab/gitlab.go

to test
```
export MONDOO_CONFIG_BASE64=xxx
go run apps/cnspec/cnspec.go scan gitlab --group mondoolabs --token TOKEN
```

🧹 update gitlab dep to latest and clean up the code

---

providers/terraform/resources/tfplan.go

Happens when we call plan resources without operating on a Terraform plan. This needs better handling for unsupported or invalid data. I strongly recommend we instead inform users that there are no plan files via an error in the future. For now, create compatibility with v8 to get it release-ready.
Fixes https://github.com/mondoohq/cnquery/issues/1866

🐛 avoid crashing terraform on unsupported plan calls

---

providers/gcp/resources/logging.go

Fixes https://github.com/mondoohq/cnquery/issues/1931

🐛 Avoid setting values to nil on GCP logging resource

---

providers/os/detector/detector_all.go
providers/os/resources/packages/aix_packages.go
providers/os/resources/packages/aix_packages_test.go
providers/os/resources/packages/packages.go
providers/os/resources/packages/testdata/packages_aix.txt
providers/os/resources/services/aixlssrc.go
providers/os/resources/services/aixlssrc_test.go
providers/os/resources/services/manager.go

Display asset information:
```
cnquery> asset { name platform version arch }
asset: {
version: "7.2"
arch: "powerpc"
platform: "aix"
name: "p1280-pvm1"
}
```
List packages:
```
cnquery> packages
packages.list: [
0: package name="GSKit8.gskcrypt32.ppc.rte" version="8.0.50.88"
1: package name="GSKit8.gskcrypt64.ppc.rte" version="8.0.50.88"
2: package name="GSKit8.gskssl32.ppc.rte" version="8.0.50.88"
3: package name="GSKit8.gskssl64.ppc.rte" version="8.0.50.88"
4: package name="ICU4C.rte" version="7.2.5.0"
5: package name="adde.v2.common.rte" version="7.2.0.0"
6: package name="adde.v2.ethernet.rte" version="7.2.5.200"
7: package name="adde.v2.rdma.rte" version="7.2.2.0"
8: package name="bos.64bit" version="7.2.5.201"
9: package name="bos.acct" version="7.2.5.200"
10: package …
```

⭐️ IBM AIX support

---

providers/k8s/resources/ingress.go
providers/k8s/resources/k8s.lr
providers/k8s/resources/k8s.lr.go

🐛 Fix k8s.ingress certificates

---

.github/.goreleaser-unstable.yml
.github/workflows/goreleaser.yml

release containers for unstable versions

✨ goreleaser docker unstable

---

providers/gcp/config/config.go
providers/k8s/config/config.go
providers/os/config/config.go
providers/terraform/config/config.go

🎉 gcp-9.0.2, k8s-9.0.2, os-9.0.4, terraform-9.0.3

---

cli/providers/providers.go

Allows disabling the update for providers by setting the env var `MONDOO_AUTO_UPDATE=false`

✨ handle auto update configuration for providers

---

.github/workflows/pr-test-lint.yml
providers/aws/connection/awsec2ebsconn/destroy.go
providers/aws/connection/awsec2ebsconn/provider.go
providers/aws/connection/awsec2ebsconn/setup.go
providers/aws/provider/provider.go

fixes https://github.com/mondoohq/cnquery/issues/1847
i don't love what i had to do to actually have all the info i needed to complete the shutdown - i had to copy a bunch of information that is usually on the provider to the asset connection options bc i was losing all the info on the provider by the time i get here...
```
cnquery> asset { platform version ids }
DBG starting query execution qrid=EmKggjLCPHY=
DBG finished query execution qrid=EmKggjLCPHY=
DBG bQqpVQgYCCh7C/Xkwh4dH/57nw0MiMSTXN4GoxUJz4PeyJsL2T2yg81qBXbpX9TR+kRYRrEBOCJfeiDkxt4LRg== finished
DBG graph has received all datapoints
asset: {
version: "22.04"
platform: "ubuntu"
ids: [
0: "//platformid.api.mondoo.app/runtime/aws/ec2/v1/accounts/367400545713/regions/us-east-1/instances/i-09739098c40b6df84"
]
}
cnquery> exit
DBG …
```

🐛 ensure aws ebs scan cleans up after itself

---

apps/cnquery/cmd/login.go
apps/cnquery/cmd/status.go

This change fixes a panic during login when the token is invalid. It also changes the fatal logging to pure warn with os exit.
```
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x104c16f70]
go.mondoo.com/ranger-rpc.(*Client).DoClientRequest(0x140002e8b80, {0x1056222a0?, 0x105fdeae0}, {0x10560f8f8, 0x14000732ff0}, {0x14000734220, 0x1e}, {0x105610598, 0x14000733230}, {0x1056105b8, ...})
/Users/chris/go/pkg/mod/go.mondoo.com/ranger-rpc@v0.5.1/client.go:65 +0x2a0
go.mondoo.com/cnquery/providers-sdk/v1/upstream.(*AgentManagerClient).PingPong(0x140002e8b80, {0x1056222a0, 0x105fdeae0}, 0x14000732ff0?)
/Users/chris/go/src/go.mondoo.com/cnquery/providers-sdk/v1/upstream/upstream.ranger.go: …
```

🧹 fix panic during login with wrong token

---

cli/providers/providers.go

We were getting errors for commands that had not been pre-processed, like `login --token`.
This PR changes the CLI pre-processor and makes it traverse the root command to find all possible flags across any command and add them to the pre-processing flags. This avoid the warning/error.
Addresses parts of: https://github.com/mondoohq/cnquery/pull/1965
namely: `! CLI pre-processing encountered an issue error="unknown shorthand flag: 't' in -t"`

🐛 pre-process all CLI flags

---

.vscode/launch.json
apps/cnquery/cmd/status.go
cli/sysinfo/sysinfo.go
providers/os/connection/mock/mock.go
providers/os/resources/networkinterface/hostip.go
providers/os/resources/networkinterface/interface.go
providers/os/resources/networkinterface/interface_test.go
providers/os/resources/networkinterface/testdata/linux.toml
providers/os/resources/networkinterface/testdata/linux_flannel.toml
providers/os/resources/networkinterface/testdata/linux_remote.toml
providers/os/resources/networkinterface/testdata/macos.toml
providers/os/resources/networkinterface/testdata/windows.toml

This PR does:
- switches `asset { * }` to a specific asset query
- detects id and platform so that users see that information for managed clients
- adds ip detection
As follow up, we need to ensure that os plugins are dynamically installed on first run

🐛 fix logjn

---

go.sum
providers/gitlab/config/config.go
providers/gitlab/connection/connection.go
providers/gitlab/provider/provider.go
providers/gitlab/resources/gitlab.go

Add discovery options to GitLab provider.
Example:
```bash
cnquery run gitlab --group mondoolabs --discover projects
```
We also support `--discover groups` if you want to add the affected group to the set as well.

⭐ gitlab provider with discovery

---

providers/gitlab/resources/gitlab.go
providers/gitlab/resources/gitlab.lr.go

```
cnquery shell gitlab --group example --discover projects
→ selected asset asset="GitLab Project test-public" selection=0
→ connected to GitLab Project
cnquery> gitlab.project
gitlab.project: gitlab.project fullName="example / test-public" webURL="https://gitlab.com/example/test-public"
```

🧹 initialize gitlab project

---

providers/k8s/resources/discovery.go

in v8 containers aren't discovered with the `auto` flag

🧹 do not discover containers with auto discovery for k8s

---

providers/terraform/provider/detector.go
providers/terraform/provider/detector_test.go

This is a followup to https://github.com/mondoohq/cnquery/pull/1975
```
cnquery shell gitlab --group example --discover terraform 
Available assets                                                               
> 1. Terraform Static Analysis example/example-gitlab (terraform-hcl)         
2. Terraform Static Analysis example/example-playground (terraform-hcl)     
3. Terraform Static Analysis example/example-code (terraform-hcl) 
4. Terraform Static Analysis example/example-demo-environment (terraform-hcl)            
```

⭐️ unique platform id for terraform when used with git

---

providers/gitlab/provider/discovery.go
providers/gitlab/provider/provider.go
providers/gitlab/resources/gitlab.go

- i wanted to also update the tf platform ids for v8 compatibility, but it's not working well - something in the reconnect is returning the incorrect id when i try that, so left that out for now
- there's an error when scanning against the server. this exists on main, i couldn't track it down quite yet, but will look later today:
```
Terraform Static Analysis mondoolabs/example-gitlab          ────────────────────────────────────────────────────────────────────────────────────────────────────────   0%
... 4 more assets ...
0/5 scanned                                                  ────────────────────────────────────────────────────────────────────────────────────────────────────────   0%
[signal SIGSEGV: …
```

✨ support gitlab conn with no group or project defined

---

providers/terraform/resources/hcl.go
providers/terraform/resources/terraform.lr
providers/terraform/resources/terraform.lr.go
providers/terraform/resources/terraform.lr.manifest.yaml

Easy accessor for the terraform backend settings.
Note: The Terraform provider needs get its testing extended considerably, which is when we will expand testing for these fields as well.
Note2: The backend settings are pulled in, but backend settings blocks are a different story.

✨ terraform.settings.backend

---

cli/providers/providers.go
cli/sysinfo/sysinfo.go
providers/providers.go
providers/runtime.go

Both commands need to get system infos at the start. Without the os provider this is not possible (at the time of writing).
This PR also clarifies how the method `EnsureProviders` works and makes the list of existing providers optional.

🐛 download os provider for login+status

---

llx/builtin_simple.go
mql/mql_test.go

The binding is non-null, we need to compare the value, not the binding struct.

🐛 resource == null fixed

---

apps/cnquery/cmd/scan.go
explorer/bundle.go

We may not always have all providers installed. When we run against an upstream server we only deal with the resolved bundle, which usually is sufficient to filter out anything we cannot run. However, with local bundles this is different. Especially when we pull bundles and compile them locally, they may contain a lot of things that the system has no provider for.
This PR filters out anything from the local execution that is not covered by the currently supported providers. These are tied to the active connection.
Before:
After:

🐛 only scan local queries that are supported

---

providers/arista/config/config.go
providers/aws/config/config.go
providers/azure/config/config.go
providers/equinix/config/config.go
providers/gcp/config/config.go
providers/github/config/config.go
providers/gitlab/config/config.go
providers/google-workspace/config/config.go
providers/ipmi/config/config.go
providers/k8s/config/config.go
providers/ms365/config/config.go
providers/oci/config/config.go
providers/okta/config/config.go
providers/opcua/config/config.go
providers/os/config/config.go
providers/slack/config/config.go
providers/terraform/config/config.go
providers/vcd/config/config.go
providers/vsphere/config/config.go

arista-9.0.3, aws-9.0.4, azure-9.0.3, equinix-9.0.2, gcp-9.0.3, github-9.0.3, gitlab-9.0.3, google-workspace-9.0.2, ipmi-9.0.2, k8s-9.0.5, ms365-9.0.2, oci-9.0.3, okta-9.0.4, opcua-9.0.3, os-9.0.6, slack-9.0.3, terraform-9.0.5, vcd-9.0.3, vsphere-9.0.3

🎉 update providers

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_ec2.go

fixes https://github.com/mondoohq/cnquery/issues/1643
```
cnquery> aws.ec2.instances.where( state == "stopped" && stateTransitionTime < time.now - 30*time.day ) { stateTransitionTime state }
DBG starting query execution qrid=GVd0vsyNOBE=
DBG daWNxyu0vy7M7lY62/znQoeC7D1caKIBbTICbdCMxXLPeSZenpEA2Hv493wQCmUoGwR9Pwvs/UqXYtNXYMHJvg== finished
DBG graph has received all datapoints
DBG finished query execution qrid=GVd0vsyNOBE=
aws.ec2.instances.where: [
0: {
state: "stopped"
stateTransitionTime: 2023-08-11 16:30:16 -0600 MDT
}
1: {
state: "stopped"
stateTransitionTime: 2022-09-30 09:16:03 -0600 MDT
}
2: {
state: "stopped"
stateTransitionTime: 2022-09-30 09:15:58 -0600 MDT
}
3: {
state: "stopped"
stateTransitionTime: 2022-05-11 03:23:47 -0600 MDT
}
4: {
state: "stopped"
stateTransitionTime: …
```

✨ add state transition time to aws ec2 instance

---

providers/ipmi/config/config.go
providers/ipmi/main.go
providers/ipmi/provider/provider.go

```
cnquery shell ipmi ADMIN@0.0.0.0 --password 'ADMIN'
→ connected to IPMI
cnquery> ipmi.guid
ipmi.guid: "A123456789AB"
cnquery> ipmi.deviceID
ipmi.deviceID: {
additionalDeviceSupport: {
bridge: false
chassisDevice: true
fruInventoryDevice: true
ipmbEventGenerator: false
ipmbEventReciever: true
sdrRepositoryDevice: true
selDevice: true
sensorDevice: true
}
deviceAvailable: true
deviceID: 0.000000
deviceRevision: 3.000000
firmwareRevision: "9.08"
ipmiVersion: 2.000000
manufacturerID: 4753.000000
manufacturerName: "Unknown"
productID: 3842.000000
productName: "Unknown" …
```

🐛 fix ipmi cli

---

providers/opcua/config/config.go
providers/opcua/main.go

```
cnquery shell opcua --endpoint opc.tcp://localhost:50000
→ connected to OPC UA
cnquery> googleworkspace.user
cnquery> opcua.root
opcua.root: opcua.node id="i=84" name="Root"
cnquery> opcua.root { * }
opcua.root: {
id: "i=84"
dataType: ""
description: ""
max: ""
properties: []
namespace: opcua.namespace id = opcua.namespace/0
min: ""
components: []
writeable: false
name: "Root"
organizes: [
0: opcua.node id="i=85" name="Objects"
1: opcua.node id="i=86" name="Types"
2: opcua.node …
```

🧹 update opcua subcommand help

---

providers/gitlab/resources/gitlab.go

fixes the issue in the gitlab api that it cannot work with int64 but only int project ids:
```
cnquery> gitlab.group { * }
* invalid ID type 123456, the ID must be an int or a string
```

🐛 fix gitlab project detection

---

providers/aws/resources/aws.lr.go
providers/aws/resources/aws_vpc.go

Found this bug during #1827 
Before 
```
aws.vpcs.where[0].routeTables: [
0: aws.vpc.routetable id="rtb-0d28b6f55dfe767c2"
1: aws.vpc.routetable id="rtb-0d28b6f55dfe767c2"
]
```
Shows the same id twice
After
```
aws.vpcs.where[0].routeTables: [
0: aws.vpc.routetable id="rtb-0d28b6f55dfe767c2"
1: aws.vpc.routetable id="rtb-0952ff3c9d1568369"
]
```

🐛 Fix AWS VPC routetable id

---

apps/cnquery/cmd/plugin.go
cli/providers/providers.go
explorer/scan/local_scanner.go
providers/coordinator.go
providers/defaults.go
providers/extensible_schema.go
providers/runtime.go

We minimize runtime creation as much as we can in this iteration.
1. Whenever an existing runtime connects to an asset (and collects identifying information about the asset like platform identifiers or MRN), it can be re-used in subsequent runs with the same asset. Discovery runs provide assets with discovery information, so they can be re-used. 
2. Runtimes that never connect to assets (like the initial runtime on a scan) will be discarded. There are very few of these.
3. On re-use, the provider-discovery is not necessary anymore, saving more calls.

⚡ re-use runtimes across providers

---

providers/coordinator.go

I messed this up in a previous PR, time to fix it!

🐛 runtime starts should be debug messages

---

go.mod
providers-sdk/v1/util/version/version.go

after #2001
Ensure all providers have an up-to-date go mod:
```
version mod-tidy providers/*/
→ Running 'go mod tidy' for providers/arista/...
→ Running 'go mod tidy' for providers/aws/...
→ Running 'go mod tidy' for providers/azure/...
→ Running 'go mod tidy' for providers/core/...
→ Running 'go mod tidy' for providers/equinix/...
→ Running 'go mod tidy' for providers/gcp/...
→ Running 'go mod tidy' for providers/github/...
→ Running 'go mod tidy' for providers/gitlab/...
→ Running 'go mod tidy' for providers/google-workspace/...
→ Running 'go mod tidy' for providers/ipmi/...
→ Running 'go mod tidy' for providers/k8s/...
→ Running 'go mod tidy' for providers/ms365/...
→ Running 'go mod tidy' for providers/network/...
→ Running 'go mod tidy' for providers/oci/...
→ Running 'go mod tidy' …
```

⭐️ simplify provider dep update

---

providers/arista/config/config.go
providers/aws/config/config.go
providers/azure/config/config.go
providers/equinix/config/config.go
providers/gcp/config/config.go
providers/github/config/config.go
providers/gitlab/config/config.go
providers/google-workspace/config/config.go
providers/ipmi/config/config.go
providers/k8s/config/config.go
providers/ms365/config/config.go
providers/oci/config/config.go
providers/okta/config/config.go
providers/opcua/config/config.go
providers/os/config/config.go
providers/slack/config/config.go
providers/terraform/config/config.go
providers/vcd/config/config.go
providers/vsphere/config/config.go

arista-9.0.4, aws-9.0.5, azure-9.0.4, equinix-9.0.3, gcp-9.0.4, github-9.0.4, gitlab-9.0.4, google-workspace-9.0.3, ipmi-9.0.3, k8s-9.0.6, ms365-9.0.3, oci-9.0.4, okta-9.0.5, opcua-9.0.4, os-9.0.7, slack-9.0.4, terraform-9.0.6, vcd-9.0.4, vsphere-9.0.4

🎉 bump provider versions

---

providers-sdk/v1/inventory/inventory.go
providers-sdk/v1/inventory/v8_inventory.go
providers-sdk/v1/util/version/version.go
providers/defaults.go
providers/runtime.go

Connection types were missing and thus caused any request that would look for them to fail. In most cases this is not noticable at all (because you eg connect to github to continue to do things with github as you discover more stuff).
But there is a very nasty case where this hurt: When we are in serve mode and don't have a primary connection that triggers provider installations. In this case we receive asset types (or rather v8 Backend fields!), which then didn't find any way to look up their provider.
So:
1. Add a script to help with defaults generation (it does 80% of the work, you only have to copy it over): ```bash version defaults providers/*/ ```
2. Update all providers with it
3. Support v8 `Backend` field (needs in-depth testing since both fields are not fully compatible; add …

🐛 update provider defaults + missing connection types + v8 compat

---

apps/provider-scaffold/template/provider/provider.go.template

These changes where necessary to make `make provider/build` go through.

🐛 fix provider scaffolding

---

apps/cnquery/cmd/shell.go
providers/ms365/connection/auth.go

Use an inventory to resolve assets before opening a shell. The inventory will ensure that all secrets are processed correctly and that any secrets, specified by a local path (certificates, private keys) are loaded in memory correctly.
This PR also adjusts the ms365 provider slightly by dropping the azure CLI support

🐛 use inventory in shell to resolve credentials properly.

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_vpc.go

Add a few new things for asset inventory:
- CIDR Block
- Instance tenancy settings
```
cnquery> aws.vpcs.first{*}
aws.vpcs.first: {
instanceTenancy: "default"
region: "ap-south-1"
cidrBlock: "172.31.0.0/16"
isDefault: true
state: "available"
arn: "FOO"
id: "vpc-0c67aa67"
flowLogs: []
tags: {}
routeTables: [
0: aws.vpc.routetable id="FOO"
]
}
```

:star: Add new properties to the aws.vpc resource

---

explorer/scan/local_scanner.go
providers-sdk/v1/inventory/asset.go

I am not sure if this is the place to fix this. Maybe indeed it's to have each provider decide that for themselves (whether they want to apply root-level asset labels to discovered assets)

🧹 Apply root-level asset labels to inventory assets.

---

explorer/scan/local_scanner.go
providers/coordinator.go
providers/mock.go
providers/runtime.go

Ephemeral runtimes are used as throw-away runtimes, that come with their own plugin runner (and execution space). These runtimes can be thrown away after they are used, while other runtimes and plugins remain shared.
This is particularly useful when scanning targets with the discover mode, where potentially many runtimes/plugins need to be instantiated on the fly and are only required for the lifetime of the scan.
Ephemeral providers:
1. Have their own plug instance that is not share with any other provider.
2. They can be safely shut down, without impacting other providers.
3. Ephemeral runtimes may spawn additional providers, which are shared in nature. On shutdown of ephemeral providers these shared providers are not closed.
4. Non-ephemeral plugin instances are now only destroyed when …

⭐ support ephemeral vs normal runtimes

---

providers/aws/config/config.go
providers/github/config/config.go
providers/gitlab/config/config.go
providers/k8s/config/config.go
providers/ms365/config/config.go

🎉 aws-9.0.6, github-9.0.5, gitlab-9.0.5, k8s-9.0.7, ms365-9.0.4

---

logger/cliwriter.go

remove special because winrm ps remote is crashing on UTF characters

🧹 fix logging for windows cli output via powershell remoteing

---

providers/os/connection/docker_container.go
providers/os/provider/provider.go

Fixes #2040 
The following are now supported:
```
~/go/bin/cnquery shell docker pensive_boyd // by container name
~/go/bin/cnquery shell docker 7b486842ac61 // by container id
~/go/bin/cnquery shell docker debian:11 // by image tag
~/go/bin/cnquery shell docker 3a30687df9b732bb88601b6c6c7866d632d5c9d4260cc7ec0fd575abffbbee32 // by image digest
~/go/bin/cnquery shell docker container pensive_boyd // by container name
~/go/bin/cnquery shell docker container 7b486842ac61 // by container id
```
I split off the `ParseCLI` logic for `container` and `docker` as having `docker container` makes sense whereas `container container` is not logical, `cnquery shell container <id>` should work just like `cnquery shell docker container <id>`

🐛 Fix docker connection to support specifying either an image or a container.

---

providers/aws/resources/aws.lr

This PR updates the default fields for AWS Security Group IP permissions to make the findings more actionable.
```
21: {
ipPermissionsEgress: [
0: aws.ec2.securitygroup.ippermission id="sg-6b43f159-0-egress"
]
vpc: aws.vpc arn="arn:aws:vpc:us-west-2:177043752222:id/vpc-ffa52222" isDefault=true
tags: {}
name: "default"
description: "default VPC security group"
id: "sg-6b432222"
ipPermissions: [
0: aws.ec2.securitygroup.ippermission id="sg-6b432222-0"
]
arn: "arn:aws:ec2:us-west-2:177043759222:security-group/sg-6b432222"
isAttachedToNetworkInterface: false
}
```
```
21: {
tags: {}
name: "default"
ipPermissionsEgress: [
0: aws.ec2.securitygroup.ippermission id="sg-6b43f159-0-egress" toPort=0 fromPort=0 ipProtocol="-1" ipRanges=[
0: "0.0.0.0/0"
] ipv6Ranges=[]
] …
```

Updates AWS ipPermissions defaults to include more fields

---

llx/data_conversions.go
providers/ms365/resources/devicemanagement.go

Undoes #2061 and fixes #2046 properly

🧹 Remove int32 llx support, ensure ms365 device configurations uses int64

---

explorer/scan/local_scanner.go

run scan with --incognito & no creds to the platform present to test

🐛 fix incognito flag failing out when no creds to platform

---

mqlc/mqlc.go
providers-sdk/v1/lr/go.go
providers-sdk/v1/plugin/runtime.go
providers/terraform/resources/hcl.go
providers/terraform/resources/terraform.lr
providers/terraform/resources/terraform.lr.go
providers/terraform/resources/terraform.lr.manifest.yaml

Support both string and regex filters for easily accessing all the resources that you need via their label.

⭐ terraform.resources( filter )

---

motor/discovery/aws/ecr.go

🧹 allow scanning untagged ecr images

---

providers/k8s/connection/api/connection.go
providers/k8s/provider/provider.go

makes sure the discovery cache is shared for a provider instance. Right now, we don't re-use the provider instance yet, but we should adjust it for the future

🧹 share k8s discovery cache within a provider instance

---

providers/aws/connection/connection.go
providers/aws/provider/provider.go

Follows the pattern of the slack mock connection. Similar to slack, this pattern is not fully streamlined yet. I'll add that in a follow-up shortly, for now this works great :)
Now you can:
```
cnquery shell mock --use-recording recording.json 
```

✨ add aws mock connection

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws_s3.go

The ID needs to be assigned after parsing at the moment. This is probably better stored in the generate file, but for now the manual assignment fixes things.

🐛 fix empty aws.s3.bucket.policy + 🐛 fix its ID

---

explorer/scan/local_scanner.go

✨ re-use provider instance for all assets when scanning k8s

---

providers/assets.go

🐛 Continue scanning when connect to one asset fails

---

providers/aws/resources/aws.lr.go
providers/aws/resources/aws_cloudwatch.go
providers/aws/resources/aws_ec2.go
providers/aws/resources/aws_iam.go
providers/aws/resources/aws_sns.go
providers/terraform/resources/hcl.go

fixes https://github.com/mondoohq/cnquery/issues/2044
run cnquery scan aws and cnquery scan terraform against the server with the asset overview policy is now error free
fixes https://github.com/mondoohq/cnquery/issues/2003

🐛 aws and terraform resource fixes

---

providers-sdk/v1/util/configure/configure.go

```
go run ./providers-sdk/v1/util/configure/configure.go -f providers.yaml -o providers/builtin_dev.go
→ (1/3) configured builtin providers path=providers/builtin_dev.go providers=["google-workspace"]
DBG build provider 1/1 provider=google-workspace
→ (2/3) built providers providers=["google-workspace"]
DBG go mod tidy
→ (3/3) rewired dependencies/files path=providers/builtin_dev.go providers=["google-workspace"]
```

🐛 Fix providers-sdk configure to support providers with dashes in their name.

---

providers/builtin_dev.go
providers/os/resources/files.go

This caused the error:
```coffee
cnspec> files.find(from: "/", type: "file", regex: ".*keychains.*")
* file does not exist
files.find.list: [
0: file path="" size=0 permissions.string=no data available
]
```
With this update it behaves correctly:
```coffee
cnspec> files.find(from: "/", type: "file", regex: ".*keychains.*")
files.find.list: []
```
Additionally I commented out the builtin os provider for much easier use (avoid uncommenting 3 sections, just uncomment it all).

🐛 find.files with no results fixed

---

providers/aws/config/config.go
providers/azure/config/config.go
providers/gcp/config/config.go
providers/ms365/config/config.go
providers/oci/config/config.go
providers/os/config/config.go
providers/terraform/config/config.go
providers/vcd/config/config.go

🎉 aws-9.0.9, azure-9.0.6, gcp-9.0.6, ms365-9.0.6, oci-9.0.6, os-9.0.9

---

providers/aws/config/config.go
providers/k8s/config/config.go

🎉 aws-9.0.11, k8s-9.0.11

---

providers/gcp/config/config.go
providers/os/config/config.go
providers/terraform/config/config.go

🎉 gcp-9.0.8, os-9.0.11, terraform-9.0.10

---

README.md
apps/cnquery/cmd/root.go

We're not using the fleet word anymore. Update to infrastructure to match the same change we made in v8

Update cnquery description from fleet -> infra

---

Makefile
providers/terraform/resources/terraform.lr.manifest.yaml

Fix the path to the LR docs for Google Workspace and regenerate the LR file for TF with the latest platform mapping

Fix google workspace and tf mql docs generation

---

providers/aws/resources/aws_es.go

Closes #2114 
Before
```
cnquery> aws.es.domains{*}
* cannot convert primitive with NO type information
aws.es.domains: [
0: {
nodeToNodeEncryptionEnabled: cannot convert primitive with NO type information
tags: cannot convert primitive with NO type information
arn: cannot convert primitive with NO type information
encryptionAtRestEnabled: cannot convert primitive with NO type information
endpoint: cannot convert primitive with NO type information
region: "eu-central-1"
name: "test"
}
]
```
After
```
cnquery> aws.es.domains{*}
aws.es.domains: [
0: {
nodeToNodeEncryptionEnabled: true
tags: {}
arn: "arn:aws:es:eu-central-1:345411212130:domain/test"
encryptionAtRestEnabled: true
endpoint: ""
region: "eu-central-1"
name: "test"
}
]
```
Problem was that `initAwsEsDomains` was …

🐛 fix aws es domains resource

---

providers/coordinator.go

make sure the new properties are wiped too when the coordinator shuts down

🐛 properly shutdown coordinator

---

providers/aws/config/config.go
providers/gitlab/config/config.go
providers/network/config/config.go
providers/terraform/config/config.go

🎉 aws-9.0.12, gitlab-9.0.7, network-9.0.4, terraform-9.0.11

---

explorer/scan/local_scanner.go

Make sure we clean the running providers after a scan. This change is already present in cnspec but was forgotten here

🧹 shutdown coordinator after a scan

---

cli/providers/providers.go

Closes #2118 
Each target that had an Alias, such as k8s and kubernetes, would show up once for each alias in `cnquery scan --help`.
Before:
```
Available Commands:
container   Scan a running container or container image
docker      Scan a running docker or docker image
filesystem  Scan a mounted file system target test.
filesystem  Scan a mounted file system target test.
k8s         Scan a Kubernetes cluster or local manifest file(s).
k8s         Scan a Kubernetes cluster or local manifest file(s).
local       Scan your local system
mock        Scan use a recording without an active connection
ssh         Scan a remote system via SSH
vagrant     Scan a Vagrant host
winrm       Scan a remote system via WinRM
```
After:
```
Available Commands:
container   Scan a running container or …
```

🐛 fix scan --help duplicates scan targets

---

cli/providers/providers.go
providers/defaults.go

Closes #2103 
We could also temporarily allow the old id as well to make upgrade smoother for beta users

🐛 fix temp v9 os provider upgrade

---

providers/terraform/resources/hcl.go
providers/terraform/resources/terraform.lr
providers/terraform/resources/terraform.lr.go
providers/terraform/resources/terraform.lr.manifest.yaml

Discover all related resources of a given terraform resource. Additionally overhaul the internal discovery of all terraform blocks and reduce the amount of repetition drastically.
For example, given the following Terraform snippet:
```hcl
resource "aws_iam_role" "dev-resources-iam-role" {
name        = "SSM-role-${local.name}-${random_string.suffix.result}"
}
resource "aws_iam_instance_profile" "dev-resources-iam-profile" {
name = "ec2_ssm_profile-${local.name}-${random_string.suffix.result}"
role = aws_iam_role.dev-resources-iam-role.name
}
```
Using this MQL:
```coffee
terraform.resources { 
nameLabel 
related { 
nameLabel
} 
}
```
We get:
```coffee
terraform.resources: [
0: {
nameLabel: "aws_iam_instance_profile"
related: [
0: {
nameLabel: "aws_iam_role"
}
]
}
1: {
nameLabel: …
```

⭐ terraform.resources { related } support

---

cli/providers/providers.go

Early runtime checks can cause providers to switch. For example: A user may start with the `aws` provider, but really want to user the `os` provider to scan an instance in AWS:
```bash
cnquery shell aws ec2 instance-connect ec2-user@i-1234abc --region us-east-1 --profile home
```
In the above example, we use the `aws` provider to parse the CLI. However, after that it's all about handing off the actual asset to the `os` provider to execute the scan.
Related to https://github.com/mondoohq/cnquery/issues/2166

🐛 switch providers after CLI parsing

---

providers/google-workspace/resources/reports.go
providers/google-workspace/resources/users.go

Fixes #2073 
Try and retrieve the report usage for each day, going back a week. If data is present, we return that.
Minor code cleanup by using the time.DateOnly format, available since go 1.20

🐛 Fix retrieval of report usage by going back a week.

---

providers/slack/resources/slack.lr

This will make the results of user queries actionable by giving an actual username instead of just an ID

Add username to the slack.user resource defaults

---

providers-sdk/v1/plugin/start.go
providers/network/config/config.go
providers/runtime.go

i haven't been able to find a good policy with examples of the os + network resources so i didn't do the cross provider types thing yet, im just skipping over the check if its network or core. gonna go find a test example for the network stuff now
```
with this branch, reporting upstream, and all providers installed:
`DEBUG=1 go run apps/cnquery/cnquery.go scan local  2.71s user 1.89s system 39% cpu 11.757 total`
`DEBUG=1 go run apps/cnspec/cnspec.go scan local  4.12s user 3.00s system 42% cpu 16.767 total`
```
im not patient enough to time out the version of this scan on main. i can say its more than 5 minutes for sure.

🐛 hot fix for too long upstream scan time

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_apigateway.go
providers/aws/resources/aws_applicationautoscaling.go
providers/aws/resources/aws_cloudtrail.go
providers/aws/resources/aws_cloudwatch.go
providers/aws/resources/aws_config.go
providers/aws/resources/aws_dms.go
providers/aws/resources/aws_dynamodb.go
providers/aws/resources/aws_ec2.go
providers/aws/resources/aws_efs.go
providers/aws/resources/aws_eks.go
providers/aws/resources/aws_elasticache.go
providers/aws/resources/aws_kms.go
providers/aws/resources/aws_lambda.go
providers/aws/resources/aws_rds.go
providers/aws/resources/aws_redshift.go
providers/aws/resources/aws_vpc.go

* Improve logging for all AWS client calls. This is useful when debugging to see what API calls are going out to see where the problem might be
* Make sure we only load an instance's VPC if actually requested, i.e. compute it once needed. To do so, I've added a `vpcArn` field that holds the vpc's ARN and can be used to request it

🧹 Improve debug logging for AWS calls, do not fetch ec2's instance VPC if not needed

---

providers/ms365/resources/applications.go
providers/ms365/resources/ms365.lr
providers/ms365/resources/ms365.lr.go
providers/ms365/resources/ms365.lr.manifest.yaml
providers/ms365/resources/serviceprincipals.go

Add support for `microsoft.enterpriseApplications`, which is a list of service principals with a special tag

✨ Add more fields to microsoft.serviceprincipal, retrieve enterprise applications

---

providers/terraform/resources/hcl.go

When reading a plan file, we do not get all the HCL bits. However, users may still call some of the resources like they would in v8 terms:
```coffee
cnquery> terraform.files
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc0f420]
goroutine 5 [running]:
github.com/hashicorp/hcl/v2/hclparse.(*Parser).Files(0xc000258718?)
/home/runner/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.18.1/hclparse/parser.go:137
go.mondoo.com/cnquery/v9/providers/terraform/resources.(*mqlTerraform).files(0xc0001b4600)
/home/runner/_work/cnquery/cnquery/providers/terraform/resources/hcl.go:39 +0x45
go.mondoo.com/cnquery/v9/providers/terraform/resources.(*mqlTerraform).GetFiles.func1()
...
```
This crash can be prevented by …

🐛 prevent crash on tf plan

---

Makefile

This has been bugging me, since I often build + install providers as a santiy check before releases (i.e. not as a builtin; let's call it overly cautious).
The new structure mirrors `make providers/build/X` and is a nice complement. Only annoying part is having to line the extra lines for each provider, but it's also easy and straightforward to copy.

🧹 make providers/install/X for inidivual providers

---

.github/actions/spelling/expect.txt
providers/network/resources/http.go
providers/network/resources/network.lr
providers/network/resources/network.lr.go
providers/network/resources/network.lr.manifest.yaml

After: https://github.com/mondoohq/cnquery/pull/2211
adds:
- X-Frame-Options
- X-XSS-Protection
- X-Content-Type-Options
- Referrer-Policy
```coffee
http.get('https://console.mondoo.com') { version header{ xFrameOptions xXssProtection xContentTypeOptions referrerPolicy }}
```
```coffee
http.get: {
header: {
xContentTypeOptions: "nosniff"
referrerPolicy: "same-origin"
xFrameOptions: "SAMEORIGIN"
xXssProtection: http.header.xssProtection enabled=true mode="block" report=null
}
version: "2.0"
}
```
... getting closer to CSP
kudos @benr

✨ more HTTP security headers

---

llx/builtin.go
mql/mql_test.go

We have fairly consisten null-chaining already:
```coffee
cnquery> parse.json("dummy.json").params.nothere
parse.json.params.nothere: null
cnquery> parse.json("dummy.json").params.nothere + 1
parse.json.params.nothere.+: null
cnquery> parse.json("dummy.json").params.nothere.field == empty
[ok] value: _
```
However, it turns out we didn't correctly chain resources:
```coffee
cnquery> http.get.header.setCookie
http.get.header.setCookie: null
cnquery> http.get.header.setCookie.name
cannot cast resource to resource type: <nil>
```
This PR fixes the behavior to be more in line with null-chaining:
```coffee
cnquery> http.get.header.setCookie
http.get.header.setCookie: null
cnquery> http.get.header.setCookie.name
http.get.header.setCookie.name: null
cnquery> http.get.header.setCookie { name } …
```

🐛 support chaining of null resources

---

providers/network/resources/http.go
providers/network/resources/network.lr
providers/network/resources/network.lr.go
providers/network/resources/network.lr.manifest.yaml

After https://github.com/mondoohq/cnquery/pull/2215
Note: all of these HTTP headers are still experimental for the time being.
I'll likely replace a few types with simpler map implementations. CSP was a good example for this.
```coffee
http.get("https://console.mondoo.com").header.csp
```
```coffee
http.get.header.csp: {
base-uri: "'self'"
block-all-mixed-content: ""
connect-src: "'self' mondoo.com *.mondoo.com *.google-analytics.com *.googleapis.com sentry.io *.doubleclick.net https://heapanalytics.com https://hubspot-forms-static-embed-eu1.s3.amazonaws.com https://forms-eu1.hsforms.com https://mondoo.statuspage.io https://status.mondoo.com https://us.api.mondoo.com"
font-src: "'self' data: fonts.gstatic.com https://heapanalytics.com"
form-action: "'self' https://forms-eu1.hsforms.com" …
```

✨ add CSP header support

---

providers/network/resources/http.go
providers/network/resources/network.lr.manifest.yaml

After https://github.com/mondoohq/cnquery/pull/2213
yeah i'm chaining a few...
i.e.:
```bash
> cnquery shell host console.mondoo.com
```
Then:
```coffee
http.get { version header url }
```
```coffee
http.get: {
header: http.header
url: url string="http://console.mondoo.com:80"
version: "2.0"
}
```
@scottford-io this fixes one of the problems you raised in https://github.com/mondoohq/cnquery/pull/2213#issuecomment-1763188304

🐛 support http.get on host connection

---

providers/network/provider/provider.go
providers/network/resources/http.go

After https://github.com/mondoohq/cnquery/pull/2220
The network provider had a small workaround for schemes to guess if we
were dealing with HTTP or HTTPS. However, this is not safe to use
outside of the two standard ports (80=http, 443=https).
I noticed that the `Runtime` field was unused for network connections.
This change uses this field to retain the "runtime of the network
connection". Users can choose to specify or not specify it. The host
provider works perfectly well without specifying it of course.
Examples:
```coffee
> cnquery run host mondoo.com -c "http.get { statusCode version url }"
http.get: {
statusCode: 200
url: url string="http://mondoo.com:80"
version: "2.0"
}
```
With scheme, default ports are guessed:
```coffee
> cnquery run host https://mondoo.com -c "http.get { …
```

✨ retain host scheme in network provider

---

providers/aws/config/config.go
providers/aws/connection/connection.go
providers/aws/provider/provider.go
providers/aws/resources/discovery.go
providers/aws/resources/discovery_test.go

i don't love the strict, hidden syntax im using to parse this all from the cli...but it does work. 
open to ideas on how to improve! 
i need filtering for the lambda (we had ec2 filtering in v8)
```
go run apps/cnquery/cnquery.go shell aws --discover instances  --filters ec2:region=us-east-2
go run apps/cnquery/cnquery.go shell aws --discover lambda-functions  --filters all:region=us-east-2
```

✨ add filters to aws discovery

---

providers/network/resources/http.go

If they are not present, set them to null instead of empty string
As reported by @tas50

🐛 set referrerPolicy+xContentType to null

---

providers/arista/config/config.go
providers/atlassian/config/config.go
providers/aws/config/config.go
providers/azure/config/config.go
providers/core/config/config.go
providers/equinix/config/config.go
providers/gcp/config/config.go
providers/github/config/config.go
providers/gitlab/config/config.go
providers/google-workspace/config/config.go
providers/ipmi/config/config.go
providers/k8s/config/config.go
providers/ms365/config/config.go
providers/network/config/config.go
providers/oci/config/config.go
providers/okta/config/config.go
providers/opcua/config/config.go
providers/os/config/config.go
providers/slack/config/config.go
providers/terraform/config/config.go
providers/vcd/config/config.go
providers/vsphere/config/config.go

arista-9.0.7, atlassian-9.0.1, aws-9.0.16, azure-9.0.11, core-9.0.3, equinix-9.0.6, gcp-9.0.10, github-9.0.9, gitlab-9.0.9, google-workspace-9.0.7, ipmi-9.0.6, k8s-9.0.13, ms365-9.0.10, network-9.0.5, oci-9.0.9, okta-9.0.8, opcua-9.0.7, os-9.0.13, slack-9.0.7, terraform-9.0.15, vcd-9.0.8, vsphere-9.0.7

🎉 update provider versions

---

providers/github/config/config.go

🎉 github-9.0.10

---

providers/os/provider/detector.go

Azure and GCP detect do not provide a name, so do not override with emtpy string.

🐛 Do not override asset name

---

providers/gcp/connection/platform.go
providers/gcp/provider/provider.go

2 important notes:
1. PlatformInfo is currently not used. Give the it the aws provider treatment and
2. Are we setting good platform IDs?
I only see this in provider.go:
```go
asset.PlatformIds = []string{"//platformid.api.mondoo.app/runtime/gcp/"}
```

🐛 fix platform bits for GCP that were missing

---

providers/extensible_schema.go

The core provider is the only special provider in our current list, treated with higher priority.
We are looking to be more explicit about the order in which providers are added and how things are getting merged together. Until we get there, we can force core to at least not be overwritten by another provider.

✨ ensure that the core provider overrides

---

providers/core/provider/provider.go

The init functions have not been called for the core provider because we used CreateResource instead of NewResource

🐛 use NewResource to load init functions in core provider

---

providers/azure/resources/monitor.go

Fixes this:
```
azure.subscription.monitor.diagnosticSettings: [
0: {
type: the 'azure' provider crashed
storageAccount: the 'azure' provider crashed
properties: the 'azure' provider crashed
id: the 'azure' provider crashed
storageAccountId: the 'azure' provider crashed
name: the 'azure' provider crashed
}
]
```
The plugin state was not being checked before trying to construct the storage account

🐛 fix retrieval of azure monitor diagnostic settings and log profiles.

---

cli/printer/mql.go
mqlc/mqlc.go
mqlc/mqlc_stats.go

After https://github.com/mondoohq/cnquery/pull/2290
```bash
cnquery run aws -c 'aws.vpcs.all(flowLogs.any(status == "ACTIVE"))' --info
```
(sorry Tim i really wanted the colors here :grin: )

✨ indicate auto-expanded MQL fields in --info

---

providers/aws/connection/awsec2ebsconn/provider.go
providers/os/connection/snapshot/blockdevices.go

picked up this hint from https://github.com/mondoohq/cnquery/pull/2171
just trying to get the small we-definitely-want-this pieces in to try to break down this ebs scan issue a bit

🐛 ensure ebs connection config has type filesystem

---

providers/atlassian/resources/atlassian.lr
providers/atlassian/resources/atlassian.lr.go
providers/atlassian/resources/atlassian.lr.manifest.yaml
providers/atlassian/resources/atlassian_admin.go

Before:
```
cnquery> atlassian.admin.organization.managedUsers
* cannot convert primitive with NO type information
atlassian.admin.organization.managedUsers: atlassian.admin.organization.managedUsers name=null
```
After:
```
cnquery> atlassian.admin.organization.managedUsers
atlassian.admin.organization.managedUsers: [
0: atlassian.admin.organization.managedUser name="Usr Two"
1: atlassian.admin.organization.managedUser name="Marius K"
2: atlassian.admin.organization.managedUser name="Ben R"
3: atlassian.admin.organization.managedUser name="Test User"
]
```

🐛 fix atlassian managed users

---

providers/coordinator.go
providers/providers.go

Support loading providers without the binary. This is useful in some isolated environments and embedded scenarios, where users may want to use MQL capabilities like compiling/linting, without having or executing the plugin binaries.
This is not something users of cnquery/cnspec will generally use, but it is super useful for embedded and very specialized use-cases. Example:

⭐ schema-only provider support

---

providers/atlassian/connection/scim/connection.go
providers/atlassian/resources/atlassian.lr
providers/atlassian/resources/atlassian.lr.go
providers/atlassian/resources/atlassian_scim.go

Before
```
cnquery> atlassian.scim.users
cannot find resource atlassian.scim.organization.scim.user in this provider
atlassian.scim.users: null
```
After
```
cnquery> atlassian.scim.users
atlassian.scim.users: [
0: atlassian.scim.user displayName="Test User"
1: atlassian.scim.user displayName="Usr Two"
2: atlassian.scim.user displayName="Marius K"
3: atlassian.scim.user displayName="Ben R"
]
```

🐛 fix atlassian scim

---

providers/extensible_schema.go
providers/providers.go
providers/runtime.go

Extensible schemas are used to go across multiple providers and aggregate a schema. We use them extensively, in order to load all available resources and fields. However, if a new provider is installed after a schema has been fully loaded, it won't show up, because the schema doesn't know it has to refresh.
This is now fixed. We keep track of the last time a provider was installed to the system. Whenever that happens, a timestamp is updated. Each extensible schema keeps track of this timestamp. If it changes, the schema gets refreshed.

🐛 provider installation should refresh schema

---

cli/providers/providers.go
cli/sysinfo/sysinfo.go
providers/providers.go
providers/runtime.go

After: https://github.com/mondoohq/cnquery/pull/2305
Refactor the whole EnsureProvider flow so users can specify providers
via ID, connector name and connector type. All of them are useful:
1. Install provider from Defaults => just specify the ID
2. Install provider from CLI args (like "local") => just specify name
3. Install provider from connection type => doh

🔧 expand EnsureProvider to cover IDs

---

providers/providers.go

This fix was required to implement the provider search by id used by https://github.com/mondoohq/cnspec/pull/868

🐛 fix searching providers by id

---

providers/aws/provider/provider.go

Under certain circumstances the discovery has not overwritten the platform id.

🐛 fix aws platform id

---

providers-sdk/v1/testutils/testutils.go
providers/recording.go

A bit simpler approach, compared to #2312 
We already have predefined recordings, which are great, but they cannot be modified in any way. 
This PR lets us create a recording from a simple asset, containing just that asset. It holds no resources/connections on the side, although we can extend
```
myAsset := &inventory.Asset{Name: "my-test"}
recording := testutils.RecordingFromAsset(myAsset)
runtime := testutils.MockFromRecording(recording)
```

✨ Allow creating of a recording from just a single asset.

---

providers-sdk/v1/vault/config.go
providers-sdk/v1/vault/config_test.go

In v8, the inventory proto had its own `VaultConfiguration`
```
message VaultConfiguration {
string name = 1;
string type = 2;
map<string, string> options = 3;
}
```
Note the type here is a string. This meant that we'd usually pass in the string representation of the enum, which is using the auto-generated map, e.g.
```
VaultType_name = map[int32]string{
0: "None",
1: "KeyRing",
2: "LinuxKernelKeyring",
3: "EncryptedFile",
4: "HashiCorp",
5: "GCPSecretsManager",
6: "AWSSecretsManager",
7: "AWSParameterStore",
8: "GCPBerglas",
9: "Memory",
}
```
In v9, we've gotten rid of the the duplicate `VaultConfiguration` in the inventory.proto and it now directly uses the proper config, which is defined (in `vault.proto`) as:
```
message VaultConfiguration {
string name = 1;
VaultType type = 2;
map …
```

🐛 Support protobuf string values for VaultType.

---

explorer/scan/local_scanner.go

In case recording isn't specififed during scanner initialisation, set the NullRecording

🧹 Prevent nil panic when recording is not set

---

providers/os/resources/registrykey.go
providers/os/resources/registrykey_test.go

Adjust the behavior of registry key to be more in line with resources like package, service, and user. If a key is not found, return the empty resource instead of an error, with fields that are null.
Additionally:
- align registrykey getEntries with the exists call
- exit out of registrykey props init earlier
- initialize properties with empty values if requested

✨ be more lenient with errors on registrykey

---

llx/rawdata_json.go

Properly handle cases where the value of `RawData` cannot be parsed
This was present in v8 but wasn't ported to v9

🐛 raw data json err (#1387)

---

providers/runtime.go

In the original design, the connect call would always return the connected asset. However, we have some legacy code that behaved differently in v8. When it was translated to v9, we had to return the fully discovered asset, which is the asset that we actually want to connect.
For now, the connect call will continue to fulfill two functions:
1. discover the actual asset and
2. establish the connection
During this time, we will check once if the provider changed after the connect call and switch providers if that happened.
We want a distinct discover and connect call in the future.
Note:
1. The connect call on the shell behaves differently, happy to adjust it if we need it there too.
2. If additional providers get connected via resources, they do not go through this procedure. This is …

✨🐛 support switching providers post-connect

---

providers/network/resources/tls.go
providers/network/resources/tlsshake/tlsshake.go

TLS checks have a tendency to timeout and hang for a long time, especially when there is nothing listening on a port at all.
This PR introduces a 2sec timeout on all initial OSI L4 connections to make sure the endpoint actually exists.
Additionally it now avoid printing a lot of very cryptic errors for TLS. Instead, this mechanism now returns `null` data if no TLS was detected for any of its fields.

🐛 avoid TLS hangups and errors

---

providers/network/provider/provider.go
providers/network/resources/network.go
providers/network/resources/tls.go

After https://github.com/mondoohq/cnquery/pull/2357
Users sometimes target a system like this:
```
cnquery shell host mondoo.com
```
Question is: What is this? If we connect to it, what do we connect to?
Until now, we'd opt to HTTP, which was of course nice for `http.get`. But it was horrible for `tls`, because it tried to connect on the default HTTP port - definitely not what the user intended.
This new mechanism allows users to skip the scheme and the port and ask the resources to figure out what they want to do with it. For `http` this is something different than for `tls`.
Example:
```
cnquery shell host mondoo.com
```
with the queries:
```coffee
> http.get { version url.string }
http.get: {
url.string: "http://mondoo.com"
version: "2.0"
}
> tls { socket versions }
tls: {
versions: [ …
```

✨ Improve default host handling for no scheme/port

---

providers/network/resources/tls.go
providers/network/resources/tlsshake/tlsshake.go
utils/multierr/errors.go

After https://github.com/mondoohq/cnquery/pull/2358
A valid endpoint with TLS returns very cryptic error messages.
We already handled the case of having no open endpoint in https://github.com/mondoohq/cnquery/pull/2357 . This extends the approach to also work for open endpoints that are not TLS.
OLD:
```coffee
> tls { socket versions }
* 1 error occurred:
* failed to get a TLS response
tls: {
versions: 1 error occurred:
* failed to get a TLS response
socket: socket protocol="tcp" port=80 address="mondoo.com"
}
```
NEW
```coffee
> tls { socket versions }
tls: {
versions: null
socket: socket protocol="tcp" port=80 address="mondoo.com"
}
```

🐛 fix TLS on open endpoint without TLS

---

mqlc/mqlc.go
mqlc/mqlc_test.go
utils/multierr/errors.go

These help us communicate when resources or fields have not been found. They are indications that can be used to infer that providers may be missing on the system.

🧹 introduce structured mqlc errors

---

explorer/bundle.go
explorer/bundle_test.go

Technically adding the filters should happen after the variant queries have been compiled, not before. This aligns with cnspec.
Partly related to the issue below vv
Fixes https://github.com/mondoohq/cnquery/issues/2279

🐛 compile variant queries in bundles earlier

---

providers/azure/resources/azure.lr

This gets us the DB type which was MongoDB in my testing

Add kind to default fields in azure cosmodb

---

providers-sdk/v1/resources/schema.go
providers/coordinator.go
providers/extensible_schema.go
providers/extensible_schema_test.go
providers/mock.go
providers/runtime.go

Currently schemas are loaded in almost random order (except for the core provider). This is problematic if 2 providers provide the same resource, like `asset.eol` which is provided by both `os` and `vsphere`. Since we now have this use-case, it became more important to control the load-order of schemas.
Notes:
1. At the very start we still `loadAllSchemas`. This will be removed in the future because we really don't need all schemas at all times. We also initialize early runtimes that we tend to throw away - so all this work is wasted.
- In this early stage we only prioritize the core provider
2. Once users connect to a provider via `runtime.Connect(..)` it sets the default provider for the runtime. It is also the signal for us to set a priority schema, based on whatever the users …

✨ prioritize connected provider schema

---

apps/cnquery/cmd/bundle.go
apps/cnquery/cmd/login.go
apps/cnquery/cmd/logout.go
apps/cnquery/cmd/root.go
apps/cnquery/cmd/status.go
cli/errors/command_error.go

fixes #2377
remove the `os.Exit` and `log.Fatal` calls from commands and return errors instead
I haven't touched the `scan` command since that one handles the coordinator shutdown inside the scanner itself

🐛 remove os.exit and log.fatal calls

---

cli/errors/command_error.go

A panic is possible because `ExitCode1WithoutError` sets err to nil.
```
go.mondoo.com/cnquery/v9/cli/errors.(*CommandError).Error(0xc000012060)
/home/jaym/workspace/mondoo/cnquery/cli/errors/command_error.go:29 +0x24
github.com/spf13/cobra.(*Command).ExecuteC(0x2a0c260)
/home/jaym/workspace/godev/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1080 +0xac7
github.com/spf13/cobra.(*Command).Execute(0x2a0c260)
/home/jaym/workspace/godev/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x32
go.mondoo.com/cnspec/v9/apps/cnspec/cmd.Execute()
/home/jaym/workspace/mondoo/cnspec/apps/cnspec/cmd/root.go:114 +0x325
main.main()
/home/jaym/workspace/mondoo/cnspec/apps/cnspec/cnspec.go:9 +0xf
```

🐛 Fix ExitCode1WithoutError panic

---

providers/arista/config/config.go
providers/atlassian/config/config.go
providers/aws/config/config.go
providers/azure/config/config.go
providers/core/config/config.go
providers/equinix/config/config.go
providers/gcp/config/config.go
providers/github/config/config.go
providers/gitlab/config/config.go
providers/google-workspace/config/config.go
providers/ipmi/config/config.go
providers/k8s/config/config.go
providers/ms365/config/config.go
providers/network/config/config.go
providers/oci/config/config.go
providers/okta/config/config.go
providers/opcua/config/config.go
providers/os/config/config.go
providers/slack/config/config.go
providers/terraform/config/config.go
providers/vcd/config/config.go
providers/vsphere/config/config.go

equinix-9.1.0, gcp-9.1.0, github-9.1.0, gitlab-9.1.0, google-workspace-9.1.0, ipmi-9.1.0, k8s-9.1.0, ms365-9.1.0, network-9.1.0, oci-9.1.0, okta-9.1.0, opcua-9.1.0, os-9.1.0, slack-9.1.0, terraform-9.1.0, vcd-9.1.0, vsphere-9.1.0

🎉 arista-9.1.0, atlassian-9.1.0, aws-9.1.0, azure-9.1.0, core-9.1.0,

---

providers/okta/resources/customRoles.go
providers/okta/resources/groups.go
providers/okta/resources/okta.lr
providers/okta/resources/okta.lr.go
providers/okta/resources/okta.lr.manifest.yaml
providers/okta/resources/sdk/roles.go
providers/okta/resources/users.go

This change allows users to fetch the okta groups with its roles and members:
```
cnspec> okta.groups.where(roles.one(type =="SUPER_ADMIN")) { name roles { * } members members.length < 2 }
okta.groups.where: [
0: {
roles: [
0: {
created: 2023-04-08 22:11:00 +0200 CEST
lastUpdated: 2023-04-08 22:11:00 +0200 CEST
assignmentType: "GROUP"
id: "gra91lrbpr7vabz4l5d7"
type: "SUPER_ADMIN"
status: "ACTIVE"
label: "Super Administrator"
}
]
name: "Super Admins"
members.length < 2: true
members: [
0: okta.user profile.email="ben@example.com"
]
}
]
```
You can also check which permissions custom roles have:
```
cnspec> okta.customRoles { * }
okta.customRoles: [
0: {
label: "Custom Role"
id: "cr0cyddwhxapVOPrB5d7"
description: "Custom Role"
permissions: []
}
]
```
This allows us to make dramatic …

⭐️ ability to fetch group roles and members

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_vpc.go

Add AZ fields to the subnet, which is critical information when digging into VPC subnets.
```
cnquery> aws.vpcs.first.subnets{*}
aws.vpcs.first.subnets: [
0: {
arn: "arn:aws:ec2:ap-south-1:177043123456:subnet/subnet-b231234"
id: "subnet-b231234"
cidrs: "172.31.16.0/20"
mapPublicIpOnLaunch: true
defaultForAvailabilityZone: true
availabilityZone: "ap-south-1c"
}
...
````

⭐ Add new fields to aws.vpc.subnet

---

providers/vsphere/resources/asset_advisories.go
providers/vsphere/resources/vsphere.lr
providers/vsphere/resources/vsphere.lr.go
providers/vsphere/resources/vsphere.lr.manifest.yaml

This is an extraction from https://github.com/mondoohq/cnquery/pull/2301. For vulnerability scanning we need return the list of packages. For ESXi we do not use the os connection therefore we need to implement the same resource in the vsphere provider. This PR adds the implementation to fetch and build the report here.
TODO:

⭐️ implement vuln report for vsphere

---

explorer/executor/executor.go

It is possible for bundles to end up having no queries at all after filtering. I noticed that the execution would hang until timeout is reached in this case.
@jaym You know this code much better than I do, could you add a test for this use-case? Also feel free to fix this up if you prefer a different approach.

🐛 support empty bundle execution

---

cli/providers/providers.go

I think in these cases we would also want to shutdown before log.fatal - we can't return an error here I think

🐛 shutdown providers

---

providers/coordinator.go
providers/extensible_schema.go
providers/extensible_schema_test.go
providers/mock.go
providers/runtime.go

1. Reduce the complexity of locks (kudos @jaym for pointing this out)
2. Split all methods into safe and unsafe calls (to reduce complexity)
3. Make sure the aggregate object is never modified, only re-created
... and add lots of instructions on how to use this.

🐛 fix concurrent access to extensible schema

---

providers/network/resources/certificates.go
providers/network/resources/certificates/extensions.go
providers/network/resources/network.lr
providers/network/resources/network.lr.go
providers/network/resources/network.lr.manifest.yaml

```
cnspec shell host google.com    
cnspec> tls.certificates { sanExtension { * }}
cnspec> tls.certificates { sanExtension { * }}
tls.certificates: [
0: {
sanExtension: {
uris: []
extension: pkix.extension id = 5842ac625349147af543f8049f60497ca270c0412667bbeb1042482e805069f9:2.5.29.17
emailAddresses: []
dnsNames: [
0: "*.google.com"
1: "*.appengine.google.com"
2: "*.bdn.dev"
3: "*.origin-test.bdn.dev"
4: "*.cloud.google.com"
5: "*.crowdsource.google.com"
6: "*.datacompute.google.com"
7: "*.google.ca"
8: "*.google.cl"
9: "*.google.co.in"
10: "*.google.co.jp"
11: "*.google.co.uk"
12: "*.google.com.ar"
13: "*.google.com.au"
14: "*.google.com.br"
15: "*.google.com.co"
16: "*.google.com.mx"
17: "*.google.com.tr"
18: "*.google.com.vn"
...
]
}
}
1: {
sanExtension: null
}
2: {
sanExtension: null …
```

⭐️ support PKIX certificate Subject Alternative Name extension

---

explorer/scan/local_scanner.go
providers/os/provider/provider.go

Mimic cnspec and ensure we only scan assets with platforms. Use the OS provider's detect to make sure inventory assets have a platform.
This fixes #2390

Ignore assets with no platform. Ensure container registry assets have a platform

---

apps/cnquery/cmd/status.go
cnquery.go

This adds a new output to `cnquery status` which shows the version number of the latest release available on github and shows a hint that a newer version is available if it the currently installed version and the latest version don't match.
```
./cnquery status
→ Platform:             ubuntu
→ Version:              22.04
→ Hostname:             mondoopad
→ IP:                   192.168.178.32
→ Time:                 2023-11-01T13:36:01+01:00
→ Version:              unstable (API Version: unstable)
→ Latest Version:       9.4.0
! A newer version is available
→ API ConnectionConfig: https://us.api.mondoo.com
→ API Status:           SERVING
→ API Time:             2023-11-01T12:36:02Z
→ API Version:          9
```
Related to: …

✨ cnquery status show latest version available

---

providers/network/resources/certificates.go
providers/network/resources/network.lr
providers/network/resources/network.lr.go
providers/network/resources/network.lr.manifest.yaml

https://github.com/mondoohq/cnquery/issues/2445
```
./cnquery shell host mondoo.com
! using builtin provider for network
! using builtin provider for network
→ connected to Network API
cnquery> tls.certificates.first.extensions
tls.certificates.first.extensions: [
0: pkix.extension id="2.5.29.15"
1: pkix.extension id="2.5.29.37"
2: pkix.extension id="2.5.29.19"
3: pkix.extension id="2.5.29.14"
4: pkix.extension id="2.5.29.35"
5: pkix.extension id="1.3.6.1.5.5.7.1.1"
6: pkix.extension id="2.5.29.17"
7: pkix.extension …
```

🐛 fix certificate extensions ids

---

providers/network/resources/certificates.go
providers/network/resources/certificates_test.go

Fixes https://github.com/mondoohq/cnquery/issues/2445
The problem is that there are many potential extensions, some which are quite niche. 
We should at least implement parsing for the most common ones.
This PR covers:

🐛 tls extension value parsing

---

apps/cnquery/cmd/status.go

https://github.com/mondoohq/cnspec/issues/887
Related to: #2439 
Example:
```
./cnquery status
→ Platform:     ubuntu
→ Version:      22.04
→ Hostname:     mondoopad
→ IP:           192.168.178.32
→ Time:         2023-11-02T09:13:47+01:00
→ Version:      unstable (API Version: unstable)
→ Providers:    azure | core | os | gcp | network | vsphere | github | okta | gitlab | google-workspace | opcua | ipmi | slack | arista | equinix | k8s | oci | mock | ms365 | terraform | aws
→ API ConnectionConfig: https://us.api.mondoo.com
→ API Status:   SERVING
→ API Time:     2023-11-02T08:13:47Z
→ API Version:  9
! API versions do not match, please update the client
```

✨ cnquery status show installed providers

---

providers/os/connection/filesystem.go
providers/os/provider/provider.go

We are missing some data from COS, that's why we supply some infomration via an inventory file. This infomration needs to be preserved, so we can sync the asset.

🐛 Fix GKE node scanning

---

providers/os/resources/services.go

#2432 
The culprit here was that if the user provided the `.service` ending we wouldn't match the service
So 
```
cnquery run -c 'service("avahi-daemon.service") {*}'
```
Would not be matched to `avahi-daemon` and returns default values.
This PR let's us ignore the `.service` suffix, so that both `avahi-daemon.service` and `avahi-deamon` will be properly recognized
Edit: This does not complete fix the issue #2432 but that said the change should still make sense.
To close the issue #2442 is also required but currently work in progress

🐛 fix os services working with .service ending

---

apps/cnquery/cmd/bundle.go
apps/cnquery/cmd/status.go

we need to suppress the errors and usage if we want to keep the behaviour the same as pre-#2379
Fixes #2440

🧹 fix error reporting for os.exit

---

.github/dependabot.yml

This should help with such PRs https://github.com/mondoohq/cnquery/pull/2418
The grouping should create one PR, which includes the current available minor and patch updates.
https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/

🧹 Use dependabot groups for update PRs

---

providers/aws/resources/discovery.go

this can happen if an image has no tag or we were unable to fetch the metadata for the image

🐛 ensure we do not return ecr image assets with no connection info from discovery call

---

explorer/scan/local_scanner.go

i found that we had the name in the provider runtime code, but when we popped back out to the local scanner code the asset did not have a name. this sets the asset to the one set by the connection, which should have the info we want
DO NOT use builtin provider to test this - things work without this change with the builtin provider. 
easiest way to test is ssh scan to linux machine - you should see a valid instance id, e.g. `i-9038439043`

🐛 ensure we use the connection asset so we do not lose info from connect call

---

providers/aws/resources/aws.lr
providers/azure/resources/azure.lr
providers/core/resources/core.lr
providers/equinix/resources/equinix.lr
providers/gcp/resources/gcp.lr
providers/github/resources/github.lr
providers/gitlab/resources/gitlab.lr
providers/google-workspace/resources/google-workspace.lr

I changed some resource descriptions to heading-style caps in some earlier commits. This returns them to sentence-style caps.
I also tacked on some other edits.

Fixes capitalization of resources for docs

---

providers/aws/provider/provider.go

fixes https://github.com/mondoohq/server/issues/6770 for ebs scanning, we should look at other places where this happens
with this pr i get a score on my asset instead of X/error: https://edge.console.mondoo.com/space/inventory/2XojNy4h1BPQyzpQWOHXuqQSbNQ/overview?spaceId=funny-poitras-168395

🧹 aws ebs scan: reassign to fs conn once mounted

---

providers/os/resources/processes/ps1getprocess.go

I believe the Inode stuff should be implemented for unix but not for windows. However, returning a "not implemented" error is breaking windows resources. Looking at the code it seems that we just need to return an empty map
Fixes #2530

🐛 fix listing of windows processes

---

examples/os.mql.yaml
explorer/bundle.go

During the initial release of cnquery we made it easy for users to write bundles. One of our decisions was to make `uid` fields optional for both querypacks and queries at that time.
However, in the meantime we have learned how important these fields are for exception-handling. Adding them on the fly will lead to changing UIDs. Even if we relied on MQL or metadata contents, it would easily cause auto-generated UIDs to change if these contents change.
We plan to add functionality to the linter and/or initial loading steps to auto-fill UIDs on the fly - but at the same time modify the bundle and write them back to disk. This helps new users while keeping the field stable.

✨ Make querypack + query UIDs mandatory

---

providers/os/provider/platform.go
providers/os/provider/provider.go
providers/os/provider/provider_test.go

With local connections, we saw the case in cnspec, that on first connect, assets had platformIDs as expected. With local connections this should only be the hostname and perhaps cloud data.
But on later connects, the set id detectors were emtpy and another default kicked in: https://github.com/mondoohq/cnquery/blob/main/providers/os/provider/detector.go\#L39-L41
This added the ssh hostkey detector to the asset which is not expected.

🐛 Keep idDetectors across connects

---

Makefile
go.mod
go.sum
providers/os/detector/detector_all.go
providers/os/resources/os.lr
providers/os/resources/os.lr.go
providers/os/resources/os.lr.manifest.yaml
providers/os/resources/packages.go
providers/os/resources/packages/apk_packages.go
providers/os/resources/packages/apk_packages_test.go
providers/os/resources/packages/dpkg_packages.go
providers/os/resources/packages/dpkg_packages_test.go
providers/os/resources/packages/packages.go
providers/os/resources/packages/pacman_packages.go
providers/os/resources/packages/pacman_packages_test.go
providers/os/resources/packages/rpm_packages.go
providers/os/resources/packages/rpm_packages_test.go
providers/os/resources/purl/purl.go
providers/os/resources/python.go
providers/os/resources/python_package.go
providers/os/resources/reboot/rhel.go

To identify packages it is useful to have the purl when available. This change adds purl for all major linux platforms and pythong packages. See https://github.com/package-url/purl-spec
To query all the package purls for ``:
```javascript
cnquery shell docker registry.access.redhat.com/ubi8/ubi 
→ connected to Red Hat Enterprise Linux 8.8 (Ootpa)
cnquery> packages.map(purl) + python.packages.map(purl)
packages.map.+: [
0: "pkg:rpm/rhel/tzdata@2023c-1.el8?arch=noarch&distro=rhel-8.8"
1: "pkg:rpm/rhel/python3-pip-wheel@9.0.3-22.el8?arch=noarch&distro=rhel-8.8"
2: …
```

⭐️  add package url to os and python packages

---

providers/network/resources/network.lr

Bare values like <> are no longer allowed in markdown so this causes errors when the parser is trying to parse it. This avoids the parsing.

Avoid mdx compilation errors in docs markdown

---

providers/os/resources/processes/testdata/aix72.toml
providers/os/resources/processes/unixps.go
providers/os/resources/processes/unixps_test.go

This adds support for `processes` on AIX:
```
cnquery> processes
processes.list: [
0: process executable="swapper" pid=0 state=""
1: process executable="/etc/init" pid=1 state=""
2: process executable="wait" pid=260 state=""
3: process executable="sched" pid=65798 state=""
4: process executable="lrud" pid=131336 state=""
5: process executable="vmptacrt" pid=196874 state=""
6: process executable="psmd" pid=262412 state=""
7: process executable="vmmd" pid=327950 state=""
8: process executable="pvlist" pid=393488 state=""
9: process executable="reaffin" pid=459026 state=""
10: process executable="memgrdd" pid=524564 state=""
11: process executable="/usr/ccs/bin/shlap64" pid=590182 state=""
...
```
Note: similar to other unix systems, state is not supported.

⭐️ support processes resource for aix

---

llx/builtin_array.go
llx/llx.go
mql/mql_test.go

Couple of problems we saw:
1. Reported in https://github.com/mondoohq/cnquery/issues/2604 we see that the child type of the list is never set correctly, if the list is empty. A bit lazy on the return, glad to have this fixed
2. I also noticed that on errors the type is retained. Technically, this shouldn't matter (because it's an error), but just to be sure, we should set it correctly when we return the results.
Fixes https://github.com/mondoohq/cnquery/issues/2604

🐛 adjust type of empty+errored array maps

---

providers/atlassian/resources/atlassian.lr
providers/atlassian/resources/atlassian.lr.go
providers/atlassian/resources/atlassian.lr.manifest.yaml
providers/atlassian/resources/atlassian_admin.go

Use proper time type for fields that return a time. Also lets expose the products user has access to.

🐛 use time datatypes for atlassian provider where possible

---

providers/os/resources/os.lr
providers/os/resources/os.lr.go
providers/os/resources/os.lr.manifest.yaml
providers/os/resources/python/mime.go
providers/os/resources/python/mine_test.go
providers/os/resources/python_package.go

after #2634 
This improves the author name output to include the email
**before**
```coffeescript
cnquery> python.packages { name author }
python.packages: [
0: {
name: "Jinja2"
author: "Armin Ronacher"
}
...
]
```
**after**
```coffeescript
cnquery> python.packages { name author authorEmail }
python.packages: [
0: {
name: "Jinja2"
author: "Armin Ronacher"
authorEmail: "armin.ronacher@active-4.com"
}
...
]
```

🧹 improve python author

---

.github/workflows/pr-test-lint.yml

From time to time we have dependabot PRs which update the cnquery go.mod and would also require an update of the providers go.mod files. But dependabot can only update one go.mod. This PR should update the providers go.mod files in these cases.

🐛 dependabot: also update providers go.mod

---

.github/workflows/pr-test-lint.yml

According to the debug logs, this workflow is triggered on push, not pull_request.
Change the check to push, but make sure the commit does not happen on merge to main again.
The debug step is only temporary to get more insight and will be removed later.

🐛 Trigger job step on push event

---

providers/aws/resources/aws_iam.go

fixes https://github.com/mondoohq/cnquery/issues/2677
```
cnquery> aws.iam.policies.where( attachedGroups.length > 0 ) { attachedGroups }
aws.iam.policies.where: [
0: {
attachedGroups: [
0: aws.iam.group arn="arn:aws:iam::..:group/ec2-instance-connect-" name="ec2-instance-connect-"
]
}
```

🐛 fix error on aws iam attachedPolicies attachedGroups

---

providers/k8s/resources/discovery.go
providers/k8s/resources/discovery_test.go

This fixes the asset name when images are discovered inside a kubernetes cluster.
Now the name is the same as with v8

🐛 Fix image names for k8s container discovery

---

providers/k8s/config/config.go

🎉 k8s-9.1.11

---

providers/network/config/config.go
providers/os/config/config.go

🎉 network-9.1.8, os-9.1.14

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_backups.go
providers/aws/resources/aws_cloudfront.go
providers/aws/resources/aws_cloudwatch.go

More aws resoure cleanup plus add retentionInDays to aws.cloudwatch.logGroups
```
cnquery> aws.cloudwatch.logGroups.first{*}
aws.cloudwatch.logGroups.first: {
arn: "arn:aws:logs:us-east-1:xxxxxxx:log-group:/aws/eks/eks-cluster-container-escape-demo-sg40-cluster/cluster:*"
name: "/aws/eks/eks-cluster-container-escape-demo-sg40-cluster/cluster"
retentionInDays: 90
metricsFilters: []
kmsKey: null
}
```

⭐ Add retentionInDays to aws.cloudwatch.logGroups + ptr cleanup

---

providers/aws/resources/aws.lr
providers/aws/resources/aws_ec2.go

Improve the defaults and cleanup some string conversions.
```
aws.ec2.securityGroups: [
0: aws.ec2.securitygroup id="sg-xxxxx" name="mondoo-scanning-securitygroup" region="ap-south-1" vpc.id="vpc-xxxxx"
1: aws.ec2.securitygroup id="sg-xxxxx" name="default" region="ap-south-1" vpc.id="vpc-xxxxx"
2: aws.ec2.securitygroup id="sg-xxxxx" name="default" region="eu-north-1" vpc.id="vpc-xxxxx"
3: aws.ec2.securitygroup id="sg-xxxxx" name="mondoo-scanning-securitygroup" region="eu-north-1" vpc.id="vpc-xxxxx"
4: aws.ec2.securitygroup id="sg-xxxxx" name="default" region="eu-west-3" vpc.id="vpc-xxxxx"
```

⭐ Improve aws.ec2.securityGroups defaults + ptr cleanup

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_ec2.go

isDefault and tags
```
19: {
isDefault: false
arn: "arn:aws:ec2:us-east-1:xxxxxxxxx:network-acl/acl-xxxxxxxxx"
tags: {
Attributes: "public"
Name: "eg-prod-app-public"
Namespace: "eg"
Stage: "prod"
}
id: "acl-xxxxxxxxx"
entries: [
0: aws.ec2.networkacl.entry id="acl-xxxxxxxxx-100-egress" egress=true ruleAction="allow" cidrBlock="0.0.0.0/0" portRange=null
1: aws.ec2.networkacl.entry id="acl-xxxxxxxxx-32767-egress" egress=true ruleAction="deny" cidrBlock="0.0.0.0/0" portRange=null
2: aws.ec2.networkacl.entry id="acl-xxxxxxxxx-100-ingress" egress=false ruleAction="allow" cidrBlock="0.0.0.0/0" portRange=null
3: aws.ec2.networkacl.entry id="acl-xxxxxxxxx-32767-ingress" egress=false ruleAction="deny" cidrBlock="0.0.0.0/0" portRange=null
]
}
```

⭐ Update aws.ec2.networkacl with new fields

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_ec2.go

```
aws.ec2.volumes: [
0: aws.ec2.volume id="vol-xxxxxxx" region="us-east-1" volumeType="gp3" size=80 encrypted=true state="in-use"
1: aws.ec2.volume id="vol-xxxxxxx" region="us-east-1" volumeType="gp3" size=16 encrypted=false state="in-use"
2: aws.ec2.volume id="vol-xxxxxxx" region="us-east-1" volumeType="gp2" size=50 encrypted=true state="in-use"
```
```
cnquery> aws.ec2.volumes.first{*}
aws.ec2.volumes.first: {
id: "vol-xxxxxxx"
arn: "arn:aws:ec2:us-west-2:xxxxxxx:volume/vol-xxxxxxx"
multiAttachEnabled: false
tags: {
ExtraTag: "EKS managed node group complete example"
Name: "eks-managed-nodes-sg40"
eks:cluster-name: "eks-cluster-container-escape-demo-sg40-cluster"
eks:nodegroup-name: "eks-managed-nodes-sg40-xxxxxxx"
}
throughput: 150
iops: 3000
availabilityZone: …
```

⭐ New defaults and fields for aws.ec2.volume

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_ec2.go

Add new fields and improve the defaults
```
cnquery> aws.ec2.snapshots
aws.ec2.snapshots: [
0: aws.ec2.snapshot id="snap-xxxxxxxxx" region="us-east-1" volumeSize=8 state="completed"
1: aws.ec2.snapshot id="snap-xxxxxxxxx" region="us-east-1" volumeSize=8 state="completed"
2: aws.ec2.snapshot id="snap-xxxxxxxxx" region="us-east-1" volumeSize=30 state="completed"
3: aws.ec2.snapshot id="snap-xxxxxxxxx" region="us-east-1" volumeSize=30 state="completed"
````
```
cnquery> aws.ec2.snapshots.first{*}
aws.ec2.snapshots.first: {
id: "snap-xxxxxxxxx"
startTime: 2022-11-30 15:31:03.985 -0800 PST
encrypted: true
tags: {
Base_AMI_Name: "amzn2-ami-kernel-5.10-hvm-2.0.20221103.3-x86_64-gp2"
Creation_Date: "2022-11-14T23:11:49.000Z"
Name: "mondoo-aws-amazon-linux-2-secure-base-20221130232803"
Source_AMI: …
```

⭐ New defaults and fields for aws.ec2.snapshot

---

providers/github/resources/github.lr
providers/github/resources/github.lr.go
providers/github/resources/github.lr.manifest.yaml
providers/github/resources/github_repo.go

Fixes: https://github.com/mondoohq/cnquery/issues/2764
Fixes: https://github.com/mondoohq/cnquery/issues/2739
Add `closedMergeRequests` and `allMergeRequests` to allow users more control over how much data they want to fetch from github.
A mini addition for github.mergeRequest also got in here that allows specifing the repo
```
github.mergeRequest(number: 2201 repoName: cnspec)
```

✨ get closed or all PRs from github

---

providers/arista/config/config.go
providers/atlassian/config/config.go
providers/aws/config/config.go
providers/azure/config/config.go
providers/core/config/config.go
providers/equinix/config/config.go
providers/gcp/config/config.go
providers/github/config/config.go
providers/gitlab/config/config.go
providers/google-workspace/config/config.go
providers/ipmi/config/config.go
providers/k8s/config/config.go
providers/ms365/config/config.go
providers/oci/config/config.go
providers/okta/config/config.go
providers/opcua/config/config.go
providers/os/config/config.go
providers/slack/config/config.go
providers/terraform/config/config.go
providers/vcd/config/config.go
providers/vsphere/config/config.go

arista-9.1.10, atlassian-9.1.10, aws-9.1.15, azure-9.1.12, core-9.1.6, equinix-9.1.11, gcp-9.1.13, github-9.1.12, gitlab-9.1.11, google-workspace-9.1.13, ipmi-9.1.11, k8s-9.1.13, ms365-9.2.8, oci-9.1.12, okta-9.1.11, opcua-9.1.10, os-9.1.15, slack-9.1.10, terraform-9.1.10, vcd-9.1.10, vsphere-9.1.11

🎉 release providers

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_config.go

Add new fields and defaults plus cleanup some ptrs
```
cnquery> aws.config.rules
aws.config.rules: [
0: aws.config.rule name="ec2-ebs-encryption-by-default" id="config-rule-2tre0q" region="us-east-1" state="ACTIVE"
1: aws.config.rule name="ec2-imdsv2-check" id="config-rule-antu1f" region="us-east-1" state="ACTIVE"
2: aws.config.rule name="ec2-instance-detailed-monitoring-enabled" id="config-rule-lilt2r" region="us-east-1" state="ACTIVE"
```
```
cnquery> aws.config.rules.first{*}
aws.config.rules.first: {
source: {
CustomPolicyDetails: null
Owner: "AWS"
SourceDetails: null
SourceIdentifier: "EC2_EBS_ENCRYPTION_BY_DEFAULT"
}
id: "config-rule-2tre0q"
arn: "arn:aws:config:us-east-1:xxxxxxxx:config-rule/config-rule-2tre0q"
description: "Check that Amazon Elastic Block Store …
```

⭐ Improve aws.config.rules resource

---

providers/k8s/connection/shared/connection.go
providers/k8s/provider/provider.go
providers/k8s/provider/provider_test.go
providers/k8s/resources/discovery.go
providers/k8s/resources/discovery_test.go

The CLI parser was already using the correct names. Now also the inventory parser is looking the correct options.
Fixes #2805

🐛 Parse k8s namespace filters from inventory file

---

providers/aws/config/config.go
providers/azure/config/config.go
providers/k8s/config/config.go

🎉 aws-9.1.16, azure-9.1.13, k8s-9.1.14

---

providers/aws/resources/aws_waf.go

Fixes 
```
cnquery> aws.waf(scope: "REGIONAL").acls{ * }
2 errors occurred:
* operation error WAFV2: GetWebACL, 1 validation error(s) found.
- missing required field, GetWebACLInput.Scope.
* cannot convert primitive with NO type information
aws.waf.acls: [
0: {
description: ""
scope: cannot convert primitive with NO type information
rules: operation error WAFV2: GetWebACL, 1 validation error(s) found.
- missing required field, GetWebACLInput.Scope.
id: "d1ae782d-700b-4112-99ab-d9df8d0d0e24"
arn: "arn:aws:wafv2:us-east-1:921877552404:regional/webacl/marius-test/d1ae782d-700b-4112-99ab-d9df8d0d0e24"
name: "marius-test"
managedByFirewallManager: false
}
]
```

fix aws waf cannot convert primitive with NO type information

---

providers/github/resources/github.lr

This makes the output of github.organization.members a lot more useful.

Update the defaults for github users

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_rds.go

Add useful data to these resources.
```coffee
aws.rds.dbClusters.first: {
storageIops: 1000
members: cannot convert primitive with NO type information
id: "timtest"
storageEncrypted: true
clusterDbInstanceClass: "db.m5d.large"
backupRetentionPeriod: 7
engine: "postgres"
multiAZ: true
storageType: "io1"
storageAllocated: 100
createdTime: 2023-12-13 17:22:30.666 -0800 PST
status: "available"
snapshots: [
0: aws.rds.snapshot id="rds:timtest-2023-12-14-01-25" region="us-west-2" type="automated" encrypted=true
]
publiclyAccessible: false
deletionProtection: true
autoMinorVersionUpgrade: true
arn: "arn:aws:rds:us-west-2:XXXXXXX:cluster:timtest"
engineVersion: "15.4"
tags: {}
}
```
```coffee
cnquery> aws.rds.dbClusters.first{snapshots{*}}
aws.rds.dbClusters.first: { …
```

⭐ Add more aws.rds.dbcluster and aws.rds.snapshot fields

---

providers/aws/config/config.go
providers/github/config/config.go
providers/k8s/config/config.go

🎉 aws-9.1.18, github-9.1.13, k8s-9.1.15

---

providers-sdk/v1/upstream/mvd/mvd.proto

there seems to be a typo here which breaks the generation for cnspec

🐛 fix mvd go package name

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_acm.go

Improve the defaults and add these new fields:
- keyAlgorithm
- serial
- source
- issuer
- issuedAt
- importedAt
```coffee
aws.acm.certificates: [
0: aws.acm.certificate domainName="example.com" issuer="Amazon" createdAt=2023-07-26 08:28:34.859 -0700 PDT notAfter=2024-08-23 16:59:59 -0700 PDT
]
```
```coffee
aws.acm.certificates.first: {
status: "ISSUED"
tags: {}
certificate: certificate serial="1234" subject.commonName="example.com" subject.dn="CN=example.com"
notBefore: 2023-07-25 17:00:00 -0700 PDT
issuer: "Amazon"
domainName: "example.com"
serial: "123"
subject: "CN=example.com"
issuedAt: 2023-07-26 08:29:03.022 -0700 PDT
importedAt: null
source: "AMAZON_ISSUED"
keyAlgorithm: "RSA-2048"
notAfter: 2024-08-23 16:59:59 -0700 PDT
createdAt: 2023-07-26 08:28:34.859 -0700 PDT
arn: "1234"
} …
```

Add new fields + better defaults in aws.acm.certificate

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_acm.go
providers/aws/resources/aws_dynamodb.go
providers/aws/resources/aws_ec2.go
providers/aws/resources/aws_ecr.go
providers/aws/resources/aws_s3.go

- Add createdAt to aws.ec2.keypair
- Improve defaults in aws.ec2.keypair
- Cleanup some incorrect min mondoo version fields
- Use StringDataPtr where we can

Add createdAt to aws.ec2.keypair + cleanup ptrs

---

providers/os/connection/ssh.go
providers/os/connection/ssh_test.go

This fixes an issue reported by @username-is-already-taken2. Packer plugin properly enables the sudo config via the inventory https://github.com/mondoohq/packer-plugin-cnspec/blob/a4c6be26de7ac51f49259fd9ea4501663d43ea87/provisioner/provisioner.go#L335-L340. 
Problem was that no sudo executable was set. The cli flag always set the executable as well https://github.com/mondoohq/cnquery/blob/main/providers/os/connection/shared/shared.go#L197-L212. Therefore the inventory for the packer scan used the following sudo setting:
```json
"sudo": {
"active": true
}
```
This PR changes the default and always falls back to `sudo` cli if no alternative executable was set.

🐛 set default sudo executable

---

providers/slack/resources/conversations.go
providers/slack/resources/slack.lr
providers/slack/resources/slack.lr.go
providers/slack/resources/slack.lr.manifest.yaml

- allows users to filter by top level categories without where queries which leads to performance improvements since we only fetch the relevant data
- implement handling for rate-limiting since slack go sdk is not doing that for the conversations api

🧹 improve slack conversations handling

---

providers/k8s/config/config.go

🎉 k8s-9.1.17

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_rds.go

This is a copy/modification of the same logic we use for the dbinstance resource

Add security group to aws.rds.dbcluster

---

providers/aws/resources/discovery.go
providers/aws/resources/discovery_conversion.go

also adds instance type to ec2 instances asset labels so we can filter on that value later 
https://github.com/mondoohq/cnquery/issues/2623

🧹 add back in ecr-api and ecs-api discovery

---

.github/pr-body.md
.github/workflows/pr-test-lint.yml
.github/workflows/update-deps.yaml

When the PR is created with a GH token, the tests aren't executed. This is becasue of limitation applied to the token.
These limiations do not apply to ssh keys.

🐛 Use ssh key instead of GH token

---

Makefile

This allows users to easily install the lr command into go bin

🧹 add make task to compile lr into go bin

---

providers/arista/config/config.go
providers/atlassian/config/config.go
providers/aws/config/config.go
providers/azure/config/config.go
providers/equinix/config/config.go
providers/gcp/config/config.go
providers/github/config/config.go
providers/gitlab/config/config.go
providers/google-workspace/config/config.go
providers/ipmi/config/config.go
providers/k8s/config/config.go
providers/ms365/config/config.go
providers/oci/config/config.go
providers/okta/config/config.go
providers/opcua/config/config.go
providers/slack/config/config.go
providers/terraform/config/config.go
providers/vcd/config/config.go
providers/vsphere/config/config.go

The following providers have been updated:
arista-9.1.12, atlassian-9.1.12, aws-9.1.21, azure-9.1.15, equinix-9.1.13, gcp-9.1.15, github-9.1.16, gitlab-9.1.13, google-workspace-9.1.16, ipmi-9.1.13, k8s-9.1.19, ms365-9.2.11, oci-9.1.14, okta-9.1.13, opcua-9.1.12, slack-9.1.14, terraform-9.1.12, vcd-9.1.12, vsphere-9.1.14

provider updates 2023 12 29

---

go.mod
providers/providers.go

Fixes #2490
When we fail to get `https://releases.mondoo.com/providers/latest.json` this will wait 1 second, try again, wait 2 seconds, try again. Should hopefully make `prep/providers` stage a bit more reliable.

✨ add retry to providers install

---

providers/aws/resources/aws.lr
providers/aws/resources/aws.lr.go
providers/aws/resources/aws.lr.manifest.yaml
providers/aws/resources/aws_rds.go

A few more useful items to align with the dbcluster resource

Add port and endpoint to aws.rds.dbinstance

---

llx/builtin.go
llx/builtin_simple.go
mqlc/builtin.go
mqlc/builtin_simple.go
providers/core/resources/mql_test.go

Support a simpler methods to see if a number is in range.
So far users have to:
```coffee
num >= 3 && num <= 5
```
Now you can:
```coffee
num.inRange(min,  max)
```
Example:
```coffee
3.inRange(3, 5)
```
This supports both integers and floats. Dict support is coming next.

⭐ number.inRange support

---

llx/builtin.go
llx/builtin_resource.go
mqlc/builtin.go
mqlc/builtin_resource.go
mqlc/mqlc_test.go
providers/core/resources/core.lr
providers/core/resources/parse_test.go

This now supports parsing durations in seconds (s), minutes (m), hours (m), days (d), and years (y). This works with both the shorthand scalar as well as the long version, e.g.:
```coffee
parse.duration("3d")
parse.duration("3days")
```
The parser is very lenient, but we recommend using the above scalars as so:
```
1s = 1 second
2m = 2 minutes
3h = 3 hours
4d = 4 days
5y = 5 years
```

✨ parse.duration

---

llx/builtin.go
llx/builtin_map.go
llx/builtin_simple.go
mqlc/builtin.go
mqlc/builtin_simple.go
providers/core/resources/mql_test.go

Support the inverse of `list.contains(string)` by adding support for `string.in(list)`. This makes queries much more flexible. Example:
```coffee
"hi".in(["a","hi","b"])
```

✨ string.in(list of strings)

---

llx/builtin.go
llx/builtin_simple.go
mqlc/builtin.go
mqlc/builtin_simple.go
providers/core/resources/mql_test.go

Add support for the inRange operator for the time type. Makes it easier to check if a time is between two timestamps.

✨ time.inRange(min, max)

---

providers/terraform/resources/terraform.lr

This PR updates some defaults for Terraform resources. 
**Before**
```
cnquery> terraform.state.resources
terraform.state.resources: [
0: terraform.state.resource name="random"
1: terraform.state.resource name="this"
2: terraform.state.resource name="current"
3: terraform.state.resource name="this"
4: terraform.state.resource name="this"
5: terraform.state.resource name="this"
6: terraform.state.resource name="this"
7: terraform.state.resource name="this"
8: terraform.state.resource name="this"
```
**AFTER**
```
cnquery> terraform.state.resources
terraform.state.resources: [
0: terraform.state.resource type="random_string" name="random"
1: terraform.state.resource type="aws_instance" name="this"
2: terraform.state.resource type="aws_partition" name="current"
3: terraform.state.resource …
```

Updates defaults for Terraform resources

---

mql/mql_test.go
mqlc/builtin_array.go
mqlc/builtin_map.go
mqlc/builtin_resource.go
mqlc/mqlc.go
providers-sdk/v1/testutils/mockprovider/resources/all.go

This is an exciting new v10 feature that allows users to set named arguments in functions.
This means that you can do things like this:
```coffee
users.all(user:
groups.contains(group:
user.uid == group.gid
)
)
```
This handles all cases where you felt you had to assign `_` to a variable. This makes it easier in all cases where you could only use one expression (like with `all`, `one`, etc).
Most exciting part about this feature is: It is backwards-compatible. It works with older runtimes of MQL since it only changes the compiler. (tested via binary LLX)
You can still rely on using `_` if no variable name is defined. This remains the default.

MERGE AFTER v9.14 -- ⭐ support named arguments in functions

---

providers/azure/connection/azureinstancesnapshot/provider.go
providers/azure/connection/azureinstancesnapshot/provider_test.go
providers/azure/provider/provider.go

We can now scan instances/snapshots across resource groups, they still need to be in the same location though.
```
sudo DEBUG=1 ./cnquery shell azure compute snapshot "/subscriptions/subId/resourceGroups/my-rg/providers/Microsoft.Compute/snapshots/test-debian-snap" --client-id <id> --tenant-id <id>--client-secret <secret>
```

✨ Support scanning instances/snapshots by a fully qualified azure resource id

---

apps/cnquery/cmd/bundle.go

This will make the manual installation of the providers in github actions obsolete, eg. https://github.com/mondoohq/cnquery-packs/blob/main/.github/workflows/lint.yaml#L21-L35

🧹 ensure that all providers are installed for bundle lint

---

providers/os/resources/group.go
providers/os/resources/group_test.go
providers/os/resources/os.lr.go
providers/os/resources/user_test.go

We had inconsistent behavior between the `user` init (which supported being called with `uid` and `name`) and `group` (which didn't have an init call at all).
Both have now been aligned, so you can call:
```coffee
> user(uid: 0)
user: user name="root" uid=0 gid=0
> user(name: "root")
user: user name="root" uid=0 gid=0
```
as well as
```coffee
> group(gid: 0)
group: group name="root" gid=0
> group(name: "root")
group: group name="root" gid=0
```
Fixes #2937 
Expands testing.

🐛 consistent group(gid:0) / group(name:"root") init

---

mqlc/mqlc.go
mqlc/mqlc_test.go
providers/core/resources/mql_test.go

The long-overdue counterpart to https://github.com/mondoohq/cnquery/pull/1695
```coffee
> {a: 23}.a
23
```

⭐ add simple accessors for maps

---

providers/azure/connection/azureinstancesnapshot/platform.go
providers/azure/connection/azureinstancesnapshot/provider.go
providers/azure/connection/azureinstancesnapshot/provider_test.go
providers/azure/connection/azureinstancesnapshot/snapshot.go
providers/azure/provider/provider.go

Adds support for scanning azure disks: `cnquery scan azure compute disk <id> ....`.
This means that the azure snapshot scanner now supports disks, instances and snapshot targets. This PR also adds some cleanup by removing unused properties and making things private where possible.

✨ Add support for scanning azure disks.

---

providers/arista/config/config.go
providers/atlassian/config/config.go
providers/aws/config/config.go
providers/core/config/config.go
providers/equinix/config/config.go
providers/gcp/config/config.go
providers/github/config/config.go
providers/gitlab/config/config.go
providers/google-workspace/config/config.go
providers/ipmi/config/config.go
providers/k8s/config/config.go
providers/ms365/config/config.go
providers/oci/config/config.go
providers/okta/config/config.go
providers/opcua/config/config.go
providers/os/config/config.go
providers/slack/config/config.go
providers/terraform/config/config.go
providers/vcd/config/config.go
providers/vsphere/config/config.go

arista-9.1.14, atlassian-9.1.14, aws-9.1.23, core-9.1.7, equinix-9.1.15, gcp-9.1.17, github-9.1.18, gitlab-9.1.15, google-workspace-9.1.18, ipmi-9.1.15, k8s-9.1.21, ms365-9.2.13, oci-9.1.16, okta-9.1.15, opcua-9.1.14, os-9.1.18, slack-9.1.16, terraform-9.1.14, vcd-9.1.14, vsphere-9.1.16

🎉  release updated providers

---

providers-sdk/v1/upstream/gql/client.go
providers/os/resources/asset_vuln.go
providers/os/resources/vulnmgmt.go
providers/vsphere/resources/vulnmgmt.go

the fact that this is not a pointer causes annoying linter warnings because we are copying some lock by reference instead of a pointer. This fixes the issue

🧹 fix warning in gql client

---

llx/builtin.go
llx/builtin_array.go
llx/builtin_map.go
mqlc/builtin.go
providers/core/resources/mql_test.go
providers/os/resources/mql_test.go

This finally supports use-cases like:
```coffee
sshd.config.ciphers.in( props.allowedCiphers )
```

✨ support []string.in([]string)

---

explorer/property.go
explorer/property_test.go
explorer/query_conductor.go

We were never fully implementing referential properties until now. This PR fixes the fact that the `for` field is referencing other properties in the same bundle using their `uid`. It now correctly generates their `mrn` and sets the `uid` to empty string like in the property itself.

🐛 update `for` field in props

---

providers/coordinator.go

Attach the zerolog logger to the plugin. This way we gain extra logging around the plugins' lifecycle:
```
cnquery> exit
x plugin process exited error="exit status 1" id=8679 plugin=/opt/mondoo/providers/azure/azure
! failed to shut down provider error="rpc error: code = Unavailable desc = error reading from server: EOF" provider=azure
→ plugin process exited id=9127 plugin=/opt/mondoo/providers/os/os
```

🧹 Attach zerolog logger to plugin clients.

---

providers/coordinator.go
providers/providers_test.go

Until now, both `Shutdown` and `Heartbeat` shared a lock. This means that if shutting down ever takes more then the heartbeat interval, the provider plugin gets killed as it cannot keep doing heartbeats since the lock is occupied.
This PR introduces a second lock to only be used for the heartbeat-related stuff: Setting `isClosed` and `isShutdown` on the provider and then using this in the heartbeat logic. The shutdown logic uses a separate lock to ensure that both can run in parallel.

🐛 Allow for provider shutdown to take longer than a heartbeat.

---

providers/azure/resources/discovery.go

In azure-land it's called a location, not a region

🧹 Rename region label to location label for azure vms.
