docs/development.md
Keep these in sync with cnspec
=> 📄 Minor updates to the dev docs

motor/discovery/docker_engine/resolver.go, motor/discovery/github/github.go, motor/discovery/local/local.go
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>
=> 🐛 do not auto-discover containers for local provider

motor/discovery/docker_engine/resolver.go, motor/discovery/github/github.go, motor/discovery/local/local.go
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>
=> [v6] 🐛 do not auto-discover containers for local provider

explorer/services.go
=> 🧹 remove deprecated resolver versions

apps/cnquery/cmd/explore.go, apps/cnquery/cmd/register.go, apps/cnquery/cmd/root.go, apps/cnquery/cmd/run.go, apps/cnquery/cmd/shell.go, apps/cnquery/cmd/status.go, apps/cnquery/cmd/unregister.go, cli/config/config.go, resources/lr/cli/cmd/root.go
=> Upcase the help and fix text formatting

LICENSE.txt, README.md
=> 🎉 make it open source

mqlc/mqlc.go, resources/packs/k8s/k8s.lr.go
1. If it starts with the term you are typing, make sure it bubbles up
2. Rank all suggestions and make good stuff go higher
OLD:
NEW
=> ⭐ smarter suggestions

README.md
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>
=> 🧹 add link to query packs

apps/cnquery/cmd/builder/builder.go, motor/discovery/k8s/list_images.go, motor/discovery/k8s/list_images_test.go, motor/discovery/k8s/list_nodes.go, motor/discovery/k8s/list_nodes_test.go, motor/discovery/k8s/list_workloads.go, motor/discovery/k8s/list_workloads_test.go, motor/discovery/k8s/resolver.go
=> 🌈 Show warning when namespace not present

llx/code_bundle.go
Want to make sure if we deserialize a thing that contained v1 code and make it into this function, it doesn't crash
=> 🧹 Be defensive

mqlc/mqlc_test.go, mqlc/parser/parser.go
=> 🐛 prevent panics on incomplete switch-case

cli/pager/pager.go
not yet in use, but will soon be added to the reporting
=> ✨ re-introduce pager

README.md
=> 🧹 update readme with new cnquery scan command

apps/cnquery/cmd/root.go, apps/gen-docs/main.go
=> 🐛 generate better titles for CLI docs

resources/packs/os/smbios/linux.go
=> 🐛 do not try to read proc file that we cannot stat

apps/cnquery/cmd/root.go
=> 🐛 remove duplicate headers from docs

apps/cnquery/cmd/scan.go, apps/cnquery/cmd/shell.go, motor/providers/ms365/provider.go
=> 🐛 spelling

apps/cnquery/cmd/register.go, apps/cnquery/cmd/run.go, apps/cnquery/cmd/scan.go, apps/cnquery/cmd/shell.go, motor/discovery/container_registry/registry.go
More updates to get into the docs site
=> Spell out MQL and use lunalectric.com in examples

motor/providers/awsec2ebs/mount.go, motor/providers/provider.pb.go, motor/providers/provider.proto, motor/providers/terraform/hcl_parser.go, mqlc/mqlc.go, resources/library/jobpool/jobpool.go, resources/lr/go.go, resources/packs/aws/aws.lr.go, resources/packs/aws/awspolicy/s3bucketpolicy.go, resources/packs/azure/azure.lr.go, resources/packs/azure/azure_rm_web.go, resources/packs/core/core.lr.go, resources/packs/core/core_regex.go, resources/packs/gcp/gcp.lr.go, resources/packs/github/github.lr.go, resources/packs/gitlab/gitlab.lr.go, resources/packs/k8s/k8s.lr.go, resources/packs/ms365/ms365.lr.go, resources/packs/os/os.lr.go, resources/packs/os/services/alpine_openrc_test.go, resources/packs/terraform/terraform.lr.go, resources/packs/vsphere/vsphere.lr.go
Just some misc updates for OSS readers
=> Fix typos in comments and error messages

motor/discovery/k8s/resolver.go
=> 🧹 Show message what we discover in auto mode

apps/cnquery/cmd/scan.go, cli/reporter/print_compact.go, explorer/query_conductor.go, explorer/query_hub.go, explorer/scan/local_scanner.go, explorer/scan/reporter.go, explorer/scan/scan.go, explorer/services.go, go.mod
This change allows cnquery to gather query packs from logged in Mondoo Platform. When authenticated, cnquery automatically uses upstream.
=> ⭐️ support communication with upstream

resources/packs/k8s/common.go, resources/packs/k8s/common_test.go
=> 🐛 Fix id for k8s non-namespaced objects

README.md
Updates community section in README for consistency
Signed-off-by: Scott Ford <scott@scottford.io>
=> Updates community section in README

apps/cnquery/cmd/builder/parse.go
=> 🐛 Fix sudo flag

cli/reporter/json_test.go, llx/rawdata_json.go
=> 🐛 remove `<unknown>` from json export

explorer/scan/local_scanner.go
The fixes an issue where a user that runs
```
cnquery scan local --json | jq .
```
was erroring out with:
```
cnquery scan local --json | jq .                                                                                                                                                                                
→ connecting to asset spacerocket.fritz.box (baremetal)
parse error: Invalid numeric literal at line 2, column 106
```
The reason was the progress bar that was written to stdout. The new change only prints the progress bar when the stdout is attached to a tty.
=> 🐛 only render progress bar in tty mode

apps/cnquery/cmd/builder/parse.go, motor/providers/awsec2ebs/setup.go
fixes https://github.com/mondoohq/cnquery/issues/338
=> 🐛 fix ssm connection (cnquery shell aws ec2 ssm ec2-user@instanceid)

explorer/scan/local_scanner.go, explorer/scan/scan.go
This change fixes a type in `UpstreamConfig`
=> 🧹 fixes a type in struct field name

resources/packs/gcp/gcloud.go
Fixes https://github.com/mondoohq/cnquery/issues/181
```
➜ gcloud compute instances list
NAME                                        ZONE                       MACHINE_TYPE      
gke-gke-cluster-generic-pool-4dfcd37f-5yza  us-central1-b              n1-standard-2               
gke-gke-cluster-generic-pool-4dfcd37f-ugvq  us-central1-b              n1-standard-2               
test-other-zone                             northamerica-northeast2-a  e2-micro                
```
cnquery:
```
cnquery> gcloud.compute.instances { name}
gcloud.compute.instances: [
0: {
name: "gke-gke-cluster-generic-pool-4dfcd37f-5yza"
}
1: {
name: "gke-gke-cluster-generic-pool-4dfcd37f-ugvq"
}
2: {
name: "test-other-zone"
}
]
```
=> 🐛Retrieve google compute instances acros all zones.

cli/config/config.go
```
export MONDOO_CONFIG_BASE64='<base64-encoded-config>'
cnquery status                                                           1m chris-rock/docker-build[3e40edd5]
→ loaded configuration from /Users/chris/.config/mondoo/mondoo.yml using source $MONDOO_CONFIG_BASE64
→ Platform:	macos
→ Version:	12.6
...
```
=> ⭐️ support base 64 env variables

.github/workflows/goreleaser.yml, .goreleaser.yml, Dockerfile
This change builds multi-arch docker images with our release.
=> ⭐️ build docker with goreleaser

motor/discovery/k8s/resolver.go
=> 🧹 Remove CICD special case

apps/cnquery/cmd/login.go
=> Update message for when cnquery is already logged in

apps/cnquery/cmd/bundle.go, apps/cnquery/cmd/scan.go
Make things uniform/obvious and fix a typo
=> 🧹 Improve help

resources/packs/aws/aws_rds.go
fixes https://github.com/mondoohq/cnquery/issues/394
=> 🐛 include tags on rds snapshot resource nested in rds dbClusters

motor/discovery/k8s/list_images.go, motor/discovery/k8s/list_workloads.go, motor/discovery/k8s/list_workloads_test.go, motor/discovery/k8s/resolver.go
Signed-off-by: Joel Diaz <joel@mondoo.com>
=> ⭐️ add globbing support for namespace inclusion/exclusion

resources/packs/core/kernel.go, resources/packs/core/packages.go, resources/packs/os/machine.go, resources/packs/os/mount.go, resources/packs/os/os.go
=> Replace suiteable with suitable in errors

.github/actions/spelling/line_forbidden.patterns, README.md, apps/cnquery/cmd/root.go, llx/primitives.go, mqlc/assertion.go, mqlc/mqlc.go, types/types.go
Sync the pattern list with cnspec
=> Fix typos + add more patterns to spellcheck

motor/providers/ms365/msgraphclient/errors.go, resources/packs/ms365/msgraph.go
=> ✨Improve msgraph API error handling.

.goreleaser.yml
As per user request, we are adding power pc architecture to our build pipeline.
=> ⭐️ powerpc 64 little-endian build

motor/discovery/gcp/resolver_gcp.go, motor/discovery/gcp/resolver_org.go, motor/discovery/gcp/resolver_project.go, motor/providers/google/provider.go
=> 🧹 add consistent deprecations for gcp project/org change

motor/providers/awsec2ebs/setup.go
adding another completion check to the snapshot creation process and adding some timeout checks to ensure we don't eternally loop 
```
! WARNING: you are using an early access feature feature=AWS_EC2_EBS status=experimental
→ validate state instance={"AccountId":"185972265011","Id":"i-04614e3ab48488e5f","PlatformId":"//platformid.api.mondoo.app/runtime/aws/ec2/v1/accounts/185972265011/regions/us-east-1/instances/i-04614e3ab48488e5f","Region":"us-east-1"}
→ find volume id instance={"AccountId":"185972265011","Id":"i-04614e3ab48488e5f","PlatformId":"//platformid.api.mondoo.app/runtime/aws/ec2/v1/accounts/185972265011/regions/us-east-1/instances/i-04614e3ab48488e5f","Region":"us-east-1"}
→ find recent snapshot
→ create snapshot
→ waiting for snapshot completion; sleeping 10 seconds progress= …
```
=> 🧹 add timeouts to snapshot creation and search for ebs volume scan

README.md
I have read the Mondoo CLA Document and I hereby sign the CLA
Signed-off-by: letha@mondoo.com
=> tiny readme edits

apps/cnquery/cmd/scan.go
Let's make sure we use the right term
=> GCP account -> organization

motor/motorid/awsec2/metadata_local.go, motor/motorid/awsec2/metadata_local_test.go
Follow up to https://github.com/mondoohq/cnquery/pull/505#discussion_r1029250391
Always prefer the tags metadata service, if that is available. Fallback to aws API as a last resort
=> 🧹 Query tags metadata service for ec2 instance name if available.

motor/providers/k8s/api_provider.go
Fixes #510 
There is no way to disable that specific warning and I saw that other repos just copy-pasted the implementation of the function and stripped down the warnings. That's what I did as well
=> 🧹 Remove client-go warnings when scanning k8s assets

motor/providers/slack/provider.go
small improvements for the slack provider and removal of a typo
=> 🧹 slack provider improvements

apps/cnquery/cmd/login.go, apps/cnquery/cmd/root.go, cli/execruntime/env_mondoo_test.go, resources/packs/terraform/tfstate.go, resources/runtime.go, resources/service/service.proto, upstream/health/health.go
=> Minor spelling fixes

motor/providers/local/local_unix.go
=> 🐛 Fix file stat when run with sudo

apps/cnquery/cmd/scan.go
=> 🐛 Fix typo in incogito

resources/packs/aws/aws.go, resources/packs/azure/azure.go, resources/packs/core/ipmi.go, resources/packs/gcp/gcloud.go, resources/packs/github/github.go, resources/packs/gitlab/gitlab.go, resources/packs/k8s/common.go, resources/packs/ms365/ms365.go, resources/packs/ms365/msgraph.go, resources/packs/os/arista.go, resources/packs/os/equinix.go, resources/packs/terraform/terraform.go, resources/packs/vsphere/vsphere.go
=> transport -> providers in resource pack errors

motor/discovery/k8s/list_workloads.go, motor/providers/awsec2ebs/setup.go, motor/providers/microsoft/ms365/msgraphconv/structs.go, motor/providers/os/events/watcher.go, motor/providers/ssh/config.go, motor/providers/ssh/provider.go, mqlc/parser/operators.go, resources/packs/aws/aws_s3.go, resources/packs/azure/azure_rm_web.go, resources/packs/core/asset_advisories.go, resources/packs/core/authorizedkeys.go, resources/packs/core/certificates.go, resources/packs/core/certificates/cert.go, resources/packs/core/networkinterface/interface.go, resources/packs/core/networkinterface/interface_test.go, resources/packs/core/parsers/ini.go, resources/packs/core/tlsshake/tlsshake.go, resources/packs/core/users.go, resources/packs/k8s/kubelet_flags.go, resources/packs/ms365/msgraph.go, resources/packs/os/command.go, resources/packs/os/pam/parser.go, resources/packs/os/smbios/smbios.go, resources/packs/os/sshd/include.go, resources/packs/os/uptime/unix.go, resources/packs/os/uptime/unix_test.go, resources/packs/os/windows/secpol.go
=> More spelling fixes

llx/builtin.go, llx/builtin_simple.go, mqlc/builtin_array.go, resources/packs/core/core_test.go
=> 🐛 support string dict contains an array of strings

.github/workflows/pr-test-generated-files.yaml, .gitignore
=> 🧹 Clean protoc installation for each commit

.github/workflows/pr-test-generated-files.yaml
=> 🐛 Fix current path

motor/providers/terraform/hcl_parser.go, motor/providers/terraform/hcl_parser_test.go, motor/providers/terraform/provider.go
=> ✨ Recursively search for terraform hcl files

go.mod, go.sum, motor/discovery/aws/ecr.go, motor/discovery/aws/resolver.go
find public and private ecr registries and their images, use existing container image connection methods to connect to each asset
=> ⭐️ add ecr discovery to the aws resolver

motor/discovery/aws/ssm_instances.go
follow up to https://github.com/mondoohq/cnquery/pull/590
=> 🧹 do not try to use ssm session for `mi-` managed instances

apps/cnquery/cmd/scan.go, apps/cnquery/cmd/shell.go
We were missing a few things here and were using incorrect terms
=> Sync in CLI updates from cnspec

apps/cnquery/cmd/bundle.go, apps/cnquery/cmd/login.go, apps/cnquery/cmd/logout.go, apps/cnquery/cmd/plugin.go, apps/cnquery/cmd/root.go, apps/cnquery/cmd/run.go, apps/cnquery/cmd/scan.go, apps/cnquery/cmd/shell.go, apps/cnquery/cmd/status.go, apps/cnquery/cmd/version.go
Signed-off-by: misterpantz <letha@mondoo.com>
=> edited help strings

.github/workflows/goreleaser-edge.yml
Fixed a few typos and made sure we don't overwrite the latest and major version releases with an edge release
=> 🐛 Fix container edge releases

.github/.goreleaser-edge.yml
Signed-off-by: Ivan Milchev <ivan@mondoo.com>
=> 🐛 Fix cnquery path for edge releases

motor/discovery/aws/ec2_instances.go, motor/discovery/aws/ssm_instances.go
realized we weren't using pagination on the ec2 and ssm discovery..
=> 🧹 aws: use token pagination when discovering ec2 and ssm instances

README.md
Signed-off-by: Charles Johnson <chip@mondoo.com>
=> Update the README.md to mention Mondoo Console

resources/packs/gcp/cluster.go
I noticed this step was missing, so I added it now
=> 🐛 Close GCP container service when done

motor/discovery/common/projectname.go, motor/discovery/common/projectname_test.go
Fixes #https://github.com/mondoohq/cnspec/issues/238
=> 🧹 Explain we are scanning a directory

.github/actions/spelling/line_forbidden.patterns
Make sure we get these right as they flow into docs
=> Add AWS product names to spellcheck

apps/cnquery/cmd/builder/builder.go
Make these match the others in help
Paging @misterpantz for rewording
=> 🧹 Capitalize azure flag descriptions to match

motor/providers/aws/provider.go
```
[11/01/23 18:41:42] ❯ go run apps/cnquery/cnquery.go shell aws --profile gov
→ loaded configuration from /Users/vj/.config/mondoo/mondoo.yml using source default
cnquery> aws.ec2.instances { * }
aws.ec2.instances: [
0: {
launchTime: 2023-01-12 01:23:47 +0000 UTC
```
=> 🐛 aws: try govcloud region if default region does not work

resources/registry.go
This fixes a problem where the aliases would create an implicit resource for something that's an actual resource, e.g
```
alias gcloud.compute = gcp.project.computeService
```
with `gcp.project` being an LR resource too. If the alias resource runs first, it would create an implicit `gcp.project` which would then fail to merge with the real `gcp.project` as the implicit one has different private modifier and a different id.
With aliases running last, the `gcp.project` resource would already exist with proper definition.
Edit:
We normally fix this by making sure we alias at every level, e.g:
```
alias gcloud.project = gcp.project
alias gcloud.project.service = gcp.project.service
```
For the example above though, that wouldn't work as the alias is only 2 levels (gcloud and compute) whereas …
=> 🧹 Import resource aliases last.

.github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/reject.txt
Avoid a few other issues that have popped up
=> Add more terms to our spellcheck rules

apps/cnquery/cmd/builder/builder.go, cli/execruntime/env_aws_codebuild.go, motor/discovery/aws/ec2_instances.go
=> Capitalize some strings

resources/packs/gcp/kms.go
=> 🐛 Check if primary GCP cryptokey version is set before using it

cli/progress/multiprogress.go, cli/progress/multiprogress_test.go, explorer/scan/local_scanner.go
=> 🧹 Follow-up to fix some issues in the multi asset progressbars

apps/cnquery/cmd/builder/parse.go
This fixes an issue where the fallback to ssh-agent authentication was not working properly
=> 🐛 fix issue where ssh agent authentication is not working

resources/packs/gcp/compute.go
Make sure all compute backend services are retrieved:
```coffee
cnquery> gcp.project.compute.backendServices
gcp.project.compute.backendServices: [
0: gcp.project.computeService.backendService name="back-lb-1-test"
1: gcp.project.computeService.backendService name="backend-test-3"
2: gcp.project.computeService.backendService name="test-backend-2"
]
```
=> 🧹 Retrieve aggregated list of GCP compute backend services

cli/progress/multiprogress.go, cli/progress/multiprogress_mock.go, cli/progress/multiprogress_test.go, cli/progress/progress.go, explorer/executor/executor.go, explorer/scan/local_scanner.go, explorer/scan/scan.go
This PR
- fixes a race condition
- changes the way how Quit for the tea.Program is called
- Abstracts the tea.Program behind a new interface
=> 🧹 Refactor multiprogressbar

cli/progress/multiprogress.go, cli/progress/multiprogress_test.go, explorer/scan/local_scanner.go
=> 🐛 Handle motor error for progress bar

cli/reporter/csv.go, cli/reporter/csv_test.go, cli/reporter/reporter.go, cli/reporter/testdata/kubernetes_report.json
**Problem**
I want to export cnquery data quickly in CSV to see the data in my favorite spreadsheet app.
**Solution**
```
cnquery scan ssh chris@34.123.123.123 --output csv > report.csv
```
The response data from the query is stored in json.
You can open the report in your favorite app then:
=> ⭐️ CSV export

cli/reporter/cli.go
=> 🐛 Show errors when all assets errored

cli/progress/multiprogress.go
This is a refactor and follow-up to the discussion in a previous PR: https://github.com/mondoohq/cnquery/pull/831#discussion_r1086841109
This is no visible change to the user.
=> 🧹 Simplify locking

explorer/scan/local_scanner.go, logger/log.go
=> 🧹 Hide progressbars when debug logging is enabled

cli/components/components.go, cli/progress/multiprogress.go, cli/progress/multiprogress_test.go, go.mod
- move asset name the left
- full width progress bar
- percentage + score is on the right
https://user-images.githubusercontent.com/1178413/214160738-212eff31-154d-4fc3-a2d1-6cc72335134b.mov
=> ⭐️ full width progress bar

apps/cnquery/cmd/builder/builder.go, resources/packs/core/dnsshake/dkim_test.go, resources/packs/core/gem/lockfile.go, resources/packs/core/networkinterface/interface.go, upstream/health/health.go
=> Fix typos in code and comments

motor/discovery/gcp/mql_asset_objects.go, motor/discovery/gcp/mql_assets.go
**Does not change anything user-facing**
This makes our code simpler since we no longer need to cast every field we query.
=> 🧹 Refactor GCP GetList to return typed results

apps/cnquery/cmd/plugin.go, apps/cnquery/cmd/shell_run.go, explorer/scan/local_scanner.go, motor/inventory/manager.go
We also don't expose public things on inventoryManager and instead expose a method on the interface
=> 🐛Make inventoryManager implement the InventoryManager interface

apps/cnquery/cmd/vault.go, motor/inventory/manager.go, motor/vault/config.go, motor/vault/keyring/keyring.go, motor/vault/keyring/keyring_test.go
https://github.com/mondoohq/cnquery/pull/893 back-ported to v7
=> ⭐️ vault subcommand to manage vaults

motor/platform/detector/detector.go, motor/providers/okta/okta.go, motor/providers/runtime.go
```
asset: {
kind: "api"
build: ""
version: ""
title: "Okta Organization"
arch: ""
labels: {}
platform: "okta-org"
runtime: "okta"
ids: [
0: "00o8..."
]
name: "Okta organization dev-....okta.com"
fqdn: ""
family: [
0: "okta"
]
}
```
=> ✨ add more info to okta providers and asset info

motor/platform/detector/platform_resolver.go, motor/providers/container/docker_engine/docker_engine.go
=> 🐛 Fix detection of containers build from scratch

.github/actions/spelling/expect.txt, .github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/patterns.txt
Remove some overly broad rules
=> Update spellcheck patterns

explorer/filters.go, explorer/filters_test.go
=> 🧹 helper for filter creation

internal/datalakes/inmemory/query_conductor.go
This is only on the API level so far, but it enables us to unset properties if they have been overwritten. Generally we don't need this in the single-client context, but it is in line with the cnspec change (see https://github.com/mondoohq/cnspec/pull/360 for more context) and provides a way for the client to unset properties.
=> 🐛 allow properties to be removed

motor/providers/microsoft/provider.go, resources/packs/azure/azure_rm_web.go, resources/packs/os/windows/security_health.go
Doing this to quiet later automation
=> URL / copy updates in comments

motor/discovery/gcp/resolver_gcp.go, resources/packs/gcp/folder.go
Since the CLI and the folder scan were in 2 separate PRs, there were some minor issues that had to be fixed before that started working
=> 🐛 Fix GCP folder scanning

explorer/query_hub.go
switches cnquery to use the new registry
=> ⭐️ switch to new registry

README.md, docs/development.md
fix broken links
add and change docs links
formatting
style/consistency
=> :page_facing_up: readme and dev doc edits

resources/packs/os/services/manager.go
It's Debian under the hood and it's been systemd since 2015.
=> Add support for detecting services on Kali Linux

.vscode/launch.json, apps/cnquery/cmd/bundle.go, apps/cnquery/cmd/plugin.go, apps/cnquery/cmd/scan.go, apps/cnquery/cmd/shell.go
This also adds the upstream config to all commands executed as plugin.
Fixes #956
=> 🐛 Add upstream config to run command

.github/workflows/goreleaser.yml
Refer to https://github.com/mondoohq/releasr#releasr for more details.
=> ⭐️ Invoke releasr after build

resources/packs/googleworkspace/domain.go
fixes an issue where we parse the time wrongly
=> 🧹 backport google workspace fix

motor/discovery/aws/ec2_instances.go, motor/discovery/aws/ecr.go, motor/discovery/aws/ecs.go, motor/discovery/aws/resolver.go, motor/discovery/aws/ssm_instances.go
follow up to the discovery refactor i just did, we need the pass in labels to make sure we add in the integration mrn label when discovering from the context of lambda
=> 🧹 add pass in labels to aws discovery

explorer/impact.go, explorer/impact_test.go, explorer/mquery.go
also add `Checksum()` call to `Impact` and have it flow into the mquery checksum
=> 🐛 validate impact value + 🧹 restructure

motor/discovery/k8s/resolver.go
Fixes #1022
This does not make running queries against a cluster for which we have no namespace rights possible. We need to figure out what to do with the platformID generation for a cluster. At the moment the UID of the kube-system namespace is used. However, it is not always the case that we have access to that
=> 🧹 Make listing k8s namespaces optional

.github/dependabot.yml
Make sure we keep this up to date. Also lint the file
=> Add dockerfile dependabot scanning

motor/providers/microsoft/provider.go
Clean up of old inventory options
=> 🧹 Cleanup of deprecated azure/ms365 inventory options.

apps/cnquery/cmd/builder/common/common.go, apps/cnquery/cmd/builder/parse.go, motor/discovery/gcp/resolver_gcp.go, motor/discovery/gcp/resolver_org.go, motor/discovery/gcp/resolver_project.go
removed the deprecated flags that are supposed to be gone in v8
=> 🧹 cleanup GCP provider flags

apps/cnquery/cmd/builder/parse.go, motor/discovery/k8s/resolver.go
=> 🐛 remove deprecated flags from k8s provider

explorer/filters.go, explorer/filters_test.go, explorer/query_conductor.go
For an easier access to all filters in the struct
=> 🔨 filters.summarize

.github/workflows/goreleaser.yml, .goreleaser.yml
For details of the method, please refer to https://github.com/mondoohq/mac-signer
=> Sign and Notarize Mac Binaries

motor/discovery/k8s/common.go, motor/discovery/k8s/resolver_cluster.go
also alphabetize the order of the list of resources that get auto-discovered
=> 🧹 add Ingresses to the auto-discovered k8s resources

explorer/property.go
The existing code didn't behave correctly if with various combinations of mrn and uid set. For example, in some places, we may have both UID and MRN explictly set. In other places, only MRN is explicitly set.
The UID checking is only necessary so you don't have to specify the full mrn from the CLI. These are now kept separate. We merge by mrn. If there also exists a UID only property set somewhere, that gets merged into the final result.
=> 🐛 fix handling of uid based property merging

.github/workflows/goreleaser-edge.yml, .github/workflows/goreleaser.yml
Caching has been slow and unreliable on upload and download.  Lets disable it.
=> 🧹 Disable Go Caching

README.md
Simplifies the install instruction
=> 🧹 update install instructions for cnquery

Makefile, resources/lr/cli/cmd/markdown.go
fixes https://github.com/mondoohq/cnquery/issues/1049
=> ⭐️ improve MQL resource docs description

motor/discovery/resolve.go
https://github.com/mondoohq/cnspec/issues/525
=> 🧹 ensure asset name is set to override asset name flag value if used

motor/platform/detector/platform_test.go, motor/providers/runtime.go
seems like this is no longer used in the code
=> 🧹 remove k8s runtime

go.mod, go.sum
Use the upstream slack-go module instead of my fork
=> 🧹 use upstream slack-go

motor/discovery/k8s/list_workloads.go, motor/discovery/k8s/resolver_test.go, motor/providers/k8s/manifest_parser.go, motor/providers/k8s/manifest_parser_test.go, motor/providers/k8s/resources/testdata/deployment-nons.yaml, motor/providers/k8s/resources/testdata/mixed.yaml
fixes #1157
also added a test for manifests containing resources with no namespace
=> 🐛 discover k8s assets with no namespace when scanning manifests

feature_string.go, featureflags.go
Needed for https://github.com/mondoohq/cnspec/pull/540
=> 🧹 Add feature flag for errors as failures

motor/discovery/docker_engine/resolver.go, motor/discovery/github/github.go, motor/discovery/vsphere/vm_guest_resolver.go, motor/discovery/vsphere/vsphere_resolver.go, motor/motorid/clouddetect/providers/aws/aws.go, motor/motorid/clouddetect/providers/azure/azure.go, motor/motorid/clouddetect/providers/gce/gce.go, motor/motorid/motorid.go, motor/platform/detector/detector_test.go, resources/packs/os/docker.go, resources/packs/os/equinix.go, resources/packs/os/services.go, resources/packs/vsphere/vsphere.go
This should be all the public facing errors
=> 🧹 Rename more transport -> provider

resources/packs/github/github_repo.go
=> 🐛 Fix GitHub repo for user owned repos

apps/cnquery/cmd/plugin.go
=> 🐛 Add default http client to upstream config for the run cmd.

resources/packs/terraform/hcl.go
Fixes: https://github.com/mondoohq/cnspec/issues/585
=> 🐛 support parsing of parenthesis hcl expressions

cli/reporter/reporter.go
Fixes #392
```
~/go/bin/cnquery scan -o yaml                  
→ no provider specified, defaulting to local.
Use --help for a list of available providers.
→ loaded configuration from /Users/preslavgerchev/.config/mondoo/mondoo.yml using source default
→ synchronize assets
assets:
//assets.api.mondoo.app/spaces/peaceful-lewin-815181/assets/2MpgOzufE8ZHpxblwgENoaul7o7:
mrn: //assets.api.mondoo.app/spaces/peaceful-lewin-815181/assets/2MpgOzufE8ZHpxblwgENoaul7o7
name: Preslav-Gerchev.local
data: {}
errors:
//assets.api.mondoo.app/spaces/peaceful-lewin-815181/assets/2MpgOzufE8ZHpxblwgENoaul7o7: asset
doesn't support any policies
```
=> 🐛 Add support for YAML output.

resources/packs/os/os.go
closes #685 
Fallback to hostname instead of returning ""
=> :bug: fix os.name not returning a value

resources/packs/core/dns.go
This ensures the order of the dns record list is stable:
**before**
```coffeescript
cnquery> dns('salesforce.com').records
dns.records: [
0: dns.record name="salesforce.com." type="A"
1: dns.record name="salesforce.com." type="DNSKEY"
2: dns.record name="salesforce.com." type="SOA"
3: dns.record name="salesforce.com." type="NS"
4: dns.record name="salesforce.com." type="NSEC3PARAM"
5: dns.record name="salesforce.com." type="DS"
6: dns.record name="salesforce.com." type="MX"
]
cnquery> dns('salesforce.com').records
dns.records: [
0: dns.record name="salesforce.com." type="DS"
1: dns.record name="salesforce.com." type="MX"
2: dns.record name="salesforce.com." type="A"
3: dns.record name="salesforce.com." type="DNSKEY"
4: dns.record name="salesforce.com." type="SOA"
5: dns.record …
```
=> 🧹 ensure the dns record list has always the same order

docs/development.md
Generally used for things that improve speed, but we will also include general performance improvements.
We have wanted an emoji here for a while, but most others don't work well. We checked https://emojicombos.com/speed and found:
- 🏍 no color in many cases, wonky in CLI
- 🏎️ often problematic in CLI 
- 💨 not very evident that this is speed (looks like a fart)
- 🏁 looks more like the goal, rather than speed
- 🚄 good alternative to ⚡
⚡ reminds us of the flash, so comics, superheroes, and lightning fast speed
=> 📃 add indicator for commits that improve performance

cli/shell/nyago.go, cli/shell/shell.go, docs/development.md, go.mod, go.sum
also fix the missing spaces in the dev docs that were messing up the formatting
=> 🐛 bump version + backport missing command

apps/cnquery/cmd/scan.go, apps/cnquery/cmd/shell.go
Make sure we have a description in the generated docs.
=> Add missing GCP docs

apps/cnquery/cmd/run.go
Copy over the basic structure of how this was done in the scan file.
=> Add docs to cnquery run

apps/cnquery/cmd/vault.go
Align the case and tense with other command docs
=> Cleanup cnquery vault docs

apps/cnquery/cmd/bundle.go, apps/cnquery/cmd/login.go, apps/cnquery/cmd/logout.go, apps/cnquery/cmd/scan.go, apps/cnquery/cmd/shell.go
Pull in some things from cnspec. Update other things. Misc cleanup
=> Sync + improve command docs

apps/cnquery/cmd/bundle.go, apps/cnquery/cmd/logout.go, apps/cnquery/cmd/run.go, apps/cnquery/cmd/scan.go, apps/cnquery/cmd/shell.go
More syncs from cnspec this time so we can get these docs generating nicely
=> 🧹 A few other minor tweaks to help

apps/cnquery/cmd/bundle.go, apps/cnquery/cmd/run.go, apps/cnquery/cmd/shell.go
Things were found on the cnspec side
=> More helps/docs fixes from review

.github/actions/spelling/advice.md, .github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/patterns.txt
=> Update spellcheck pattern matches

resources/packs/os/services/manager.go
It's a systemd distro.
Fixes https://github.com/mondoohq/cnquery/issues/1341
=> Detect services on raspbian Linux

Makefile, README.md
Also fixed error in OPC UA text
=> 🧹 Update README

cli/printer/printer_test.go, providers-sdk/v1/resources/resources.go, providers-sdk/v1/testutils/testutils.go, providers/mock/mock.go, providers/os/resources/file.go, providers/os/resources/file_test.go, providers/recording.go, providers/runtime.go
After https://github.com/mondoohq/cnquery/pull/1362
one step closer to test coverage, 11 failing remaining
=> 🔨 migrate printer test + parameterized test utils

apps/cnquery/cmd/builder/common/common.go, apps/cnquery/cmd/scan.go
Make things a bit more uniform
=> Minor updates to help for better docs generation

cli/printer/printer_test.go, explorer/scan/local_scanner.go, llx/builtin_resource.go, mql/mql_test.go, providers-sdk/v1/lr/go.go, providers-sdk/v1/testutils/testdata/arch.json, providers/core/resources/core.lr.go, providers/os/id/aws/aws_test.go, providers/os/id/awsec2/metadata_cmd_test.go, providers/os/id/awsecs/awsecs_test.go, providers/os/id/azcompute/azcompute_test.go, providers/os/id/gce/gce_test.go, providers/os/id/gcp/gcp_test.go, providers/os/id/hostname/hostname_test.go, providers/os/id/platformid/linux_test.go, providers/os/id/platformid/osx_test.go, providers/os/id/platformid/win_test.go, providers/os/resources/file.go, providers/os/resources/groups/manager_test.go, providers/os/resources/os.lr.go, providers/os/resources/smbios/smbios_test.go, providers/os/resources/users/manager_test.go, providers/recording.go, providers/runtime.go
- restore resourceWhere to the new plugin system
- only set resource IDs when necessary (in LR generator)
- create resource with ID support
- sort resources in recording
only 7 remaining, but we need more os resources
=> ✨ migrate where for resources

motor/discovery/aws/mql_asset_objects.go
global dynamo db tables do not have tags
=> 🧹 remove tags from aws global dynamodb table discovery

apps/cnquery/cmd/providers.go, go.mod, go.sum, providers/providers.go
=> ⭐ install provider from file

apps/cnquery/cmd/providers.go, providers-sdk/v1/lr/go.go, providers/core/resources/core.lr.go, providers/os/resources/os.lr.go, providers/providers.go
=> ✨ providers install --url <url>

cli/providers/providers.go
After https://github.com/mondoohq/cnquery/pull/1412
... to:
```bash
> cnquery --record file.json
> cnquery --use-recording file.json
> cnquery --record file.json --pretty
```
=> ✨ update recording cli options 

motor/platform/detector/detector_test.go, motor/platform/detector/parser_linux_version.go, motor/platform/detector/parser_linux_version_test.go, motor/platform/detector/platform_specs.go, motor/platform/detector/testdata/detect-opensuse-11.toml, motor/platform/detector/testdata/detect-suse-sles-10.toml, motor/platform/detector/testdata/detect-suse-sles-11.toml
This adds platform detection of suse systems without /etc/os-release
=> ⭐️ add suse 11 platform detection

go.mod, go.sum
Fixes errors when running commands for docker containers
=> 🧹 update docker module

resources/packs/os/updates/suse_updates.go, resources/packs/os/updates/suse_updates_test.go, resources/packs/os/updates/testdata/updates_zypper.toml
port of https://github.com/mondoohq/cnquery/pull/1423 to v8
=> 🐞 add non-interactive flag to the zypper command

_motor/providers/aws/provider.go
=> Add space in AWS RDS DB Instance platform name

_motor/discovery/aws/mql_asset_objects.go, _motor/providers/aws/provider.go, _resources/packs/aws/aws_cloudwatch.go
These show up in the asset overview now
=> Fix more typos in platform names

_motor/discovery/aws/mql_asset_objects.go, _motor/providers/aws/provider.go
I promise this is the last commit here. Fixing a few concatenated names that are not actually brands.
=> 🧹 More AWS resource brand name updates

motor/discovery/aws/mql_asset_objects.go, motor/providers/aws/provider.go, resources/packs/aws/aws_cloudwatch.go
=> 🧹 Fix platform names that get used in asset overview pages

.github/workflows/providers.yaml, scripts/provider_bundler.sh
- Generate SHA256 Checksums 
- Trigger Reindex of release after upload
=> Provider Release Improvements

resources/packs/aws/aws_ec2.go
=> 🐛 Use bool value and not pointer for entry.Egress

providers/os/connection/local_windows.go, providers/os/detector/windows/build_version_windows.go, providers/os/detector/windows/wmi_windows.go, providers/os/id/platformid/win_guid_windows.go, providers/os/resources/os.lr.go, scripts/provider_bundler.sh
- fixes the build of the os provider for windows
- re-activates windows builds for publishing
=> 🐛 fix windows build of v9 os provider

providers/os/resources/command.go
since we use it a lot across resources
=> ✨ introduce a shortcut runCommand

apps/cnquery/cmd/vault.go, go.mod, go.sum, motor/inventory/manager.go, motor/inventory/v1/inventory.go, motor/vault/config/vaultconfigstore.go
The sub-command has not worked properly when there were permission errors for the local keyring. That features was barely used since you can embedded vault configuration in inventory files.
Lets assume you have an inventory file like:
```yaml
apiVersion: v1
kind: Inventory
spec:
assets:
- name: vsphere
connections:
- backend: vsphere
host: 192.168.5.24
credentials:
- secret_id: my-secret
discover:
targets:
- host-machines
credentials:
my-secret:
type: password
user: chris@vsphere.local
password: myPassword
```
You can easily scan the inventory via `cnquery scan --inventory-file inventory.yaml`. `cnquery` allows you to use external vault systems to store secrets. To generate the correct config for vault, you can use:
```
$ cnquery vault configure mondoo-client-vault --type encrypted-file …
```
=> 🐛 fix vault sub-command

resources/packs/terraform/terraform_test.go, resources/packs/terraform/testdata/tfplan-replace-paths/tfplan.json, resources/packs/terraform/tfplan.go, resources/packs/terraform/tfplan_test.go
Fixes https://github.com/mondoohq/cnspec/issues/689
=> 🐛 Fix unmarshal for terraform plan `replace_paths`

resources/packs/aws/aws_ec2.go, resources/packs/aws/aws_secretsmanager.go
fixes https://github.com/mondoohq/cnquery/issues/1468
fixes https://github.com/mondoohq/cnquery/issues/1467
=> 🐛 aws secrets manager and security groups resource fixes

apps/cnquery/cmd/shell.go, explorer/scan/local_scanner.go, providers-sdk/v1/inventory/manager/manager.go, providers/runtime.go
=> 🐛 fix inventory resolution and shell requirement on valid configuration

mqlc/parser/parser.go
For example, if you use the number 089, that will cause a panic because 9 is not valid octal.
=> 🐛 Don't let parseValue panic on bad input

apps/provider-scaffold/provider-scaffold.go, apps/provider-scaffold/provider-scaffold_test.go, apps/provider-scaffold/template/config/config.go.template, apps/provider-scaffold/template/connection/connection.go.template, apps/provider-scaffold/template/gen/main.go.template, apps/provider-scaffold/template/go.mod.template, apps/provider-scaffold/template/main.go.template, apps/provider-scaffold/template/provider/provider.go.template, apps/provider-scaffold/template/resources/providerid.go.template, apps/provider-scaffold/template/resources/providerid.lr.template
Quick start to get a new provider with the base files:
```bash
go install apps/provider-scaffold/provider-scaffold.go
provider-scaffold --path providers/vsphere --provider-id vsphere --provider-name "VMware vSphere" --go-package go.mondoo.com/cnquery/providers/vsphere
```
=> ⭐️ provider scaffolding

motor/discovery/gcp/mql_asset_objects.go
fixes https://github.com/mondoohq/cnquery/issues/1507
=> 🧹 add region to subnet name for gcp to help differentiate

providers/slack/config/config.go, providers/slack/provider/provider.go, providers/slack/resources/accesslogs.go, providers/slack/resources/conversations.go, providers/slack/resources/team.go, providers/slack/resources/usergroups.go, providers/slack/resources/users.go
=> 🧹 improve slack provider

motor/discovery/gcp/resolver_org.go, motor/discovery/gcp/resolver_project.go
fixes https://github.com/mondoohq/cnquery/issues/1584
=> 🧹 log gcp asset discovery err instead of returning

apps/provider-scaffold/template/provider/provider.go.template, providers/github/provider/provider.go, providers/gitlab/provider/provider.go, providers/ipmi/provider/provider.go, providers/oci/provider/provider.go, providers/okta/provider/provider.go, providers/opcua/provider/provider.go, providers/os/provider/provider.go, providers/slack/provider/provider.go, providers/terraform/provider/provider.go, providers/vsphere/provider/provider.go
We used conn for a config and a connection.
This confused me multiple times during reviews.
=> 🧹 Refactor conn var to conf

resources/packs/gcp/project.go
fixes https://github.com/mondoohq/cnquery/issues/1599
=> 🐛 skip discovering gcp projects marked for deletion

Makefile, providers/ms365/resources/ms365.lr.go, providers/ms365/resources/ms365.lr.manifest.yaml
We don't seem to be generating the .yaml manifests for the LR definitions, so I've added that in
Additionally, I've ran that for ms365.
=> 🧹 Generate YAML LR manifest

Makefile, providers/ms365/provider/provider.go
also fix the runtime initialization in the provider to work again
=> 🐛 add missing ms365 in make providers/build

providers/gcp/config/config.go, providers/gcp/provider/provider.go, providers/gcp/resources/discovery.go
- add `auto` and `all` discovery
- fix bigquery dataset discovery issue
- fix bigquery dataset platform ID
=> 🐛 gcp discovery fixes

apps/cnquery/cmd/plugin.go, providers/builtin.go, providers/core/provider/provider.go
Thanks to @preslavgerchev , we found this.
Fixes #1654
=> 🐛 Fix asset data for multiple assets

explorer/scan/local_scanner.go, providers/aws/config/config.go, providers/aws/connection/connection.go, providers/aws/provider/provider.go, providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_ecs.go, providers/aws/resources/discovery.go, providers/aws/resources/discovery_conversion.go, providers/os/connection/shared/shared.go
fixes https://github.com/mondoohq/cnquery/issues/1640
=> v9 aws fixes

providers/aws/config/config.go
thanks to @czunker for the catch on this, https://github.com/mondoohq/cnquery/pull/1642#discussion_r1321636162
=> 🐛 fix aws config

.github/workflows/providers.yaml
Make sure all the providers are built and released
=> 🔨 build and release all providers

providers/os/resources/machine.go, providers/os/resources/os.lr.go
=> 🐛 fix machine resource

providers/k8s/connection/admission/connection.go, providers/k8s/connection/api/connection.go, providers/k8s/connection/manifest/connection.go, providers/k8s/connection/shared/connection.go, providers/k8s/resources/discovery.go, providers/k8s/resources/platform_ownership.go
- Added platform ownership for k8s
- Set platform runtime correctly
- Make sure we don't execute discovery multiple times
=> ✨ implement related assets for k8s provider

.github/dependabot.yml
Update dependabot to also check providers.
=> 🧹 Check go.mod for providers

providers-sdk/v1/resources/schema.go
We never merged the Name and the min version
=> 🐛 add missing fields to schema merge

providers/gcp/resources/gcp.lr
Fixes https://github.com/mondoohq/cnquery/issues/1504
=> ✨ add more gcp resource defaults

providers/aws/resources/aws_ec2.go
Ported https://github.com/mondoohq/cnquery/pull/1508
Fixes https://github.com/mondoohq/cnquery/issues/1510
=> 🐛 Fix networkAcl portRange and egress

providers/os/config/config.go, providers/os/connection/docker_container.go, providers/os/provider/provider.go, providers/os/resources/discovery/docker_engine/container.go, providers/os/resources/discovery/docker_engine/images.go, providers/os/resources/discovery/docker_engine/resolver.go
2nd try after https://github.com/mondoohq/cnquery/pull/1701
This fixes the issue reported in https://github.com/mondoohq/cnquery/pull/1760
=> ✨ Add container discovery to v9 os provider

providers/aws/resources/aws.lr, providers/aws/resources/aws_rds.go
Migrate https://github.com/mondoohq/cnquery/pull/1435 to v9
Fixes https://github.com/mondoohq/cnquery/issues/1473
=> ✨ Add autoMinorVersionUpgrade to rds instance

providers-sdk/v1/vault/hashivault/hashivault.go, providers-sdk/v1/vault/hashivault/hashivault_test.go
Migrate https://github.com/mondoohq/cnquery/pull/1459
Fixes https://github.com/mondoohq/cnquery/issues/1476
=> 🐛 fix hashi vault

motor/discovery/gitlab/gitlab.go
to test with env var:
`DEBUG=1 go run apps/cnquery/cnquery.go shell gitlab --group mondoolabs`
to test with passed in token:
`unset SSH_AUTH_SOCK`
`DEBUG=1 go run apps/cnquery/cnquery.go shell gitlab --group mondoolabs --token value`
please give this a good round of testing before merging!
=> 🧹 clean up gitlab discovery and fix bad platformids for tf

providers/os/resources/packages/rpm_packages.go, providers/os/resources/packages/rpm_updates.go, providers/os/resources/packages/rpm_updates_test.go, providers/os/resources/packages/testdata/updates_zypper.toml, providers/os/resources/services/sysv.go
Migrate https://github.com/mondoohq/cnquery/pull/1469 and other follow-on PRs. I ran a diff for `sysv.go` and migrated a few more things from latest v8.
Fixes https://github.com/mondoohq/cnquery/issues/1475
=> 🐛 fixes for suse linux

providers/defaults.go
=> Make provider short descriptions more consistent

providers/os/provider/provider.go
=> 🐛 Add host key to ssh connection platform id

providers-sdk/v1/util/configure/configure.go, providers/os/connection/vagrant.go, providers/os/provider/detector.go, providers/os/provider/provider.go
=> 🐛 Fix vagrant asset information

providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml
Autogenerated after the backport from v8
=> Add missing AWS LR entries

providers/network/resources/dns.go
fixes https://github.com/mondoohq/cnquery/issues/1720
=> 🐛 fix 1720: error in dns fields parsing

providers/aws/resources/aws.lr.manifest.yaml, providers/equinix/resources/equinix.lr.manifest.yaml, providers/gcp/resources/gcp.lr.manifest.yaml, providers/k8s/resources/k8s.lr.manifest.yaml, providers/network/resources/network.lr.manifest.yaml, providers/oci/resources/oci.lr.manifest.yaml, providers/okta/resources/okta.lr.manifest.yaml, providers/opcua/resources/opcua.lr.manifest.yaml, providers/os/resources/os.lr.manifest.yaml, providers/terraform/resources/terraform.lr.manifest.yaml
Get it so that `make providers/build` doesn't leave files in the git repo. This is a combo of what was generated + min version data from these files in v8.
=> Add missing lr.manifest.yaml entries

providers/gitlab/resources/gitlab.go, providers/gitlab/resources/gitlab.lr, providers/gitlab/resources/gitlab.lr.go, providers/gitlab/resources/gitlab.lr.manifest.yaml
Another really useful bit of data for the asset overview
=> ⭐ Add createdAt to the gitlab.group resource

providers/gcp/resources/discovery.go
see https://github.com/mondoohq/cnquery/issues/1856
fixes the first problem
=> 🧹 make gcp asset platform info match v8

providers/github/resources/github_org.go, providers/github/resources/github_repo.go, providers/github/resources/github_user.go
The child object might be non-pointers, but their parents are all pointers now. Correctly handle nil-values.
=> 🐛 fix time parsing in github

providers/github/resources/github.lr.manifest.yaml
Slap a few more release versions in here
=> Add missing versions in the GH LR file

providers-sdk/v1/util/version/version.go
The line you can use in your browser to open the git commit.
=> 🧹 add info line on version update

docs/development.md, providers-sdk/v1/util/version/version.go
Note: This is written assuming that all providers have had at least one release. I'm in the process of closing that gap :)
=> 📃 dev guide on provider versioning

providers/github/resources/discovery.go, providers/github/resources/github_org.go
=> 🐛 Fix GitHub org name

motor/providers/gitlab/platform.go
i get 32 projects with this, 20 without
=> 🧹 add pagination to gitlab projects fetching

providers/os/connection/container/image/disk.go, providers/os/connection/container/image/docker.go, providers/os/connection/docker_container.go, providers/os/connection/tar.go, providers/os/resources/discovery/container_registry/resolver.go
=> 🐛 Fetch and save container images only once

scripts/provider_bundler.sh
=> 🐛 Add file extension to windows binaries

providers/okta/provider/provider.go
=> 🐛 Fix okta asset name.

providers/github/provider/provider.go
=> 🐛 Do not try and parse github repo if owner is set.

go.sum, providers/gitlab/connection/connection.go, providers/gitlab/go.mod, providers/gitlab/go.sum, providers/gitlab/provider/discovery.go, providers/gitlab/provider/provider.go, providers/gitlab/resources/gitlab.lr, providers/terraform/provider/provider.go
Massive overhaul to the discovery code to make it clearer, reduce duplicate calls to the API, and make it ready for groups discovery.
It also now discovers Terraform assets, the next PR will have the terraform+git implementation to use these.
=> ✨ discover terraform in gitlab + overhaul discovery

providers/terraform/connection/hcl_manifest.go
After https://github.com/mondoohq/cnquery/pull/1976
=> 🛡 do not leak credentials on git clone in logs

providers/k8s/connection/api/connection.go
Logic ported from v8: when using in-cluster config for connecting to the k8s api, use the first node's name as cluster name
=> 🐛 fix k8s provider panic for incluster config

providers/gitlab/provider/discovery.go
New projects without a commit are ok and not an error. Handle this accordingly.
This avoids warnings like:
```
cnquery shell gitlab --group example --discover terraform
x failed to discover terraform repo in gitlab error="GET https://gitlab.com/api/v4/projects/52400234/repository/tree: 404 {message: 404 Tree Not Found}"
```
=> 🧹 handle case where gitlab project has no commit yet

cli/printer/mql.go, cli/printer/printer_test.go
=> 🐛 fix printing of nested structures

providers/github/resources/github.lr, providers/github/resources/github.lr.go, providers/github/resources/github.lr.manifest.yaml, providers/github/resources/github_org.go, providers/github/resources/github_repo.go
Use new things in the updated library
=> ⭐ Add more properties to github.organization and github.repository

providers/terraform/provider/provider.go
My previous PR https://github.com/mondoohq/cnquery/pull/1975 messed up the interaction with Terraform on the CLI. It optimized it for connection handover (like we do with GitLab to Terraform), but missed the point on fully supporting the CLI.
This PR restores the CLI options.
=> 🐛 fix terraform cli interaction

providers/aws/resources/aws.lr.manifest.yaml, providers/azure/resources/azure.lr.manifest.yaml, providers/ms365/resources/ms365.lr.manifest.yaml, providers/os/resources/os.lr.manifest.yaml
Diffing back some content from the v8 LR files
=> Add back more LR content that didn't make it to v9

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_s3.go
This is a handy this to know for the asset overview
=> Add creationDate to aws.s3.bucket resource

providers/terraform/resources/tfstate.go
i mentioned the err here: https://github.com/mondoohq/cnquery/pull/1990
=> 🐛 fix panic on uninitialized tf state

providers/equinix/config/config.go
With the updated CLI you can connect to Equinix Metal organization and project to gather information.
```
cnquery shell equinix org 2f44c505-b506-4889-b598-7f13769907f3 --token <token>
→ connected to Equinix Metal
cnquery> equinix.metal.organization { * }
equinix.metal.organization: {
createdAt: 2021-03-02 20:28:20 +0100 CET
updatedAt: 2023-08-27 11:38:32 +0200 CEST
users: [
0: equinix.metal.user email="chris@example.com"
]
mainPhone: ""
website: ""
taxId: ""
description: "Example Metal Infra"
address: {
address: ""
country: ""
zip_code: ""
}
creditAmount: 0
url: …
```
=> 🐛 fix equinix cli

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_vpc.go, providers/aws/resources/shared.go
#1794
first time making changes to providers, so please review carefully. 
Example usage
I wasn't sure what kind of fields to add here. Just went with `id` and `cidrs` for now - there's probably more that could make sense.
=> ✨ Add AWS VPC subnet resource

providers/coordinator.go
After: https://github.com/mondoohq/cnquery/pull/2015
See the comment in code: 
If the plugin was not in active use, we may not have a client at this
point. Since all of this is run within a sync-lock, we can check the
client and if it exists use it to send the kill signal.
=> 🐛 correctly shutdown plugin clients

apps/cnquery/cmd/shell.go
fixes https://github.com/mondoohq/cnspec/issues/746
=> 🐛 get value of incognito for shell (instead of always true)

.github/workflows/pr-test-lint.yml
Runs provider tests in our lint pipeline
=> ⭐️ run provider tests in pipeline

providers-sdk/v1/util/version/version.go
The version tool will also check if the provider go dependencies have changed since the 
last version and will suggest to update them as well. To just clean up the go.mod
and go.sum files, run:
$ version mod-tidy providers/*/ 
To update all provider go dependencies to the latest patch version, run:
$ version mod-update providers/*/ --patch 
To update all provider go dependencies to the latest version, run:
$ version mod-update providers/*/ --latest
=> ⭐️ make version tool more smart for go dependency updates

providers/github/resources/github.lr, providers/gitlab/resources/gitlab.lr
Minor updates since these feed the docs
=> Fix typos in GitHub/GitLab descriptions

providers/k8s/resources/discovery.go
=> 🧹 k8s cluster auto discovery

providers/providers.go
fixes #2047
**Install cnquery without any provider**
```
PS C:\Users\Administrator\Downloads> .\cnquery.exe providers list                                
- builtin (found 2 providers)
core 9.0.1
mock 9.0.0 with connectors: mock
- C:\Users\Administrator\.config\mondoo\providers has no providers
- C:\ProgramData\Mondoo\providers has no providers
PS C:\Users\Administrator\Downloads> .\cnquery.exe shell                                         
- installing provider 'os' version=9.0.7
- successfully installed os provider path="C:\\Users\\Administrator\\.config\\mondoo\\providers\\os" version=9.0.7
- no provider specified, defaulting to local. Use --help to see all providers.
- no Mondoo configuration file provided, using defaults
- connected to Microsoft Windows Server 2022 Datacenter …
```
=> 🐛 fix provider installation for windows

providers/k8s/resources/discovery.go
sets the asset category for discovered assets based on the root asset
=> 🐛 set asset category for discovered k8s assets

providers/azure/resources/discovery.go
fixes https://github.com/mondoohq/cnquery/issues/2054
=> 🐛 fix panic in azure discovery

providers/slack/provider/provider.go
=> 🐛 report slack name and runtime

cli/providers/providers.go
We were still getting some leftover warnings on CLI flags. To work around this issue, this PR changes the way the detection works:
1. All unknown flags are now blindly accepted. These flags will continue to show up in the CLI and for the vast majority of use-cases they don't matter. At this early stage we don't have to get it right.
2. Only add root and attaching command flags now. This means we no longer recurse deep into all commands that exist under the root command. This saves a ton of time. Only works because of (1).
=> 🐛 avoid warnings on unknown CLI flags

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_ecr.go, providers/ms365/resources/ms365.lr.manifest.yaml, providers/terraform/resources/terraform.lr, providers/vcd/resources/externalnetworks.go, providers/vcd/resources/vcd.lr, providers/vcd/resources/vcd.lr.go
Fixes: https://github.com/mondoohq/cnquery/issues/2088
=> 🐛 fix v8 compat issues

mqlc/mqlc.go, providers-sdk/v1/lr/go.go, providers-sdk/v1/plugin/runtime.go, providers/terraform/resources/hcl.go, providers/terraform/resources/terraform.lr, providers/terraform/resources/terraform.lr.go, providers/terraform/resources/terraform.lr.manifest.yaml
This reverts commit 020a75032cbe986c5dc7c8b0e32059a10592bfb1.
We have to make this compatible with v8 compiled code before releasing.
=> Revert "⭐ terraform.resources( filter ) (#2069)"

providers-sdk/v1/util/version/version.go
I make the mistake of forgetting it every single time I've released providers...
=> ✨ automatically signoff version updates

providers/k8s/resources/discovery.go
Something that we forgot to implement in v9 but it is needed by the mondoo-operator. To test this use the following inventory file:
```yaml
apiVersion: v1
kind: Inventory
metadata:
name: inventory
spec:
assets:
- connections:
- type: k8s
options:
k8s-resources: pod:default:nginx,deployment:mondoo-operator:mondoo-operator-controller-manager
discover:
targets:
- auto
```
run it with `cnquery scan k8s --inventory-file inv.yaml`. Only the pod `nginx` in the `default` namespace and the pod `mondoo-controller-manager` in the `mondoo-operator` namespace should be scanned
=> ✨ implement k8s resource filters

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_vpc.go
=> ✨ Add AWS VPC Endpoints

providers-sdk/v1/lr/cli/cmd/docs.go, providers/gcp/resources/gcp.lr.manifest.yaml, providers/terraform/resources/terraform.lr.manifest.yaml
This was a great catch by @tas50 Thank you
=> 🧹 update platform mappings for the docs

providers/defaults.go
We have complete sentences and then weird fragments. Update everything to match by including the actual objects in these providers we're scanning.
=> Improve consistency of our scan help

providers/network/resources/dns.go, providers/network/resources/dns_test.go
=> 🐛 Fix dns.fqdn when connection via IP

providers/k8s/connection/shared/resources/util.go, providers/k8s/resources/testdata/nginx-deployment.yaml, providers/k8s/resources/unsupported_test.go
=> 🐛 Add error message for unsupported k8s API version

Makefile
https://goreleaser.com/deprecations/\#-skip
=> 🧹 Fix deprecated goreleaser flags

.github/actions/spelling/expect.txt, providers/azure/resources/azure.lr, providers/azure/resources/azure.lr.go, providers/azure/resources/azure.lr.manifest.yaml, providers/azure/resources/monitor.go, providers/azure/resources/network.go
The new resources:
- virtual networks
- virtual network gateways
- load balancers
- subnets
- nat gateways
- firewalls
- firewall policies
- application security groups
Still need to do:
cc @HRouhani, feel free to test it out. I have added most of the stuff that was required, but ping me if there's something missing
=> ✨ Add new azure network resources

providers/ms365/provider/provider.go
Ran into this while working on new resources. 
Note I coudn't reproduce afterwards though but best to keep this consistent with the other providers
=> 🧹 Add StoreData impl for ms365 provider.

providers/azure/resources/azure.lr.manifest.yaml
```
azure.subscription.network.virtualNetworks
Unable to run query, cnquery version 9.0.4 required
```
I had the wrong patch version here
=> Downgrade new azure resources to 9.0.3 min mondoo version.

providers/azure/config/config.go
=> 🎉 azure-9.0.9

providers/aws/resources/aws.lr.manifest.yaml
=> Update new AWS policies to ship in 9.0.3

providers/terraform/resources/hcl.go
fixes https://github.com/mondoohq/cnspec/issues/832
=> 🐛 avoid adding nil tf blocks when fetching related blocks

providers/aws/config/config.go, providers/terraform/config/config.go
=> 🎉 aws-9.0.14, terraform-9.0.13

providers/aws/resources/aws.lr, providers/os/resources/os.lr
A few issues came up during release notes review
=> MQL docs updates from review

providers/aws/resources/aws.lr.go, providers/aws/resources/aws_apigateway.go, providers/aws/resources/aws_cloudtrail.go, providers/aws/resources/aws_cloudwatch.go, providers/aws/resources/aws_dynamodb.go, providers/aws/resources/aws_ec2.go, providers/aws/resources/aws_ecr.go, providers/aws/resources/aws_ecs.go, providers/aws/resources/aws_elb.go, providers/aws/resources/aws_kms.go, providers/aws/resources/aws_lambda.go, providers/aws/resources/aws_rds.go, providers/aws/resources/aws_redshift.go, providers/aws/resources/aws_s3.go, providers/aws/resources/aws_sagemaker.go, providers/aws/resources/aws_ssm.go
=> 🐛 Fix aws dynamodb table init function, make all AWS init funcs use the mql cache

providers/aws/config/config.go, providers/azure/config/config.go, providers/ms365/config/config.go
=> 🎉 aws-9.0.15, azure-9.0.10, ms365-9.0.9

providers/terraform/config/config.go
=> 🎉 terraform-9.0.14

providers/network/resources/http.go, providers/network/resources/network.lr, providers/network/resources/network.lr.go, providers/network/resources/network.lr.manifest.yaml, providers/network/resources/url.go
We are starting with one specific use-case, but it's a fun one:
```coffee
http.get('https://www.gov.uk') { version statusCode header.sts }
```
which gets us:
```coffee
http.get: {
statusCode: 200
header.sts: http.header.sts maxAge=365 days  includeSubDomains=false preload=true
version: "2.0"
}
```
=> ⭐ http.get + url + STS support

providers/network/resources/http.go, providers/network/resources/network.lr, providers/network/resources/network.lr.go, providers/network/resources/network.lr.manifest.yaml
After https://github.com/mondoohq/cnquery/pull/2213
=> ✨ add Content-Type + Set-Cookie headers

providers/github/go.mod, providers/github/go.sum, providers/google-workspace/go.mod, providers/google-workspace/go.sum
=> 🐛 Downgrade participle to fix provider build

Makefile, providers/atlassian/resources/atlassian.lr
=> Generate Atlassian docs via makefile

.github/dependabot.yml
Add this to the list of others
=> Setup Dependabot for the Atlassian provider

.github/actions/spelling/expect.txt, providers/azure/resources/azure.lr
Use the branding that Azure has on their blogs about this stuff.
=> Update resource names for docs

.github/actions/spelling/expect.txt, providers/atlassian/config/config.go
followup on https://github.com/mondoohq/cnquery/pull/2253
=> 🧹 add help to atlassian provider

providers/gitlab/connection/connection.go
the id is always more stable
tested with `DEBUG=1 go run apps/cnquery/cnquery.go scan gitlab  --url https://gitlab.lunalectric.com --discover groups,projects  --group lunalabs --token TOKEN`
=> 🧹 always prefer gitlab group id over gitlab group name

providers/atlassian/connection/admin/connection.go, providers/atlassian/connection/confluence/connection.go, providers/atlassian/connection/jira/connection.go, providers/atlassian/connection/scim/connection.go
=> 🐛 ensure that atlassian connection authenticated successfully

providers/atlassian/config/config.go, providers/gcp/config/config.go, providers/gitlab/config/config.go, providers/os/config/config.go
=> 🎉 atlassian-9.0.2, gcp-9.0.11, gitlab-9.0.10, os-9.0.14

cli/printer/mql.go, mqlc/mqlc.go, mqlc/mqlc_stats.go
```
Resources and Fields used:
- aws.iam
- credentialReport  type=[]aws.iam.usercredentialreportentry
- aws.iam.usercredentialreportentry
- accessKey1Active  type=bool
- userCreationTime  type=time
- accessKey1LastRotated  type=time
- arn  type=string
- time
- now  type=time
- day  type=time
```
=> ✨ provider type + sorting in compiler info

providers-sdk/v1/plugin/runtime.go
Expose some helper functions to work with the plugin State flags
=> 🧹 Add helper functions for State flags.

providers/atlassian/config/config.go, providers/aws/config/config.go, providers/azure/config/config.go, providers/core/config/config.go, providers/os/config/config.go
=> 🎉 atlassian-9.0.3, aws-9.0.17, azure-9.0.12, core-9.0.4, os-9.0.15

providers/azure/go.mod, providers/azure/go.sum, providers/azure/resources/advisor.go, providers/azure/resources/azure.lr, providers/azure/resources/azure.lr.go, providers/azure/resources/azure.lr.manifest.yaml, providers/azure/resources/cloud_defender.go, providers/azure/resources/keyvault.go, providers/azure/resources/monitor.go, providers/azure/resources/network.go, providers/azure/resources/subscription.go
New resources/fields:
* Application gateway
* Application firewall policy
* Advisor recommendations
* Advisor overall score
* Advisor scores by category
* Add `rbacAuthorizationEnabled` to key vaults
=> ✨ Add more azure resources

providers/azure/config/config.go
=> 🎉 azure-9.0.13

providers-sdk/v1/util/version/version.go
on the update command we use for development of cnquery only
=> 🧹 remove duplicate registered commands

cli/sysinfo/sysinfo.go
=> 🐛 Fix platform in status output

apps/cnquery/cmd/root.go, go.mod, go.sum, test/cli/cli_test.go, test/cli/testdata/cnquery.ct, test/cli/testdata/cnquery_providers.ct, test/cli/testdata/cnquery_run.ct, test/cli/testdata/cnquery_scan.ct, test/cli/testdata/cnquery_vault.ct
This PR sets up a basic infra to do cli testing with https://github.com/google/go-cmdtest
=> ⭐️ basic cli testing

apps/cnquery/cmd/scan.go, explorer/scan/local_scanner.go
https://github.com/mondoohq/cnspec/pull/885
=> 🐛 fix --asset-name flag

.github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/patterns.txt, .github/workflows/spell-check.yaml
Sync over some docs site changes
=> Updates to patterns in spellcheck

providers/azure/resources/azure.lr
Remove ID which is not very useful and instead show data that would be helpful to a user.
=> 🧹 Update the azure vault default fields

explorer/scan/local_scanner.go
On distributeJob, we create runtimes but only shut them down at the end of the execution. However, it is possible to exit this function before all runtimes have been executed, i.e. before they all have a chance to shut down properly. With this deferred function we make sure all new runtimes are terminated.
=> 🧹 make sure all asset runtime are shut down after job

providers/coordinator.go
When using heartbeats, currently the provider has a chance to start and execute the heartbeat async. This means that for commands like run and shell (and others), we gett confusing error messages:
```bash
> make cnquery/install && cnquery run aws -c asset.eol
x please update the provider plugin for aws plugin-ID=go.mondoo.com/cnquery/v9/providers/aws
→ loaded configuration from /home/zero/.config/mondoo/mondoo.yml using source default
FTL failed to run query error="rpc error: code = Canceled desc = grpc: the client connection is closing"
```
The mechanism in this PR is much more proactive at checking the heartbeat first, before returning a running provider, thus eliminating confusing errors:
```bash
> make cnquery/install && cnquery shell aws -c asset.eol
FTL failed to start provider aws …
```
=> ✨ early heartbeat failure

apps/cnquery/cmd/scan.go
It is possible to specify the same querypack multiple times in the CLI. This leads to unexpected results. For now, deduplicate to avoid bugs.
--- side note: ---
Also i think I had the weirdest bug:
```bash
cnquery scan -f qp.mql.yaml
```
resulted in duplicate args from the CLI: 
```go
[]string len: 2, cap: 2, ["qp.mql.yaml","qp.mql.yaml"]
```
I cannot explain why this happend, all we have is a regular `viper.GetStringSlice("querypack-bundle")` call
=> 🐛 deduplicate querypacks

providers/network/resources/tls_test.go, providers/network/resources/tlsshake/tlsshake.go, utils/multierr/errors.go, utils/multierr/errors_test.go
We have not done the error handling properly. This PR adds resource tests to see those earlier next time.
=> 🐛 fix network error handling

providers/network/config/config.go
=> 🎉 network-9.1.1

providers/azure/resources/azure.lr
Improve the data we return in a few more places by default
=> ⭐ More improvements to the Azure defaults

providers/aws/resources/aws.lr
Improve the default output we use in our query packs.
=> Update defaults in the AWS resources

providers/atlassian/config/config.go, providers/atlassian/connection/admin/connection.go, providers/atlassian/connection/confluence/connection.go, providers/atlassian/connection/connection.go, providers/atlassian/connection/jira/connection.go, providers/atlassian/connection/scim/connection.go, providers/gitlab/connection/connection.go
=> Update wording in Atlassian error messages

providers/azure/resources/azure.lr, providers/vsphere/resources/vsphere.lr
=> 🧹 Minor updates for MQL docs generation

mqlc/mqlc.go, mqlc/mqlc_test.go
Fixes https://github.com/mondoohq/cnquery/issues/2223#issuecomment-1780528051
=> 🐛 do not panic on empty list assertions

providers/azure/resources/mysql.go
=> 🐛 Fix azure mysql resources.

providers/gcp/resources/gcp.lr
Changed to draft while I'm figuring out my signing issue!
=> 📄  Updates GCP resource docs

providers/azure/config/config.go
=> 🎉 azure-9.1.1

providers/network/resources/tls.go
=> 🐛 fix tls.certificates is not properly initialized

providers/azure/resources/azure.lr
Show the type and location as well
=> Improve the defaults for Azure Monitor Application Insights

providers/aws/resources/aws_account.go, providers/aws/resources/aws_ec2.go, providers/aws/resources/discovery_conversion.go
the first thing is a guard for https://github.com/mondoohq/cnquery/issues/2344
also added some labels we depend on for ebs scans on pre-discovered assets
=> 🧹 fixups for aws ebs scanning and ec2 image fetch

providers/aws/config/config.go, providers/azure/config/config.go, providers/network/config/config.go, providers/os/config/config.go
=> 🎉 aws-9.1.2, azure-9.1.2, network-9.1.3, os-9.1.2

providers/os/provider/provider.go
The brain fixes them on the fly, but once you they are there...
=> 🐛 Fix typos

providers/k8s/config/config.go, providers/k8s/connection/manifest/connection_test.go, providers/k8s/resources/discovery.go
Fixes https://github.com/mondoohq/cnspec/issues/862
=> 🐛 Add back discover all to k8s provider

providers/gcp/resources/compute.go, providers/gcp/resources/gcp.lr.go
Fixes https://github.com/mondoohq/cnspec/issues/863
=> 🐛 Fix panic in GCP compute instance

providers/ipmi/resources/ipmi.lr, providers/k8s/resources/k8s.lr
- Updates k8s resource docs to follow the usage practices of the official Kubernetes Documentation
- Makes docs a bit more helpful
- Corrects grammar issues
=> 📄  Edits IPMI and K8s resource docs

cnquery.go, cnquery_test.go
=> 🐛 fix comments and add tests for latest release

.github/actions/spelling/expect.txt, providers/aws/resources/aws.lr, providers/core/resources/core.lr, providers/gcp/resources/gcp.lr, providers/k8s/resources/k8s.lr, providers/ms365/resources/ms365.lr, providers/network/resources/network.lr, providers/oci/resources/oci.lr, providers/okta/resources/okta.lr, providers/opcua/resources/opcua.lr, providers/os/resources/os.lr
- Changes for consistency, grammar, helpfulness
- Adds missing help for some fields
=> 📄  Edits auto-generated documentation entries, m through o

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_cloudfront.go, providers/aws/resources/aws_dynamodb.go, providers/aws/resources/aws_s3.go
More improvements to resources in AWS
=> :star: Expand fields and defaults in AWS

providers/slack/resources/slack.lr, providers/terraform/resources/terraform.lr, providers/vcd/resources/vcd.lr, providers/vsphere/resources/vsphere.lr
=> Doc improvements S through V

llx/rawdata_json.go, llx/rawdata_json_test.go
Fixes https://github.com/mondoohq/server/issues/6811
=> 🐛 fix json escaping

providers/ms365/config/config.go
=> 🎉 ms365-9.2.0

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_ec2.go
=> Add ipv6CidrBlock to aws.ec2.networkacl.entry

.github/workflows/pr-test-lint.yml, Makefile, explorer/cnquery_explorer.proto, explorer/scan/cnquery_explorer_scan.proto, llx/llx.proto, providers-sdk/v1/inventory/inventory.proto, providers-sdk/v1/plugin/plugin.proto, providers-sdk/v1/upstream/health/health.proto, providers-sdk/v1/upstream/mvd/cvss/cvss.proto, providers-sdk/v1/upstream/mvd/mvd.proto, providers-sdk/v1/upstream/upstream.proto, providers-sdk/v1/vault/vault.proto, shared/proto/cnquery.proto
This brings in protolint to ensure we follow best practices for proto definition. It does not change existing proto files but allows us to be more consistent going forward.
=> 🧹 enable protolint

providers/os/resources/cpe/platforms.go, providers/os/resources/cpe/platforms_test.go
after #2615 
This simplified the CPE generation and harmonizes the approaches we've see for different platforms.
=> 🧹 simplify cpe platform detection

.github/workflows/pr-test-lint.yml
Fix
```
fatal: ambiguous argument 'HEAD~1..HEAD': unknown revision or path not in the working tree.
```
=> 🐛 Fix dependabot PR main ref

.github/workflows/pr-test-lint.yml, providers/os/connection/docker_container.go, providers/os/connection/docker_container_test.go
=> 🐛 Fix asset.name for remote images

providers-sdk/v1/util/version/version.go
This extends the existing `version` cli to ignore specific packages if required:
```
version mod-update . --latest --ignore-packages github.com/alecthomas/participle  
```
=> ⭐️ allows us to ignore specific packages from upgrade in version command

providers/runtime.go
When an auxiliary provider is detected, its connection errors currently don't propagate after the initial connect call.
Example: You are connecting to AWS and request `asset{*}`. This will request fields form the `os` provider, including `cpes` and `vulnerabilityReport`.
The first call to `cpes` will fail to connect (as it should) and the error will be reported. On the second call (when we request `vulnerabilityReport`) it will return the provider during `provider := r.providers[info.Provider]; provider != nil `. However, that provider now doesn't have a valid connection.
This PR adds the connection errors as a stable field within the provider and also returns them on returning a cached provider.
Fixes https://github.com/mondoohq/cnquery/issues/2724
I'd love to follow-up on this to not …
=> 🐛 cascade provider connection errors

.github/workflows/update-deps.yaml
Aliases need to be enabled: https://github.com/actions/toolkit/issues/766#issuecomment-928305811
=> 🐛 Fix alias in GHA

.github/workflows/update-deps.yaml
This should fix:
```
could not compute title or body defaults: failed to run git: fatal: ambiguous argument 'origin/main...version/deps_update_20231204': unknown revision or path not in the working tree.
```
https://github.com/mondoohq/cnquery/actions/runs/7084820555/job/19279851001
=> 🐛 Fix create PR in GHA

providers/atlassian/config/config.go
All other providers include v9.
=> 🧹 Align atlassian provider ID

providers-sdk/v1/inventory/inventory_test.go, providers-sdk/v1/inventory/testdata/ssh_inventory.yaml, providers/os/provider/provider.go, providers/os/provider/provider_test.go
=> 🐛 ssh connections act more like IdentitiesOnly

providers/network/provider/provider.go
Fixes https://github.com/mondoohq/cnquery/issues/2760
=> fix asset name for host assets

sbom/cyclonedx.go
bug introduced in https://github.com/mondoohq/cnquery/pull/2791
=> 🐛 update to latest cyclone-dx behaviour

providers/terraform/config/config.go, providers/terraform/connection/hcl_manifest.go, providers/terraform/connection/hcl_manifest_test.go, providers/terraform/connection/hcl_schema.go, providers/terraform/provider/provider.go, providers/terraform/resources/hcl.go
=> ⭐️ allow users to ignore .terraform directory

.github/pr-body.md, .github/workflows/pr-test-lint.yml, .github/workflows/update-deps.yaml
This should help to debug, why we didn't have tests for the last PR.
=> Debug GHA PRs

providers/aws/resources/aws.lr
Per @mariuskimmina's feedback (thank you!)
=> fixes some AWS WAF doc strings

providers/aws/config/config.go
=> 🎉 aws-9.1.17

providers/k8s/connection/manifest/connection.go, providers/k8s/connection/manifest/connection_test.go, providers/k8s/connection/manifest/testdata/mondoo-operator-manifests.yaml, providers/k8s/connection/manifest/testdata/no-discovered-objects.yaml
=> 🐛 Fix platform IDs for operator manifests

providers/aws/resources/aws.lr.manifest.yaml
- Make them all 9.0 since we provider update
- Add missing fields by going over the release notes
=> 🐛 Update + add min_mondoo_version to AWS

providers/aws/config/config.go, providers/aws/resources/discovery.go
https://github.com/mondoohq/cnquery/issues/2623
=> 🧹 re-enable ec2 & ssm instances api discovery

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_dynamodb.go, providers/aws/resources/aws_vpc.go
Expand DynamoDB and VPC resources.
=> More fields in AWS resources

providers/ms365/connection/exchange_report.go, providers/ms365/connection/teams_report.go, providers/ms365/resources/ms365.go, providers/ms365/resources/ms365.lr, providers/ms365/resources/ms365.lr.go, providers/ms365/resources/ms365.lr.manifest.yaml
all documented here:  https://www.notion.so/mondoo/MS365-Foundations-85e65eacdb4f42baaeee6c2d57bb7622
**********
Regarding sharepoint, I did my best to change the pnpTenant module to following, and did many test, but somehow the SPOservice has problem with mfa connection:
We need this to cover some more tests.....
var sharepointReport = `
$ErrorActionPreference = "Stop"
$token = '%s'
$url = "%s"
Install-Module Microsoft.Online.SharePoint.PowerShell -Force -Scope CurrentUser
Import-Module Microsoft.Online.SharePoint.PowerShell -DisableNameChecking
Connect-SPOService -Credential $token -Url $url -ModernAuth true -AuthenticationUrl https://login.microsoftonline.com/organizations
$SPOTenant = (Get-SPOTenant)
$SPOTenantSyncClientRestriction = (Get-SPOTenantSyncClientRestriction)
$sharepoint = …
=> 🧹   improve ms365 resources

providers/slack/config/config.go
=> 🎉 slack-9.1.11

providers/ms365/connection/sharepoint_report.go, providers/ms365/resources/groups.go, providers/ms365/resources/ms365.lr, providers/ms365/resources/ms365.lr.go, providers/ms365/resources/ms365.lr.manifest.yaml, providers/ms365/resources/structs.go
* Add `visibility` to `microsoft.group`
* Add `AllowedToCreateTenants` to the auth policy in `microsoft.policies`
* Ensure PnP version is set to latest so we get back all the required props. Use `-EnumsAsStrings` to get a better representation for the enums in there
=> ✨ Multiple ms365 resource updates

providers/slack/connection/connection.go, providers/slack/resources/conversations.go
- global retry logic for slack api
- exclude archived channels for `slack.conversations.publicChannels` and `slack.conversations.privateChannels`
=> 🧹 introduce retry handling for slack api

providers/slack/config/config.go
=> 🎉 slack-9.1.12

providers/slack/resources/accesslogs.go, providers/slack/resources/conversations.go
implements the logic from slack https://api.slack.com/methods/conversations.list
=> 🐛 use max limit value for slack which is lower than 1000

providers/k8s/connection/manifest/connection_test.go, providers/k8s/provider/provider.go, providers/k8s/resources/discovery.go
We had this check in v8 and lost it during migration.
=> 🐛 Add back k8s node feature flag check

providers/aws/resources/aws_guardduty.go
This was copied from the codebuild file
=> Fix incorrect error message in guardduty

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_ecs.go
Also use StringDataPtr where we can
=> ⭐ Add region to aws.ecs.cluster + improve defaults

sbom/cnquery_bom_test.go, sbom/report_collection.go, sbom/sbom.go, sbom/sbom_test.go
This PR ensures that the platform ids are also added to the sbom
=> ⭐️ includes the platform ids and ec2 instance arn in sbom exports

providers/ms365/config/config.go
=> 🎉 ms365-9.2.10

providers/azure/resources/azure.lr
=> E-mail to Email in docs

apps/cnquery/cmd/status.go, cnquery.go, cnquery_test.go
=> 🐛 fix status cmd behind proxy

README.md
=> Use HTTPS for the Console link

providers/aws/resources/aws_rds.go
```
cnquery> aws.rds.dbClusters { * }
aws.rds.dbClusters: [
0: {
0: aws.ec2.securitygroup id="sg-e1b634b7" name="default" region="us-east-1" vpc.id="vpc-7f775605"
]
multiAZ: false
engineVersion: "8.0.mysql_aurora.3.02.0"
deletionProtection: false
status: "available"
clusterDbInstanceClass: null
members: [
0: aws.rds.dbinstance id="database-1-instance-1" region="us-east-1" engine="aurora-mysql" engineVersion="8.0.mysql_aurora.3.02.0"
]
engine: "aurora-mysql"
tags: {}
storageType: null
backupRetentionPeriod: 1
storageEncrypted: true
autoMinorVersionUpgrade: true
storageIops: 0
createdTime: 2024-01-04 12:11:02.918 -0700 MST
id: "database-1"
snapshots: []
publiclyAccessible: null
arn: "arn:aws:rds:us-east-1:ID:cluster:database-1"
storageAllocated: 1
}
] …
```
=> 🐛 fix aws rds dbclusters members

llx/builtin.go, llx/builtin_map.go, llx/builtin_simple.go, mqlc/builtin.go, mqlc/builtin_simple.go, providers/core/resources/mql_test.go, providers/os/resources/mql_test.go
=> ✨ support dict.inRange for numbers

providers/azure/config/config.go
=> 🎉 azure-9.2.0

providers-sdk/v1/testutils/testdata/windows.json, providers/os/resources/auditpol.go, providers/os/resources/auditpol_test.go
fixes https://github.com/mondoohq/cnquery/issues/2782
=> 🐛 enforce utf8 for auditpol on windows

providers/aws/config/config.go, providers/os/config/config.go, providers/vsphere/config/config.go
=> 🎉 aws-9.1.24, os-9.1.19, vsphere-9.1.17

providers/os/resources/vulnmgmt.go
Some CVEs do not have a publish or modified date. Do not exit in these case.
Fixes #2995
=> 🐛 Do not exit on time parse errors

providers/ms365/config/config.go
=> 🎉 ms365-9.2.14

providers/aws/provider/provider.go, providers/azure/connection/azureinstancesnapshot/provider_test.go, providers/azure/connection/azureinstancesnapshot/snapshot.go, providers/azure/resources/compute.go, providers/azure/resources/resourceid.go, providers/gcp/connection/gcpinstancesnapshot/snapshot.go, providers/os/resources/vulnmgmt.go, providers/terraform/provider/provider.go, providers/vsphere/resources/vulnmgmt.go
=> 🧹 Fix a few minor types in variables/log messages

providers/ms365/resources/securescores.go
Fixes #3048 by ensuring we have the proper latest security score. Until now, we always fetched the *earliest*, not the latest one.
This PR also ensures that the `secureScores` resource is being re-used for `latestSecureScore` as well, saving a redundant API call towards MS graph
=> 🐛 Fix fetching of latest security score.

.github/workflows/pr-test-lint.yml, .github/workflows/test-report.yml
This PR also makes sure we use the same test reporting action as for other repos
=> 🧹 fix test reporting

providers/azure/resources/azure.lr, providers/azure/resources/azure.lr.go, providers/azure/resources/azure.lr.manifest.yaml, providers/azure/resources/network.go, providers/azure/resources/network_test.go
=> ✨ Add direction to network security rules. Ensure destination port ranges are always populated

providers/aws/resources/aws_applicationautoscaling.go, providers/aws/resources/aws_elb.go, providers/aws/resources/discovery.go
fixes 
https://github.com/mondoohq/cnquery/issues/2853
https://github.com/mondoohq/cnquery/issues/2912
https://github.com/mondoohq/cnquery/issues/2903
https://github.com/mondoohq/cnquery/issues/2893
this is rfr
=> 🧹 aws resource fixes

explorer/property.go
Instead of using reflections to copy this object, manually copy the object instead. We have a bit more maintenance in the code, but gain a good chunk of speed and memory-friendliness with this approach.
=> ⚡ use copy instead of proto.clone for property

providers/azure/config/config.go, providers/network/config/config.go, providers/slack/config/config.go
=> 🎉 azure-10.0.2, network-9.1.10, slack-10.0.2

providers/azure/resources/mysql.go, providers/azure/resources/postgresql.go
=> 🐛 Fix wrong resource name for sql firewall rules.

providers/azure/config/config.go
=> 🎉 azure-10.0.3

providers/azure/resources/azure.lr, providers/azure/resources/azure.lr.go, providers/azure/resources/azure.lr.manifest.yaml, providers/azure/resources/compute.go
Adds 3 new properties to the azure compute VMS:
* `zones`
* `state` - either `unknown`, `stopped` or `running`
* `isRunning` -> a shortcut for verifying that `state == 'running'`
=> ✨ Add zones, state, isRunning properties to azure compute VMs.

providers/aws/resources/aws_s3.go
Fixes https://github.com/mondoohq/cnspec/issues/1087
=> 🐛 avoid panics when trying to get s3 bucket location

providers/aws/config/config.go, providers/azure/config/config.go
=> 🎉 aws-10.0.4, azure-10.0.6

providers/ms365/config/config.go
=> 🎉 ms365-10.0.4

docs/development.md
2 little things I missed in my review
=> dev docs quick fix

providers/aws/resources/aws_cloudwatch.go, providers/aws/resources/aws_ec2.go, providers/aws/resources/aws_iam.go
fixes https://github.com/mondoohq/cnquery/issues/3179
fixes https://github.com/mondoohq/cnquery/issues/3178
=> 🐛 fix crash on aws.iam.virtualMfaDevices & logGroup.metricsFilters alarms failure

.github/actions/spelling/line_forbidden.patterns
Bring in a few we're using in docs
=> Sync over additional spellcheck patterns

.github/actions/spelling/expect.txt, .github/actions/spelling/line_forbidden.patterns, providers/arista/resources/arista.lr, providers/gcp/resources/gcp.lr
=> Fix typos in MQL docs + update spellcheck rules

providers/atlassian/resources/atlassian.lr.manifest.yaml
atlassian.jira.applicationRole is the true name now
=> Remove unused field that is a typo

providers/aws/config/config.go
=> 🎉 aws-10.0.7

providers/os/provider/detector.go
fixes https://github.com/mondoohq/cnquery/issues/3261
=> 🐛 make sure the os provider always returns unique platform ids

providers/aws/config/config.go
=> 🎉 aws-10.1.2

providers/aws/resources/aws_dms.go, providers/aws/resources/aws_ec2.go, providers/aws/resources/aws_elasticache.go, providers/aws/resources/shared.go
especially in cases where users have region deny set up, this error can cause chaos!
fixes https://github.com/mondoohq/cnquery/issues/3246
=> 🐛 ensure we catch all 403 access denied errors

providers/os/id/sshhostkey/sshhostkey.go
=> 🐛 make sure ssh host key detector reads from target connection

providers/os/resources/python/mime.go, providers/os/resources/python/python.go, providers/os/resources/python/python_test.go, providers/os/resources/python/requirestxt_test.go
Cleans up the python resource a bit and add more tests.
=> 🧹 refactor python resource helper

providers/os/resources/cpe/pkg2cpe.go, providers/os/resources/cpe/pkg2cpe_test.go, providers/os/resources/npm/npm.go, providers/os/resources/npm/npm_test.go, providers/os/resources/npm/package_json.go, providers/os/resources/npm/package_json_test.go, providers/os/resources/npm/package_lock.go, providers/os/resources/npm/package_lock_test.go, providers/os/resources/npm/yarn_lock.go, providers/os/resources/npm/yarn_lock_test.go, providers/os/resources/packages/rpm_packages_test.go, providers/os/resources/packages/windows_packages_test.go
This adjusts the npm package parsing to enrich it Purl and CPE information.
=> ⭐️ generate purl & cpe for npm packages

providers/aws/config/config.go
=> 🎉 aws-10.2.2

providers/ms365/config/config.go
=> 🎉 ms365-10.2.2

apps/provider-scaffold/template/config/config.go.template, apps/provider-scaffold/template/go.mod.template
Update to v10 and the latest golang release
=> Update the provider scaffold

.github/actions/spelling/line_forbidden.patterns, explorer/scan/discovery.go, llx/code.go, providers/gcp/resources/pubsub.go
It's correct in the .lr file, but wrong where it's set.
Also fix a few other misc things and update the spellcheck matchers
=> 🐛 Fix a gcp resource field typo

providers/gitlab/config/config.go
=> 🎉 gitlab-10.2.3

providers/gitlab/config/config.go
=> 🎉 gitlab-10.2.5

providers/github/config/config.go
=> 🎉 github-10.2.4

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_config.go
Finally solved the problem:
It should be array based on following:
=> 🧹  Improving by adding resourcetypes to AWS config recorder (aws)

apps/cnquery/cmd/shell.go
If we have a single asset, we need to select it
=> 🐛 Fix shell: select asset if just one.

providers/os/resources/port.go
fixes https://github.com/mondoohq/cnquery/issues/2957
=> 🐛 handle case where ipv4 or ipv6 is disabled

providers/os/config/config.go, providers/vsphere/config/config.go
=> 🎉 vsphere-10.2.4, os-10.2.2

providers/aws/resources/aws.lr.manifest.yaml
Make sure we have 2 spaces not 1 here so the indent is correct
=> Minor fix to formatting in docs

providers/aws/resources/aws_cloudtrail.go
fixes https://github.com/mondoohq/cnquery/issues/3374
=> 🐛 ensure we return an err when cloudtrail trail cannot be found

providers/aws/config/config.go, providers/os/config/config.go
=> 🎉 aws-10.2.7, os-10.2.4

providers/github/config/config.go
=> 🎉 github-10.2.7

providers/ms365/config/config.go
=> 🎉 ms365-10.2.6

providers/aws/resources/aws_cloudtrail.go
related to:  https://github.com/mondoohq/cnquery/issues/3370  and 
https://github.com/mondoohq/cnspec-enterprise-policies/pull/726
=> ⭐️ Added support for advanced selector (aws)

providers/os/resources/os.lr
Get this in before shipping 10.6 docs
=> Minor typo fix in field description

.github/actions/spelling/line_forbidden.patterns
=> Update spellcheck forbidden terms

providers/gcp/config/config.go
=> 🎉 gcp-10.3.2

providers/gcp/resources/bigquery.go, providers/gcp/resources/compute.go, providers/gcp/resources/gke.go, providers/gcp/resources/iam.go, providers/gcp/resources/storage.go
multiple resources didn't properly return errors on init if not found. That caused panics
=> 🐛 fix init for GCP resources

providers/aws/config/config.go, providers/os/config/config.go
=> 🎉 aws-10.3.3, os-10.3.3

providers/gcp/resources/common.go, providers/gcp/resources/compute.go
=> 🐛 implement gcp.project.computeService.attachedDisk.source

providers/gcp/config/config.go
=> 🎉 gcp-10.3.4

providers-sdk/v1/inventory/asset_url.go, providers-sdk/v1/inventory/asset_url_test.go
I need these changes to properly integrate with the asset url changes
=> 🧹 Bug fixes and additional helpers for asset urls

providers/os/resources/cpe/platforms.go
This is an LTS release shipping next month
=> Add Ubuntu 24.04 to CPE generation

providers/aws/resources/aws_iam.go
fixes https://github.com/mondoohq/cnquery/issues/3582
=> 🐛 fix aws iam {attachedRoles {*}} query

explorer/filters.go, explorer/mquery.go
=> 🧹 make filter checksum calculation re-usable

.github/actions/spelling/expect.txt, .github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/patterns.txt
=> Update spellcheck configs

providers/ms365/resources/groups.go
Fetch more than 100 groups if present
=> 🐛 Fetch all microsoft groups using the iterator.

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_rds.go
- hostedZoneId
- masterUsername
- latestRestorableTime
=> Add new fields for AWS RDS DB instances and clusters

providers/coordinator.go, providers/providers.go
This makes the update provider function public accessible so that we can use that same function in packer to solve https://github.com/mondoohq/packer-plugin-cnspec/issues/207
=> 🧹 move provider update to providers.go

providers/network/config/config.go
=> 🎉 network-10.3.0

providers/os/id/aws/aws.go
There is no need in continuously trying to get the identity multiple times if different sysfs things tell us its amazon. If any say its amazon, we try to get the instance metadata once.
=> 🧹 cleanup aws detect function

.github/actions/spelling/patterns.txt, .github/workflows/cla.yaml, .github/workflows/link-check.yaml, providers/arista/resources/eos/README.md
Automate myself out of a job for the better
=> Find dead markdown links via GHA

providers-sdk/v1/inventory/asset_url.go, providers/providers.go
add a function to make the asset url schema from the providers
=> 🧹 Add function to load the asset url schema for all known providers

providers/aws/config/config.go
=> 🎉 aws-10.5.1

providers/gcp/config/config.go
=> 🎉 gcp-10.5.1

providers/aws/resources/aws.lr.go, providers/aws/resources/aws_cloudtrail.go
to improve the speed of queries like `aws.cloudtrail.trail.kmsKey != null` https://github.com/mondoohq/cnquery/issues/3224
=> 🧹 improve the aws.cloudtrails.trail query

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws_ec2.go
improve the aws ec2 instance resource -- see https://github.com/mondoohq/cnquery/issues/3224
=> 🧹 improve aws ec2 instance resource

providers/aws/resources/aws.lr, providers/aws/resources/aws_inspector.go
Improve the auto generated docs a bit
=> Minor updates to AWS LR file for docs

providers/aws/resources/aws_s3.go
fixes https://github.com/mondoohq/cnquery/issues/3800
=> 🐛 fix aws.s3.bucket acl grant

providers/aws/resources/aws.lr, providers/core/resources/core.lr
=> A few more minor LR text updates

feature_string.go, featureflags.go, providers/aws/provider/provider.go, providers/aws/resources/discovery.go, providers/azure/provider/provider.go, providers/azure/resources/discovery.go, providers/gcp/provider/provider.go, providers/gcp/resources/discovery.go
Add a feature flag to enable fine-grained assets scans for cloud providers
=> ⭐️ fine-grained assets discovery feature flag

providers/os/resources/os.lr
This isn't all of them, but it's a start
=> Add descriptions to some dockerfile resources

providers/aws/resources/aws.lr
This improves docs page generation
=> Add docs to the Amazon Inspector resource

providers/aws/resources/aws.lr.manifest.yaml
=> Add more descriptions / links for AWS docs

apps/cnquery/cmd/bundle_querypack-example.mql.yaml
adjust the asset filter in the query pack example to the new style
=> introduce the new asset filter style

providers/aws/resources/aws.lr
=> Two minor docs improvements to the elb resource

providers/atlassian/config/config.go
=> 🎉 atlassian-11.0.3

providers/atlassian/resources/atlassian.lr, providers/atlassian/resources/atlassian.lr.manifest.yaml, providers/azure/resources/azure.lr.manifest.yaml
- Add minimum mondoo release for atlassian to be 9.0.0
- Change all 9.0.3 min versions to be just 9.0.0
- Add more Azure links
- Fix incorrect Azure link titles
- Fix some bad formatting in Atlassian
=> Expand docs LR files

providers/os/resources/os.lr, providers/os/resources/os.lr.manifest.yaml
=> Expand docker resource documentation

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_ec2.go
```
cnquery> aws.ec2.instances.where(image.createdAt < time.now + time.day*-365) { instanceId region image { id createdAt}}
```
=> ✨ add creation date to ec2 images

providers/gcp/resources/gcp.lr, providers/gcp/resources/gcp.lr.go, providers/gcp/resources/gcp.lr.manifest.yaml, providers/gcp/resources/gke.go
Add a few more config options to the cluster resource and give it more useful defaults
=> Add more configs to gcp.project.gkeService.cluster + better defaults

.github/actions/spelling/expect.txt, providers/gcp/resources/gcp.lr, providers/gcp/resources/gcp.lr.go, providers/gcp/resources/gcp.lr.manifest.yaml, providers/gcp/resources/gke.go
There's new ones now that we should grab the config for.
=> Add additional addons to GKE cluster resource

providers/github/resources/github.go, providers/github/resources/github_org.go, providers/github/resources/github_repo.go
- fix memoizer for users
- add memoizer for org
- fix panics for committer and author being empty
=> 🧹 github provider improvements

providers/github/config/config.go
=> 🎉 github-11.1.1

providers/aws/resources/aws.lr.go, providers/aws/resources/aws_elb.go
=> 🐛 Fix AWS loadbalancer init.

providers/aws/config/config.go
=> 🎉 aws-11.0.6

Makefile
This was just copied from GitHub and the resources are different there
=> Fix the description of the GitLab resource pack

providers/github/resources/github.lr, providers/github/resources/github.lr.go, providers/github/resources/github.lr.manifest.yaml, providers/github/resources/github_org.go
Grab project data for the org and projects
=> Add new fields for github orgs

providers/github/config/config.go
=> 🎉 github-11.1.4

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_dynamodb.go, providers/aws/resources/aws_kms.go
```
cnquery> aws.dynamodb.exports { * }
aws.dynamodb.exports: [
0: {
arn: "arn:aws:dynamodb:us-east-1:---------:table/test-table/export/0171......"
format: "DYNAMODB_JSON"
kmsKey: null
s3SseAlgorithm: "AES256"
itemCount: 0
type: "FULL_EXPORT"
startTime: 2024-05-10 17:20:20.127 -0600 MDT
s3Prefix: ""
s3Bucket: aws.s3.bucket name="mondoo.cnspec.scanreports" location="us-east-1" public=false
table: aws.dynamodb.table name="test-table" region="us-east-1"
endTime: 2024-05-10 17:25:59.413 -0600 MDT
status: "COMPLETED"
}
]
```
=> ✨ add aws dynamodb exports resource

providers/network/config/config.go
=> 🎉 network-11.0.1

providers/ms365/resources/ms365.lr, providers/ms365/resources/ms365.lr.go, providers/ms365/resources/ms365.lr.manifest.yaml, providers/ms365/resources/ms365_teams.go
=> ⭐️  Added a field for checking the external meeting chat (MS365)

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_ec2.go
This tell us if NitroTPM has been enabled or not
=> :star: Add tpmSupport field to aws.ec2.instance

providers/ms365/resources/ms365.lr, providers/ms365/resources/ms365.lr.go, providers/ms365/resources/ms365.lr.manifest.yaml, providers/ms365/resources/ms365_exchange.go
=> ⭐️  Add team protection policy in Exchange (MS365)

providers/azure/config/config.go, providers/ms365/config/config.go
=> 🎉 ms365-11.0.8, azure-11.0.9

llx/data_conversions.go, llx/rawdata_test.go
=> 🐛 Preserve semver type when converting to result

.github/actions/spelling/expect.txt, providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_rds.go
=> ✨ rds cluster and instance backup settings

providers/aws/config/config.go
=> 🎉 aws-11.0.10

providers/ms365/resources/ms365.lr, providers/ms365/resources/ms365.lr.go, providers/ms365/resources/ms365.lr.manifest.yaml, providers/ms365/resources/ms365_teams.go
=>  ⭐️  Adding new resource for TeamsMessagingPolicy (MS365)

providers/ms365/resources/ms365.lr, providers/ms365/resources/ms365.lr.go, providers/ms365/resources/ms365.lr.manifest.yaml, providers/ms365/resources/ms365_exchange.go
=> ⭐️  Added ReportSubmissionPolicy resources to asses Defender (MS365)

providers/ms365/config/config.go
=> 🎉 ms365-11.0.10

providers/azure/resources/azure.lr, providers/azure/resources/azure.lr.manifest.yaml
- Use proper branded capitalization and abbreviations
- Link to more specific docs
=> Improve documentation generation for Azure resources

providers/arista/provider/provider.go, providers/arista/resources/eos/README.md
Right now this is just an empty string
=> Add a runtime for "arista" to Arista EOS devices

providers/network/config/config.go
=> 🎉 network-11.0.3

providers-sdk/v1/util/configure/configure.go
If the provider we're pulling in as a built in has specific pinned dependencies, ensure we also pull those in the main `go.mod` file.
Else we might pull newer versions of the provided dependency, which might cause failures in compilation, e.g.
the azure provider pins a specific `armsecurity` package here:  https://github.com/mondoohq/cnquery/blob/main/providers/azure/go.mod#L6
With this change, we also pull in this `replace` statement when building azure as a built-in provider.
Before:
```
module go.mondoo.com/cnquery/v11
replace go.mondoo.com/cnquery/v11/providers/azure => ./providers/azure
go 1.22
toolchain go1.22.0
```
After:
```
module go.mondoo.com/cnquery/v11
replace go.mondoo.com/cnquery/v11/providers/azure => ./providers/azure
replace …
```
=> 🧹 Pull in replace dependencies from provider go.mods when using configure

.github/dependabot.yml, Makefile, docs/development.md, providers/cloudformation/config/config.go, providers/defaults.go
Make sure we have the new cloudformation provider everywhere.
=> Add cloudformation provider to a few other places

providers/k8s/connection/shared/resources/manifest_file.go, providers/k8s/resources/discovery.go
- make sure we discover all objects that we can from manifests
- make sure asset names are correct for objects with no specified namespace
=> 🐛 fix k8s manifest scanning bugs

.github/actions/spelling/expect.txt, providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_elb.go
=> ✨ aws elb targetgroup

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_ec2.go
This is one of the more important things for this resource
=> Add private IP address to AWS EC2 network interfaces

providers/ms365/resources/structs.go
=> ⭐️  adding the DefaultUserRolePermissions in MgPolicyAuthorizationPolicy  (MS365)

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_eks.go
=> Add modifiedAt to aws.eks.nodegroup

providers/aws/config/config.go
=> 🎉 aws-11.1.2

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws_autoscaling.go, providers/aws/resources/aws_eks.go
=> ✨ add autoscaling groups to aws eks cluster nodegroups

providers/vsphere/resources/datacenter.go, providers/vsphere/resources/discovery.go
And be more descriptive what went wrong during discovery.
=> 🧹 Do not end discovery when single ESXi host is unreachable

providers/os/resources/os.lr.manifest.yaml
- Update the wording a bit
- Copy the example over to the non-deprecated resource
=> Update the docs examples for windows feature resources

providers/os/connection/device/device_connection.go
We run `DetectOS` first before we run `IdentifyPlatform`.  `DetectOS` was already being called inside of `IdentifyPlatform` so this does not change a lot.
It does enable us to scan an asset where we've identified the platform but the ID detectors were unable to pick up a platform-id. If one is provided via the `--platform-ids` param and the OS detection was successful we can still scan the asset.
=> 🧹 Run OS detection before running the ID detectors for the device connection

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws_ecs.go
=> 🐛 fix aws ecs cluster tasks resource

providers/aws/config/config.go
=> 🎉 aws-11.1.6

providers/os/connection/ssh/cat/cat_file.go
fixes https://github.com/mondoohq/cnquery/issues/4198
fixes https://github.com/mondoohq/packer-plugin-cnspec/issues/247
=> 🧹 implement missing Readdir for catfs

Makefile
Command typo here caused a failure
=> Fix docs generation for Snowflake

providers/cloudformation/provider/provider.go
=> 🧹 set runtime for cloudformation assets

providers/cloudformation/config/config.go
=> 🎉 cloudformation-11.0.7

providers/azure/resources/discovery.go, providers/azure/resources/sql.go
See https://en.wikipedia.org/wiki/Microsoft_Azure_SQL_Database
=> Update the platform name for Azure SQL Database servers

.github/.goreleaser-edge.yml, .github/.goreleaser-unstable.yml
Follow-up to #4233
I didn't fix all config files in the first PR:
https://github.com/mondoohq/cnquery/actions/runs/9512915756/job/26221920008
=> 🐛 Fix goreleaser config version

.github/.goreleaser-edge.yml
=> 🐛 Fix goreleaser config changelog

providers/ms365/resources/ms365_exchange.go
=> 🐛 Fix panic in ms365 provider

providers/ms365/config/config.go
=> 🎉 ms365-11.0.18

providers/aws/resources/aws.lr.go, providers/aws/resources/aws_efs.go
=> 🧹 use cache for kms key on efs filesystem

Makefile, providers-sdk/v1/util/docs/summarize.go
With example output:
```bash
> make lr/docs/stats
Total providers: 26
Total resources: 851
Total fields:    6076
```
=> 📃 add make lr/docs/stats

Makefile
=> Fix the makefile echo for the stats command

providers-sdk/v1/util/docs/summarize.go
```
Total providers:   26
Total connectors:  32    <= this
Total resources:   851
Total fields:      6076
```
=> 📃 add connectors to docs schema analysis

providers/aws/config/config.go, providers/azure/config/config.go
=> 🎉 aws-11.1.9, azure-11.0.19

providers/aws/config/config.go
=> 🎉 aws-11.1.10

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_eks.go
Trying to fix https://github.com/mondoohq/cnquery/issues/4222
=> Create AWS resource `aws.eks.addon`

providers/aws/config/config.go
=> 🎉 aws-11.1.11

providers/google-workspace/resources/google-workspace.lr, providers/google-workspace/resources/google-workspace.lr.go, providers/google-workspace/resources/google-workspace.lr.manifest.yaml, providers/google-workspace/resources/users.go
=> ✨ add isDelegatedAdmin to google workspace users

providers/azure/resources/discovery.go
The current code does not work well with the parent connection, it needs to be refactored such that each subscription does the discovery on its own (with its own runtime). I am reverting back as a hotfix so that the azure provider can go back to normal until we fix it properly
=> 🐛 Do not use parent connection for azure provider.

providers/azure/config/config.go
=> 🎉 azure-11.0.20

providers/aws/resources/aws_iam.go
increasing sleep time to avoid hitting API limits
=> 🧹 increase sleep time for iam GetCredentialReport retries

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_eks.go
```
cnquery> aws.eks.clusters.first{*}
aws.eks.clusters.first: {
...
iamRole: aws.iam.role arn="arn:aws:iam::177043123456:role/online-shop-byh8" name="online-shop-byh8"
...
}
```
=> ⭐ Collect the IAM role of the EKS cluster

providers/os/config/config.go
=> 🎉 os-11.2.14

providers/aws/resources/discovery_conversion.go, providers/aws/resources/discovery_test.go
just some cleanup - make the labels constants and add a small test
=> 🧹 add a test for ec2 instance labels

providers/azure/resources/aks.go, providers/azure/resources/azure.lr, providers/azure/resources/azure.lr.go, providers/azure/resources/azure.lr.manifest.yaml
=> ✨ Add support for apiServerAccessProfile to AKS resource

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_iam.go
fixes https://github.com/mondoohq/cnquery/issues/3206
=> 🐛 fix aws iam users attachedpolicies

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_ec2.go
and a bit of cleanup too
https://github.com/mondoohq/cnquery/issues/4322
=> ⭐ add userIdGroupPairs and prefixListIds to secGroup IpPerms

providers/aws/config/config.go
=> 🎉 aws-11.1.15

providers/azure/config/config.go
=> 🎉 azure-11.0.24

providers/aws/config/config.go
=> 🎉 aws-11.1.18

providers/gitlab/resources/gitlab.go, providers/gitlab/resources/gitlab.lr
=> ⭐️ Adding the approvalrule settings to the project (Gitlab)

providers/gitlab/resources/gitlab.go, providers/gitlab/resources/gitlab.lr
=> ⭐️  Adding support to fetch merge methods (Gitlab)

providers/gitlab/resources/gitlab.go, providers/gitlab/resources/gitlab.lr
=> ⭐️ Adding support for fetching the Protected Branchs configs (Gitlab)

.github/actions/spelling/line_forbidden.patterns
Match the docs repo more or less
=> Update spellcheck config

providers/gitlab/resources/gitlab.lr.go, providers/gitlab/resources/gitlab.lr.manifest.yaml, providers/google-workspace/resources/google-workspace.lr.manifest.yaml
These are getting updated every time we build, but weren't added to the repo
=> Add in boilerplate from the latest resource updates

providers/gitlab/resources/gitlab.go, providers/gitlab/resources/gitlab.lr, providers/gitlab/resources/gitlab.lr.manifest.yaml
=> ⭐️ Adding support for fetching the code Owner Approval from Protected Branch (Gitlab)

providers/gitlab/resources/gitlab.go, providers/gitlab/resources/gitlab.lr, providers/gitlab/resources/gitlab.lr.manifest.yaml
=> ⭐️ Adding the support to list the files in a Project (Gitlab)

providers/gitlab/resources/gitlab.go, providers/gitlab/resources/gitlab.lr, providers/gitlab/resources/gitlab.lr.manifest.yaml
=> ⭐️ Adding the support to fetch the webhooks and the ssl config (Gitlab)

providers/google-workspace/config/config.go
This improves the long form getting started help. Thanks Letha for all the updates!
=> Improve the google-workspace provider help

providers/shodan/resources/discovery.go
The shodan token flag was not being accepted properly.
Fixes #4355
=> 🐛 Fix issue with shodan token flag

providers/aws/resources/aws_iam.go
=> 🐛 Fix aws iam time parsing

providers/atlassian/config/config.go, providers/atlassian/connection/confluence/connection.go, providers/atlassian/connection/connection.go, providers/atlassian/provider/provider.go
=> Fix confluence shared connection type

providers/aws/resources/aws_ec2.go
fixes https://github.com/mondoohq/cnquery/issues/4353
=> 🐛 fix aws ec2 instance keypair

providers/gitlab/resources/gitlab.go, providers/gitlab/resources/gitlab.lr, providers/gitlab/resources/gitlab.lr.go, providers/gitlab/resources/gitlab.lr.manifest.yaml
It will solve the issue mentioned here:  https://github.com/mondoohq/cnquery/pull/4365
=> 🧹  Adding timer and retry to fetching Approvalsettings (Gitlab)

providers/aws/config/config.go
=> 🎉 aws-11.1.19

providers/gitlab/config/config.go
=> 🎉 gitlab-11.1.15

providers/github/config/config.go
=> 🎉 github-11.4.0

providers/google-workspace/config/config.go
=> 🎉 google-workspace-11.1.0

providers/os/config/config.go
Needed to release https://github.com/mondoohq/cnquery/pull/4453
=> :arrow_up: update os-provider 11.2.21

providers/github/config/config.go
=> 🎉 github-11.4.1

providers/github/config/config.go
=> 🎉 github-11.4.2

providers/mondoo/go.mod, providers/mondoo/provider/provider.go, providers/mondoo/provider/provider_test.go, providers/mondoo/resources/mondoo.lr, providers/mondoo/resources/mondoo.lr.go, providers/mondoo/resources/mondoo.lr.manifest.yaml, providers/mondoo/resources/mondoo_assets.go, providers/mondoo/resources/mondoo_organization.go, providers/mondoo/resources/mondoo_space.go
* Add `mondoo.organization`. Depending on what the config is that we load the provider with we will either init `mondoo.space` or `mondoo.organization`
* Add `spaces()` to mondoo.organization
* Extend asset info with score value and score grade
* Split `mondoo.go` into 3 files for space, org and assets
=> ✨ Add mondoo.organization. Add score value and grade to mondoo assets.

providers/mondoo/config/config.go
=> 🎉 mondoo-11.1.0

providers/mondoo/connection/connection.go, providers/mondoo/connection/connection_test.go, providers/mondoo/provider/provider.go, providers/mondoo/provider/provider_test.go, providers/mondoo/resources/mondoo.lr.go, providers/mondoo/resources/mondoo_organization.go, providers/mondoo/resources/mondoo_space.go
If we're connecting with an org config, this won't work. Switch to using the space's MRN from the MQL resource.
=> 🐛 Use unique ids for mondoo spaces. Improve provider code

providers/mondoo/config/config.go
=> 🎉 mondoo-11.1.1

providers/azure/config/config.go
=> 🎉 azure-11.0.26

providers/github/config/config.go
=> 🎉 github-11.4.3

providers/mondoo/resources/mondoo.lr.go, providers/mondoo/resources/mondoo_assets.go
Example query:
```
mondoo.asset(mrn: "//assets.api.mondoo.app/spaces/test-infallible-taussig-796596/assets/2gT5NDy3JudaMZRYntjNRo0v2XA") { * }
```
=> ✨ Allow loading asset by mrn

providers/github/config/config.go
=> 🎉 github-11.4.5

providers/azure/resources/cloud_defender.go
The latest CIS implementation indicates that we can check the pricing tier for the defender for servers plan. IF set to `standard` it's considered enabled. This PR adjusts the `defenderForServers` check to take that into account
=> 🧹 Check the pricing tier for the Servers plan when verifying if Azure's Defender for Servers is enabled

providers/atlassian/config/config.go
=> 🎉 atlassian-11.0.26

providers/atlassian/config/config.go
=> 🎉 atlassian-11.0.27

providers/atlassian/resources/atlassian.lr, providers/atlassian/resources/atlassian.lr.go, providers/atlassian/resources/atlassian.lr.manifest.yaml
I didn't check in the boilerplate files. I also made it part of the default output for issues in the shell
=> Fix the atlassian.jira.issue created -> createdAt rename

providers/aws/resources/aws.lr.manifest.yaml
Make sure the docs continue to generate as expected
=> Move the accessAnalyzer docs to the new resource

providers/aws/config/config.go
=> 🎉 aws-11.2.0

providers/network/resources/network.lr, providers/network/resources/network.lr.manifest.yaml
Some minor improvements and links
=> Improve docs generation for some network resources

providers/aws/config/config.go
=> 🎉 aws-11.2.1

providers/google-workspace/resources/google-workspace.lr.manifest.yaml, providers/k8s/resources/k8s.lr.manifest.yaml, providers/oci/resources/oci.lr.manifest.yaml
=> Add docs references for OCI + K8s

providers/aws/config/config.go
=> 🎉 aws-11.2.2

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_dynamodb.go
- add new field `items` and `latestStreamArn`
- use correct dict type in for resource initialization
=> 🧹 improve aws.dynamodb.table resource

providers/aws/config/config.go
=> 🎉 aws-11.3.0

providers/k8s/resources/k8s.lr.manifest.yaml
The build process updates this file
=> Pull in automatic changes during the provider builds

providers/azure/resources/postgresql.go
=> 🧹   Adding id function to postgresql flexible server (Azure)

providers/azure/config/config.go
=> 🎉 azure-11.1.0

providers/azure/config/config.go
=> 🎉 azure-11.2.0

providers/azure/go.mod, providers/azure/go.sum, providers/azure/resources/azure.lr, providers/azure/resources/azure.lr.go, providers/azure/resources/azure.lr.manifest.yaml, providers/azure/resources/iam.go
This PR allows us to verify managed identities. 
**Verify assigned roles to managed identities**
It is critical that managed identities have no privileged roles assigned:
```javascript
cnquery> azure.subscription.iam.managedIdentities.all(roleAssignments.none(role.name ==  "Owner" ))
[ok] value: true
cnquery> azure.subscription.iam.managedIdentities.all(roleAssignments.none(role.name ==  "Contributor" ))
[ok] value: true
cnquery> azure.subscription.iam.managedIdentities.all(roleAssignments.none(role.name ==  "User Access Administrator" ))
[ok] value: true
cnquery> azure.subscription.iam.managedIdentities.all(roleAssignments.none(role.name ==  "Role Based Access Control Administrator" ))
[ok] value: true
```
**List managed identities**
We can list all managed identities with the following …
=> ⭐️ Azure IAM role assignment and managed identities

apps/cnquery/cmd/login.go
=> 🧹 token validation errors handling

providers/aws/config/config.go
=> 🎉 aws-11.3.3

providers/github/resources/discovery.go
Seems like the Github code search provides many inconsistencies in its results. There is a huge thread with complaints piling in the past >1 year https://github.com/orgs/community/discussions/18624 
This is an alternative way for finding terraform in repos. With this approach we lose the ability to ignore hidden terraform files
=> 🧹 use languages to detect terraform in github

providers/github/config/config.go
=> 🎉 github-11.4.10

providers/atlassian/resources/atlassian.lr
=> Improve MQL Atlassian docs

providers/azure/config/config.go
=> 🎉 azure-11.3.0

providers/vsphere/resources/vsphere.lr.manifest.yaml
Fix a typo that shows up in the docs
=> Minor typo in the vsphere MQL docs

providers/core/resources/core.lr.manifest.yaml
These fields have been removed already
=> Remove documention for removed fields

providers/os/resources/smbios/smbios_test.go, providers/os/resources/smbios/win.go
=> 🐛 handle dynamically types `ChassisTypes`

providers/mondoo/config/config.go
=> 🎉 mondoo-11.1.8

providers/ms365/config/config.go
=> 🎉 ms365-11.0.34

providers/github/resources/github.lr, providers/github/resources/github.lr.go, providers/github/resources/github.lr.manifest.yaml, providers/github/resources/github_repo.go
- There are now fields to fetch the code of conduct, security file, and support file. These should create less garbage in cnquery
- There is a specific field for admin collaborators so we do not need to list all the collaborators if we just care about admins
=> ⭐️ Optimized fields for github provider

providers/github/config/config.go
=> 🎉 github-11.4.14

providers/azure/config/config.go
=> 🎉 azure-11.3.3

providers/ms365/resources/ms365.lr, providers/ms365/resources/ms365.lr.go, providers/ms365/resources/ms365.lr.manifest.yaml, providers/ms365/resources/policies.go
=> ⭐️ Adding consent settings  - ms365 

providers/aws/config/config.go
=> 🎉 aws-11.4.0

explorer/executor/executor.go, internal/datalakes/inmemory/query_conductor.go, utils/iox/chunker.go, utils/iox/chunker_test.go
There is an upper limit to what is accepted by the platform per request. Make sure we do not go past it when sending data.
=> 🐛 Chunk sending results by size

providers/os/connection/docker/docker_file_connection.go, providers/os/connection/shared/shared.go, providers/os/resources/groups/manager.go, providers/os/resources/users/manager.go
=> 🐛 fix dockerfile asset family

providers/ipmi/config/config.go, providers/mondoo/config/config.go, providers/okta/config/config.go, providers/opcua/config/config.go, providers/shodan/config/config.go
Adds long-form CLI help for:
- ipmi
- mondoo
- okta
- opcua
- shodan
=> 📄  Add long-form CLI help for a bunch of providers

providers/aws/config/config.go
=> 🎉 aws-11.4.4

providers/aws/config/config.go
=> 🎉 aws-11.4.6

apps/cnquery/cmd/bundle.go
=> Update wording to remove mention of registry

providers/aws/config/config.go
=> 🎉 aws-11.5.0

providers/ms365/resources/ms365_exchange.go
=> 🐛 catch nil errors when assembling ms365 exchange report

providers/ms365/config/config.go
=> 🎉 ms365-11.0.40

providers/os/resources/asset_purl.go, providers/os/resources/os.lr, providers/os/resources/os.lr.go, providers/os/resources/os.lr.manifest.yaml, providers/os/resources/purl/platform_purl.go, providers/os/resources/purl/platform_purl_test.go
Add the asset platform in package URL format.
=> ✨ Add platform PURLs

providers/ms365/config/config.go
=> 🎉 ms365-11.0.42

providers/ms365/config/config.go
=> 🎉 ms365-11.0.43

providers/azure/config/config.go
=> 🎉 azure-11.3.14

providers/os/detector/windows/build_version_windows.go
When running locally, collect all the data we need.
=> 🐛 Fix Windows platform detection

providers/os/resources/processes/unixps.go
=> 🐛 consistent processes executable for unix and linux

.github/actions/spelling/line_forbidden.patterns
Make sure we catch a few things we've typo'd throughout codebases
=> Add 2 more pattern matches to spellcheck

providers/ms365/config/config.go
=> 🎉 ms365-11.1.0

.github/actions/spelling/line_forbidden.patterns
=> Add Cloudflare to the spellcheck

providers/cloudflare/resources/cloudflare.lr
This way the list isn't just the resource name over and over again
=> Give Cloudflare R2 buckets a nice default value

providers/gitlab/connection/connection.go, providers/gitlab/go.mod, providers/gitlab/go.sum, providers/gitlab/provider/discovery.go, providers/gitlab/provider/provider.go, providers/gitlab/resources/gitlab.go
For more details: https://github.com/xanzy/go-gitlab?tab=readme-ov-file#migration-steps
=> 🧹 Replace archived go-gitlab

Makefile
=> Generate docs for nmap

providers/github/connection/connection.go, providers/github/connection/connection_test.go
=> 🐛 fix github provider load secret from inventory

providers/github/config/config.go
=> 🎉 github-11.4.31

providers/github/config/config.go
=> 🎉 github-11.4.32

Makefile, providers/nmap/resources/discovery.go
Fixes this error:
```
x unable to create runtime for asset error="rpc error: code = Unknown desc = cannot find resource nmap.network  in this provider" asset=Nmap
```
Also fixes the makefile to actually install
=> Fix failures scanning with nmap

providers/ms365/resources/applications.go
tested by setting top to 1 locally and ensuring i got all expected results (3)
=> 🧹 fetch all ms365 applications (add pagination when fetching resources)

.github/actions/spelling/line_forbidden.patterns, mql/internal/execution_manager.go, providers-sdk/v1/lr/lr.go, providers/aws/connection/connection.go, providers/aws/resources/discovery.go, providers/aws/resources/discovery_conversion.go
Fixes detected by a rule that didn't quite work out
=> Minor spellcheck updates

providers/aws/config/config.go
=> 🎉 aws-11.5.17

providers/ms365/resources/applications.go, providers/ms365/resources/ms365.lr
allow users to fetch by name or id
```
microsoft.application(id: "2efd0330-112c-4971-ab20-eaa54c.....") { * }
```
```
microsoft.application(name: "nametest") { * }
```
=> ✨ add ability to fetch ms365 application by id

providers/ms365/config/config.go
=> 🎉 ms365-11.1.10

providers/gcp/resources/cloudrun.go
=> 🐛 ensure regions data is fetched when querying gcp services

providers/terraform/config/config.go
=> 🎉 terraform-11.1.0

providers/vsphere/config/config.go
This changed in https://github.com/mondoohq/cnquery/pull/4978 but the config was not updated
=> 🐛 Fix vmware asset url

providers/oci/provider/provider.go
Was broken in https://github.com/mondoohq/cnquery/pull/4557
=> 🐛 Fix oci asset url

providers-sdk/v1/inventory/inventory.go, providers/aws/resources/discovery_conversion.go
fixes https://github.com/mondoohq/cnspec/issues/1531
=> 🐛 fix handling of aws filters (ensure filters are copied in cfg clone)

providers/os/config/config.go
=> 🎉 os-11.3.24

providers/network/config/config.go
=> 🎉 network-11.0.51

providers/os/resources/vulnmgmt.go
This is needed to create the correct PURL, for MQL vulnmgmt resource.
=> 🐛 Add format to packages

README.md
=> updates copyright in readme

logger/zerologadapter/adapter.go, providers-sdk/v1/upstream/health/errors.go
=> 🧹 Fix 2 minor comment typos

providers-sdk/v1/lr/lr_test.go
We merged this PR https://github.com/mondoohq/cnquery/pull/5181 that had failed CI jobs.
=> 🧹 fix broken test

llx/range.go, llx/range_test.go
First time using this with a large config I got a few screens of scrollback from trying to print the entire block of file.context. Most file context handlers however only ever want a few core content lines. We are starting with 8 by default, not sure yet if this is adequate or not.
Example with `maxlines = 7`:
```
Some super long file
with multiple lines
of code
...
final lines
of the file
and its end.
```
see the tests for more examples and different range types
=> ⭐ only show 8 lines in file.context by default

providers-sdk/v1/util/azauth/token.go
Closes https://github.com/mondoohq/cnquery/issues/5003
=> 🐛 azure fix can't access vaults from tenant

providers/cloudflare/resources/cloudflare.lr.manifest.yaml
=> 🧹 Remove an extra field from the cloudflare provider yaml

providers/github/resources/github.lr.manifest.yaml
There were lots of fields in here that don't exist
=> 🧹 Cleanup the GitHub provider lr yaml

providers/slack/resources/slack.lr.manifest.yaml
Regenerated the file and identified fields that are not in the codebase
=> 🧹 Cleanup fields in the Slack provider yaml

providers/aws/resources/aws.lr.manifest.yaml
Regenerated this file from scrach and identified fields/resources that aren't actually in the lr files from that.
=> 🧹 Cleanup fields/resources in AWS provider yaml

providers/cloudformation/resources/cloudformation.lr.manifest.yaml
Deleted and regenerated to find invalid fields in this file
=> 🧹 Cleanup extra fields in the cloudformation provider yaml

providers/shodan/resources/shodan.lr.manifest.yaml
Deleted and regenerated this file to find fields not actually present in code
=> 🧹 Cleanup an extra field in the shodan provider yaml

providers/vsphere/resources/vsphere.lr.manifest.yaml
=> 🧹 Cleanup extra port group fields/resources in the vsphere provider

providers/os/resources/packages/windows_packages.go, providers/os/resources/packages/windows_packages_test.go
=> 🐛 Fix Windows PURLs for locally collected packages

providers/aws/resources/aws_s3.go
We now check Public Access Block settings first, then Bucket PolicyStatus
which is the native way that AWS computes if a bucket is public or not, but
if that doesn't work, we still parse the bucket policy to see if it public.
=> 🐛  fix aws s3 bucket public()

providers/arista/resources/arista.lr, providers/aws/resources/aws.lr, providers/cloudformation/resources/cloudformation.lr, providers/equinix/resources/equinix.lr, providers/gcp/resources/gcp.lr, providers/oci/resources/oci.lr, providers/os/resources/os.lr, providers/terraform/resources/terraform.lr
Improve our docs generation a tiny bit
=> Capitalize some resource docs

providers/gcp/resources/cloudrun.go
```
gcloud.project.cloudRun.services: [
0: {
template: {
scaling: {
maxInstanceCount: 100.000000
minInstanceCount: 0.000000
}
annotations: {}
projectId: "luna-common"
executionEnvironment: "EXE....
....
```
=> 🐛 fix gcloud.project.cloudRun.services { template { * }}

providers/aws/resources/aws.lr
I was a bit confused reading some of this
=> Improve documentation for security groups

providers/ms365/config/config.go
```
➜  cnquery git:(main) version update providers/ms365
crawling git history....................................................................................................................................................................................................................................................................................................................................................................................
! looks like there is no previous version in your commit history => we assume this is the first version commit
→ provider changed changes=369 provider=ms365 version=11.1.18
→ set new version previous=11.1.18 provider=ms365 version=11.1.19
→ updated config path=providers/ms365/config/config.go
→ git add providers/ms365/config/config.go && git …
```
=> 🎉 ms365-11.1.19

.vscode/launch.json
=> 🧹 vscode debug config: Remove hardcoded ips and homefolders

providers/network/config/config.go
=> 🎉 network-11.0.52

providers/network/config/config.go
=> 🎉 network-11.0.53

providers/os/resources/os.lr.manifest.yaml
=> 🐛 os: pin `cloud.instance` to version `>=11.45.0`

providers-sdk/v1/upstream/mvd/cvss/cvss.go, providers-sdk/v1/upstream/mvd/cvss/cvss_test.go
=> 🌟 CVSS V4 Metrics

providers/ms365/resources/applications.go, providers/ms365/resources/devices.go, providers/ms365/resources/groups.go, providers/ms365/resources/microsoft.go, providers/ms365/resources/ms365.lr, providers/ms365/resources/ms365.lr.go, providers/ms365/resources/ms365.lr.manifest.yaml, providers/ms365/resources/users.go
```
→ connected to Microsoft 365
cnquery> microsoft.devices
microsoft.devices.list: [
0: microsoft.device id="03991a7c-01d0-434b-93c7-af4ba16b39b3" displayName="example"
1: microsoft.device id="144189f6-e8eb-479f-ba24-f5c9611cddde" displayName="vmaqs2503131438"
2: microsoft.device id="3c89fefb-8459-484a-a746-ff1d30328120" displayName="example2"
3: microsoft.device id="523fbf29-5b75-4845-8b1a-936790ea5c2d" displayName="vmaqs2503211816"
4: microsoft.device id="70bdc3b9-3d5a-4568-897b-1d7f085926c3" displayName="vmaqs2503191431"
5: microsoft.device …
```
=> ⭐️ add support for reading microsoft 365 devices

providers/os/config/config.go
=> 🎉 os-11.3.44

providers/gcp/go.mod, providers/gcp/go.sum, providers/gcp/resources/gcp.lr, providers/gcp/resources/gcp.lr.go, providers/gcp/resources/gcp.lr.manifest.yaml, providers/gcp/resources/redis.go
Adds a new service into the GCP provider to interact with Redis API (`redis.googleapis.com`).
=> ✨ gcp: new redis service to fetch instances

providers/gcp/resources/gcp.lr, providers/gcp/resources/gcp.lr.go, providers/gcp/resources/gcp.lr.manifest.yaml, providers/gcp/resources/redis.go
This prevents multiple instances to be loaded in MQL.
=> 🐛 fix redis instance id

providers-sdk/v1/inventory/inventory.go
- Consistent capitalization
- Match what we're doing in asset overview now
=> 🧹 Improve our pretty platform values

providers/azure/config/config.go
=> 🎉 azure-11.3.44

providers/os/resources/groups/etcgroups.go, providers/os/resources/groups/etcgroups_test.go, providers/os/resources/groups/manager_test.go, providers/os/resources/groups/testdata/debian.toml, providers/os/resources/groups/testdata/freebsd12.toml
The primary group for a user isn't in /etc/group
https://askubuntu.com/questions/1373865/etc-group-why-the-username-does-not-appear-in-its-own-primary-group
=> 🐛 Fetch primary group members from /etc/passwd

.github/workflows/providers.yaml
Addresses https://github.com/mondoohq/server/issues/10891
=> Send Slack notification on provider build failure

providers/aws/config/config.go
=> 🎉 aws-11.5.40

providers/os/resources/os.lr
Make sure this is ready for the docs page
=> Update auditd resource docs

providers/os/provider/provider.go
During an ec2 instance-connect scan, we establish a connection via SSH from our `os` provider, this change tries to detect that connection type and fetches tags from the instance if it is possible.
=> ✨ discover ec2 tags via instance-connect

providers/terraform/config/config.go
=> 🎉 terraform-11.1.21

providers/terraform/config/config.go
=> 🎉 terraform-11.1.22

providers/os/resources/processes/linuxproc.go
this change fixes issue where kernel threads weren't properly detected due to empty /proc/<pid>/cmdline
and adds fallback to read process name from /proc/<pid>/comm when cmdline is empty
resolves #5422
=> 🐛 Fix process handling for Linux kernel threads

providers/network/resources/certificates/README.md
=> 📝 disable 403 link check

providers/azure/config/config.go
=> 🎉 azure-11.3.52

llx/builtin.go, llx/builtin_array.go, llx/builtin_map.go, llx/builtin_simple.go, mql/mql_test.go, mqlc/builtin.go, mqlc/builtin_simple.go, providers/core/resources/mql_test.go, providers/os/resources/mql_test.go
Add the counterpart to the `in` call:
```coffee
> 'term'.notIn(['a','b','c'])
true
> 'term'.notIn(['term'])
false
```
=> ✨ add string.notIn([..])

providers/os/resources/os.lr, providers/os/resources/os.lr.go, providers/os/resources/os.lr.manifest.yaml, providers/os/resources/sshd.go, providers/os/resources/sshd_test.go
So now you can say: 
```coffee
sshd.config.blocks.all( ciphers.containsNone( forbiddenList ))
```
=> ✨ add ciphers, macs, kexs, hostKeys, and permitRootLogin to blocks

.github/actions/spelling/expect.txt, .github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/patterns.txt
Pull in a few new terms + remove some expects we don't need anymore
=> Updates to the spellcheck config

providers/os/detector/detector_all.go
```
cnquery> asset { platform version build }
asset: {
platform: "aix"
build: "7300-03-00-2446"
version: "7.3"
}
```
=> ⭐️ collect build version for aix

providers/core/resources/core.lr.manifest.yaml, providers/os/resources/os.lr.manifest.yaml
We removed this already. Related to https://github.com/mondoohq/cnquery/issues/1051
=> Remove references to yaml.path

providers/aws/config/config.go, providers/aws/connection/platform.go, providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_eks.go, providers/aws/resources/discovery.go, providers/aws/resources/discovery_conversion.go
Expose these as an asset so we can improve check output
=> ⭐ Add asset discovery for aws-eks-cluster assets

providers/aws/config/config.go
tiny change to make it easier to filter
=> 🧹 add example for filtering instanceids to help output

providers/aws/config/config.go
=> 🎉 aws-11.5.47

.github/actions/spelling/excludes.txt, .github/actions/spelling/line_forbidden.patterns, .github/workflows/spell-check.yaml
Add some more terms and a dictionary so we don't have to manage ourselves as much
=> Pull in the latest spellcheck updates

providers/aws/resources/aws_codedeploy.go
=> 🐛 aws codedeploy deploymentGroup typo

providers/aws/config/config.go
=> 🎉 aws-11.5.50

providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws_codedeploy.go
=> 🐛 aws code deploy fixes

providers/aws/config/config.go
=> 🎉 aws-11.5.51

providers/os/resources/packages/aix_packages.go, providers/os/resources/packages/aix_packages_test.go
Sets the arch for AIX packages
=> 🧹 set aix packages arch

explorer/mquery.go, explorer/mquery_test.go
Tags were not being checksummed properly. They needed to be taken from the ref
=> 🐛 Fix mquery checksuming

providers/ms365/resources/ms365.lr.manifest.yaml
Remove fields and resources that aren't actually in the product
=> Cleanup the MS365 manifest

providers/azure/resources/azure.lr.manifest.yaml, providers/core/resources/core.lr.manifest.yaml, providers/gcp/resources/gcp.lr.manifest.yaml, providers/google-workspace/resources/google-workspace.lr.manifest.yaml, providers/k8s/resources/k8s.lr.manifest.yaml, providers/network/resources/network.lr.manifest.yaml, providers/oci/resources/oci.lr.manifest.yaml, providers/opcua/resources/opcua.lr.manifest.yaml, providers/os/resources/os.lr.manifest.yaml, providers/vcd/resources/vcd.lr.manifest.yaml
This is somewhat manual work. I removed all the manifests and then regenerated them. From that I found the fields or resources that we didn't actually have in the product. There's probably a lot more to do, but I have pretty high confidence this is all junk.
=> More manifest cleanup

README.md, providers-sdk/v1/upstream/mvd/cvss/cvss.go, providers/defaults.go, providers/ms365/config/config.go, providers/ms365/connection/connection.go, providers/ms365/provider/provider.go, providers/ms365/resources/structs.go
- Backend -> provider
- Active Directory -> Entra ID
- microsoft provider -> ms365 provider
- Microsoft Azure title -> Microsoft 365 title
- Account -> Tenant
=> Minor cleanup to the MS365 provider

providers/ms365/resources/ms365.lr, providers/ms365/resources/ms365.lr.go, providers/ms365/resources/ms365.lr.manifest.yaml, providers/ms365/resources/users.go
Add `perUserMfaState` value to  `microsoft.user`
```grq
cnquery> microsoft.users[0].authenticationRequirements {perUserMfaState}
microsoft.users.list[0].authenticationRequirements: {
perUserMfaState: "disabled"
}
```
resolves #5588
=> Added support for user authentication method states for ms365

providers-sdk/v1/plugin/grpc.go
This cleans up the Error field in DataReq to be utf8. Its possible on Windows this is not utf8. This will prevent the following error message:
```
grpc: server failed to encode response: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
```
You can test it out on a German Windows system. First, build the os provider:
```
cd providers/os
GOOS=windows GOARCH=arm64 go build -o os.exe ./main.go
```
copy `os.exe` to `.config/mondoo/providers/os/` on the Windows system and run the scan
=> 🐛 Ensure that strings being encoded by grpc are utf8

providers/azure/resources/discovery.go
this will help us build links to navigate directly to the resources
=> 🧹 add resource group label to azure resources

content/mondoo-ms365-inventory.mql.yaml
First commit of the Microsoft 365 Query Pack
=> Microsoft 365 Query Pack

providers/azure/config/config.go
=> 🎉 azure-11.3.62

providers/os/config/config.go
=> 🎉 os-11.4.21

Makefile
This is just a title change for SEO so we align with MS marketing terms
=> Update the MQL pack MS365 -> M365

providers/ms365/resources/ms365.lr
Remove periods where statements are not a full sentence to match the format we use everywhere. Reword one very weird description
=> Minor cleanup to MS365 docs

providers/ms365/resources/ms365.lr
Remove periods where things are not a full sentence
=> Minor resource updates for docs generation

cli/config/config.go, providers-sdk/v1/upstream/sts.go
Currently, our WIF integration does not support supplying a JSON Web Token (JWT) as part of the credential exchange process. This change adds support for using a JWT as a credential source during the WIF authentication flow. It allows users to pass in a JWT token via environment variable or configuration file during the WIF exchange process.
In modern cloud-native environments, particularly when integrating with cloud providers (e.g., AWS, GCP, Azure), it is common to perform secure federated identity exchanges using JWTs issued by an OIDC-compliant identity provider.
Supporting JWT input will:
- Improve compatibility with existing Identity Providers (IdPs)
- Enable seamless authentication for CI/CD workflows and short-lived credentials
- Reduce reliance on service account keys and static …
=> ⭐️ sts: allow passing JWT Token

providers/ms365/resources/ms365.lr, providers/ms365/resources/ms365.lr.go, providers/ms365/resources/ms365.lr.manifest.yaml, providers/ms365/resources/ms365_exchange.go
```
cnspec> ms365.exchangeonline.transportConfig.SmtpClientAuthenticationDisabled == true
[ok] value: true
```
https://github.com/mondoohq/cnquery/pull/5717
=> Add `SmtpClientAuthenticationDisabled`

providers/os/resources/languages/javascript/packagejson/parser.go
Fixes: https://github.com/mondoohq/cnquery/issues/5748
=> 🧹 Remove warning about wrong type for JS packages

.github/actions/spelling/expect.txt, providers/ms365/resources/ms365.lr, providers/ms365/resources/ms365.lr.go, providers/ms365/resources/ms365.lr.manifest.yaml, providers/ms365/resources/security_exchange.go
Resolves: https://github.com/mondoohq/cnquery/issues/5586
test:
```
microsoft.security.exchange { antispam { hostedConnectionFilterPolicy { * } } }
microsoft.security.exchange: {
antispam: {
hostedConnectionFilterPolicy: {
ipBlockList: []
identity: "Default"
ipAllowList: []
enableSafeList: false
adminDisplayName: ""
}
}
}
```
=> feature/ms365: Extend `microsoft.security` with `exchange.antispam.HostedConnectionFilterPolicy`

providers/builtin.go
Closes https://github.com/mondoohq/cnquery/issues/5752
=> 🐛 sbom provider without schema

.github/actions/spelling/expect.txt, providers/ms365/README.md
=> [ms365] Added provider notes

cli/config/config.go, cli/config/config_test.go
We were not able to set annotations with a dot in it in the config
=> 🐛 Fix annotations in config

providers/aws/go.mod, providers/aws/go.sum, providers/aws/resources/aws.lr, providers/aws/resources/aws.lr.go, providers/aws/resources/aws.lr.manifest.yaml, providers/aws/resources/aws_eks.go
This was just added to the API this week: https://awsapichanges.com/archive/changes/21afbf-eks.html
```
cnquery> aws.eks.clusters.first.deletionProtection
[failed] aws.eks.clusters.first.deletionProtection
expected: == true
actual:   false
```
=> Expose deletionProtection on EKS clusters

providers/os/resources/packages/windows_packages.go, providers/os/resources/packages/windows_packages_test.go
.NET Framework bundled with Windows does not show up in the default package list. Query the registry keys separatly and add the disciovered version to the packages.
=> ✨ Detect .NET Framework as package

providers/aws/provider/provider.go, providers/aws/resources/discovery.go, providers/aws/resources/discovery_test.go, providers/gcp/resources/discovery.go
similar to https://github.com/mondoohq/cnquery/pull/5871
=> 🧹 clean up aws discovery, remove fine grained assets flag

explorer/cnquery_explorer.pb.go, explorer/cnquery_explorer.proto, explorer/cnquery_explorer_vtproto.pb.go, explorer/resolved_pack.go, explorer/scan/local_scanner.go
This allows the server to set or unset certain features that it supports. This means e.g. that if the server can store resources data in the new format, we can send it this way.
=> ⭐ add support for server-side features

content/mondoo-azure-inventory.mql.yaml, content/mondoo-kubernetes-incident-response.mql.yaml
Switch out a few deprecated fields/resource names
=> Query pack updates for v12

content/mondoo-ms365-inventory.mql.yaml
=> Update MS365 inventory pack for V12

providers/defaults.go, providers/runtime.go
Adds the ai provider to the defaults, so that it can be downloaded.
=> ⭐️ add ai provider to the defaults

providers/azure/config/config.go
=> 🎉 azure-11.3.85

providers/os/detector/detector_all.go, providers/os/detector/detector_platform_test.go, providers/os/detector/testdata/detect-elementary.toml
It's a different UI on top of Ubuntu 22.02.
=> ⭐ Detect elementary OS and put it in debian family

providers/os/resources/services/manager.go
Make sure we can detect services on anything euler
=> ⭐ Use systemd on euler family for services

providers/os/resources/networkinterface/interface.go
Make it a bit more consistent and fix incorrect macos information on Linux.
=> 🧹 Improve debug logging in network interfaces resource

providers/os/config/config.go
=> 🎉 os-11.4.45
